// Regression guard for the version-chrome decoupling (לקח #72, P0).
// version.g.dart is generated by scripts/gen_version.sh (gitignored). These
// tests lock the contract that the *test-trap* can never come back: free-text
// in the version string rendered on every screen broke 10 journey tests.
import 'package:buildsmart/version.g.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('kVersionLabel is vMAJOR.MINOR (generated from STATUS)', () {
    expect(RegExp(r'^v\d+\.\d+$').hasMatch(kVersionLabel), isTrue,
        reason: 'label must be vX.Y; gen_version derives it from STATUS.md');
  });

  test('kReleaseNote stays empty in UI — test-trap guard (לקח #72)', () {
    expect(kReleaseNote, isEmpty,
        reason:
            'free-text in the version chrome rendered on every screen and broke '
            '10 journey tests; changelog lives in markdown, never in the UI');
  });

  test('kBuild is count.shortSHA (unique, not monotonic)', () {
    expect(RegExp(r'^\d+\.[0-9a-f]+$').hasMatch(kBuild), isTrue,
        reason: 'build = rev-count.shortSHA — SHA carries cross-branch uniqueness');
  });
}
