// אטום-דאטה · commands-build-commands-strings — תאום-Dart שנפלט אוטומטית מהמקור-הקדוש
// (מנוע-ההמרה-מחדש · הכרעה 19) המקור: new/atoms/commands-build-commands-strings.mjs — אל תערוך ידנית; שינוי = במקור + פליטה-מחדש.
const Map<String, String> COMMANDS_BUILD_COMMANDS_T = {
  'k1': 'cmd:add',
  'k2': 'add',
  'k3': '➕ הוספת ',
  'k4': 'פעולה',
  'k5': 'הוספה חדש חדשה תורם add new',
  'k6': 'cmd:work',
  'k7': 'work',
  'k8': '🎯 חלון העבודה',
  'k9': 'ניווט',
  'k10': 'קוקפיט משימות עבודה היום cockpit',
  'k11': 'cmd:data',
  'k12': 'data',
  'k13': '☰ מסך הנתונים',
  'k14': 'טבלה נתונים רשימה סינון data',
  'k15': 'cmd:import',
  'k16': 'import',
  'k17': '⬆ ייבוא מקובץ CSV',
  'k18': 'ייבוא csv excel קובץ import',
  'k19': 'cmd:customreport',
  'k20': 'customreport',
  'k21': '📊 דו״ח מותאם',
  'k22': 'דוח מותאם ייצוא טווח report export',
  'k23': 'cmd:dedup',
  'k24': 'dedup',
  'k25': '🔗 איחוד כפולים · ',
  'k26': 'כפולים מיזוג איחוד dedup merge',
  'k27': 'cmd:incoming',
  'k28': 'incoming',
  'k29': '💰 תשלומים נכנסים',
  'k30': 'תשלומים נכנסים סליקה payments',
  'k31': 'cmd:nedarim',
  'k32': 'nedarim',
  'k33': '🔄 סנכרון מנדרים',
  'k34': 'נדרים סנכרון nedarim sync',
  'k35': 'donor:',
  'k36': 'openDonor',
  'k37': 'ללא שם',
  'k38': 'פתיחת כרטיס',
  'k39': 'תורם',
};
