// 🗄️ שמות · חולצו מ-dart-maor/commands-build-commands.dart (מכונת-AST). מטרה→שם; מתחלף פר-וורטיקל.
const Map<String, String> kTerms = {
  'pavlh': 'פעולה',
  'hvsph-chdsh-chdshh-tvrm': 'הוספה חדש חדשה תורם add new',
  'chlvn-habvdh': '🎯 חלון העבודה',
  'nyvvt': 'ניווט',
  'kvkpyt-mshymvt-abvdh-hyvm': 'קוקפיט משימות עבודה היום cockpit',
  'msk-hntvnym': '☰ מסך הנתונים',
  'tblh-ntvnym-rshymh-synvn': 'טבלה נתונים רשימה סינון data',
  'yybva-mkvbts': '⬆ ייבוא מקובץ CSV',
  'yybva-kvbts': 'ייבוא csv excel קובץ import',
  'dvch-mvtam': '📊 דו״ח מותאם',
  'dvch-mvtam-yytsva-tvvch': 'דוח מותאם ייצוא טווח report export',
  'kpvlym-myzvg-aychvd': 'כפולים מיזוג איחוד dedup merge',
  'tshlvmym-nknsym': '💰 תשלומים נכנסים',
  'tshlvmym-nknsym-slykh': 'תשלומים נכנסים סליקה payments',
  'snkrvn-mndrym': '🔄 סנכרון מנדרים',
  'ndrym-snkrvn': 'נדרים סנכרון nedarim sync',
  'lla-shm': 'ללא שם',
  'ptycht-krtys': 'פתיחת כרטיס',
  'tvrm': 'תורם',
  'xi_hvspt': '➕ הוספת ',
  'xi_aychvd-kpvlym': '🔗 איחוד כפולים · ',
};
