// 🗄️ שמות · חולצו מ-dart-maor/exp-field-defs.dart (מכונת-AST). מטרה→שם; מתחלף פר-וורטיקל.
const Map<String, String> kTerms = {
  'shm-hchvg': 'שם החוג',
  'mvrh-tlpvn': 'מורה + טלפון',
  'mslvl-vmchyr': 'מסלול ומחיר',
  'tpvsh': 'תפוסה',
  'rshymt': 'רשימת ',
  'tshlvmym-btvvch': 'תשלומים בטווח',
  'chysvrym-btvvch': 'חיסורים בטווח',
  'shm-h': 'שם ה',
  'tlpvn': ' + טלפון',
  'kytvt': 'כיתות',
  'khl-yad': 'קהל יעד',
  'yvm-vshah': 'יום ושעה',
  'tlpvn-ytrh': ' + טלפון + יתרה',
  'shk-hknsvt': 'סה\"כ הכנסות',
  'harvt': 'הערות',
  'kvtrt': 'כותרת',
  'svg-ayrva': 'סוג אירוע',
  'taryk-abry': 'תאריך עברי',
  'taryk-lvazy': 'תאריך לועזי',
  'shah': 'שעה',
  'bvtsa': 'בוצע',
  'shm': 'שם',
  't22': 'טלפון',
  'aymyyl': 'אימייל',
  'btvvch-mspr-skvm': ' בטווח (מספר + סכום)',
  'shlb': 'שלב ',
  'tshvbvtharvt-btvvch': 'תשובות/הערות בטווח',
  'taryk-yad-lkshr': 'תאריך יעד לקשר',
  'ktvbt': 'כתובת',
  'ayr': 'עיר',
  'ktgvryh': 'קטגוריה',
  'abvr-my': 'עבור מי',
  'shk': 'סה\"כ ',
  'kl-hzmn': ' (כל הזמן)',
  'dyrvg': 'דירוג',
  'shvlm': 'שולם',
};
