// אטום-דאטה · heb-cal-data — תאום-Dart שנפלט אוטומטית מהמקור-הקדוש (מנוע-ההמרה-מחדש · הכרעה 19).
// המקור: new/atoms/heb-cal-data.mjs — אל תערוך ידנית; שינוי = במקור + פליטה-מחדש.
const Map<String, Object> HEB_CAL = {
  'anchor': -1373427,
  'hebYearOffset': 3761,
  'scanWindowDays': 440,
  'approx': {
    'a': 98496,
    'b': 35975351,
  },
  'leap': {
    'a': 7,
    'b': 1,
    'm': 19,
    't': 7,
  },
  'months': {
    'a': 235,
    'b': 234,
    'c': 19,
  },
  'carry': {
    'base': 29,
    'p0': 12084,
    'q': 13753,
    'parts': 25920,
  },
  'postpone': {
    'm': 3,
    'k': 7,
    't': 3,
  },
  'span': {
    'hi': 356,
    'lo': 382,
  },
  'yearLens': {
    'longMid': [
      355,
      385,
    ],
    'shortMid': [
      353,
      383,
    ],
  },
  'shortMonths': [
    2,
    4,
    6,
    10,
    13,
  ],
  'flexLong': 8,
  'flexShort': 9,
  'leapFlex': 12,
  'monthsInLeap': 13,
  'monthsInPlain': 12,
  'shortLen': 29,
  'longLen': 30,
  'nisan': 1,
  'tishrei': 7,
  'names': [
    'ניסן',
    'אייר',
    'סיוון',
    'תמוז',
    'אב',
    'אלול',
    'תשרי',
    'חשוון',
    'כסלו',
    'טבת',
    'שבט',
    'אדר',
    'אדר ב׳',
  ],
  'leapName12': 'אדר א׳',
  'greg': {
    'yearDays': 365,
    'c4': 4,
    'c100': 100,
    'c400': 400,
    'mA': 367,
    'mB': 362,
    'mC': 12,
    'leapAdj': -1,
    'plainAdj': -2,
  },
};
