// אטום-דאטה · lib-cloud-terms — תאום-Dart שנפלט אוטומטית מהמקור-הקדוש (מנוע-ההמרה-מחדש · הכרעה 19).
// המקור: new/atoms/lib-cloud-terms.mjs — אל תערוך ידנית; שינוי = במקור + פליטה-מחדש.
const Map<String, String> LIB_CLOUD_TERMS = {
  'k1': 'default',
  'k2': 'donations',
  'k3': 'seq',
  'k4': 'receiptSeq',
  'k5': 'donationSeq',
  'k6': 'shopReceiptSeq',
  'k7': 'auth/invalid-credential',
  'k8': 'auth/invalid-login-credentials',
  'k9': 'auth/wrong-password',
  'k10': 'auth/user-not-found',
  'k11': 'auth/invalid-email',
  'k12': 'אימייל או סיסמה שגויים',
  'k13': 'auth/network-request-failed',
  'k14': 'אין חיבור לאינטרנט — בדקו את החיבור ונסו שוב',
  'k15': 'auth/too-many-requests',
  'k16': 'יותר מדי ניסיונות — המתינו מספר דקות ונסו שוב',
  'k17': 'auth/user-disabled',
  'k18': 'החשבון הושבת — פנו למנהל המערכת',
  'k19': 'הכניסה נכשלה — נסו שוב',
  'k20': 'auth/email-already-in-use',
  'k21': 'האימייל כבר רשום — נסו להתחבר או לאפס סיסמה',
  'k22': 'auth/weak-password',
  'k23': 'הסיסמה חלשה מדי — לפחות 6 תווים',
  'k24': 'כתובת האימייל אינה תקינה',
  'k25': 'auth/operation-not-allowed',
  'k26': 'ההרשמה סגורה כרגע — פנו למנהל המערכת',
  'k27': 'לא נמצא משתמש עם האימייל הזה',
  'k28': 'הסיסמה הנוכחית שגויה',
  'k29': 'הסיסמה החדשה חלשה מדי — לפחות 6 תווים',
  'k30': 'number',
  'k31': 'כתובת-משיכה לא-תקינה (חייבת https)',
  'k32': 'root',
  'k33': 'org',
  'k34': 'full',
  'k35': 'reset',
  'k36': 'vault',
  'k37': 'הענן לא אותחל — פנו למנהל המערכת',
  'k38': 'auditlog',
  'k39': 'אין משתמש מחובר — התחברו ונסו שוב',
  'k40': 'skey',
  'k41': 'pkey',
  'k42': 'string',
  'k43': 'נתוני הענן אינם בפורמט מוכר — לא בוצע סנכרון',
  'k44': 'removed',
  'k45': 'nedarimDonors',
  'k46': 'incomingPayments',
  'k47': 'status',
  'k48': 'pending',
  'k49': 'provider',
  'k50': 'נדרשת התחברות-ענן',
  'k51': 'POST',
  'k52': 'Bearer ',
  'k53': 'משיכה נכשלה (',
  'k54': 'handled',
  'k55': 'smsOutbox',
  'k56': 'mailOutbox',
};
