// אטום-דאטה · plan-demo-cleanup-strings — תאום-Dart שנפלט אוטומטית מהמקור-הקדוש (מנוע-ההמרה-מחדש · הכרעה 19).
// המקור: new/atoms/plan-demo-cleanup-strings.mjs — אל תערוך ידנית; שינוי = במקור + פליטה-מחדש.
const Map<String, String> PLAN_DEMO_CLEANUP_T = {
  'k1': 'name',
  'k2': 'father',
  'k3': 'mother',
  'k4': 'phone',
  'k5': 'phone2',
  'k6': 'city',
  'k7': 'address',
  'k8': 'email',
  'k9': 'idNum',
  'k10': 'cat',
  'k11': 'forWho',
  'k12': 'description',
  'k13': 'price',
  'k14': 'price1',
  'k15': 'price2',
  'k16': 'specialty',
  'k17': 'location',
  'k18': 'cap',
  'k19': 'title',
  'k20': 'type',
  'k21': 'customType',
  'k22': 'notes',
  'k23': 'time',
  'k24': 'area',
  'k25': 'note',
  'k26': 'goal',
  'k27': 'kind',
  'k28': 'value',
  'k29': 'basePrice',
  'k30': 'label',
  'k31': 'desc',
  'k32': 'sku',
  'k33': '(ללא שם)',
  'k34': 'families',
  'k35': 'enrollments',
  'k36': 'courses',
  'k37': 'deliveries',
  'k38': 'distributionDays',
  'k39': 'volunteers',
  'k40': 'shopAssignments',
  'k41': 'shopProducts',
  'k42': 'tzBoxes',
  'k43': 'tzCoordinators',
};
