// אטום-דאטה · sections-strings — תאום-Dart שנפלט אוטומטית מהמקור-הקדוש
// (מנוע-ההמרה-מחדש · הכרעה 19) המקור: new/atoms/sections-strings.mjs — אל תערוך ידנית; שינוי = במקור + פליטה-מחדש.
const Map<String, String> S = {
  'k0': 'families',
  'k1': 'משפחות',
  'k2': 'nav.families',
  'k3': 'entity.family',
  'k4': 'entity.familyOf',
  'k5': 'entity.member',
  'k6': 'entity.members',
  'k7': 'entity.cred',
  'k8': 'courses',
  'k9': 'חוגים',
  'k10': 'nav.courses',
  'k11': 'entity.course',
  'k12': 'entity.teacher',
  'k13': 'entity.enrollment',
  'k14': 'entity.enrollments',
  'k15': 'entity.student',
  'k16': 'entity.students',
  'k17': 'calendar',
  'k18': 'לוח שנה',
  'k19': 'nav.calendar',
  'k20': 'diary',
  'k21': 'יומן חדרים',
  'k22': 'nav.diary',
  'k23': 'entity.room',
  'k24': 'entity.rooms',
  'k25': 'supporters',
  'k26': 'תורמים',
  'k27': 'nav.supporters',
  'k28': 'entity.supporter',
  'k29': 'entity.donation',
  'k30': 'entity.donations',
  'k31': 'nav.ayin',
  'k32': 'entity.ayinItem',
  'k33': 'entity.ayinUnit',
  'k34': 'ayin.stage.new',
  'k35': 'ayin.stage.lead',
  'k36': 'ayin.stage.eyes',
  'k37': 'ayin.stage.answer',
  'k38': 'ayin.stage.done',
  'k39': 'tzedaka',
  'k40': 'קופות צדקה',
  'k41': 'nav.tzedaka',
  'k42': 'entity.tzCoordinator',
  'k43': 'entity.tzBox',
  'k44': 'entity.tzCampaign',
  'k45': 'shop',
  'k46': 'חנות',
  'k47': 'nav.shop',
  'k48': 'entity.shopProduct',
  'k49': 'entity.shopStore',
  'k50': 'entity.shopCriterion',
  'k51': 'entity.shopAssignment',
  'k52': 'entity.shopItem',
  'k53': 'shop7',
  'k54': 'חלוקה',
  'k55': 'nav.shop7',
  'k56': 'entity.volunteer',
  'k57': 'entity.volunteers',
  'k58': 'reports',
  'k59': 'דוחות',
  'k60': 'nav.reports',
  'k61': 'home',
  'k62': 'מסך הבית',
  'k63': 'nav.timer',
  'k64': 'nav.cashbox',
  'k65': 'nav.bodymap',
  'k66': 'settings',
  'k67': 'הגדרות',
  'k68': 'core',
  'k69': 'ליבה',
  'k70': 'shell',
  'k71': 'מעטפת וניווט',
  'k72': 'signup',
  'k73': 'מסך ההרשמה',
};
