import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'src/extractor.dart';
import 'src/models.dart';
import 'src/logic_models.dart';
import 'src/data_models.dart';
import 'src/primitive_models.dart';
import 'src/journey_models.dart';
import 'src/async_models.dart';
import 'src/backend_models.dart';
import 'src/registry_index.dart';

export 'src/models.dart';
export 'src/extractor.dart' show decomposeScreen;
export 'src/registry_index.dart' show RegistryIndex;
export 'src/logic_models.dart';
export 'src/logic_extractor.dart' show decomposeModule;
export 'src/data_models.dart';
export 'src/data_extractor.dart' show decomposeData;
export 'src/primitive_models.dart';
export 'src/primitive_extractor.dart' show decomposePrimitives;
export 'src/journey_models.dart';
export 'src/journey_extractor.dart' show decomposeJourneys, decomposeJourneyGraph;
export 'src/async_models.dart';
export 'src/async_extractor.dart' show decomposeAsync, decomposeAsyncOverview;
export 'src/backend_models.dart';
export 'src/backend_extractor.dart' show decomposeBackend, decomposeBackendOverview;

const _json = JsonEncoder.withIndent('  ');

/// Decompose [sourcePath] against [registryPath] and return the model. Pure —
/// no I/O — so the golden test can compare in-memory. [screenName] overrides the
/// logical screen key (default = file basename).
ScreenDecomposition decompose(
  String sourcePath,
  String registryPath, {
  String? screenName,
}) {
  final registry = RegistryIndex.fromFile(registryPath);
  return decomposeScreen(sourcePath, registry, screenName: screenName);
}

/// Render every output file for [d] into a `{name: contents}` map — the exact
/// bytes written to `knowledge/screens/<screen>/`. Kept as a pure map so the
/// golden test asserts on it without touching disk.
Map<String, String> renderFiles(ScreenDecomposition d) {
  final files = <String, String>{};
  files['screen.json'] = '${_json.convert(d.toJson())}\n';
  files['registry.json'] = '${_json.convert(d.registry.toJson())}\n';
  files['index.md'] = _indexMd(d);
  for (final a in d.atoms) {
    final base = _slug(a.name);
    files['$base.json'] = '${_json.convert(a.toJson())}\n';
    files['$base.md'] = _atomMd(d.screen, a);
  }
  return files;
}

/// Write [renderFiles] to `<outDir>/<screen>/`.
void writeOut(ScreenDecomposition d, String outDir) {
  final dir = Directory(p.join(outDir, d.screen));
  dir.createSync(recursive: true);
  renderFiles(d).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

/// One screen's batch result.
class BatchResult {
  BatchResult(this.file, this.screen, this.atoms, this.matched, this.total,
      {this.error});
  final String file;
  final String screen;
  final int atoms;
  final int matched;
  final int total;
  final String? error;

  /// A "full" save = a real decomposition (a composer + at least one section).
  bool get full => error == null && atoms > 1;
  bool get skipped => error == null && atoms <= 1;
}

/// Decompose every `*.dart` under [screensDir] (non-recursively), writing each to
/// `<outDir>/<basename>/`, cross-checking against [registryPath] parsed ONCE.
/// Returns a per-file result list. Files with no widget class (or a parse error)
/// are recorded, never fatal.
List<BatchResult> decomposeBatch(
  String screensDir,
  String registryPath,
  String outDir,
) {
  final registry = RegistryIndex.fromFile(registryPath);
  final files = Directory(screensDir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .map((f) => f.path)
      .toList()
    ..sort();
  final results = <BatchResult>[];
  for (final file in files) {
    final screen = p.basenameWithoutExtension(file);
    try {
      final d = decomposeScreen(file, registry, screenName: screen);
      if (d.atoms.isNotEmpty) writeOut(d, outDir);
      results.add(BatchResult(
        p.basename(file),
        screen,
        d.atoms.length,
        d.registry.matched,
        d.registry.total,
      ));
    } on Object catch (e) {
      results.add(BatchResult(p.basename(file), screen, 0, 0, 0,
          error: e.toString().split('\n').first));
    }
  }
  return results;
}

String _slug(String className) {
  var s = className.startsWith('_') ? className.substring(1) : className;
  // CamelCase → kebab: SmartHomeBody → smart-home-body
  final b = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    final ch = s[i];
    if (ch.toUpperCase() == ch && ch.toLowerCase() != ch && i > 0) b.write('-');
    b.write(ch.toLowerCase());
  }
  return b.toString();
}

String _indexMd(ScreenDecomposition d) {
  final b = StringBuffer()
    ..writeln('# ${d.screen} — atom decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose`. Do not hand-edit —')
    ..writeln('> re-run the decomposer. Source: `${d.sourcePath}`.')
    ..writeln()
    ..writeln('- **Atoms:** ${d.atoms.length}')
    ..writeln('- **Registry:** ${d.registry.matched}/${d.registry.total} ids matched against `element_registry`')
    ..writeln('- **Gaps:** ${d.atoms.fold<int>(0, (s, a) => s + a.unregistered.length)} unregistered text nodes across the screen')
    ..writeln()
    ..writeln('| # | atom | role | section | variant | n·e·f | extractable | gaps |')
    ..writeln('|---|------|------|---------|---------|-------|-------------|------|');
  for (var i = 0; i < d.atoms.length; i++) {
    final a = d.atoms[i];
    final variant = a.variant == null
        ? '—'
        : '${a.variant}${a.gate != null ? '·${a.gate}' : ''}';
    b.writeln('| ${i + 1} | `${a.name}` | ${a.role} | ${a.section ?? '—'} '
        '| $variant | ${a.nodes.length}·${a.edges.length}·${a.flows.length} '
        '| ${a.contract.extractable} | ${a.unregistered.length} |');
  }
  b
    ..writeln()
    ..writeln('## Registry reconciliation (${d.registry.matched}/${d.registry.total})')
    ..writeln();
  for (final r in d.registry.entries) {
    b.writeln('- ${r.ok ? '✅' : '❌'} `${r.id}` — `${r.atom}`');
  }
  return b.toString();
}

String _atomMd(String screen, Atom a) {
  final variantTag = a.variant == null
      ? ''
      : ' · ${a.variant}${a.gate != null ? ' (gated `${a.gate}`)' : ''}';
  final b = StringBuffer()
    ..writeln('# ${a.name}')
    ..writeln()
    ..writeln('- **screen:** `$screen`')
    ..writeln('- **role:** ${a.role}${a.section != null ? ' · section `${a.section}`' : ''}$variantTag')
    ..writeln()
    ..writeln('## עצם · object (${a.nodes.length})')
    ..writeln()
    ..writeln('> registry ${a.registeredCount} · mapped ${a.nodes.where((n) => n.registryOk).length}/${a.registeredCount} · **unregistered ${a.unregistered.length}**')
    ..writeln();
  if (a.nodes.isEmpty) {
    b.writeln('_(no text nodes)_');
  } else {
    for (final n in a.nodes) {
      final reg = n.registryId == null
          ? ' · — לא-רשום'
          : ' · `${n.registryId}` ${n.registryOk ? '✅' : '❌'}';
      final txt = n.text.isEmpty ? '' : ' "${n.text}"';
      b.writeln('- **${n.kind}**$txt$reg');
    }
  }
  b
    ..writeln()
    ..writeln('## חיבורים · connections (${a.edges.length})')
    ..writeln();
  if (a.edges.isEmpty) {
    b.writeln('_(no edges)_');
  } else {
    for (final e in a.edges) {
      b.writeln('- **${e.kind}** · `${e.via}` → `${e.target}`');
    }
  }
  b
    ..writeln()
    ..writeln('## התנהגות · behaviour (${a.flows.length})')
    ..writeln();
  if (a.flows.isEmpty) {
    b.writeln('_(no flows)_');
  } else {
    for (final f in a.flows) {
      b.writeln('- **${f.trigger}** → _${f.mechanism}_ `${f.detail}` → ${f.effect}');
    }
  }
  b
    ..writeln()
    ..writeln('## floor · external functions (${a.floor.length})')
    ..writeln();
  if (a.floor.isEmpty) {
    b.writeln('_(none)_');
  } else {
    for (final fn in a.floor) {
      b.writeln('- `$fn`');
    }
  }
  b
    ..writeln()
    ..writeln('## חוזה-רכיב · contract + gaps')
    ..writeln()
    ..writeln('- **extractable:** `${a.contract.extractable}`')
    ..writeln('- **props:** ${a.contract.props.isEmpty ? '—' : a.contract.props.map((p) => '`$p`').join(' · ')}');
  if (a.contract.untangle.isNotEmpty) {
    b.writeln('- **untangle:**');
    for (final u in a.contract.untangle) {
      b.writeln('  - $u');
    }
  }
  b.writeln('- **gaps:** ${a.unregistered.isEmpty ? 'none (all registry-backed)' : '${a.unregistered.length} unregistered — ${a.unregistered.map((t) => '"$t"').join(' · ')}'}');
  return b.toString();
}

// ─── logic decomposition (DECOMP-DEPTH phase 0) ───────────────────────────────

/// Render every output file for a logic [module] — `module.logic.json` (the full
/// machine model) + one `<fn>.logic.md` per atom (the human view). Pure map so
/// the caller decides where (or whether) to write.
Map<String, String> renderLogicFiles(ModuleDecomposition module) {
  final files = <String, String>{};
  files['module.logic.json'] = '${_json.convert(module.toJson())}\n';
  for (final a in module.atoms) {
    files['${_logicSlug(a.fn)}.logic.md'] = _logicMd(module, a);
  }
  return files;
}

/// Write [renderLogicFiles] to `<outDir>/<module>/`.
void writeLogicOut(ModuleDecomposition module, String outDir) {
  final dir = Directory(p.join(outDir, module.module));
  dir.createSync(recursive: true);
  renderLogicFiles(module).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

/// Kebab slug that KEEPS the private-underscore so `isPipe` and `_isPipe` don't
/// collide (a leading `_` becomes a `p_` prefix — filesystem-safe, still readable).
String _logicSlug(String fn) {
  final private = fn.startsWith('_');
  final s = _slug(fn); // strips the leading `_` and kebabs
  return private ? 'p_$s' : s;
}

String _logicMd(ModuleDecomposition m, LogicAtom a) {
  String list(Iterable<String> xs) =>
      xs.isEmpty ? '_none_' : xs.map((x) => '`$x`').join(' · ');
  final b = StringBuffer()
    ..writeln('# ${a.fn} — logic decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (logic). Read-only —')
    ..writeln('> re-run the decomposer. Module: `${m.module}` · `${m.sourcePath}`.')
    ..writeln()
    ..writeln('## עצם · object')
    ..writeln('- **kind:** ${a.kind}')
    ..writeln('- **signature:** `${a.signature}`')
    ..writeln('- **constants:** ${list(a.constants)}')
    ..writeln()
    ..writeln('## חיבורים · connections')
    ..writeln('- **reads:** ${list(a.reads.map((r) => '${r.name}${r.transitive ? '↝' : ''}'))}')
    ..writeln('- **writes:** ${list(a.writes.map((w) => '${w.kind}:${w.name}${w.transitive ? '↝' : ''}'))}')
    ..writeln('- **calls:** ${list(a.calls.map((c) => c.name))}')
    ..writeln('- **called-by:** ${list(a.calledBy)}')
    ..writeln('- **gated-by:** ${list(a.gatedBy)}')
    ..writeln('  <br/>(`↝` = reached transitively, through a call)')
    ..writeln()
    ..writeln('## התנהגות · behaviour (algorithm)');
  for (final s in a.steps) {
    b.writeln('- **${s.kind}** — ${s.detail}');
  }
  b
    ..writeln()
    ..writeln('## floor')
    ..writeln('- ${list(a.floor)}')
    ..writeln()
    ..writeln('## חוזה · contract')
    ..writeln('- **input:** `${a.contract.input}`')
    ..writeln('- **output:** `${a.contract.output}`')
    ..writeln('- **purity:** ${a.contract.purity}');
  if (a.contract.precond.isNotEmpty) {
    b.writeln('- **precond:**');
    for (final p in a.contract.precond) {
      b.writeln('  - $p');
    }
  }
  if (a.contract.nullReturn != null) {
    b.writeln('- **null when:** ${a.contract.nullReturn}');
  }
  b.writeln('- **throws:** ${list(a.contract.throws)}');
  return b.toString();
}

// ─── data decomposition (DECOMP-DEPTH phase D) ────────────────────────────────

/// Render every output file for a data [module] — `module.data.json` + one
/// `<entity>.data.md` per entity.
Map<String, String> renderDataFiles(DataModuleDecomposition module) {
  final files = <String, String>{};
  files['module.data.json'] = '${_json.convert(module.toJson())}\n';
  for (final e in module.entities) {
    files['${_slug(e.entity)}.data.md'] = _dataMd(module, e);
  }
  return files;
}

/// Write [renderDataFiles] to `<outDir>/<module>/`.
void writeDataOut(DataModuleDecomposition module, String outDir) {
  final dir = Directory(p.join(outDir, module.module));
  dir.createSync(recursive: true);
  renderDataFiles(module).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

// ─── backend decomposition (DECOMP-DEPTH phase B) ─────────────────────────────

/// Render one backend [module] — `module.backend.json` + `<module>.backend.md`.
Map<String, String> renderBackendFiles(BackendModuleDecomposition module) {
  final b = StringBuffer()
    ..writeln('# ${module.module} — backend decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (backend). Read-only —')
    ..writeln('> re-run the decomposer. Source: `${module.sourcePath}`.')
    ..writeln()
    ..writeln('| function | trigger | auth | reads | writes | calls | error codes |')
    ..writeln('|---|---|---|---|---|---|---|');
  for (final f in module.functions) {
    b.writeln('| `${f.name}` | ${f.trigger} | ${f.authGated ? '🔒' : '—'} '
        '| ${_j(f.reads)} | ${_j(f.writes)} | ${_j(f.calls)} | ${_j(f.errorCodes)} |');
  }
  return <String, String>{
    'module.backend.json': '${_json.convert(module.toJson())}\n',
    '${_slug(module.module)}.backend.md': b.toString(),
  };
}

/// Write [renderBackendFiles] to `<outDir>/<module>/`.
void writeBackendOut(BackendModuleDecomposition module, String outDir) {
  final dir = Directory(p.join(outDir, module.module));
  dir.createSync(recursive: true);
  renderBackendFiles(module).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

/// Render the merged backend [overview] — `overview.backend.json` + `OVERVIEW.md`.
Map<String, String> renderBackendOverview(BackendOverview overview) {
  final b = StringBuffer()
    ..writeln('# backend — the Cloud Functions surface')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (backend). Read-only.')
    ..writeln()
    ..writeln('- **functions:** ${overview.functions.length} — '
        '**${overview.callables} callable** (`onCall`) · '
        '**${overview.triggers} firestore triggers** (`onDocument*`) · '
        '**${overview.scheduled} scheduled** (`onSchedule`)')
    ..writeln('- **error codes (the typed failure surface):** '
        '${overview.allErrorCodes.map((c) => '`$c`').join(' · ')}')
    ..writeln()
    ..writeln('> The client mirrors these: a `HttpsError("failed-precondition", …)`'
        ' here becomes an `OrderFunctionsException` there (see `knowledge/async`).')
    ..writeln()
    ..writeln('| function | trigger | auth | reads | writes | calls | error codes |')
    ..writeln('|---|---|---|---|---|---|---|');
  final sorted = [...overview.functions]
    ..sort((a, z) => a.name.compareTo(z.name));
  for (final f in sorted) {
    b.writeln('| `${f.name}` | ${f.trigger} | ${f.authGated ? '🔒' : '—'} '
        '| ${_j(f.reads)} | ${_j(f.writes)} | ${_j(f.calls)} | ${_j(f.errorCodes)} |');
  }
  return <String, String>{
    'overview.backend.json': '${_json.convert(overview.toJson())}\n',
    'OVERVIEW.md': b.toString(),
  };
}

String _j(List<String> xs) => xs.isEmpty ? '—' : xs.map((x) => '`$x`').join(' ');

// ─── async decomposition (DECOMP-DEPTH phase async) ───────────────────────────

/// Render one async [module] — `module.async.json` + `<module>.async.md`.
Map<String, String> renderAsyncFiles(AsyncModuleDecomposition module) {
  final b = StringBuffer()
    ..writeln('# ${module.module} — async decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (async). Read-only —')
    ..writeln('> re-run the decomposer. Source: `${module.sourcePath}`.')
    ..writeln()
    ..writeln('## Providers')
    ..writeln('| provider | kind | async? | backing | line |')
    ..writeln('|---|---|---|---|---|');
  for (final pr in module.providers) {
    b.writeln('| `${pr.name}` | ${pr.kind} | ${pr.async ? '⏳ async' : 'sync'} '
        '| ${pr.backing} | ${pr.line} |');
  }
  b
    ..writeln()
    ..writeln('## Consumers (`.when`)');
  if (module.consumers.isEmpty) {
    b.writeln('- _none_');
  } else {
    b
      ..writeln('| source | line | states | error→empty (#3) | empty-in-data |')
      ..writeln('|---|---|---|---|---|');
    for (final c in module.consumers) {
      final states = [
        if (c.loading) 'loading',
        if (c.error) 'error',
        if (c.data) 'data'
      ].join('·');
      b.writeln('| `${c.source}` | ${c.line} | $states '
          '| ${c.errorFoldsToEmpty ? '✅' : '—'} '
          '| ${c.emptyInData ? '✅' : '—'} |');
    }
  }
  b
    ..writeln()
    ..writeln('## Typed exceptions');
  if (module.exceptions.isEmpty) {
    b.writeln('- _none_');
  } else {
    for (final e in module.exceptions) {
      b.writeln('- `${e.name}` (line ${e.line}) · ${e.throwSites} throw-site(s)');
    }
  }
  return <String, String>{
    'module.async.json': '${_json.convert(module.toJson())}\n',
    '${_slug(module.module)}.async.md': b.toString(),
  };
}

/// Write [renderAsyncFiles] to `<outDir>/<module>/`.
void writeAsyncOut(AsyncModuleDecomposition module, String outDir) {
  final dir = Directory(p.join(outDir, module.module));
  dir.createSync(recursive: true);
  renderAsyncFiles(module).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

/// Render the merged async [overview] — `overview.async.json` + `OVERVIEW.md`.
Map<String, String> renderAsyncOverview(AsyncOverview overview) {
  final byBacking = <String, int>{};
  for (final pr in overview.providers.where((p) => p.async)) {
    byBacking[pr.backing] = (byBacking[pr.backing] ?? 0) + 1;
  }
  final b = StringBuffer()
    ..writeln('# async — the loading state machine, and the split')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (async). Read-only.')
    ..writeln()
    ..writeln('- **providers:** ${overview.providers.length} — '
        '**${overview.asyncProviders} async** (Stream/Future) · '
        '**${overview.syncProviders} sync** (State/plain, cannot fail)')
    ..writeln('- **async backing:** ${byBacking.entries.map((e) => '${e.value} ${e.key}').join(' · ')}')
    ..writeln('- **`.when` consumers:** ${overview.consumers.length} '
        '(${overview.errorFoldedConsumers} fold error→empty · HARD RULE #3)')
    ..writeln('- **typed exceptions:** ${overview.exceptions.length}')
    ..writeln()
    ..writeln('## The split (step 85)')
    ..writeln()
    ..writeln('The catalog / cart are **synchronous const data** — no `AsyncValue`, '
        'no loading, empty is ad-hoc. Only **firestore / functions** flow through '
        '`AsyncValue` + `.when`. There is **no uniform async contract**; a sync '
        'provider has **no error path because it cannot fail** — a documented gap, '
        'not a missing feature.')
    ..writeln()
    ..writeln('## Typed exceptions (the repo failure surface)')
    ..writeln();
  for (final e in overview.exceptions) {
    b.writeln('- `${e.name}` · ${e.throwSites} throw-site(s)');
  }
  b
    ..writeln()
    ..writeln('## `.when` consumers — the modeled states')
    ..writeln()
    ..writeln('| source | states | error→empty (#3) | empty-in-data |')
    ..writeln('|---|---|---|---|');
  for (final c in overview.consumers) {
    final states = [
      if (c.loading) 'loading',
      if (c.error) 'error',
      if (c.data) 'data'
    ].join('·');
    b.writeln('| `${c.source}` | $states '
        '| ${c.errorFoldsToEmpty ? '✅' : '—'} '
        '| ${c.emptyInData ? '✅' : '—'} |');
  }
  return <String, String>{
    'overview.async.json': '${_json.convert(overview.toJson())}\n',
    'OVERVIEW.md': b.toString(),
  };
}

// ─── journey decomposition (DECOMP-DEPTH phase N) ─────────────────────────────

/// Render every output file for a journey [module] — `module.journey.json` +
/// one `<module>.journey.md` (from→to edge table).
Map<String, String> renderJourneyFiles(JourneyModuleDecomposition module) {
  return <String, String>{
    'module.journey.json': '${_json.convert(module.toJson())}\n',
    '${_slug(module.module)}.journey.md': _journeyMd(module),
  };
}

/// Write [renderJourneyFiles] to `<outDir>/<module>/`.
void writeJourneyOut(JourneyModuleDecomposition module, String outDir) {
  final dir = Directory(p.join(outDir, module.module));
  dir.createSync(recursive: true);
  renderJourneyFiles(module).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

/// Render the merged journey [graph] — `graph.journey.json` + `GRAPH.md`.
Map<String, String> renderJourneyGraph(JourneyGraph graph) {
  final b = StringBuffer()
    ..writeln('# journeys — the whole graph')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (journeys). Read-only.')
    ..writeln('> Navigator 1.0 imperative — recovered from the pushes, not a route table.')
    ..writeln()
    ..writeln('- **nodes (screens):** ${graph.nodes.length}')
    ..writeln('- **edges (transitions):** ${graph.edges.length}')
    ..writeln('- **route-addressable:** ${graph.nodes.values.where((n) => n.routeAddressable).length}')
    ..writeln('- **provider-swap (Navigator-invisible):** ${graph.edges.where((e) => e.kind == 'provider-swap').length}')
    ..writeln('- **raw-push (off-convention, no route()):** ${graph.edges.where((e) => e.kind == 'raw-push').length}')
    ..writeln('- **dormant (flag-gated):** ${graph.edges.where((e) => e.dormant).length}')
    ..writeln()
    ..writeln('## Bypass surfaces (step 73)')
    ..writeln();
  for (final n in graph.nodes.values.where((n) => n.bypassSurface != null)) {
    b.writeln('- **${n.bypassSurface}** · `${n.screen}`');
  }
  b
    ..writeln()
    ..writeln('## Edges')
    ..writeln()
    ..writeln('| from | → | to | kind | trigger | dormant |')
    ..writeln('|---|---|---|---|---|---|');
  final sorted = [...graph.edges]..sort((a, z) => a.from.compareTo(z.from));
  for (final e in sorted) {
    b.writeln('| `${e.from}` | → | `${e.to}` | ${e.kind} | `${e.trigger}` '
        '| ${e.dormant ? '⚠️ `${e.gate}`' : '—'} |');
  }
  return <String, String>{
    'graph.journey.json': '${_json.convert(graph.toJson())}\n',
    'GRAPH.md': b.toString(),
  };
}

String _journeyMd(JourneyModuleDecomposition m) {
  final b = StringBuffer()
    ..writeln('# ${m.module} — journey decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (journeys). Read-only —')
    ..writeln('> re-run the decomposer. Source: `${m.sourcePath}`.')
    ..writeln()
    ..writeln('## Nodes (screens)')
    ..writeln('| screen | line | route()? | returns value? | bypass |')
    ..writeln('|---|---|---|---|---|');
  for (final n in m.nodes) {
    b.writeln('| `${n.screen}` | ${n.line} '
        '| ${n.routeAddressable ? '`route(${n.routeParams})`' : '—'} '
        '| ${n.returnsValue ? '↑ pop-value' : '—'} '
        '| ${n.bypassSurface ?? '—'} |');
  }
  b
    ..writeln()
    ..writeln('## Edges (transitions)');
  if (m.edges.isEmpty) {
    b.writeln('- _none_');
  } else {
    b
      ..writeln('| from | → | to | kind | trigger | params | dormant |')
      ..writeln('|---|---|---|---|---|---|---|');
    for (final e in m.edges) {
      b.writeln('| `${e.from}` | → | `${e.to}` | ${e.kind} | `${e.trigger}` '
          '| ${e.params.isEmpty ? '—' : '`${e.params}`'} '
          '| ${e.dormant ? '⚠️ `${e.gate}`' : '—'} |');
    }
  }
  return b.toString();
}

// ─── primitive decomposition (DECOMP-DEPTH phase P) ───────────────────────────

/// Render every output file for a primitive [module] — `module.prim.json` (the
/// machine table) + one `<module>.prim.md` (the human contract table, step 69).
Map<String, String> renderPrimitiveFiles(PrimitiveModuleDecomposition module) {
  return <String, String>{
    'module.prim.json': '${_json.convert(module.toJson())}\n',
    '${_slug(module.module)}.prim.md': _primMd(module),
  };
}

/// Write [renderPrimitiveFiles] to `<outDir>/<module>/`.
void writePrimitiveOut(PrimitiveModuleDecomposition module, String outDir) {
  final dir = Directory(p.join(outDir, module.module));
  dir.createSync(recursive: true);
  renderPrimitiveFiles(module).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

String _primMd(PrimitiveModuleDecomposition m) {
  final b = StringBuffer()
    ..writeln('# ${m.module} — primitive contracts')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (primitives). Read-only —')
    ..writeln('> re-run the decomposer. Source: `${m.sourcePath}`.')
    ..writeln()
    ..writeln('> The floor turned from a NAME into a CONTRACT: each row is one')
    ..writeln('> floor-primitive — signature · returns · edge cases · purity.')
    ..writeln()
    ..writeln('| # | primitive | line | signature | returns | pure? |')
    ..writeln('|---|---|---|---|---|---|');
  for (var i = 0; i < m.primitives.length; i++) {
    final pr = m.primitives[i];
    final purity = pr.pure ? '✅ pure' : '❌ ${pr.sideEffect}';
    b.writeln('| ${i + 1} | `${pr.name}` | ${pr.line} | `${pr.signature}` '
        '| `${pr.returns}` | $purity |');
  }
  b
    ..writeln()
    ..writeln('## Edge contracts (step 70 → assertions)')
    ..writeln();
  for (final pr in m.primitives) {
    b.writeln('### `${pr.name}` — `${pr.signature}`');
    if (pr.edges.isEmpty) {
      b.writeln('- _no boundary edges detected (total function)_');
    } else {
      for (final e in pr.edges) {
        b.writeln('- **${e.note}** — _signal_ `${e.signal}`');
      }
    }
    b.writeln();
  }
  return b.toString();
}

String _dataMd(DataModuleDecomposition m, DataEntity e) {
  String flags(DataField f) => [
        if (f.required) 'required',
        if (f.nullable) 'nullable',
        if (f.collection) 'collection',
        if (f.derived) 'DERIVED',
        if (f.defaultValue != null) 'default=${f.defaultValue}',
      ].join(' · ');
  final b = StringBuffer()
    ..writeln('# ${e.entity} — data decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose` (data). Read-only —')
    ..writeln('> re-run the decomposer. Module: `${m.module}` · `${m.sourcePath}`.')
    ..writeln()
    ..writeln('- **kind:** ${e.kind}')
    ..writeln()
    ..writeln('## עצם · object (fields)')
    ..writeln('| field | type | flags |')
    ..writeln('|---|---|---|');
  for (final f in e.fields) {
    b.writeln('| `${f.name}` | `${f.type}` | ${flags(f).isEmpty ? '—' : flags(f)} |');
  }
  b
    ..writeln()
    ..writeln('## חיבורים · connections (relations)');
  if (e.relations.isEmpty) {
    b.writeln('- _none_');
  } else {
    for (final r in e.relations) {
      b.writeln('- **${r.kind}** `${r.field}` → `${r.ref}`${r.collection ? ' (many)' : ''}');
    }
  }
  b
    ..writeln()
    ..writeln('## התנהגות · behaviour')
    ..writeln('- **decoders:** ${e.decoders.isEmpty ? '_none_' : e.decoders.map((d) => '`$d`').join(' · ')}'
        '${e.tolerantDecoder ? '  ⚠️ TOLERANT (malformed input degrades silently — validation debt)' : ''}')
    ..writeln('- **methods:** ${e.behaviour.isEmpty ? '_none_' : e.behaviour.map((x) => '`$x`').join(' · ')}')
    ..writeln()
    ..writeln('## חוזה · contract')
    ..writeln('- **required:** ${e.required.isEmpty ? '_none_' : e.required.map((x) => '`$x`').join(' · ')}')
    ..writeln('- **defaults:** ${e.defaults.isEmpty ? '_none_' : e.defaults.entries.map((x) => '`${x.key}=${x.value}`').join(' · ')}');
  if (e.invariants.isNotEmpty) {
    b.writeln('- **invariants:**');
    for (final inv in e.invariants) {
      b.writeln('  - $inv');
    }
  }
  return b.toString();
}
