import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'src/extractor.dart';
import 'src/models.dart';
import 'src/registry_index.dart';

export 'src/models.dart';
export 'src/extractor.dart' show decomposeScreen;
export 'src/registry_index.dart' show RegistryIndex;

const _json = JsonEncoder.withIndent('  ');

/// Decompose [sourcePath] against [registryPath] and return the model. Pure —
/// no I/O — so the golden test can compare in-memory. [screenName] overrides the
/// logical screen key (default = file basename).
ScreenDecomposition decompose(
  String sourcePath,
  String registryPath, {
  String? screenName,
}) {
  final registry = RegistryIndex.fromFile(registryPath);
  return decomposeScreen(sourcePath, registry, screenName: screenName);
}

/// Render every output file for [d] into a `{name: contents}` map — the exact
/// bytes written to `knowledge/screens/<screen>/`. Kept as a pure map so the
/// golden test asserts on it without touching disk.
Map<String, String> renderFiles(ScreenDecomposition d) {
  final files = <String, String>{};
  files['screen.json'] = '${_json.convert(d.toJson())}\n';
  files['registry.json'] = '${_json.convert(d.registry.toJson())}\n';
  files['index.md'] = _indexMd(d);
  for (final a in d.atoms) {
    final base = _slug(a.name);
    files['$base.json'] = '${_json.convert(a.toJson())}\n';
    files['$base.md'] = _atomMd(d.screen, a);
  }
  return files;
}

/// Write [renderFiles] to `<outDir>/<screen>/`.
void writeOut(ScreenDecomposition d, String outDir) {
  final dir = Directory(p.join(outDir, d.screen));
  dir.createSync(recursive: true);
  renderFiles(d).forEach((name, contents) {
    File(p.join(dir.path, name)).writeAsStringSync(contents);
  });
}

/// One screen's batch result.
class BatchResult {
  BatchResult(this.file, this.screen, this.atoms, this.matched, this.total,
      {this.error});
  final String file;
  final String screen;
  final int atoms;
  final int matched;
  final int total;
  final String? error;

  /// A "full" save = a real decomposition (a composer + at least one section).
  bool get full => error == null && atoms > 1;
  bool get skipped => error == null && atoms <= 1;
}

/// Decompose every `*.dart` under [screensDir] (non-recursively), writing each to
/// `<outDir>/<basename>/`, cross-checking against [registryPath] parsed ONCE.
/// Returns a per-file result list. Files with no widget class (or a parse error)
/// are recorded, never fatal.
List<BatchResult> decomposeBatch(
  String screensDir,
  String registryPath,
  String outDir,
) {
  final registry = RegistryIndex.fromFile(registryPath);
  final files = Directory(screensDir)
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.dart'))
      .map((f) => f.path)
      .toList()
    ..sort();
  final results = <BatchResult>[];
  for (final file in files) {
    final screen = p.basenameWithoutExtension(file);
    try {
      final d = decomposeScreen(file, registry, screenName: screen);
      if (d.atoms.isNotEmpty) writeOut(d, outDir);
      results.add(BatchResult(
        p.basename(file),
        screen,
        d.atoms.length,
        d.registry.matched,
        d.registry.total,
      ));
    } on Object catch (e) {
      results.add(BatchResult(p.basename(file), screen, 0, 0, 0,
          error: e.toString().split('\n').first));
    }
  }
  return results;
}

String _slug(String className) {
  var s = className.startsWith('_') ? className.substring(1) : className;
  // CamelCase → kebab: SmartHomeBody → smart-home-body
  final b = StringBuffer();
  for (var i = 0; i < s.length; i++) {
    final ch = s[i];
    if (ch.toUpperCase() == ch && ch.toLowerCase() != ch && i > 0) b.write('-');
    b.write(ch.toLowerCase());
  }
  return b.toString();
}

String _indexMd(ScreenDecomposition d) {
  final b = StringBuffer()
    ..writeln('# ${d.screen} — atom decomposition')
    ..writeln()
    ..writeln('> Auto-generated by `tools/atom/decompose`. Do not hand-edit —')
    ..writeln('> re-run the decomposer. Source: `${d.sourcePath}`.')
    ..writeln()
    ..writeln('- **Atoms:** ${d.atoms.length}')
    ..writeln('- **Registry:** ${d.registry.matched}/${d.registry.total} ids matched against `element_registry`')
    ..writeln('- **Gaps:** ${d.atoms.fold<int>(0, (s, a) => s + a.unregistered.length)} unregistered text nodes across the screen')
    ..writeln()
    ..writeln('| # | atom | role | section | variant | n·e·f | extractable | gaps |')
    ..writeln('|---|------|------|---------|---------|-------|-------------|------|');
  for (var i = 0; i < d.atoms.length; i++) {
    final a = d.atoms[i];
    final variant = a.variant == null
        ? '—'
        : '${a.variant}${a.gate != null ? '·${a.gate}' : ''}';
    b.writeln('| ${i + 1} | `${a.name}` | ${a.role} | ${a.section ?? '—'} '
        '| $variant | ${a.nodes.length}·${a.edges.length}·${a.flows.length} '
        '| ${a.contract.extractable} | ${a.unregistered.length} |');
  }
  b
    ..writeln()
    ..writeln('## Registry reconciliation (${d.registry.matched}/${d.registry.total})')
    ..writeln();
  for (final r in d.registry.entries) {
    b.writeln('- ${r.ok ? '✅' : '❌'} `${r.id}` — `${r.atom}`');
  }
  return b.toString();
}

String _atomMd(String screen, Atom a) {
  final variantTag = a.variant == null
      ? ''
      : ' · ${a.variant}${a.gate != null ? ' (gated `${a.gate}`)' : ''}';
  final b = StringBuffer()
    ..writeln('# ${a.name}')
    ..writeln()
    ..writeln('- **screen:** `$screen`')
    ..writeln('- **role:** ${a.role}${a.section != null ? ' · section `${a.section}`' : ''}$variantTag')
    ..writeln()
    ..writeln('## עצם · object (${a.nodes.length})')
    ..writeln()
    ..writeln('> registry ${a.registeredCount} · mapped ${a.nodes.where((n) => n.registryOk).length}/${a.registeredCount} · **unregistered ${a.unregistered.length}**')
    ..writeln();
  if (a.nodes.isEmpty) {
    b.writeln('_(no text nodes)_');
  } else {
    for (final n in a.nodes) {
      final reg = n.registryId == null
          ? ' · — לא-רשום'
          : ' · `${n.registryId}` ${n.registryOk ? '✅' : '❌'}';
      final txt = n.text.isEmpty ? '' : ' "${n.text}"';
      b.writeln('- **${n.kind}**$txt$reg');
    }
  }
  b
    ..writeln()
    ..writeln('## חיבורים · connections (${a.edges.length})')
    ..writeln();
  if (a.edges.isEmpty) {
    b.writeln('_(no edges)_');
  } else {
    for (final e in a.edges) {
      b.writeln('- **${e.kind}** · `${e.via}` → `${e.target}`');
    }
  }
  b
    ..writeln()
    ..writeln('## התנהגות · behaviour (${a.flows.length})')
    ..writeln();
  if (a.flows.isEmpty) {
    b.writeln('_(no flows)_');
  } else {
    for (final f in a.flows) {
      b.writeln('- **${f.trigger}** → _${f.mechanism}_ `${f.detail}` → ${f.effect}');
    }
  }
  b
    ..writeln()
    ..writeln('## floor · external functions (${a.floor.length})')
    ..writeln();
  if (a.floor.isEmpty) {
    b.writeln('_(none)_');
  } else {
    for (final fn in a.floor) {
      b.writeln('- `$fn`');
    }
  }
  b
    ..writeln()
    ..writeln('## חוזה-רכיב · contract + gaps')
    ..writeln()
    ..writeln('- **extractable:** `${a.contract.extractable}`')
    ..writeln('- **props:** ${a.contract.props.isEmpty ? '—' : a.contract.props.map((p) => '`$p`').join(' · ')}');
  if (a.contract.untangle.isNotEmpty) {
    b.writeln('- **untangle:**');
    for (final u in a.contract.untangle) {
      b.writeln('  - $u');
    }
  }
  b.writeln('- **gaps:** ${a.unregistered.isEmpty ? 'none (all registry-backed)' : '${a.unregistered.length} unregistered — ${a.unregistered.map((t) => '"$t"').join(' · ')}'}');
  return b.toString();
}
