// ⚛️ אטום-Dart-דאטה (דרגת-חוזה) · schema-fields — קודם מכנית ע"י gen-data-dart.mjs.
// מקור: new/atoms/schema-fields.mjs (אטום-קבוע, צילום-ערך). טוהר: getter top-level,
// אפס import (רק dart:core). חוק-4 — ערך זהה-ביט למקור-ה-JS.
// ההמרה: ‏JS-const ⇒ ‏Dart-const (ליטרל שומר-סדר, LinkedHashMap≡סדר-מפתחות-JS).

/// Verbatim data port of `FIELDS` from new/atoms/schema-fields.mjs.
List<dynamic> get fields => const [
        const {
          'e': 'Member',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Member',
          'n': 'first',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'gender',
          'o': false,
          't': 'Gender',
        },
        const {
          'e': 'Member',
          'n': 'birth',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'Member',
          'n': 'idNum',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'phone2',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'school',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'grade',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'health',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'mSefach',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Member',
          'n': 'mInvite',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Member',
          'n': 'mRecommend',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Member',
          'n': 'mPhotos',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Member',
          'n': 'mVideos',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Member',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Member',
          'n': 'isParent',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'CredLogEntry',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'CredLogEntry',
          'n': 'delta',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'CredLogEntry',
          'n': 'reason',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'FamilyCred',
          'n': 'score',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'FamilyCred',
          'n': 'log',
          'o': false,
          't': 'CredLogEntry[]',
        },
        const {
          'e': 'FamilyDoc',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'FamilyDoc',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'FamilyDoc',
          'n': 'addedAt',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Family',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Family',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'father',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'fatherId',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'mother',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'motherId',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'phone2',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'email',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'city',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'address',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'community',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'maritalStatus',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'language',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'tzedaka',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'fullSefach',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Family',
          'n': 'discount',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'status',
          'o': false,
          't': 'FamilyStatus',
        },
        const {
          'e': 'Family',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Family',
          'n': 'kidsHome',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Family',
          'n': 'kidsMarried',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Family',
          'n': 'members',
          'o': false,
          't': 'Member[]',
        },
        const {
          'e': 'Family',
          'n': 'docs',
          'o': false,
          't': 'FamilyDoc[]',
        },
        const {
          'e': 'Family',
          'n': 'cred',
          'o': false,
          't': 'FamilyCred',
        },
        const {
          'e': 'Family',
          'n': 'createdAt',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'CourseSession',
          'n': 'day',
          'o': false,
          't': 'Weekday',
        },
        const {
          'e': 'CourseSession',
          'n': 'time',
          'o': false,
          't': 'TimeHM',
        },
        const {
          'e': 'CourseSession',
          'n': 'label',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'CourseFile',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'CourseFile',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'CourseFile',
          'n': 'kind',
          'o': false,
          't': '\'image\' | \'file\' | \'link\'',
        },
        const {
          'e': 'CourseFile',
          'n': 'data',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'CourseFile',
          'n': 'mime',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'CourseFile',
          'n': 'size',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Course',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'teacherId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Course',
          'n': 'roomId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Course',
          'n': 'description',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'price',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'price1',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'price2',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'price1Name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'price2Name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'price3',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'price3Name',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'model',
          'o': false,
          't': 'PricingModel',
        },
        const {
          'e': 'Course',
          'n': 'size',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'start',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Course',
          'n': 'end',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Course',
          'n': 'weekday',
          'o': false,
          't': 'Weekday',
        },
        const {
          'e': 'Course',
          'n': 'time',
          'o': false,
          't': 'TimeHM',
        },
        const {
          'e': 'Course',
          'n': 'maxStudents',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'gender',
          'o': false,
          't': 'Gender | \'all\'',
        },
        const {
          'e': 'Course',
          'n': 'ageMin',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'ageMax',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'cat',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'semester',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'sector',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'audience',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'img',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'gradeMin',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'gradeMax',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'sessions',
          'o': false,
          't': 'CourseSession[]',
        },
        const {
          'e': 'Course',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'files',
          'o': true,
          't': 'CourseFile[]',
        },
        const {
          'e': 'Course',
          'n': 'perLesson',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'Course',
          'n': 'lessonPrice',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'lessonPrice1',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'lessonPrice2',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'lessonPrice3',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Course',
          'n': 'year',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Course',
          'n': 'prevYearId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'Absence',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Absence',
          'n': 'reason',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Absence',
          'n': 'makeup',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'Absence',
          'n': 'makeupDate',
          'o': true,
          't': 'IsoDate',
        },
        const {
          'e': 'Absence',
          'n': 'noshow',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'Absence',
          'n': 'justified',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'Payment',
          'n': 'rid',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Payment',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Payment',
          'n': 'amount',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Payment',
          'n': 'method',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Enrollment',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Enrollment',
          'n': 'memberId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Enrollment',
          'n': 'courseId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Enrollment',
          'n': 'plan',
          'o': false,
          't': 'PricingModel',
        },
        const {
          'e': 'Enrollment',
          'n': 'purchased',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Enrollment',
          'n': 'used',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Enrollment',
          'n': 'group',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Enrollment',
          'n': 'absences',
          'o': false,
          't': 'Absence[]',
        },
        const {
          'e': 'Enrollment',
          'n': 'presents',
          'o': true,
          't': 'IsoDate[]',
        },
        const {
          'e': 'Enrollment',
          'n': 'payments',
          'o': false,
          't': 'Payment[]',
        },
        const {
          'e': 'Enrollment',
          'n': 'totalDue',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Enrollment',
          'n': 'dueDate',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'Enrollment',
          'n': 'dueEventId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'Enrollment',
          'n': 'status',
          'o': false,
          't': 'EnrollmentStatus',
        },
        const {
          'e': 'Enrollment',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Enrollment',
          'n': 'enrolledAt',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Enrollment',
          'n': 'endedAt',
          'o': true,
          't': 'IsoDate',
        },
        const {
          'e': 'Enrollment',
          'n': 'paidFull',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'Enrollment',
          'n': 'freq',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Enrollment',
          'n': 'freqUnit',
          'o': true,
          't': '\'week\' | \'month\'',
        },
        const {
          'e': 'Enrollment',
          'n': 'term',
          'o': true,
          't': 'PricingTerm',
        },
        const {
          'e': 'Enrollment',
          'n': 'termMonths',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Enrollment',
          'n': 'tier',
          'o': true,
          't': '\'\' | \'1\' | \'2\' | \'3\'',
        },
        const {
          'e': 'Enrollment',
          'n': 'renew',
          'o': true,
          't': '\'yes\' | \'no\' | \'hold\'',
        },
        const {
          'e': 'Enrollment',
          'n': 'renewNote',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Enrollment',
          'n': 'renewedToId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'Teacher',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Teacher',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'phone2',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'email',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'idNum',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'address',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'specialty',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'payRate',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Teacher',
          'n': 'startDate',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'Teacher',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'payMethod',
          'o': true,
          't': '\'cash\' | \'salary\' | \'check\' | \'\'',
        },
        const {
          'e': 'Teacher',
          'n': 'payToOther',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'Teacher',
          'n': 'payeeName',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'payeePhone',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'payeeIdNum',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'bankName',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'bankBranch',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Teacher',
          'n': 'bankAccount',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Room',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Room',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Room',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Room',
          'n': 'slot',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Room',
          'n': 'cap',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Room',
          'n': 'location',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Room',
          'n': 'rate',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Room',
          'n': 'from',
          'o': false,
          't': 'TimeHM',
        },
        const {
          'e': 'Room',
          'n': 'to',
          'o': false,
          't': 'TimeHM',
        },
        const {
          'e': 'Room',
          'n': 'access',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Room',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Room',
          'n': 'eq',
          'o': false,
          't': 'Record<string, boolean>',
        },
        const {
          'e': 'OrgEvent',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'OrgEvent',
          'n': 'title',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'OrgEvent',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'OrgEvent',
          'n': 'time',
          'o': false,
          't': 'TimeHM',
        },
        const {
          'e': 'OrgEvent',
          'n': 'type',
          'o': false,
          't': 'EventType',
        },
        const {
          'e': 'OrgEvent',
          'n': 'customType',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'OrgEvent',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'OrgEvent',
          'n': 'price',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'OrgEvent',
          'n': 'roomId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'OrgEvent',
          'n': 'famId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'OrgEvent',
          'n': 'spId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'OrgEvent',
          'n': 'priority',
          'o': false,
          't': 'EventPriority',
        },
        const {
          'e': 'OrgEvent',
          'n': 'done',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Donation',
          'n': 'rid',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Donation',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Donation',
          'n': 'amount',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Donation',
          'n': 'cur',
          'o': false,
          't': '\'₪\' | \'\$\'',
        },
        const {
          'e': 'Donation',
          'n': 'cat',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Donation',
          'n': 'designation',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Donation',
          'n': 'purpose',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'AyinName',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'AyinName',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'AyinName',
          'n': 'eyes',
          'o': false,
          't': 'number | \'\'',
        },
        const {
          'e': 'AyinName',
          'n': 'done',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'AyinName',
          'n': 'rate',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'AyinName',
          'n': 'note',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'AyinName',
          'n': 'days',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'AyinName',
          'n': 'deps',
          'o': true,
          't': 'Id[]',
        },
        const {
          'e': 'KitItem',
          'n': 'label',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'KitItem',
          'n': 'done',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'WarehouseItem',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'WarehouseItem',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WarehouseItem',
          'n': 'unit',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WarehouseItem',
          'n': 'qty',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'WarehouseItem',
          'n': 'cost',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'AyinAnswer',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'AyinAnswer',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TimeEntry',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'TimeEntry',
          'n': 'hours',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'TimeEntry',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TimeEntry',
          'n': 'rate',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'MatEntry',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'MatEntry',
          'n': 'qty',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'MatEntry',
          'n': 'cost',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'AyinLog',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'AyinLog',
          'n': 'eyes',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'AyinLog',
          'n': 'name',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'AyinCase',
          'n': 'stage',
          'o': false,
          't': 'AyinStage',
        },
        const {
          'e': 'AyinCase',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'AyinCase',
          'n': 'answeredNote',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'AyinCase',
          'n': 'paid',
          'o': true,
          't': 'boolean',
        },
        const {
          'e': 'AyinCase',
          'n': 'answerPushed',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'AyinCase',
          'n': 'nextTalk',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'AyinCase',
          'n': 'nextTalkTime',
          'o': false,
          't': 'TimeHM',
        },
        const {
          'e': 'AyinCase',
          'n': 'lastTouch',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'AyinCase',
          'n': 'names',
          'o': false,
          't': 'AyinName[]',
        },
        const {
          'e': 'AyinCase',
          'n': 'answers',
          'o': false,
          't': 'AyinAnswer[]',
        },
        const {
          'e': 'AyinCase',
          'n': 'log',
          'o': false,
          't': 'AyinLog[]',
        },
        const {
          'e': 'AyinCase',
          'n': 'time',
          'o': true,
          't': 'TimeEntry[]',
        },
        const {
          'e': 'AyinCase',
          'n': 'mat',
          'o': true,
          't': 'MatEntry[]',
        },
        const {
          'e': 'AyinCase',
          'n': 'kit',
          'o': true,
          't': 'KitItem[]',
        },
        const {
          'e': 'AyinCase',
          'n': 'boardEventIds',
          'o': true,
          't': 'Partial<Record<string, Id>>',
        },
        const {
          'e': 'Hok',
          'n': 'amount',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Hok',
          'n': 'cur',
          'o': false,
          't': '\'₪\' | \'\$\'',
        },
        const {
          'e': 'Hok',
          'n': 'day',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Hok',
          'n': 'method',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Hok',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Hok',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Hok',
          'n': 'startedAt',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Hok',
          'n': 'kevaId',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Supporter',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'email',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'address',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'city',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'idNum',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'extId',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'cat',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'forWho',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'count',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Supporter',
          'n': 'ils',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Supporter',
          'n': 'usd',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Supporter',
          'n': 'first',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'Supporter',
          'n': 'last',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'Supporter',
          'n': 'nextDate',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'Supporter',
          'n': 'nextNote',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Supporter',
          'n': 'photos',
          'o': true,
          't': 'string[]',
        },
        const {
          'e': 'Supporter',
          'n': 'nextEventId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'Supporter',
          'n': 'donations',
          'o': false,
          't': 'Donation[]',
        },
        const {
          'e': 'Supporter',
          'n': 'hok',
          'o': true,
          't': 'Hok',
        },
        const {
          'e': 'Supporter',
          'n': 'ayin',
          'o': true,
          't': 'AyinCase',
        },
        const {
          'e': 'Supporter',
          'n': 'calls',
          'o': true,
          't': 'CallEntry[]',
        },
        const {
          'e': 'NotifPrefs',
          'n': 'email',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'NotifPrefs',
          'n': 'push',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'NotifPrefs',
          'n': 'sms',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'NotifPrefs',
          'n': 'strong',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ReportPrefs',
          'n': 'daily',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ReportPrefs',
          'n': 'weekly',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ReportPrefs',
          'n': 'monthly',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ReportPrefs',
          'n': 'quarterly',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'QuoteTemplate',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'QuoteTemplate',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'QuoteTemplate',
          'n': 'lines',
          'o': false,
          't': '{ name: string',
        },
        const {
          'e': 'DialLogEntry',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'DialLogEntry',
          'n': 'outcome',
          'o': false,
          't': 'DialOutcome',
        },
        const {
          'e': 'DialLogEntry',
          'n': 'note',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'DialLogEntry',
          'n': 'at',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'CallEntry',
          'n': 'at',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'CallEntry',
          'n': 'outcome',
          'o': false,
          't': 'DialOutcome',
        },
        const {
          'e': 'DialerCampaign',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'DialerCampaign',
          'n': 'startedAt',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'DialerCampaign',
          'n': 'queue',
          'o': false,
          't': 'Id[]',
        },
        const {
          'e': 'DialerCampaign',
          'n': 'total',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'DialerCampaign',
          'n': 'log',
          'o': false,
          't': 'DialLogEntry[]',
        },
        const {
          'e': 'UiPrefs',
          'n': 'famView',
          'o': false,
          't': '\'list\' | \'grid\'',
        },
        const {
          'e': 'UiPrefs',
          'n': 'crsView',
          'o': false,
          't': '\'list\' | \'grid\'',
        },
        const {
          'e': 'UiPrefs',
          'n': 'quoteTemplates',
          'o': true,
          't': 'QuoteTemplate[]',
        },
        const {
          'e': 'UiPrefs',
          'n': 'supView',
          'o': true,
          't': '\'list\' | \'grid\'',
        },
        const {
          'e': 'UiPrefs',
          'n': 'receiptFmt',
          'o': true,
          't': '\'txt\' | \'pdf\'',
        },
        const {
          'e': 'UiPrefs',
          'n': 'homeLayout',
          'o': true,
          't': 'string[]',
        },
        const {
          'e': 'UiPrefs',
          'n': 'theme',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'UiPrefs',
          'n': 'accent',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'UiPrefs',
          'n': 'dialer',
          'o': true,
          't': 'DialerCampaign',
        },
        const {
          'e': 'TzScoreEntry',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'TzScoreEntry',
          'n': 'delta',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'TzScoreEntry',
          'n': 'reason',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'famId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'memberId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'startDate',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'score',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'TzCoordinator',
          'n': 'scoreLog',
          'o': false,
          't': 'TzScoreEntry[]',
        },
        const {
          'e': 'TzCollection',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'TzCollection',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'TzCollection',
          'n': 'amount',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'TzCollection',
          'n': 'campaignId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'TzCollection',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzBox',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'TzBox',
          'n': 'num',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzBox',
          'n': 'coordinatorId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'TzBox',
          'n': 'famId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'TzBox',
          'n': 'holderKind',
          'o': false,
          't': '\'donor\' | \'supported\' | \'\'',
        },
        const {
          'e': 'TzBox',
          'n': 'since',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'TzBox',
          'n': 'status',
          'o': false,
          't': 'TzBoxStatus',
        },
        const {
          'e': 'TzBox',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzBox',
          'n': 'collections',
          'o': false,
          't': 'TzCollection[]',
        },
        const {
          'e': 'TzCampaign',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'TzCampaign',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzCampaign',
          'n': 'start',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'TzCampaign',
          'n': 'end',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'TzCampaign',
          'n': 'goal',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'TzCampaign',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'TzCampaign',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzEvent',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'TzEvent',
          'n': 'title',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzEvent',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'TzEvent',
          'n': 'time',
          'o': false,
          't': 'TimeHM | \'\'',
        },
        const {
          'e': 'TzEvent',
          'n': 'kind',
          'o': false,
          't': '\'round\' | \'campaign\' | \'reminder\' | \'cus',
        },
        const {
          'e': 'TzEvent',
          'n': 'coordinatorId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'TzEvent',
          'n': 'boxId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'TzEvent',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'TzEvent',
          'n': 'done',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ShopItem',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopItem',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopItem',
          'n': 'kind',
          'o': false,
          't': 'ShopComponentKind',
        },
        const {
          'e': 'ShopItem',
          'n': 'storeId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'ShopItem',
          'n': 'value',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopItem',
          'n': 'basePrice',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopItem',
          'n': 'stock',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopItem',
          'n': 'minStock',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopItem',
          'n': 'validDays',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopItem',
          'n': 'holidays',
          'o': true,
          't': 'string[]',
        },
        const {
          'e': 'ShopItem',
          'n': 'waits',
          'o': true,
          't': '{ famId: Id',
        },
        const {
          'e': 'ShopItem',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ShopItem',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopComponent',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopComponent',
          'n': 'itemId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopComponent',
          'n': 'kind',
          'o': false,
          't': 'ShopComponentKind',
        },
        const {
          'e': 'ShopComponent',
          'n': 'label',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopComponent',
          'n': 'storeId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'ShopComponent',
          'n': 'value',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopComponent',
          'n': 'basePrice',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopComponent',
          'n': 'stock',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopComponent',
          'n': 'validDays',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'ShopComponent',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopIntake',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopIntake',
          'n': 'itemId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopIntake',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'ShopIntake',
          'n': 'qty',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopIntake',
          'n': 'kind',
          'o': false,
          't': '\'buy\' | \'donation\'',
        },
        const {
          'e': 'ShopIntake',
          'n': 'source',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopIntake',
          'n': 'cost',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopIntake',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopIntake',
          'n': 'expiry',
          'o': true,
          't': 'IsoDate',
        },
        const {
          'e': 'ShopProduct',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopProduct',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopProduct',
          'n': 'desc',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopProduct',
          'n': 'img',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'ShopProduct',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ShopProduct',
          'n': 'components',
          'o': false,
          't': 'ShopComponent[]',
        },
        const {
          'e': 'ShopProduct',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopStore',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopStore',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopStore',
          'n': 'contact',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopStore',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopStore',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'ShopStore',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopCriterion',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopCriterion',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopCriterion',
          'n': 'discountPct',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopCriterion',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'rid',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'voidedAt',
          'o': true,
          't': 'IsoDate',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'voidReason',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'componentId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'holiday',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'paid',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'value',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'ShopRedemption',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'productId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'famId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'memberId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'criterionIds',
          'o': false,
          't': 'Id[]',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'since',
          'o': false,
          't': 'IsoDate | \'\'',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'status',
          'o': false,
          't': 'ShopAssignmentStatus',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopAssignment',
          'n': 'redemptions',
          'o': false,
          't': 'ShopRedemption[]',
        },
        const {
          'e': 'ShopEvent',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'ShopEvent',
          'n': 'title',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopEvent',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'ShopEvent',
          'n': 'time',
          'o': false,
          't': 'TimeHM | \'\'',
        },
        const {
          'e': 'ShopEvent',
          'n': 'kind',
          'o': false,
          't': '\'meeting\' | \'delivery\' | \'holiday\' | \'cu',
        },
        const {
          'e': 'ShopEvent',
          'n': 'assignmentId',
          'o': false,
          't': 'Id | \'\'',
        },
        const {
          'e': 'ShopEvent',
          'n': 'roomId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'ShopEvent',
          'n': 'mainEventId',
          'o': true,
          't': 'Id',
        },
        const {
          'e': 'ShopEvent',
          'n': 'notes',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'ShopEvent',
          'n': 'done',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Volunteer',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Volunteer',
          'n': 'name',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Volunteer',
          'n': 'phone',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Volunteer',
          'n': 'area',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Volunteer',
          'n': 'maxDeliveries',
          'o': true,
          't': 'number',
        },
        const {
          'e': 'Volunteer',
          'n': 'active',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'Volunteer',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Volunteer',
          'n': 'createdAt',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'WorkTask',
          'n': 'id',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'assignee',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'by',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'title',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'ref',
          'o': true,
          't': '{ kind: \'supporter\' | \'family\' | \'course',
        },
        const {
          'e': 'WorkTask',
          'n': 'pri',
          'o': false,
          't': '1 | 2 | 3',
        },
        const {
          'e': 'WorkTask',
          'n': 'due',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'createdAt',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'doneAt',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'WorkTask',
          'n': 'note',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'Delivery',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Delivery',
          'n': 'dayId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Delivery',
          'n': 'assignmentId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Delivery',
          'n': 'volunteerId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Delivery',
          'n': 'familyId',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'Delivery',
          'n': 'status',
          'o': false,
          't': 'DeliveryStatus',
        },
        const {
          'e': 'Delivery',
          'n': 'deliveredAt',
          'o': true,
          't': 'IsoDate',
        },
        const {
          'e': 'Delivery',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Delivery',
          'n': 'signature',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'DistributionDay',
          'n': 'id',
          'o': false,
          't': 'Id',
        },
        const {
          'e': 'DistributionDay',
          'n': 'date',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'DistributionDay',
          'n': 'title',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'DistributionDay',
          'n': 'note',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'DistributionDay',
          'n': 'closed',
          'o': false,
          't': 'boolean',
        },
        const {
          'e': 'DistributionDay',
          'n': 'createdAt',
          'o': false,
          't': 'IsoDate',
        },
        const {
          'e': 'Db',
          'n': 'v',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'savedAt',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Db',
          'n': 'seq',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'receiptSeq',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'donationSeq',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'shopReceiptSeq',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'families',
          'o': false,
          't': 'Family[]',
        },
        const {
          'e': 'Db',
          'n': 'enrollments',
          'o': false,
          't': 'Enrollment[]',
        },
        const {
          'e': 'Db',
          'n': 'courses',
          'o': false,
          't': 'Course[]',
        },
        const {
          'e': 'Db',
          'n': 'events',
          'o': false,
          't': 'OrgEvent[]',
        },
        const {
          'e': 'Db',
          'n': 'rooms',
          'o': false,
          't': 'Room[]',
        },
        const {
          'e': 'Db',
          'n': 'teachers',
          'o': false,
          't': 'Teacher[]',
        },
        const {
          'e': 'Db',
          'n': 'supporters',
          'o': false,
          't': 'Supporter[]',
        },
        const {
          'e': 'Db',
          'n': 'tzCoordinators',
          'o': false,
          't': 'TzCoordinator[]',
        },
        const {
          'e': 'Db',
          'n': 'tzBoxes',
          'o': false,
          't': 'TzBox[]',
        },
        const {
          'e': 'Db',
          'n': 'tzCampaigns',
          'o': false,
          't': 'TzCampaign[]',
        },
        const {
          'e': 'Db',
          'n': 'tzEvents',
          'o': false,
          't': 'TzEvent[]',
        },
        const {
          'e': 'Db',
          'n': 'shopItems',
          'o': false,
          't': 'ShopItem[]',
        },
        const {
          'e': 'Db',
          'n': 'shopProducts',
          'o': false,
          't': 'ShopProduct[]',
        },
        const {
          'e': 'Db',
          'n': 'shopStores',
          'o': false,
          't': 'ShopStore[]',
        },
        const {
          'e': 'Db',
          'n': 'shopCriteria',
          'o': false,
          't': 'ShopCriterion[]',
        },
        const {
          'e': 'Db',
          'n': 'shopAssignments',
          'o': false,
          't': 'ShopAssignment[]',
        },
        const {
          'e': 'Db',
          'n': 'shopEvents',
          'o': false,
          't': 'ShopEvent[]',
        },
        const {
          'e': 'Db',
          'n': 'shopIntakes',
          'o': false,
          't': 'ShopIntake[]',
        },
        const {
          'e': 'Db',
          'n': 'volunteers',
          'o': false,
          't': 'Volunteer[]',
        },
        const {
          'e': 'Db',
          'n': 'distributionDays',
          'o': false,
          't': 'DistributionDay[]',
        },
        const {
          'e': 'Db',
          'n': 'deliveries',
          'o': false,
          't': 'Delivery[]',
        },
        const {
          'e': 'Db',
          'n': 'tasks',
          'o': false,
          't': 'WorkTask[]',
        },
        const {
          'e': 'Db',
          'n': 'warehouse',
          'o': false,
          't': 'WarehouseItem[]',
        },
        const {
          'e': 'Db',
          'n': 'orgName',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Db',
          'n': 'orgSite',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Db',
          'n': 'orgDonate',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'Db',
          'n': 'orgGoal',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'budget',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'usdRate',
          'o': false,
          't': 'number',
        },
        const {
          'e': 'Db',
          'n': 'notif',
          'o': false,
          't': 'NotifPrefs',
        },
        const {
          'e': 'Db',
          'n': 'reports',
          'o': false,
          't': 'ReportPrefs',
        },
        const {
          'e': 'Db',
          'n': 'ui',
          'o': false,
          't': 'UiPrefs',
        },
        const {
          'e': 'Db',
          'n': 'attnDone',
          'o': false,
          't': 'Record<string, string>',
        },
        const {
          'e': 'Db',
          'n': 'security',
          'o': false,
          't': 'SecurityCfg',
        },
        const {
          'e': 'Db',
          'n': 'audit',
          'o': true,
          't': 'AuditEntry[]',
        },
        const {
          'e': 'AuditEntry',
          'n': 'at',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'AuditEntry',
          'n': 'who',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'AuditEntry',
          'n': 'act',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'AuditEntry',
          'n': 'what',
          'o': false,
          't': 'string',
        },
        const {
          'e': 'SecurityCfg',
          'n': 'primary',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'SecurityCfg',
          'n': 'secondary',
          'o': true,
          't': 'string',
        },
        const {
          'e': 'SecurityCfg',
          'n': 'zones',
          'o': true,
          't': 'string[]',
        },
      ];
