// ⚛️ אטום-Dart-דאטה (דרגת-חוזה) · site-ui-labels — קודם מכנית ע"י gen-data-dart.mjs.
// מקור: new/atoms/site-ui-labels.mjs (אטום-קבוע, צילום-ערך). טוהר: getter top-level,
// אפס import (רק dart:core). חוק-4 — ערך זהה-ביט למקור-ה-JS.
// ההמרה: ‏JS-const ⇒ ‏Dart-const (ליטרל שומר-סדר, LinkedHashMap≡סדר-מפתחות-JS).

/// Verbatim data port of `SITE_UI_LABELS` from new/atoms/site-ui-labels.mjs.
Map<String, dynamic> get siteUiLabels => const {
        'he': const {
          'donate': 'לתרומה',
          'contact': 'צור קשר',
          'enter': 'כניסה למערכת',
          'services': 'מה אנחנו עושים',
          'story': 'הסיפור שמאחורי',
          'news': 'כל חודש — מה חדש',
          'gallery': 'רגעים',
          'campaign': 'הקמפיין שלנו',
          'raised': 'גויסו',
          'goal': 'יעד',
          'daysLeft': 'ימים נותרו',
          'call': 'חייגו',
          'whatsapp': 'וואטסאפ',
          'email': 'מייל',
          'poweredBy': 'מופעל על-ידי מאור',
          'dir': 'rtl',
        },
        'en': const {
          'donate': 'Donate',
          'contact': 'Contact',
          'enter': 'Staff login',
          'services': 'What we do',
          'story': 'Our story',
          'news': 'This month',
          'gallery': 'Moments',
          'campaign': 'Our campaign',
          'raised': 'Raised',
          'goal': 'Goal',
          'daysLeft': 'days left',
          'call': 'Call',
          'whatsapp': 'WhatsApp',
          'email': 'Email',
          'poweredBy': 'Powered by Maor',
          'dir': 'ltr',
        },
        'yi': const {
          'donate': 'שפּענדן',
          'contact': 'פֿאַרבינדונג',
          'enter': 'אַרײַנגאַנג',
          'services': 'וואָס מיר טוען',
          'story': 'אונדזער געשיכטע',
          'news': 'דעם חודש',
          'gallery': 'מאָמענטן',
          'campaign': 'אונדזער קאַמפּיין',
          'raised': 'געזאַמלט',
          'goal': 'ציל',
          'daysLeft': 'טעג געבליבן',
          'call': 'רופֿט',
          'whatsapp': 'וואַטסאַפּ',
          'email': 'בליץ-פּאָסט',
          'poweredBy': 'געטריבן דורך מאור',
          'dir': 'rtl',
        },
      };
