// ⚛️ אטום-Dart-דאטה (דרגת-חוזה) · vertical-packs — קודם מכנית ע"י gen-data-dart.mjs.
// מקור: new/atoms/vertical-packs.mjs (אטום-קבוע, צילום-ערך). טוהר: getter top-level,
// אפס import (רק dart:core). חוק-4 — ערך זהה-ביט למקור-ה-JS.
// ההמרה: ‏JS-const ⇒ ‏Dart-const (ליטרל שומר-סדר, LinkedHashMap≡סדר-מפתחות-JS).

/// Verbatim data port of `VERTICAL_PACKS` from new/atoms/vertical-packs.mjs.
List<dynamic> get verticalPacks => const [
        const {
          'id': 'chesed',
          'emoji': '🕊️',
          'label': 'עמותת חסד',
          'sub': 'גמ"ח · קופת צדקה',
          'terms': const <String, dynamic>{},
          'modules': const <String, dynamic>{},
          'theme': 'or-rishon',
        },
        const {
          'id': 'clinic',
          'emoji': '💇',
          'label': 'קליניקה',
          'sub': 'לייזר · קוסמטיקה · רפואה',
          'theme': 'kehila',
          'accent': '#e05a8f',
          'icon': '💇',
          'motion': 'calm',
          'terms': const {
            'nav.families': 'מטופלים',
            'entity.family': 'מטופל',
            'entity.familyOf': 'מטופל',
            'entity.member': 'איש קשר',
            'entity.members': 'אנשי קשר',
            'entity.enrollments': 'טיפולים',
            'entity.student': 'מטופל/ת',
            'entity.students': 'מטופלים',
            'nav.courses': 'חבילות טיפול',
            'entity.course': 'חבילת טיפול',
            'entity.enrollment': 'טיפול',
            'entity.room': 'חדר טיפול',
            'nav.diary': 'חדרי טיפול',
            'nav.supporters': 'מטופלים במעקב',
            'nav.ayin': 'פרוטוקול טיפול',
            'entity.ayinItem': 'אזור טיפול',
            'ayin.stage.new': 'ייעוץ',
            'ayin.stage.lead': 'תוכנית',
            'ayin.stage.eyes': 'טיפול',
            'ayin.stage.answer': 'מעקב',
            'ayin.stage.done': 'שוחרר',
          },
          'modules': const {
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'shop',
          'emoji': '🛍️',
          'label': 'חנות / קמעונאות',
          'sub': 'מכירה · שירות',
          'theme': 'heichal',
          'accent': '#0e9f6e',
          'icon': '🛍️',
          'motion': 'snappy',
          'terms': const {
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'entity.member': 'איש קשר',
            'nav.supporters': 'מועדון לקוחות',
            'entity.supporter': 'לקוח',
            'entity.donation': 'רכישה',
            'entity.donations': 'רכישות',
            'entity.familyOf': 'לקוח',
            'entity.members': 'אנשי קשר',
            'entity.cred': 'נקודות נאמנות',
            'nav.shop': 'מוצרים',
            'entity.shopProduct': 'מוצר',
            'entity.shopAssignment': 'הזמנה',
            'entity.shopCriterion': 'מועדון',
          },
          'modules': const {
            'courses': false,
            'diary': false,
            'tzedaka': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'services',
          'emoji': '💼',
          'label': 'שירותים / פרילנסר',
          'sub': 'ייעוץ · צלם · טיפול-בית',
          'theme': 'tsohar',
          'accent': '#7c5cff',
          'icon': '💼',
          'motion': 'snappy',
          'terms': const {
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'nav.calendar': 'פגישות',
            'entity.familyOf': 'לקוח',
            'entity.member': 'איש קשר',
            'entity.members': 'אנשי קשר',
            'nav.supporters': 'לידים',
            'nav.ayin': 'משפך מכירות',
            'entity.ayinItem': 'ליד',
            'ayin.stage.new': 'פנייה',
            'ayin.stage.lead': 'הצעה',
            'ayin.stage.eyes': 'מו״מ',
            'ayin.stage.answer': 'נסגר',
            'ayin.stage.done': 'סופק',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'rooms',
          'emoji': '🏠',
          'label': 'השכרת חללים',
          'sub': 'חדרי ישיבות · סטודיו · אולמות',
          'theme': 'kehila',
          'accent': '#0d9488',
          'icon': '🏠',
          'motion': 'calm',
          'terms': const {
            'nav.diary': 'לוח חללים',
            'entity.room': 'חלל',
            'entity.rooms': 'חללים',
            'entity.familyOf': 'שוכר',
            'entity.donations': 'תשלומים',
            'nav.families': 'שוכרים',
            'entity.family': 'שוכר',
            'entity.member': 'איש קשר',
            'entity.members': 'אנשי קשר',
            'nav.supporters': 'לקוחות חוזרים',
            'entity.supporter': 'לקוח',
            'entity.donation': 'תשלום',
            'nav.ayin': 'בקשות השכרה',
            'entity.ayinItem': 'בקשה',
            'ayin.stage.new': 'פנייה',
            'ayin.stage.lead': 'הצעת מחיר',
            'ayin.stage.eyes': 'אישור',
            'ayin.stage.answer': 'חוזה',
            'ayin.stage.done': 'הושכר',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'fleet',
          'emoji': '🚗',
          'label': 'צי רכב / השכרה',
          'sub': 'רכבים · ציוד · כלים',
          'theme': 'tsohar',
          'accent': '#e23b3b',
          'icon': '🚗',
          'motion': 'snappy',
          'terms': const {
            'nav.diary': 'לוח רכבים',
            'entity.room': 'רכב',
            'entity.rooms': 'רכבים',
            'entity.familyOf': 'לקוח',
            'entity.donations': 'תשלומי שכירות',
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'entity.member': 'נהג',
            'entity.members': 'נהגים',
            'nav.supporters': 'מועדון לקוחות',
            'entity.supporter': 'לקוח',
            'entity.donation': 'תשלום שכירות',
            'nav.ayin': 'הזמנות רכב',
            'entity.ayinItem': 'הזמנה',
            'ayin.stage.new': 'בקשה',
            'ayin.stage.lead': 'שריון',
            'ayin.stage.eyes': 'מסירה',
            'ayin.stage.answer': 'בשימוש',
            'ayin.stage.done': 'הוחזר',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'garage',
          'emoji': '🔧',
          'label': 'מוסך / מעבדה',
          'sub': 'תיקונים · שירות · טיפולים',
          'theme': 'tsohar',
          'accent': '#5b6b7c',
          'icon': '🔧',
          'motion': 'bold',
          'terms': const {
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'entity.member': 'רכב/פריט',
            'entity.members': 'רכבים/פריטים',
            'nav.diary': 'עמדות עבודה',
            'entity.room': 'עמדה',
            'entity.rooms': 'עמדות',
            'entity.familyOf': 'לקוח',
            'entity.donations': 'תשלומים',
            'nav.supporters': 'לקוחות קבועים',
            'entity.supporter': 'לקוח',
            'entity.donation': 'תשלום',
            'nav.ayin': 'תהליך תיקון',
            'entity.ayinItem': 'עבודה',
            'ayin.stage.new': 'קבלה',
            'ayin.stage.lead': 'אבחון',
            'ayin.stage.eyes': 'בתיקון',
            'ayin.stage.answer': 'מוכן לאיסוף',
            'ayin.stage.done': 'נמסר',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'hospitality',
          'emoji': '🏨',
          'label': 'אירוח / צימרים',
          'sub': 'מלונית · צימר · אכסניה',
          'theme': 'heichal',
          'accent': '#c2761a',
          'icon': '🏨',
          'motion': 'calm',
          'terms': const {
            'nav.diary': 'לוח יחידות',
            'entity.room': 'יחידת אירוח',
            'entity.rooms': 'יחידות אירוח',
            'entity.familyOf': 'אורח',
            'entity.donations': 'תשלומי שהייה',
            'nav.families': 'אורחים',
            'entity.family': 'אורח',
            'entity.member': 'מלווה',
            'entity.members': 'מלווים',
            'nav.supporters': 'מועדון אורחים',
            'entity.supporter': 'אורח',
            'entity.donation': 'תשלום שהייה',
            'entity.cred': 'נקודות נאמנות',
            'nav.ayin': 'הזמנות אירוח',
            'entity.ayinItem': 'הזמנה',
            'ayin.stage.new': 'בקשה',
            'ayin.stage.lead': 'שריון',
            'ayin.stage.eyes': 'צ\'ק-אין',
            'ayin.stage.answer': 'שוהה',
            'ayin.stage.done': 'צ\'ק-אאוט',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'gemach',
          'emoji': '🧰',
          'label': 'גמ"ח (השאלת ציוד)',
          'sub': 'קטלוג · השאלות · תורמים',
          'theme': 'or-rishon',
          'terms': const {
            'nav.shop': 'גמ"ח',
            'entity.shopProduct': 'חבילת השאלה',
            'entity.shopItem': 'פריט',
            'entity.shopAssignment': 'השאלה',
            'nav.families': 'משפחות',
            'nav.supporters': 'תורמים',
          },
          'modules': const {
            'families': true,
            'courses': false,
            'calendar': true,
            'diary': false,
            'supporters': true,
            'reports': true,
            'tzedaka': false,
            'shop': true,
            'shop7': true,
          },
        },
        const {
          'id': 'tzedakot',
          'emoji': '🪙',
          'label': 'ארגון מבצעי התרמה',
          'sub': 'רכזים · קופות · מבצעים',
          'theme': 'or-rishon',
          'terms': const {
            'nav.tzedaka': 'מבצעים',
            'entity.tzCoordinator': 'רכז',
            'entity.tzBox': 'קופה',
            'entity.tzCampaign': 'מבצע',
          },
          'modules': const {
            'families': true,
            'courses': false,
            'calendar': true,
            'diary': false,
            'supporters': true,
            'reports': true,
            'tzedaka': true,
            'shop': false,
            'shop7': true,
          },
        },
        const {
          'id': 'digital',
          'emoji': '💻',
          'label': 'סטודיו דיגיטל',
          'sub': 'אפליקציות · אתרים · פיתוח',
          'theme': 'heichal',
          'accent': '#5b6cff',
          'icon': '💻',
          'motion': 'snappy',
          'terms': const {
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'entity.familyOf': 'לקוח',
            'entity.member': 'איש קשר',
            'entity.members': 'אנשי קשר',
            'nav.calendar': 'פגישות',
            'nav.supporters': 'לידים',
            'entity.supporter': 'ליד',
            'entity.donation': 'תשלום',
            'entity.donations': 'תשלומים',
            'nav.ayin': 'פרויקטים',
            'entity.ayinItem': 'פרויקט',
            'ayin.stage.new': 'בריף',
            'ayin.stage.lead': 'הצעת מחיר',
            'ayin.stage.eyes': 'בפיתוח',
            'ayin.stage.answer': 'בבדיקה',
            'ayin.stage.done': 'הושק',
          },
          'modules': const {
            'courses': false,
            'diary': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'build',
          'emoji': '🏗️',
          'label': 'בנייה / קבלנות',
          'sub': 'אתרים · קבלני-משנה · שלבי-ביצוע',
          'theme': 'tsohar',
          'accent': '#e8912a',
          'icon': '🏗️',
          'motion': 'bold',
          'terms': const {
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'entity.familyOf': 'לקוח',
            'entity.member': 'איש קשר',
            'entity.members': 'אנשי קשר',
            'nav.calendar': 'לוח עבודות',
            'nav.diary': 'אתרי בנייה',
            'entity.room': 'אתר',
            'entity.rooms': 'אתרים',
            'nav.supporters': 'ספקים וקבלנים',
            'entity.supporter': 'ספק/קבלן',
            'entity.donation': 'תשלום',
            'entity.donations': 'תשלומים',
            'nav.ayin': 'פרויקטים',
            'entity.ayinItem': 'פרויקט',
            'ayin.stage.new': 'פנייה',
            'ayin.stage.lead': 'הצעת מחיר',
            'ayin.stage.eyes': 'בביצוע',
            'ayin.stage.answer': 'מסירה',
            'ayin.stage.done': 'הושלם',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
        const {
          'id': 'studio',
          'emoji': '🏢',
          'label': 'סטודיו דיגיטל + בנייה',
          'sub': 'פרויקטים · לקוחות · ספקים — משולב',
          'theme': 'kehila',
          'accent': '#0ea5e9',
          'icon': '🏢',
          'motion': 'calm',
          'terms': const {
            'nav.families': 'לקוחות',
            'entity.family': 'לקוח',
            'entity.familyOf': 'לקוח',
            'entity.member': 'איש קשר',
            'entity.members': 'אנשי קשר',
            'nav.calendar': 'פגישות',
            'nav.diary': 'אתרים וצוותים',
            'entity.room': 'אתר/צוות',
            'entity.rooms': 'אתרים וצוותים',
            'nav.supporters': 'ספקים ולידים',
            'entity.supporter': 'ספק/ליד',
            'entity.donation': 'תשלום',
            'entity.donations': 'תשלומים',
            'nav.ayin': 'פרויקטים',
            'entity.ayinItem': 'פרויקט',
            'ayin.stage.new': 'בריף',
            'ayin.stage.lead': 'הצעת מחיר',
            'ayin.stage.eyes': 'בביצוע',
            'ayin.stage.answer': 'מסירה',
            'ayin.stage.done': 'הושלם',
          },
          'modules': const {
            'courses': false,
            'tzedaka': false,
            'shop': false,
            'shop7': false,
          },
          'features': const {
            'core.taxreceipt': false,
            'families.cred': false,
            'home.goldbook': false,
            'home.impactwall': false,
            'home.community': false,
            'home.credmetrics': false,
            'shell.privacy': false,
            'supporters.hist': false,
          },
        },
      ];
