// ─────────────────────────────────────────────────────────────────────────────
// BuildSmart Studio · Pillar 1 · Step 12 — the element registry.
//
// [ElementDescriptor] is the contract for ONE editable element. It carries the SIX
// governance fields (R1-A1) — editableProps · allowedActions · allowedValues ·
// kImmutable · kRoleFloor · kind — plus identity (id/screen/area/labelHe). The
// inspector lists descriptors; `validateSafe` (P4) gates every write against them.
//
// [findDescriptor] is FAIL-CLOSED: an id NOT in the registry ⇒ null ⇒ the inspector
// won't edit it and a publish validator rejects it (no vacuous green — R1-A1/R2-#15).
// `kElementRegistry` is `const` (zero runtime cost); [elementRegistryProvider] chains
// [domainElementsProvider] so Pillar-2's no-code domain builder can append rows.
// ─────────────────────────────────────────────────────────────────────────────

import 'package:flutter/foundation.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// Bumped whenever the registry's SHAPE changes — lets Pillar-3 analytics annotate
/// funnels across builds without a full diff.
const int kElementRegistryVersion = 1;

/// The axes an element exposes for editing (mirrors the CfgNode axes).
enum EditAxis { text, emoji, hidden, order, style, action }

/// The broad kind of an element — drives which inspector panel + wrapper apply.
enum ElementKind { text, container, list, action, theme }

/// The contract for one editable element.
///
/// ⚠️ FROZEN (step 12.5 · seam-freeze before step 30) — Pillars 2/4/5 ground their
/// `validateSafe` on the six governance fields below. Changing/removing a field
/// needs a schema migration + an update to `descriptor_contract_test`; do NOT edit
/// the shape casually.
@immutable
class ElementDescriptor {
  const ElementDescriptor({
    required this.id,
    required this.screen,
    required this.area,
    required this.labelHe,
    required this.kind,
    this.editableProps = const {},
    this.allowedActions = const [],
    this.allowedValues = const {},
    this.kImmutable = false,
    this.kRoleFloor = 'contractor',
    this.wired = false,
  });

  // identity
  final String id;
  final String screen;
  final String area;
  final String labelHe;

  // the 6 governance fields (R1-A1)
  final ElementKind kind;
  final Set<EditAxis> editableProps;
  final List<String> allowedActions;
  final Map<String, List<String>> allowedValues;

  /// Critical — can never be hidden / action-rerouted (enforced in merge + publish).
  final bool kImmutable;

  /// The minimum canonical roleKey that may see/edit this element.
  final String kRoleFloor;

  /// Flipped true once a widget actually adopts this id (step 14 / Phase E); lets the
  /// inspector show "not yet wired" without a warn-scan.
  final bool wired;
}

/// The built-in elements. SEED set (pilot targets, `wired: false`); step 14 wraps the
/// widgets + flips them wired, and adopts the rest screen-by-screen.
const List<ElementDescriptor> kElementRegistry = [
  ElementDescriptor(
    id: 'cart.cta',
    screen: 'cart',
    area: 'checkout',
    labelHe: 'כפתור הזמנה (עגלה)',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.emoji, EditAxis.style},
  ),
  // Step-14 pilot — the 5 cockpit KPI labels (manager_dashboard _MetricGrid), wired.
  ElementDescriptor(
    id: 'manager.cockpit.kpi.openOrders',
    screen: 'manager',
    area: 'cockpit',
    labelHe: 'KPI — הזמנות פתוחות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.cockpit.kpi.products',
    screen: 'manager',
    area: 'cockpit',
    labelHe: 'KPI — מוצרים בקטלוג',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.cockpit.kpi.accessories',
    screen: 'manager',
    area: 'cockpit',
    labelHe: 'KPI — אביזרים נלווים',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.cockpit.kpi.available',
    screen: 'manager',
    area: 'cockpit',
    labelHe: 'KPI — זמינים כעת',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.cockpit.kpi.stores',
    screen: 'manager',
    area: 'cockpit',
    labelHe: 'KPI — חנויות פעילות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // ── Phase-E content adoption (step 29) — high-value screen literals wrapped as
  // CfgText, the literal kept as the fallback (OFF ⇒ verbatim). Append-only.
  ElementDescriptor(
    id: 'manager.cockpit.copilot.title',
    screen: 'manager',
    area: 'cockpit',
    labelHe: 'כותרת קו-פיילוט',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // catalog product-detail section headers (s29-b8).
  ElementDescriptor(
    id: 'catalog.detail.requiredStandards',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: תקינות נדרשת',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.detail.connectionNeeds',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: מה הקו צריך לחיבור',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.detail.acceptanceCheck',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: בדיקת קבלה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.detail.israeliStandard',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: תקן ישראלי רלוונטי',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.detail.commonMistakes',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: טעויות נפוצות וטיפים',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // catalog misc labels (s29-b9).
  ElementDescriptor(
    id: 'catalog.detail.brandGuide',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: מתי לבחור איזה מותג',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.detail.recentlyViewed',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: נצפו לאחרונה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.card.productBadge',
    screen: 'catalog',
    area: 'card',
    labelHe: 'תג: מוצר',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.templates.label',
    screen: 'catalog',
    area: 'templates',
    labelHe: 'תווית: תבניות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.search.clearAll',
    screen: 'catalog',
    area: 'search',
    labelHe: 'כפתור: נקה הכל',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // catalog action buttons + data header (s29-b10).
  ElementDescriptor(
    id: 'catalog.detail.dataHeader',
    screen: 'catalog',
    area: 'detail',
    labelHe: 'כותרת: נתוני קטלוג',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.action.buildBom',
    screen: 'catalog',
    area: 'action',
    labelHe: 'כפתור: בנה לי קו (BOM)',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.action.addToProject',
    screen: 'catalog',
    area: 'action',
    labelHe: 'כפתור: הוסף לפרויקט',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.action.saveVersion',
    screen: 'catalog',
    area: 'action',
    labelHe: 'כפתור: שמור גרסה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // catalog product-chip actions (s29-b11) — completes catalog static-text adoption.
  ElementDescriptor(
    id: 'catalog.action.proposal',
    screen: 'catalog',
    area: 'action',
    labelHe: 'כפתור: הצעה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.action.draft',
    screen: 'catalog',
    area: 'action',
    labelHe: 'כפתור: נסח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'catalog.action.howToBridge',
    screen: 'catalog',
    area: 'action',
    labelHe: 'כפתור: איך לגשר?',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // ── Critical/protected set (step 26) — navigation + auth the owner may RENAME but
  // never hide or re-route. `kImmutable:true` is the canonical critical flag (R1-A1);
  // declared here (wired:false) so the merge defence + publish validator protect them
  // even before a widget adopts them (defence-in-depth — §8.1).
  ElementDescriptor(
    id: 'auth.login.cta',
    screen: 'welcome',
    area: 'auth',
    labelHe: 'כניסה (מסך פתיחה)',
    kind: ElementKind.action,
    editableProps: {EditAxis.text},
    kImmutable: true,
  ),
  ElementDescriptor(
    id: 'auth.logout',
    screen: 'app',
    area: 'auth',
    labelHe: 'התנתקות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text},
    kImmutable: true,
  ),
  ElementDescriptor(
    id: 'nav.bottombar',
    screen: 'app',
    area: 'nav',
    labelHe: 'סרגל ניווט תחתון',
    kind: ElementKind.container,
    kImmutable: true,
  ),
  ElementDescriptor(
    id: 'manager.entry',
    screen: 'app',
    area: 'nav',
    labelHe: 'כניסת מנהל',
    kind: ElementKind.action,
    editableProps: {EditAxis.text},
    kImmutable: true,
  ),
  ElementDescriptor(
    id: 'studio.exit',
    screen: 'studio',
    area: 'chrome',
    labelHe: 'יציאה מהסטודיו',
    kind: ElementKind.action,
    editableProps: {EditAxis.text},
    kImmutable: true,
  ),
  // ── Coverage round 1 — home_shell + store_dashboard adoptions (wired) ──
  ElementDescriptor(
    id: 'home.topbar.brand',
    screen: 'home',
    area: 'topbar',
    labelHe: 'לוגו/כותרת האפליקציה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.helpmode.banner',
    screen: 'home',
    area: 'helpmode',
    labelHe: 'באנר מצב היכרות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.newchat.title',
    screen: 'home',
    area: 'newchat',
    labelHe: 'כותרת "שיחה חדשה"',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.newchat.subtitle',
    screen: 'home',
    area: 'newchat',
    labelHe: 'כתובית בורר איש קשר',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.profilecard.editCta',
    screen: 'home',
    area: 'profile',
    labelHe: 'כפתור "ערוך פרופיל"',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.action.exit',
    screen: 'store',
    area: 'nav',
    labelHe: 'כפתור יציאה (חנות)',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.home.greeting',
    screen: 'store',
    area: 'home',
    labelHe: 'ברכת פתיחה (חנות)',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.section.orders',
    screen: 'store',
    area: 'orders',
    labelHe: 'כותרת הזמנות (חנות)',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.action.newProduct',
    screen: 'store',
    area: 'stock',
    labelHe: 'כפתור הוסף-מוצר (מלאי)',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.addProduct.title',
    screen: 'store',
    area: 'addProduct',
    labelHe: 'כותרת גיליון מוצר',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.addProduct.category',
    screen: 'store',
    area: 'addProduct',
    labelHe: 'תווית קטגוריה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.action.addProduct',
    screen: 'store',
    area: 'addProduct',
    labelHe: 'כפתור שליחת מוצר',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.settings.title',
    screen: 'store',
    area: 'settings',
    labelHe: 'כותרת הגדרות ספק',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.settings.businessProfile',
    screen: 'store',
    area: 'settings',
    labelHe: 'כותרת פרופיל עסקי',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.settings.logo',
    screen: 'store',
    area: 'settings',
    labelHe: 'כותרת לוגו',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'store.action.captureLogo',
    screen: 'store',
    area: 'settings',
    labelHe: 'כפתור צלם/העלה לוגו',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // ── Coverage round 2 — worker/courier/manager screen adoptions (wired) ──
  ElementDescriptor(
    id: 'worker.section.title',
    screen: 'worker',
    area: 'section',
    labelHe: 'כותרת עובד',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.exit',
    screen: 'worker',
    area: 'action',
    labelHe: 'יציאה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.section.journal',
    screen: 'worker',
    area: 'section',
    labelHe: 'היומן שלי',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.fullMonth',
    screen: 'worker',
    area: 'action',
    labelHe: 'חודש מלא',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.checkEquipment',
    screen: 'worker',
    area: 'action',
    labelHe: 'בדוק ציוד',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.employerStock',
    screen: 'worker',
    area: 'action',
    labelHe: 'מלאי הקבלן',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.addTask',
    screen: 'worker',
    area: 'action',
    labelHe: 'הוסף משימה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.gantt',
    screen: 'worker',
    area: 'action',
    labelHe: 'גאנט משימות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.defects',
    screen: 'worker',
    area: 'action',
    labelHe: 'ליקויים',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.section.proposeTitle',
    screen: 'worker',
    area: 'section',
    labelHe: 'כותרת הצעת משימה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.propose.subtitle',
    screen: 'worker',
    area: 'propose',
    labelHe: 'תת-כותרת הצעה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.action.submit',
    screen: 'worker',
    area: 'action',
    labelHe: 'שלח לאישור',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.title',
    screen: 'worker',
    area: 'reports',
    labelHe: 'כותרת דוחות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.weekly_title',
    screen: 'worker',
    area: 'reports',
    labelHe: 'כותרת סיכום שבועי',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.time_title',
    screen: 'worker',
    area: 'reports',
    labelHe: 'כותרת זמן למשימה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.area_title',
    screen: 'worker',
    area: 'reports',
    labelHe: 'כותרת אזור עבודה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.time_empty',
    screen: 'worker',
    area: 'reports',
    labelHe: 'מצב-ריק זמנים',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.area_note',
    screen: 'worker',
    area: 'reports',
    labelHe: 'הערת אזור',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.history_empty',
    screen: 'worker',
    area: 'reports',
    labelHe: 'מצב-ריק היסטוריה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.rejections_empty',
    screen: 'worker',
    area: 'reports',
    labelHe: 'מצב-ריק דחיות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.send_daily_button',
    screen: 'worker',
    area: 'reports',
    labelHe: 'כפתור שליחת דוח יומי',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.ai_button',
    screen: 'worker',
    area: 'reports',
    labelHe: 'כפתור ניסוח דוח AI',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.reports.send_note',
    screen: 'worker',
    area: 'reports',
    labelHe: 'הערת שליחת דוח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.dash.appbar_title',
    screen: 'courier',
    area: 'dash',
    labelHe: 'כותרת סרגל השליח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.dash.exit',
    screen: 'courier',
    area: 'dash',
    labelHe: 'כפתור יציאה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.gate.vehicle_title',
    screen: 'courier',
    area: 'gate',
    labelHe: 'כותרת שער בחירת רכב',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.gate.vehicle_sub',
    screen: 'courier',
    area: 'gate',
    labelHe: 'תת-כותרת שער הרכב',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.dash.subtitle',
    screen: 'courier',
    area: 'dash',
    labelHe: 'תת-כותרת הבית',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.dash.vehicle_title',
    screen: 'courier',
    area: 'dash',
    labelHe: 'כותרת בורר הרכב',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.vehicle.preferred',
    screen: 'courier',
    area: 'vehicle',
    labelHe: 'תג רכב מועדף',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.notifs.title',
    screen: 'courier',
    area: 'notifs',
    labelHe: 'כותרת גיליון התראות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.notifs.empty',
    screen: 'courier',
    area: 'notifs',
    labelHe: 'מצב ריק בהתראות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.notifs.mark_all',
    screen: 'courier',
    area: 'notifs',
    labelHe: 'סמן הכל כנקרא',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.notifs.clear_all',
    screen: 'courier',
    area: 'notifs',
    labelHe: 'נקה הכל',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.title',
    screen: 'courier',
    area: 'settings',
    labelHe: 'כותרת הגדרות שליח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.push',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג התראות Push',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.shipment_updates',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג עדכוני משלוחים',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.new_chats',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג הודעות צ׳אט',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.quiet_driving',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג שקט בנהיגה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.sound',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג צליל',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.vibration',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג רטט',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.language',
    screen: 'courier',
    area: 'settings',
    labelHe: 'תווית בורר שפה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.text_size',
    screen: 'courier',
    area: 'settings',
    labelHe: 'תווית גודל טקסט',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.high_contrast',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג ניגודיות גבוהה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.settings.reduced_motion',
    screen: 'courier',
    area: 'settings',
    labelHe: 'מתג הנפשות מופחתות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.info.terms',
    screen: 'courier',
    area: 'info',
    labelHe: 'ניווט לתנאי שימוש',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.info.privacy',
    screen: 'courier',
    area: 'info',
    labelHe: 'ניווט למדיניות פרטיות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.profile.title',
    screen: 'courier',
    area: 'profile',
    labelHe: 'כותרת מסך הפרופיל',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.profile.settings_title',
    screen: 'courier',
    area: 'profile',
    labelHe: 'פתיחת הגדרות שליח',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.profile.role_switch_title',
    screen: 'courier',
    area: 'profile',
    labelHe: 'החלפת תפקיד',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.profile.logout_title',
    screen: 'courier',
    area: 'profile',
    labelHe: 'יציאה מהחשבון',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.personal.attendance_title',
    screen: 'courier',
    area: 'personal',
    labelHe: 'נוכחות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.personal.forms_title',
    screen: 'courier',
    area: 'personal',
    labelHe: 'טפסים',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.personal.certs_title',
    screen: 'courier',
    area: 'personal',
    labelHe: 'תעודות נהג',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.personal.payslips_title',
    screen: 'courier',
    area: 'personal',
    labelHe: 'תלושי שכר',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.profile.save_action',
    screen: 'courier',
    area: 'profile',
    labelHe: 'שמירת פרופיל',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.dash.title',
    screen: 'manager',
    area: 'dash',
    labelHe: 'כותרת מרכז השליטה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.dash.subtitle',
    screen: 'manager',
    area: 'dash',
    labelHe: 'תת-כותרת פרסונת המנהל',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.dash.exit',
    screen: 'manager',
    area: 'dash',
    labelHe: 'כפתור יציאה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.dash.pipeline.title',
    screen: 'manager',
    area: 'dash',
    labelHe: 'כותרת צינור ההזמנות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.orders.advance',
    screen: 'manager',
    area: 'orders',
    labelHe: 'כפתור קידום שלב',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.orders.empty',
    screen: 'manager',
    area: 'orders',
    labelHe: 'מצב ריק — אין הזמנות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.customers.empty',
    screen: 'manager',
    area: 'customers',
    labelHe: 'מצב ריק — אין קבלנים',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.manage.intro',
    screen: 'manager',
    area: 'manage',
    labelHe: 'באנר פתיח לטאב ניהול',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.manage.roles.open',
    screen: 'manager',
    area: 'manage',
    labelHe: 'כפתור פתיחת שיוך תפקידים',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'manager.manage.regression.open',
    screen: 'manager',
    area: 'manage',
    labelHe: 'כפתור פתיחת בדיקות רגרסיה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // ── Coverage round 3 — worker_profile + courier forms/attendance/certs (wired) ──
  ElementDescriptor(
    id: 'courier.attend.title',
    screen: 'courier',
    area: 'attend',
    labelHe: 'כותרת מסך נוכחות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.attend.today',
    screen: 'courier',
    area: 'attend',
    labelHe: 'כותרת כרטיס היום',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.attend.prev',
    screen: 'courier',
    area: 'attend',
    labelHe: 'חודש קודם',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.attend.next',
    screen: 'courier',
    area: 'attend',
    labelHe: 'חודש הבא',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.attend.empty',
    screen: 'courier',
    area: 'attend',
    labelHe: 'מצב-ריק נוכחות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.attend.month_total',
    screen: 'courier',
    area: 'attend',
    labelHe: 'תווית סיכום חודשי',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.certs.title',
    screen: 'courier',
    area: 'certs',
    labelHe: 'כותרת תעודות נהג',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.certs.empty',
    screen: 'courier',
    area: 'certs',
    labelHe: 'מצב-ריק ארנק תעודות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.certs.add_button',
    screen: 'courier',
    area: 'certs',
    labelHe: 'כפתור הוספת תעודה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.certs.sheet_title',
    screen: 'courier',
    area: 'certs',
    labelHe: 'כותרת גיליון הוספת תעודה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.certs.save_button',
    screen: 'courier',
    area: 'certs',
    labelHe: 'כפתור שמירת תעודה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.title',
    screen: 'courier',
    area: 'forms',
    labelHe: 'כותרת מסך טפסים',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.form101_note',
    screen: 'courier',
    area: 'forms',
    labelHe: 'הבהרת טופס 101',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.save_101',
    screen: 'courier',
    area: 'forms',
    labelHe: 'שמירת טופס 101',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.send_101',
    screen: 'courier',
    area: 'forms',
    labelHe: 'שליחת טופס לחנות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.vacation_submit',
    screen: 'courier',
    area: 'forms',
    labelHe: 'שליחת בקשת חופשה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.my_requests',
    screen: 'courier',
    area: 'forms',
    labelHe: 'כותרת הבקשות שלי',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.sicknote_hint',
    screen: 'courier',
    area: 'forms',
    labelHe: 'הנחיית אישור מחלה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.forms.sicknote_attach',
    screen: 'courier',
    area: 'forms',
    labelHe: 'צירוף צילום אישור',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.tasks_title',
    screen: 'worker',
    area: 'profile',
    labelHe: 'כותרת כרטיס משימות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.settings_title',
    screen: 'worker',
    area: 'profile',
    labelHe: 'שורת הגדרות עובד',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.role_switch_title',
    screen: 'worker',
    area: 'profile',
    labelHe: 'שורת החלפת תפקיד',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.role_switch_hint',
    screen: 'worker',
    area: 'profile',
    labelHe: 'כתובית מוגן בקוד',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.logout_title',
    screen: 'worker',
    area: 'profile',
    labelHe: 'שורת יציאה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.edit_title',
    screen: 'worker',
    area: 'profile',
    labelHe: 'כותרת עריכת פרופיל',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.save_button',
    screen: 'worker',
    area: 'profile',
    labelHe: 'כפתור שמירת פרופיל',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.emergency_title',
    screen: 'worker',
    area: 'profile',
    labelHe: 'כותרת איש קשר לחירום',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.profile.specialty_label',
    screen: 'worker',
    area: 'profile',
    labelHe: 'תווית שדה התמחות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  // ── Coverage round 4 — welcome (non-auth) + home_shell (smarttree + menus) ──
  ElementDescriptor(
    id: 'welcome.hero.title',
    screen: 'welcome',
    area: 'hero',
    labelHe: 'כותרת ראשית',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'welcome.hero.tagline',
    screen: 'welcome',
    area: 'hero',
    labelHe: 'סלוגן',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'welcome.signup.divider',
    screen: 'welcome',
    area: 'signup',
    labelHe: 'מפריד הרשמה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'welcome.signup.heading',
    screen: 'welcome',
    area: 'signup',
    labelHe: 'כותרת הרשמה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'welcome.signup.subtitle',
    screen: 'welcome',
    area: 'signup',
    labelHe: 'תת-כותרת הרשמה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.status.smarttree',
    screen: 'home',
    area: 'status',
    labelHe: 'תווית סטטוס עץ חכם',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.catalogmenu.aihub',
    screen: 'home',
    area: 'catalogmenu',
    labelHe: 'תפריט: בינה מלאכותית ואוטומציה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.chatsmenu.archive',
    screen: 'home',
    area: 'chatsmenu',
    labelHe: 'תפריט: ארכיון שיחות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.notifmenu.readall',
    screen: 'home',
    area: 'notifmenu',
    labelHe: 'תפריט: סמן הכל כנקרא',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.notifmenu.clearall',
    screen: 'home',
    area: 'notifmenu',
    labelHe: 'תפריט: נקה הכל',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.notifmenu.settings',
    screen: 'home',
    area: 'notifmenu',
    labelHe: 'תפריט: הגדרות התראות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.storemenu.cart',
    screen: 'home',
    area: 'storemenu',
    labelHe: 'תפריט: הסל שלי',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'home.storemenu.orders',
    screen: 'home',
    area: 'storemenu',
    labelHe: 'תפריט: הזמנות',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  // ── Coverage round 5 — store/shop + worker_today + courier_reports (wired) ──
  ElementDescriptor(
    id: 'worker.today.title',
    screen: 'worker',
    area: 'today',
    labelHe: 'כותרת רצועת היום',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.today.empty',
    screen: 'worker',
    area: 'today',
    labelHe: 'מצב-ריק היום',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'worker.today.alldone',
    screen: 'worker',
    area: 'today',
    labelHe: 'הכל הושלם היום',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.reports.title',
    screen: 'courier',
    area: 'reports',
    labelHe: 'כותרת דוחות שליח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.reports.subtitle',
    screen: 'courier',
    area: 'reports',
    labelHe: 'תת-כותרת דוחות שליח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.reports.history_title',
    screen: 'courier',
    area: 'reports',
    labelHe: 'כותרת היסטוריית מסירות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.reports.empty_title',
    screen: 'courier',
    area: 'reports',
    labelHe: 'מצב-ריק מסירות',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'courier.reports.send_report',
    screen: 'courier',
    area: 'reports',
    labelHe: 'כפתור שליחת דוח יומי',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.emptycart.title',
    screen: 'shop',
    area: 'emptycart',
    labelHe: 'כותרת סל ריק',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.emptycart.hint',
    screen: 'shop',
    area: 'emptycart',
    labelHe: 'הנחיית סל ריק',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.delivery.title',
    screen: 'shop',
    area: 'delivery',
    labelHe: 'כותרת אפשרויות משלוח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.notes.title',
    screen: 'shop',
    area: 'notes',
    labelHe: 'כותרת הערות לשליח',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.payment.title',
    screen: 'shop',
    area: 'payment',
    labelHe: 'כותרת אמצעי תשלום',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.checkout.title',
    screen: 'shop',
    area: 'checkout',
    labelHe: 'כותרת סיכום הזמנה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.checkout.confirm',
    screen: 'shop',
    area: 'checkout',
    labelHe: 'כפתור אישור הזמנה',
    kind: ElementKind.action,
    editableProps: {EditAxis.text, EditAxis.style},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.orders.hidden',
    screen: 'shop',
    area: 'orders',
    labelHe: 'הודעת היסטוריה מוסתרת',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(
    id: 'shop.tracking.title',
    screen: 'shop',
    area: 'tracking',
    labelHe: 'כותרת מעקב הזמנה',
    kind: ElementKind.text,
    editableProps: {EditAxis.text, EditAxis.style, EditAxis.hidden},
    wired: true,
  ),
  ElementDescriptor(id: 'catalog_screen.t01', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'ניהול רשימות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t02', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'יצירת רשימה מותאמת אישית', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t03', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'רשימה חדשה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t04', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t05', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'הוספה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t06', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'שינוי שם הרשימה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t07', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t08', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'שמירה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t09', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'שינוי שם הרשימה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t10', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t11', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'שמירה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t12', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'שמירה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t13', screen: 'catalog_screen', area: 'lists_manager', labelHe: 'בחר אילו פריטים יופיעו ברשימה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t14', screen: 'catalog_screen', area: 'empty_states', labelHe: 'אין תוצאות תואמות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t15', screen: 'catalog_screen', area: 'empty_states', labelHe: 'אין מוצרים תואמים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t16', screen: 'catalog_screen', area: 'empty_states', labelHe: 'אין תוצאות תואמות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t17', screen: 'catalog_screen', area: 'empty_states', labelHe: 'אין מוצרים תואמים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t18', screen: 'catalog_screen', area: 'empty_states', labelHe: 'אין פריטים להצגה.\\nפתחו את ניהול הרשימות והקישו ✏️ כדי לבחור פריטים.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t19', screen: 'catalog_screen', area: 'results_header', labelHe: 'מוצרים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t20', screen: 'catalog_screen', area: 'sort', labelHe: 'מיון לפי', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t21', screen: 'catalog_screen', area: 'coming_soon', labelHe: 'בקרוב', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t22', screen: 'catalog_screen', area: 'coming_soon', labelHe: 'הקטגוריה הזו בבנייה — תת-קטגוריות ומוצרים יתווספו בקרוב.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t23', screen: 'catalog_screen', area: 'product_card', labelHe: 'מומלץ', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t24', screen: 'catalog_screen', area: 'bom_dialog', labelHe: 'סגור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t25', screen: 'catalog_screen', area: 'bom_dialog', labelHe: 'סגור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t26', screen: 'catalog_screen', area: 'brand_filter', labelHe: 'אין מותג תואם לסינון שנבחר', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t27', screen: 'catalog_screen', area: 'smart_card', labelHe: 'הצעת המחיר הועתקה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t28', screen: 'catalog_screen', area: 'smart_card', labelHe: '🛒 + בטיחות לסל', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t29', screen: 'catalog_screen', area: 'smart_card', labelHe: 'נוסף ל-3 חדרים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t30', screen: 'catalog_screen', area: 'smart_card', labelHe: '×3 חדרים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t31', screen: 'catalog_screen', area: 'smart_card', labelHe: '📋 BOM פרויקט מלא', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t32', screen: 'catalog_screen', area: 'smart_card', labelHe: 'הצעת מחיר לפרויקט הועתקה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t33', screen: 'catalog_screen', area: 'smart_card', labelHe: '📋 הצעת מחיר לפרויקט', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t34', screen: 'catalog_screen', area: 'line_builder', labelHe: '⚡ פריטי חובה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t35', screen: 'catalog_screen', area: 'line_builder', labelHe: '💡 פריטים אופציונליים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t36', screen: 'catalog_screen', area: 'install_stages', labelHe: '💡 הקש על שלב כדי להדגיש את האביזרים שלו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t37', screen: 'catalog_screen', area: 'accessory_detail', labelHe: 'למה צריך:', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t38', screen: 'catalog_screen', area: 'accessory_detail', labelHe: 'מחיר ליחידה:', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t39', screen: 'catalog_screen', area: 'accessory_detail', labelHe: 'סגור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t40', screen: 'catalog_screen', area: 'variants', labelHe: 'אין משפחות וריאנטים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'catalog_screen.t41', screen: 'catalog_screen', area: 'variants_sort', labelHe: 'מיון לפי:', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t01', screen: 'chat_settings_screen', area: 'app bar', labelHe: 'הגדרות שיחות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t02', screen: 'chat_settings_screen', area: 'reset dialog', labelHe: 'איפוס הגדרות?', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t03', screen: 'chat_settings_screen', area: 'reset dialog', labelHe: 'כל הגדרות השיחות יוחזרו לברירת המחדל.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t04', screen: 'chat_settings_screen', area: 'reset dialog', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t05', screen: 'chat_settings_screen', area: 'reset dialog', labelHe: 'אפס', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t06', screen: 'chat_settings_screen', area: 'quick-reply info dialog', labelHe: 'תשובות מהירות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t07', screen: 'chat_settings_screen', area: 'quick-reply info dialog', labelHe: 'הבנתי', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t08', screen: 'chat_settings_screen', area: 'quick-reply banner', labelHe: 'תשובות מהירות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t09', screen: 'chat_settings_screen', area: 'quick-reply banner', labelHe: 'ערוך', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t10', screen: 'chat_settings_screen', area: 'clear-history dialog', labelHe: 'מחיקת היסטוריית שיחות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t11', screen: 'chat_settings_screen', area: 'clear-history dialog', labelHe: 'היסטוריית השיחות תימחק והשיחות ייפתחו ריקות.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t12', screen: 'chat_settings_screen', area: 'clear-history dialog', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t13', screen: 'chat_settings_screen', area: 'clear-history dialog', labelHe: 'מחק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t14', screen: 'chat_settings_screen', area: 'section tile', labelHe: 'בבנייה — ההגדרות נשמרות אך עדיין אינן משפיעות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t15', screen: 'chat_settings_screen', area: 'switch row', labelHe: 'בבנייה — עדיין לא משפיע', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t16', screen: 'chat_settings_screen', area: 'radio group row', labelHe: 'בבנייה — עדיין לא משפיע', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chat_settings_screen.t17', screen: 'chat_settings_screen', area: 'placeholder row', labelHe: 'בבנייה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.appbar_title', screen: 'chats_screen', area: 'AppBar', labelHe: 'שיחות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.empty_title', screen: 'chats_screen', area: 'Empty state', labelHe: 'אין שיחות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.empty_hint', screen: 'chats_screen', area: 'Empty state', labelHe: 'כשיהיו שיחות — הן יופיעו כאן', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.archived_snack', screen: 'chats_screen', area: 'Archive snackbar', labelHe: 'שיחה הועברה לארכיון', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.menu_archive', screen: 'chats_screen', area: 'Chat menu', labelHe: 'העבר לארכיון', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.menu_search', screen: 'chats_screen', area: 'Chat menu', labelHe: 'חיפוש בשיחה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.menu_block', screen: 'chats_screen', area: 'Chat menu', labelHe: 'חסום איש קשר', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.online_now', screen: 'chats_screen', area: 'Chat header', labelHe: 'פעיל כעת', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.retry', screen: 'chats_screen', area: 'Delivery status', labelHe: 'נסה שוב', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.typing', screen: 'chats_screen', area: 'Typing bubble', labelHe: 'מקליד...', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.privacy_notice', screen: 'chats_screen', area: 'Privacy notice', labelHe: '🔒 ההודעות בשיחה זו מוצפנות מקצה לקצה. רק המשתתפים יכולים לקרוא אותן.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.voice_title', screen: 'chats_screen', area: 'Voice dialog', labelHe: 'הקלטת קול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.voice_body', screen: 'chats_screen', area: 'Voice dialog', labelHe: 'הקלטת הודעות קוליות אינה זמינה בגרסת הדמו.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.voice_ok', screen: 'chats_screen', area: 'Voice dialog', labelHe: 'הבנתי', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.attach_camera', screen: 'chats_screen', area: 'Attach sheet', labelHe: 'מצלמה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.attach_doc', screen: 'chats_screen', area: 'Attach sheet', labelHe: 'מסמך', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.attach_doc_unavail', screen: 'chats_screen', area: 'Attach sheet', labelHe: 'לא זמין בדמו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.attach_location', screen: 'chats_screen', area: 'Attach sheet', labelHe: 'מיקום', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.attach_location_unavail', screen: 'chats_screen', area: 'Attach sheet', labelHe: 'לא זמין בדמו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.archive_title', screen: 'chats_screen', area: 'Archive screen', labelHe: 'ארכיון שיחות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.archive_empty_title', screen: 'chats_screen', area: 'Archive empty state', labelHe: 'אין שיחות בארכיון', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'chats_screen.archive_empty_hint', screen: 'chats_screen', area: 'Archive empty state', labelHe: 'החלק שיחה שמאלה כדי לארכב אותה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.cheaper_title', screen: 'contractor_tools_sheets', area: 'חלופות זולות', labelHe: '💡 חלופות זולות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.cheaper_subtitle', screen: 'contractor_tools_sheets', area: 'חלופות זולות', labelHe: 'מותג חלופי זול יותר לאותו מוצר — אותה התקנה, פחות עלות.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.why_worth', screen: 'contractor_tools_sheets', area: 'חלופות זולות', labelHe: 'למה כדאי?', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.cheaper_prod_note', screen: 'contractor_tools_sheets', area: 'חלופות זולות', labelHe: '⚙️ בפרודקשן: השוואת-מחירים חיה מול מחירוני הספקים.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.compare_title', screen: 'contractor_tools_sheets', area: 'השוואת מחירים', labelHe: '📊 השוואת מחירים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.compare_subtitle', screen: 'contractor_tools_sheets', area: 'השוואת מחירים', labelHe: 'מחירים מ-3 חנויות שותפות — הזול ביותר מסומן.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.compare_empty', screen: 'contractor_tools_sheets', area: 'השוואת מחירים', labelHe: 'אין מחירים להשוואה כרגע.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.compare_prices_note', screen: 'contractor_tools_sheets', area: 'השוואת מחירים', labelHe: '💰 המחירים נמשכים מ-3 חנויות שותפות. BuildSmart בוחר אוטומטית את ההצעה המשתלמת ביותר לכל פריט.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.scan_title', screen: 'contractor_tools_sheets', area: 'סרוק תוכנית', labelHe: '📐 סרוק תוכנית עבודה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.scan_pick', screen: 'contractor_tools_sheets', area: 'סרוק תוכנית', labelHe: 'בחר סוג תוכנית לסריקה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.scan_analyzing', screen: 'contractor_tools_sheets', area: 'סרוק תוכנית', labelHe: 'מנתח את תצורת הבנייה ומחלץ כמויות חומרים…', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.scan_prices_note', screen: 'contractor_tools_sheets', area: 'סרוק תוכנית', labelHe: '💰 המחירים נמשכים מ-3 חנויות שותפות. BuildSmart בוחר אוטומטית את ההצעה המשתלמת ביותר לכל פריט.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'contractor_tools_sheets.scan_another', screen: 'contractor_tools_sheets', area: 'סרוק תוכנית', labelHe: 'סרוק תוכנית אחרת', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.stats_heading', screen: 'courier_profile_screen', area: 'מסירות — סטטיסטיקה', labelHe: 'מסירות — סטטיסטיקה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.role_switch_subtitle', screen: 'courier_profile_screen', area: 'פעולות', labelHe: 'מוגן בקוד', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.demo_chip', screen: 'courier_profile_screen', area: 'כרטיס זהות', labelHe: 'דמו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.attendance_subtitle', screen: 'courier_profile_screen', area: 'אזור אישי', labelHe: 'כניסה/יציאה ודוח חודשי', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.forms_subtitle', screen: 'courier_profile_screen', area: 'אזור אישי', labelHe: 'טופס 101 · בקשת חופשה · אישור מחלה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.certs_subtitle', screen: 'courier_profile_screen', area: 'אזור אישי', labelHe: 'רישיון נהיגה · ביטוח רכב · רישיון רכב', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.payslips_subtitle', screen: 'courier_profile_screen', area: 'אזור אישי', labelHe: 'יחובר עם חיבור השרת', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.edit_sheet_title', screen: 'courier_profile_screen', area: 'עריכת פרופיל', labelHe: 'עריכת פרופיל', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.remove_photo', screen: 'courier_profile_screen', area: 'עריכת פרופיל', labelHe: 'הסר תמונה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.preferred_vehicle_label', screen: 'courier_profile_screen', area: 'עריכת פרופיל', labelHe: 'סוג רכב מועדף', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.role_switch_dialog_title', screen: 'courier_profile_screen', area: 'דיאלוג החלפת תפקיד', labelHe: 'החלפת תפקיד', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.role_switch_dialog_body', screen: 'courier_profile_screen', area: 'דיאלוג החלפת תפקיד', labelHe: 'מעבר בין לוחות מוגן בקוד. הזן את קוד החלפת התפקיד:', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.dialog_cancel', screen: 'courier_profile_screen', area: 'דיאלוג החלפת תפקיד', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'courier_profile_screen.dialog_confirm', screen: 'courier_profile_screen', area: 'דיאלוג החלפת תפקיד', labelHe: 'אישור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.zoom_hint_fullscreen', screen: 'lipskey_product_sheet', area: 'fullscreen image viewer', labelHe: 'צבוט להגדלה · הקש לסגירה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.added_to_cart', screen: 'lipskey_product_sheet', area: 'add-to-cart toast', labelHe: 'נוסף לסל ✓', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.related_rail_title', screen: 'lipskey_product_sheet', area: 'related rail header', labelHe: '🔗 קשור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.connects_rail_title', screen: 'lipskey_product_sheet', area: 'what-connects rail header', labelHe: '🔌 מה מתחבר לזה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.add_to_line', screen: 'lipskey_product_sheet', area: 'line controls chip', labelHe: 'הוסף לקו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.added_to_line', screen: 'lipskey_product_sheet', area: 'add-to-line toast', labelHe: 'נוסף לקו ✓', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.line_bom_title', screen: 'lipskey_product_sheet', area: 'line BOM sheet title', labelHe: '📋 רשימת חומרים — קו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.line_bom_empty', screen: 'lipskey_product_sheet', area: 'line BOM sheet empty state', labelHe: 'לא נמצאו פריטים לפתרון — בחר מוצרים אחרים לקו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.sku_copied', screen: 'lipskey_product_sheet', area: 'SKU copied toast', labelHe: 'מק"ט הועתק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.hop_back', screen: 'lipskey_product_sheet', area: 'hop back chip', labelHe: 'חזרה למוצר הקודם', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.chip_hint', screen: 'lipskey_product_sheet', area: 'variant chips hint', labelHe: '💡 צ׳יפ כתום ▾ — הקש להחלפת גודל/צבע/דגם', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.recommended_kit', screen: 'lipskey_product_sheet', area: 'install-kit banner title', labelHe: 'ערכת התקנה מומלצת', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.add_kit', screen: 'lipskey_product_sheet', area: 'install-kit banner button', labelHe: '+ ערכה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.selected_accessories', screen: 'lipskey_product_sheet', area: 'purchase bar', labelHe: 'אביזרים נבחרים:', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.add_to_cart_btn', screen: 'lipskey_product_sheet', area: 'purchase bar CTA', labelHe: 'הוסף לסל', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.spec_copilot_cta', screen: 'lipskey_product_sheet', area: 'purchase bar copilot CTA', labelHe: 'מתאים לתנאים שלי?', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.paired_explain_cta', screen: 'lipskey_product_sheet', area: 'purchase bar paired-explain CTA', labelHe: 'מה עוד צריך להתקנה?', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.ppr_ct_badge', screen: 'lipskey_product_sheet', area: 'product image material badge', labelHe: 'PPR-CT', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.details_spec', screen: 'lipskey_product_sheet', area: 'product image flip button', labelHe: 'פרטים / מפרט', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.zoom', screen: 'lipskey_product_sheet', area: 'image zoom hint', labelHe: 'הגדלה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.back_to_product', screen: 'lipskey_product_sheet', area: 'spec image flip button', labelHe: 'חזרה למוצר', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.must_smart_tree', screen: 'lipskey_product_sheet', area: 'install-kit panel section', labelHe: 'חובה (עץ חכם)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.optional_smart_tree', screen: 'lipskey_product_sheet', area: 'install-kit panel section', labelHe: 'אופציונלי (עץ חכם)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.tools_auto', screen: 'lipskey_product_sheet', area: 'install-kit panel section', labelHe: 'כלים ואיטומים (אוטומטי)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.must_badge', screen: 'lipskey_product_sheet', area: 'accessory row badge', labelHe: 'חובה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.must_badge_compliance', screen: 'lipskey_product_sheet', area: 'compliance row badge', labelHe: 'חובה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.ppr_caption', screen: 'lipskey_product_sheet', area: 'info panel caption (polyroll)', labelHe: 'צנרת PPR לאספקת מים חמים וקרים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.smartlock_caption', screen: 'lipskey_product_sheet', area: 'info panel caption (huliot)', labelHe: 'SMART LOCK — מערכת דלוחין, צנרת ואביזרים מפוליפרופילן בקטרים 32-63 מ"מ בצבע שחור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.per_unit', screen: 'lipskey_product_sheet', area: 'price panel suffix', labelHe: 'ליחידה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.estimate_badge', screen: 'lipskey_product_sheet', area: 'price panel badge', labelHe: 'הערכה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_product_sheet.price_note', screen: 'lipskey_product_sheet', area: 'price panel disclaimer', labelHe: 'הערכה לפי קטגוריה — מחיר אמיתי תלוי בספק, מותג ומידה ספציפית.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.empty_title', screen: 'lipskey_products_screen', area: 'empty state', labelHe: 'אין מוצרים להצגה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.empty_hint', screen: 'lipskey_products_screen', area: 'empty state', labelHe: 'נסו לבחור קטגוריה אחרת בקטלוג', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.price_by_supplier_grid', screen: 'lipskey_products_screen', area: 'grid card', labelHe: 'מחיר לפי ספק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.to_cart', screen: 'lipskey_products_screen', area: 'grid card add button', labelHe: 'לסל', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.choose_qty', screen: 'lipskey_products_screen', area: 'quantity wheel', labelHe: 'בחר כמות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.price_by_supplier_row', screen: 'lipskey_products_screen', area: 'product row', labelHe: 'מחיר לפי ספק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.sku_copied', screen: 'lipskey_products_screen', area: 'SKU copy toast', labelHe: 'מק"ט הועתק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'lipskey_products_screen.size_label', screen: 'lipskey_products_screen', area: 'hierarchy chips', labelHe: 'מידה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.hi_pill', screen: 'manager_dashboard_screen', area: 'AppBar live pill', labelHe: 'חי', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.studio_hero_title', screen: 'manager_dashboard_screen', area: 'Studio hero (cockpit)', labelHe: 'סטודיו — ערוך את האפליקציה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.studio_experimental_badge', screen: 'manager_dashboard_screen', area: 'Studio hero badge', labelHe: 'ניסיוני', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.order_completed_badge', screen: 'manager_dashboard_screen', area: 'Orders — order row', labelHe: '✓ הושלם', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.order_completed_delivered', screen: 'manager_dashboard_screen', area: 'Orders — detail sheet', labelHe: '✓ ההזמנה הושלמה ונמסרה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.credit_explain_btn', screen: 'manager_dashboard_screen', area: 'Customers — detail sheet', labelHe: 'הסבר אשראי', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.journey_title', screen: 'manager_dashboard_screen', area: 'Customers — journey timeline', labelHe: '🧭 מסע הלקוח', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.approvals_empty', screen: 'manager_dashboard_screen', area: 'Manage — approvals (empty)', labelHe: '🎉 אין משימות הממתינות לאישור.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.vacations_empty', screen: 'manager_dashboard_screen', area: 'Manage — vacations (empty)', labelHe: 'אין בקשות חופשה.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.producttree_intro', screen: 'manager_dashboard_screen', area: 'Manage — product tree', labelHe: 'עריכת האביזרים המשלימים של כל מוצר — בחירת מוצר חושפת את עץ האביזרים שלו.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.regression_intro', screen: 'manager_dashboard_screen', area: 'Manage — regression', labelHe: 'הרצת חבילת בדיקות הרגרסיה המלאה (קטלוג · מאתר · מנוע תאימות · state · ניווט) על המכשיר.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'manager_dashboard_screen.roleassign_intro', screen: 'manager_dashboard_screen', area: 'Manage — role assign', labelHe: 'הקצאת תפקיד למשתמש לפי טלפון או מזהה (uid). השיוך מופעל ע״י השרת של בעל המערכת ומשפיע על המשתמש בהתחברות הבאה.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.appbar_title', screen: 'store_profile_screen', area: 'כותרת מסך', labelHe: 'אזור אישי — ספק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.settings_row', screen: 'store_profile_screen', area: 'פעולות', labelHe: 'הגדרות ספק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.logout_row', screen: 'store_profile_screen', area: 'פעולות', labelHe: 'יציאה מהחשבון', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.demo_chip', screen: 'store_profile_screen', area: 'כרטיס זהות', labelHe: 'דמו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.stats_title', screen: 'store_profile_screen', area: 'סטטיסטיקת חנות', labelHe: '📊 סטטיסטיקת חנות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.stats_note', screen: 'store_profile_screen', area: 'סטטיסטיקת חנות', labelHe: 'נתונים חיים ממנוע ההזמנות — כלל ההזמנות של החנות.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.profile_row', screen: 'store_profile_screen', area: 'אזור אישי', labelHe: 'פרופיל עסק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.profile_row_sub', screen: 'store_profile_screen', area: 'אזור אישי', labelHe: 'שם, טלפון, כתובת, ח.פ. ולוגו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.certs_row', screen: 'store_profile_screen', area: 'אזור אישי', labelHe: 'תעודות עסק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.certs_row_sub', screen: 'store_profile_screen', area: 'אזור אישי', labelHe: 'רישיון עסק · ביטוח עסק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.docs_row', screen: 'store_profile_screen', area: 'אזור אישי', labelHe: 'מסמכים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.docs_row_sub', screen: 'store_profile_screen', area: 'אזור אישי', labelHe: 'יחובר עם חיבור השרת', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.edit_sheet_title', screen: 'store_profile_screen', area: 'עריכת פרופיל עסק', labelHe: 'עריכת פרופיל עסק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.remove_logo', screen: 'store_profile_screen', area: 'עריכת פרופיל עסק', labelHe: 'הסר לוגו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.save_profile_btn', screen: 'store_profile_screen', area: 'עריכת פרופיל עסק', labelHe: '✓ שמור פרופיל', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.certs_screen_title', screen: 'store_profile_screen', area: 'תעודות עסק', labelHe: '🪪 תעודות עסק', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.add_cert_title', screen: 'store_profile_screen', area: 'הוספת תעודה', labelHe: '🪪 הוספת תעודה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.attach_photo_btn', screen: 'store_profile_screen', area: 'הוספת תעודה', labelHe: '📷 צרף צילום תעודה (לא חובה)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.photo_attached', screen: 'store_profile_screen', area: 'הוספת תעודה', labelHe: '📷 צילום צורף ✓', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.save_cert_btn', screen: 'store_profile_screen', area: 'הוספת תעודה', labelHe: '💾 שמור תעודה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.certs_empty', screen: 'store_profile_screen', area: 'ארנק תעודות', labelHe: 'אין תעודות בארנק עדיין — הוסף את הראשונה.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_profile_screen.add_cert_btn', screen: 'store_profile_screen', area: 'ארנק תעודות', labelHe: '➕ הוסף תעודה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.proj_assign_title', screen: 'store_screen', area: 'cart-project-selector', labelHe: '🏗️ שיוך לפרויקט', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.proj_add_chip', screen: 'store_screen', area: 'cart-project-selector', labelHe: '+ הוסף', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.proj_add_dialog_title', screen: 'store_screen', area: 'cart-project-add-dialog', labelHe: 'הוספת פרויקט', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.proj_add_cancel', screen: 'store_screen', area: 'cart-project-add-dialog', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.proj_add_confirm', screen: 'store_screen', area: 'cart-project-add-dialog', labelHe: 'הוסף', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.supplier_lead_time', screen: 'store_screen', area: 'cart-supplier-header', labelHe: 'אספקה: יום-יומיים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.shipto_title', screen: 'store_screen', area: 'shipto-popup', labelHe: 'לאן לשלוח?', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.shipto_hint', screen: 'store_screen', area: 'shipto-popup', labelHe: 'לא חובה — אפשר לאשר את ההזמנה גם בלי כתובת ולהשלים בהמשך.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.shipto_skip', screen: 'store_screen', area: 'shipto-popup', labelHe: 'דלג', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.shipto_save', screen: 'store_screen', area: 'shipto-popup', labelHe: 'שמירה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.large_order_title', screen: 'store_screen', area: 'checkout-large-order-dialog', labelHe: 'אישור הזמנה גדולה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.large_order_cancel', screen: 'store_screen', area: 'checkout-large-order-dialog', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.large_order_confirm', screen: 'store_screen', area: 'checkout-large-order-dialog', labelHe: 'אשר והמשך', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.checkout_project_label', screen: 'store_screen', area: 'checkout-summary-sheet', labelHe: 'פרויקט', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.checkout_delivery_label', screen: 'store_screen', area: 'checkout-summary-sheet', labelHe: '📦 משלוח', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.checkout_payment_label', screen: 'store_screen', area: 'checkout-summary-sheet', labelHe: '💳 תשלום', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.checkout_total_label', screen: 'store_screen', area: 'checkout-summary-sheet', labelHe: 'סה"כ לתשלום', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.save_list_title', screen: 'store_screen', area: 'cart-save-dialog', labelHe: 'שמור סל כרשימה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.save_list_cancel', screen: 'store_screen', area: 'cart-save-dialog', labelHe: 'ביטול', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.save_list_confirm', screen: 'store_screen', area: 'cart-save-dialog', labelHe: 'שמור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.saved_lists_title', screen: 'store_screen', area: 'saved-lists-sheet', labelHe: '🔖 רשימות שמורות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.saved_lists_empty', screen: 'store_screen', area: 'saved-lists-sheet', labelHe: 'אין רשימות שמורות עדיין', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.actions_lists', screen: 'store_screen', area: 'cart-actions-row', labelHe: 'רשימות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.actions_save', screen: 'store_screen', area: 'cart-actions-row', labelHe: 'שמור', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.actions_share', screen: 'store_screen', area: 'cart-actions-row', labelHe: 'שתף', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.actions_clear', screen: 'store_screen', area: 'cart-actions-row', labelHe: 'נקה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.service_under_construction', screen: 'store_screen', area: 'service-sheet', labelHe: '🚧 בבנייה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.orders_hidden_hint', screen: 'store_screen', area: 'orders-hidden', labelHe: 'הפעלת "היסטוריית רכישות" בהגדרות תציג שוב את ההזמנות.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.orders_hidden_show', screen: 'store_screen', area: 'orders-hidden', labelHe: 'הצג היסטוריה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.order_no_items', screen: 'store_screen', area: 'order-detail-sheet', labelHe: 'פרטי הפריטים אינם זמינים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.order_subtotal', screen: 'store_screen', area: 'order-detail-sheet', labelHe: 'סכום ביניים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.order_vat_delivery', screen: 'store_screen', area: 'order-detail-sheet', labelHe: 'מע"מ + משלוח', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.order_total', screen: 'store_screen', area: 'order-detail-sheet', labelHe: 'סה"כ', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'store_screen.order_scan_delivery', screen: 'store_screen', area: 'order-detail-sheet', labelHe: 'סרוק תעודת-משלוח', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.mgr_login_title', screen: 'welcome_screen', area: 'Manager login', labelHe: 'כניסת מנהל המערכת', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.mgr_login_subtitle', screen: 'welcome_screen', area: 'Manager login', labelHe: 'חשבון הבעלים — כניסה מאובטחת עם חשבון Google.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.mgr_continue_google', screen: 'welcome_screen', area: 'Manager login', labelHe: 'המשך עם Google', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.mgr_needs_connection', screen: 'welcome_screen', area: 'Manager login', labelHe: 'כניסת מנהל דורשת חיבור לאינטרנט. נסה שוב כשיש חיבור.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.mgr_or_code_login', screen: 'welcome_screen', area: 'Board login', labelHe: 'או כניסה עם קוד (demo)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.board_existing_login_btn', screen: 'welcome_screen', area: 'Board login', labelHe: 'כניסה ללקוח קיים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.board_demo_mode', screen: 'welcome_screen', area: 'Board login', labelHe: 'מצב דמו', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.owner_google_login', screen: 'welcome_screen', area: 'Signup sheet', labelHe: 'כניסה עם Google (בעלים)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.existing_login_btn', screen: 'welcome_screen', area: 'Signup sheet', labelHe: 'כניסה ללקוח קיים', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.terms_prefix', screen: 'welcome_screen', area: 'Terms footer', labelHe: 'בהרשמה אתה מאשר את ', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.terms_of_use', screen: 'welcome_screen', area: 'Terms footer', labelHe: 'תנאי השימוש', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.terms_and', screen: 'welcome_screen', area: 'Terms footer', labelHe: ' ואת ', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.privacy_policy', screen: 'welcome_screen', area: 'Terms footer', labelHe: 'מדיניות הפרטיות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'welcome_screen.terms_suffix', screen: 'welcome_screen', area: 'Terms footer', labelHe: ' של BuildSmart', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.appbar_title', screen: 'worker_safety_screen', area: 'AppBar', labelHe: '🛡️ תיק בטיחות', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.add_training_title', screen: 'worker_safety_screen', area: 'Add-training sheet', labelHe: '🎓 הוספת הדרכה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.attach_doc', screen: 'worker_safety_screen', area: 'Add-training sheet', labelHe: '📄 צרף מסמך הדרכה (לא חובה)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.doc_attached', screen: 'worker_safety_screen', area: 'Add-training sheet', labelHe: '📄 מסמך צורף ✓', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.save_training', screen: 'worker_safety_screen', area: 'Add-training sheet', labelHe: '💾 שמור הדרכה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.add_cert_title', screen: 'worker_safety_screen', area: 'Add-cert sheet', labelHe: '🪪 הוספת תעודה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.attach_photo', screen: 'worker_safety_screen', area: 'Add-cert sheet', labelHe: '📷 צרף צילום תעודה (לא חובה)', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.photo_attached', screen: 'worker_safety_screen', area: 'Add-cert sheet', labelHe: '📷 צילום צורף ✓', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.save_cert', screen: 'worker_safety_screen', area: 'Add-cert sheet', labelHe: '💾 שמור תעודה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.no_trainings', screen: 'worker_safety_screen', area: 'Trainings card', labelHe: 'אין הדרכות רשומות עדיין — הוסף את הראשונה.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.demo_hint', screen: 'worker_safety_screen', area: 'Trainings card', labelHe: 'נתוני דמו — רישום הדרכות אמיתי יחובר עם חיבור השרת.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.add_training_btn', screen: 'worker_safety_screen', area: 'Trainings card', labelHe: '➕ הוסף הדרכה', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.no_certs', screen: 'worker_safety_screen', area: 'Certs card', labelHe: 'אין תעודות בארנק עדיין — הוסף את הראשונה.', kind: ElementKind.text, wired: true),
  ElementDescriptor(id: 'worker_safety_screen.add_cert_btn', screen: 'worker_safety_screen', area: 'Certs card', labelHe: '➕ הוסף תעודה', kind: ElementKind.text, wired: true),
];

/// Pillar-2 (the no-code domain builder) overrides this to append domain elements.
/// Empty until then, so the registry is exactly [kElementRegistry].
final domainElementsProvider =
    Provider<List<ElementDescriptor>>((_) => const []);

/// SEAM 4 — FROZEN (step 30): Pillar-2 appends domain rows via
/// [domainElementsProvider]; the 6-field [ElementDescriptor] froze at step 12.5.
/// Pinned by `test/studio/seam_contract_test.dart`.
/// The full registry = built-ins ⊕ domain elements.
final elementRegistryProvider = Provider<List<ElementDescriptor>>(
  (ref) => [...kElementRegistry, ...ref.watch(domainElementsProvider)],
);

/// The critical/immutable set — every registered id flagged `kImmutable` (R1-A1).
/// SINGLE source for both the merge defence (resolve drops a hide/reroute on these)
/// and the publish validator, so the two can never drift (gate-118 · step 26).
final criticalIdsProvider = Provider<Set<String>>(
  (ref) => ref
      .watch(elementRegistryProvider)
      .where((d) => d.kImmutable)
      .map((d) => d.id)
      .toSet(),
);

/// FAIL-CLOSED lookup: returns null for an id not in [all] (the inspector then
/// refuses to edit it and the publish validator rejects it).
ElementDescriptor? findDescriptor(Iterable<ElementDescriptor> all, String id) {
  for (final d in all) {
    if (d.id == id) return d;
  }
  return null;
}

/// The descriptor for `id` across the live (built-in ⊕ domain) registry, or null.
final descriptorProvider = Provider.family<ElementDescriptor?, String>(
  (ref, id) => findDescriptor(ref.watch(elementRegistryProvider), id),
);
