// GENERATED (swarm 10/7, merged by super-cat|classification|slang). Plain layman
// names for catalog categories the core [kPlainDict] misses, matched by EXACT
// category so "מאתר פשוט" reaches ~every product. Re-curate rather than hand-edit.
//
// Appended to the PlainDive tree by plain_dive.dart; the auto-fallback there
// catches anything even these miss, so coverage is ~100%.
import 'package:buildsmart/features/ring_dive/plain_dive.dart' show PlainNode;

const List<PlainNode> kPlainCoverage = <PlainNode>[
  PlainNode(superCat: 'אביזרי חיבור', classification: 'חיבורי נחושת', technical: 'חיבור נחושת', slang: 'חיבור נחושת', english: 'Copper fitting', usage: 'לחיבור צינורות נחושת', categoriesExact: <String>['אביזרי נחושת']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מכסים ורשתות ניקוז', technical: 'מכסה ניקוז', slang: 'מכסה ניקוז', english: 'Drain cover', usage: 'מכסה לפתח ניקוז ברצפה', categoriesExact: <String>['מכסים ורשתות']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'מחברי צנרת פלסטיק', technical: 'מחבר שחור', slang: 'מחבר שחור', english: 'HDPE coupler', usage: 'לחיבור צינורות פלסטיק', categoriesExact: <String>['מחברי HDPE']),
  PlainNode(superCat: 'צנרת וחומרים', classification: 'צינורות ניקוז', technical: 'צינור ניקוז', slang: 'צינור ניקוז', english: 'Drain pipe', usage: 'צינור לניקוז וביוב', categoriesExact: <String>['צינורות', 'צינורות אפורות', 'צינור חלק']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'חבקים ותליה', technical: 'חבק', slang: 'חבק', english: 'Pipe clamp', usage: 'לתלות צינור על הקיר', categoriesExact: <String>['חבקי תליה', 'חבקי צינור']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'אטמים ואומים', technical: 'אטם', slang: 'אטם', english: 'Seals & nuts', usage: 'אטמים ואומים לחיבורים', categoriesExact: <String>['אביזרים משלימים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מכסים ורשתות ניקוז', technical: 'הגבהה לניקוז', slang: 'הגבהה לניקוז', english: 'Drain riser', usage: 'להגביה ניקוז לגובה האריח', categoriesExact: <String>['מכסים, הגבהות ורשתות']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'מחברי צנרת פלסטיק', technical: 'מחבר לצינור', slang: 'מחבר לצינור', english: 'Compression coupler', usage: 'לחיבור צינורות מים מפלסטיק', categoriesExact: <String>['מחברי NTM']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'מזלפי יד', technical: 'מזלף', slang: 'מזלף', english: 'Hand shower', usage: 'מזלף יד למקלחת', categoriesExact: <String>['מזלפי יד']),
  PlainNode(superCat: 'גינה והשקיה', classification: 'צינורות גינה', technical: 'צינור גינה', slang: 'צינור גינה', english: 'Garden hose', usage: 'להשקיה בגינה', categoriesExact: <String>['ציוד גן']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'ברזי קיר', technical: 'ברז קיר', slang: 'ברז קיר', english: 'Wall faucet', usage: 'ברז לכיור אמבטיה מהקיר', categoriesExact: <String>['ברזי קיר']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מכסים ורשתות', technical: 'מכסה ניקוז', slang: 'מכסה ניקוז', english: 'Drain cover', usage: 'מכסה למחסום רצפה', categoriesExact: <String>['כיסויים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'חיבורי ניקוז', technical: 'מחבר ביוב', slang: 'מחבר ביוב', english: 'Drain fitting', usage: 'חיבור לצינורות ביוב', categoriesExact: <String>['אביזרי שקע-תקע']),
  PlainNode(superCat: 'צנרת וחומרים', classification: 'צינורות ניקוז', technical: 'צינור כתום', slang: 'צינור כתום', english: 'PP pipe', usage: 'צינור ביוב חיצוני', categoriesExact: <String>['צינורות PP']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'ראשי מקלחת', technical: 'ראש מקלחת', slang: 'ראש מקלחת', english: 'Shower head', usage: 'הראש הגדול של המקלחת', categoriesExact: <String>['ראשי מקלחת']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'מחלקי מים', technical: 'מחלק מים', slang: 'מחלק מים', english: 'Manifold', usage: 'מחלק קווי מים בבית', categoriesExact: <String>['מחלקים']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'נקודות מים', technical: 'נקודת מים', slang: 'נקודת מים', english: 'Water outlet', usage: 'יציאת מים בקיר עם מתלה', categoriesExact: <String>['נקודות מים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'תעלות ניקוז', technical: 'תעלת ניקוז', slang: 'תעלת ניקוז', english: 'Linear drain', usage: 'ניקוז קווי לרצפת מקלחת', categoriesExact: <String>['מאסף קווי AQUA SLIM']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מחסומי רצפה', technical: 'מחסום רצפה', slang: 'מחסום רצפה', english: 'Floor drain', usage: 'ניקוז רצפה גלוי', categoriesExact: <String>['מחסומים גלויים']),
  PlainNode(superCat: 'צנרת וחומרים', classification: 'צינורות ניקוז', technical: 'צינור שחור', slang: 'צינור שחור', english: 'Multilayer pipe', usage: 'צינור ביוב שקט', categoriesExact: <String>['צינורות רב שכבתי']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מיכלי הדחה', technical: 'מיכל הדחה נמוך', slang: 'מיכל הדחה נמוך', english: 'Low cistern', usage: 'מיכל הדחה נמוך לאסלה', categoriesExact: <String>['התקנה נמוכה']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'מערכות אמבטיה', technical: 'מערכת אמבטיה', slang: 'מערכת אמבטיה', english: 'Bath system', usage: 'ברז וראש מקלחת יחד', categoriesExact: <String>['מערכות אמבטיה']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'עוגנים וחבקים', technical: 'אוגן', slang: 'אוגן', english: 'Wall anchor', usage: 'קיבוע נקודות מים בקיר', categoriesExact: <String>['עוגנים ובנדים']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'אביזרי אמבטיה', technical: 'מתלה מגבת', slang: 'מתלה מגבת', english: 'Towel bar', usage: 'לתלות מגבות באמבטיה', categoriesExact: <String>['אביזרי חדר רחצה']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'מחברים ומצמדים', technical: 'מחבר', slang: 'מחבר', english: 'Coupling', usage: 'לחבר שני צינורות ניקוז', categoriesExact: <String>['אביזרי תבריג']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'ברזי מטבח', technical: 'ברז מטבח', slang: 'ברז מטבח', english: 'Kitchen faucet', usage: 'לכיור המטבח', categoriesExact: <String>['ברזי מטבח']),
  PlainNode(superCat: 'צנרת וחומרים', classification: 'צינורות גמישים', technical: 'צינור גמיש', slang: 'צינור גמיש', english: 'Flexible hose', usage: 'חיבור מים גמיש', categoriesExact: <String>['צינורות גמישים']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'ברזי דלי', technical: 'ברז דלי', slang: 'ברז דלי', english: 'Bib tap', usage: 'מילוי דלי במרפסת שירות', categoriesExact: <String>['ברזי דלי']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'צינורות מקלחת', technical: 'צינור מקלחת', slang: 'צינור מקלחת', english: 'Shower hose', usage: 'מחבר למזלף המקלחת', categoriesExact: <String>['צינורות מקלחת']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מיכלי הדחה', technical: 'מיכל הדחה מונובלוק', slang: 'מיכל הדחה מונובלוק', english: 'Toilet cistern', usage: 'מיכל הדחה על האסלה', categoriesExact: <String>['התקנה צמודה']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'אביזרי מקלחת', technical: 'מפצל מקלחת', slang: 'מפצל מקלחת', english: 'Shower diverter', usage: 'מפצל מים בין ראש למזלף', categoriesExact: <String>['אביזרי מקלחת']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'בקרת לחץ', technical: 'מקטין לחץ', slang: 'מקטין לחץ', english: 'Pressure regulator', usage: 'מווסת לחץ מים בבית', categoriesExact: <String>['מכשירי לחץ']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'פיות ברז', technical: 'פיה', slang: 'פיה', english: 'Faucet spout', usage: 'פיה לברז ולמילוי אמבטיה', categoriesExact: <String>['דיורים ופיות']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'חלקי חילוף', technical: 'ערכת תיקון ברז', slang: 'ערכת תיקון ברז', english: 'Repair kit', usage: 'תיקון ברז דולף', categoriesExact: <String>['חלקים סניטריים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'ניקוז מקלחת', technical: 'תעלת ניקוז', slang: 'תעלת ניקוז', english: 'Shower drain', usage: 'ניקוז רצפת המקלחת', categoriesExact: <String>['תעלות ניקוז']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'ראשי מקלחת', technical: 'זרוע מקלחת', slang: 'זרוע מקלחת', english: 'Shower arm', usage: 'מחזיקה את ראש המקלחת', categoriesExact: <String>['זרועות דוש']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'אביזרי חדר רחצה', technical: 'סט אביזרים לאמבטיה', slang: 'סט אביזרים לאמבטיה', english: 'Bath set', usage: 'אביזרים לתלייה בחדר האמבטיה', categoriesExact: <String>['ערכות רחצה']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'פיות לברז', technical: 'פיה לברז', slang: 'פיה לברז', english: 'Faucet spout', usage: 'יציאת המים בברז', categoriesExact: <String>['אביזרי ברזים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מאספי ניקוז', technical: 'מאסף', slang: 'מאסף', english: 'Drain collector', usage: 'איסוף ניקוז מתחת לרצפה', categoriesExact: <String>['מאספים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מיכלי הדחה', technical: 'ניאגרה גבוהה', slang: 'ניאגרה גבוהה', english: 'High cistern', usage: 'מיכל מים גבוה לאסלה', categoriesExact: <String>['התקנה גבוהה']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'מאספי ניקוז', technical: 'מאסף רצפה', slang: 'מאסף רצפה', english: 'Floor collector', usage: 'ניקוז ברצפת חדר רחצה', categoriesExact: <String>['מאספי רצפה']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'אביזרי חדר רחצה', technical: 'ידית אחיזה', slang: 'ידית אחיזה', english: 'Grab bar', usage: 'אחיזה בטוחה במקלחת', categoriesExact: <String>['ידיות אחיזה']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'ארונות מחלק', technical: 'ארון מחלק', slang: 'ארון מחלק', english: 'Manifold cabinet', usage: 'ארון לצנרת מחלק המים', categoriesExact: <String>['ארונות מחלק']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'ברזי אמבטיה ומקלחת', technical: 'ברז אמבטיה', slang: 'ברז אמבטיה', english: 'Bath faucet', usage: 'ברז ומזלף לאמבטיה', categoriesExact: <String>['ברזי אמבטיה']),
  PlainNode(superCat: 'מקלחת ואמבטיה', classification: 'ברזי אמבטיה ומקלחת', technical: 'ברז מקלחת', slang: 'ברז מקלחת', english: 'Shower faucet', usage: 'ברז ומזלף למקלחת', categoriesExact: <String>['ברזי מקלחת']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'מסעפים ומצמדים', technical: 'מסעף', slang: 'מסעף', english: 'Branch fitting', usage: 'פיצול בצינור ניקוז', categoriesExact: <String>['מסעף']),
  PlainNode(superCat: 'גינה והשקיה', classification: 'ברזי גן', technical: 'ברז גן', slang: 'ברז גן', english: 'Garden tap', usage: 'ברז מים בחצר', categoriesExact: <String>['ברזי גן']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'סיפונים', technical: 'סיפון', slang: 'סיפון', english: 'Sink trap', usage: 'מתחת לכיור, מנקז מים', categoriesExact: <String>['סיפונים']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'ברזים כלליים', technical: 'ברז', slang: 'ברז', english: 'Tap', usage: 'פותח וסוגר מים', categoriesExact: <String>['ברזים']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'סיפונים', technical: 'סיפון אמבטיה', slang: 'סיפון אמבטיה', english: 'Bath drain', usage: 'ניקוז מתחת לאמבטיה', categoriesExact: <String>['סיפונים SmartLock']),
  PlainNode(superCat: 'סניטרי וניקוז', classification: 'שסתומי אל-חזור', technical: 'אל חזור', slang: 'אל חזור', english: 'Check valve', usage: 'מונע חזרת ביוב', categoriesExact: <String>['אל חזור']),
  PlainNode(superCat: 'ברזים ובקרים', classification: 'ברזי כיור', technical: 'ברז כיור', slang: 'ברז כיור', english: 'Basin tap', usage: 'מותקן על הכיור', categoriesExact: <String>['ברזי כיור']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'מצמדים ומחברים', technical: 'מתאם ג\'וקר', slang: 'מתאם ג\'וקר', english: 'Angle adapter', usage: 'מחבר צינורות בזווית', categoriesExact: <String>['מתאם זווית - ג\'וקר']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'מצמדים ומחברים', technical: 'מצמד', slang: 'מצמד', english: 'Coupling', usage: 'מחבר שני צינורות', categoriesExact: <String>['מצמד כפול']),
  PlainNode(superCat: 'אביזרי חיבור', classification: 'אומים ואטמים', technical: 'אום', slang: 'אום', english: 'Nut', usage: 'מהדק חיבור בצנרת', categoriesExact: <String>['אום SmartLock']),
];
