// 🔨 אטום-Dart מחושל (forge) · משפחת-Pure "action" · מחולל ע"י machtzev/ds-forge.mjs ממקור-האמת
// machtzev/pure/action-family.html (אל תערוך ידנית — regen). לובש עיצוב מהחריץ בלבד (DsSeam.skinOf/of/fontsOf,
// חוק-5/6): אפס צבע-קבוע. תוכן Label/Value/Meta.
import 'package:flutter/material.dart';
import '../../dart-ui-bs/ds/ds_seam.dart';

/// PrimaryBtn — seam:fields · מצבים חיים
enum ForgePrimaryBtnState { state, state1, state2, state3, state4, state5 }

class ForgePrimaryBtn extends StatelessWidget {
  final ForgePrimaryBtnState state;
  const ForgePrimaryBtn({super.key, this.state = ForgePrimaryBtnState.state});
  @override
  Widget build(BuildContext context) {
    final skin = DsSeam.skinOf(context);   // מלוא-העיצוב מהחריץ
    final theme = DsSeam.of(context);       // אקצנט (מורף)
    final fonts = DsSeam.fontsOf(context);  // פונט
    return switch (state) {
      ForgePrimaryBtnState.state => Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 34, alignment: Alignment.center, padding: const EdgeInsets.fromLTRB(12, 0, 12, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a, theme.a800], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(9), boxShadow: [BoxShadow(color: const Color(0x66000000), offset: const Offset(0, 1), blurRadius: 2, spreadRadius: 0), BoxShadow(color: theme.gl, offset: const Offset(0, 7), blurRadius: 18, spreadRadius: 0)]), child: Text("Action", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.he, fontSize: 12, fontWeight: FontWeight.w700))), Text("default", style: TextStyle(color: skin.ink, fontFamily: fonts.he))]),
      ForgePrimaryBtnState.state1 => Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 34, alignment: Alignment.center, padding: const EdgeInsets.fromLTRB(12, 0, 12, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a, theme.a800], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(9), boxShadow: [BoxShadow(color: const Color(0x66000000), offset: const Offset(0, 1), blurRadius: 2, spreadRadius: 0), BoxShadow(color: theme.gl, offset: const Offset(0, 12), blurRadius: 26, spreadRadius: 0)]), child: Text("Action", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.he, fontSize: 12, fontWeight: FontWeight.w700))), Text("hover", style: TextStyle(color: skin.ink, fontFamily: fonts.he))]),
      ForgePrimaryBtnState.state2 => Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 34, alignment: Alignment.center, padding: const EdgeInsets.fromLTRB(12, 0, 12, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a, theme.a800], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(9), boxShadow: [BoxShadow(color: const Color(0x66000000), offset: const Offset(0, 1), blurRadius: 2, spreadRadius: 0), BoxShadow(color: theme.gl, offset: const Offset(0, 7), blurRadius: 18, spreadRadius: 0)]), child: Text("Action", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.he, fontSize: 12, fontWeight: FontWeight.w700))), Text("focus", style: TextStyle(color: skin.ink, fontFamily: fonts.he))]),
      ForgePrimaryBtnState.state3 => Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 34, alignment: Alignment.center, padding: const EdgeInsets.fromLTRB(12, 0, 12, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a, theme.a800], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(9)), child: Text("Action", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.he, fontSize: 12, fontWeight: FontWeight.w700))), Text("selected", style: TextStyle(color: skin.ink, fontFamily: fonts.he))]),
      ForgePrimaryBtnState.state4 => Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Opacity(opacity: 0.5, child: Container(height: 34, alignment: Alignment.center, padding: const EdgeInsets.fromLTRB(12, 0, 12, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a, theme.a800], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(9)), child: Text("Action", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.he, fontSize: 12, fontWeight: FontWeight.w700)))), Text("disabled", style: TextStyle(color: skin.ink, fontFamily: fonts.he))]),
      ForgePrimaryBtnState.state5 => Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 34, alignment: Alignment.center, padding: const EdgeInsets.fromLTRB(12, 0, 12, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a, theme.a800], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(9), boxShadow: [BoxShadow(color: const Color(0x66000000), offset: const Offset(0, 1), blurRadius: 2, spreadRadius: 0), BoxShadow(color: theme.gl, offset: const Offset(0, 7), blurRadius: 18, spreadRadius: 0)]), child: Row(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.center, spacing: 7, children: [Container(width: 14, height: 14, decoration: BoxDecoration(border: Border.all(color: const Color(0x660B0B0D), width: 2), borderRadius: BorderRadius.circular(50)))])), Text("loading", style: TextStyle(color: skin.ink, fontFamily: fonts.he))]),
    };
  }
}
