// 🗄️ שמות · חולצו מ-dart/estimate_pressure_drop.dart (מכונת-AST). מטרה→שם; מתחלף פר-וורטיקל.
const Map<String, String> kTerms = {
  'xi_tsvvarbkbvk-kvtr': 'צוואר-בקבוק — קוטר ',
  'xi_tsr-mdy-lzrymh': 'צר מדי לזרימה ',
  'xi_hchlf-at': 'החלף את \"',
  'xi_b': '\" ב-\"',
  'xi_bmydh-gdvlh-yvtr': '\" במידה גדולה יותר',
  'xi_hmvtsr-htsr': 'המוצר הצר',
  'xi_mhyrvt-zrymh': 'מהירות זרימה ',
  'xi_msh-mal-msh-rashkvvyttsyh': ' מ\"ש (מעל 2 מ\"ש = רעש/קוויטציה)',
  'xi_hgdl-at-hkvtr-hchlf': 'הגדל את הקוטר: החלף \"',
  'xi_hgdl-at-hkvtr-shl': 'הגדל את הקוטר של \"',
  'xi_yrydt-lchts': 'ירידת לחץ ',
  'xi_br': ' בר — ',
  'xi_mal-tktsyb-br-hbrz-ysbvl-mchvsr-zrymh': 'מעל תקציב 1 בר. הברז יסבול מחוסר זרימה.',
  'xi_hvsf-mshabt-hgbrh-lhalat-lchts-hknysh': 'הוסף משאבת הגברה (booster) להעלאת לחץ הכניסה',
  'xi_alyyh-ankyt': 'עלייה אנכית ',
  'xi_m': ' מ׳ — ',
  'xi_br-avbdym-al-hgvbh': ' בר אובדים על הגובה',
  'xi_hvsf-mshabt-hgbrh-lpny-halyyh-hankyt': 'הוסף משאבת הגברה לפני העלייה האנכית',
  'xi_zrymh-lamynryt': 'זרימה לאמינרית (Re=',
  'xi_hkvtr-gdvl-mhndrsh-mbzbz-chvmr': 'הקוטר גדול מהנדרש, מבזבז חומר',
  'xi_hktn-at-hkvtr-bchr-vryant-tsr-yvtr-shl': 'הקטן את הקוטר — בחר וריאנט צר יותר של \"',
  'xi_hkv-tkyn': 'הקו תקין',
  'xi_ayn-pavlvt-ndrshvt-lshypvr-hzrymh': 'אין פעולות נדרשות לשיפור הזרימה',
};
