// 🗄️ שמות · חולצו מ-dart/recommended_kit_for_product.dart (מכונת-AST). מטרה→שם; מתחלף פר-וורטיקל.
const Map<String, String> kTerms = {
  'xi_pvlyrvl': 'פולירול',
  'xi_nvmynly': 'dn נומינלי',
  'xi_mm': ' מ\"מ',
  'xi_mtsmd': 'מצמד PPR',
  'xi_abyzr-chybvr': ' (אביזר חיבור)',
  'xi_machd-shny-ktay-tsynvr-brytvkshka': 'מאחד שני קטעי צינור בריתוך-שקע',
  'xi_tbnytrash-rytvk': 'תבנית/ראש ריתוך',
  'xi_zvg-tbnyvt-zkrnkbh-lkvtr-htsynvr': 'זוג תבניות (זכר+נקבה) לקוטר הצינור',
  'xi_chvlyvt': 'חוליות',
  'xi_tsynvr': 'צינור',
  'xi_mptch-lavm-mkt': 'מפתח לאום SmartLock 32-40 (מק\"ט 61040360)',
  'xi11': 'מפתח לאום SmartLock 50-63 (מק\"ט 61060560)',
  'xi_hydvkshchrvr-avm-mptch-yyavdy-mbtych-mvmnt-nkvn': 'הידוק/שחרור אום SmartLock — מפתח ייעודי מבטיח מומנט נכון',
  'xi_mptch-shvvdy-mtkvvnn-lhbrgh': 'מפתח שוודי מתכוונן להברגה ',
  'xi_hydvk-hchybvr-am-hktsh-hzh': 'הידוק החיבור עם הקצה הזה',
  'xi_mptch-chbyshh': 'מפתח חבישה DN',
  'xi_l': ' ל-',
  'xi_hydvk-avm-al-tsynvr': 'הידוק אום compression על צינור',
  'xi_mkvvts-l': 'מכווץ PEX (Crimper) ל-',
  'xi_lchytst-shrvvl-al-tsynvr': 'לחיצת שרוול על צינור PEX',
  'xi_kly-lchytsh-lnchvsht': 'כלי לחיצה לנחושת ',
  'xi_lchytst-al-tsynvr-nchvsht': 'לחיצת O-ring על צינור נחושת',
};
