// task #85ו · RUNTIME WORKER NOTIFICATIONS — the 🔔 bell on the worker board.
//
// A small on-device notification feed: engine events (manager approve/reject,
// a new task auto-assigned by the engine's auto-advance) append entries here,
// and the worker board shows them behind a bell icon with an unread badge.
// NO push / no server — these are honest RUNTIME notifications generated by
// real engine transitions only (אין המצאות: nothing is seeded; the list starts
// empty and fills from actual events). SERVER-READY: real push lands with the
// server; this provider is the seam (`addNotification` becomes the FCM sink).
//
// PER-USERNAME storage: the state is a map `username → list` so each logged
// worker (ran→רן · omer→עומר · demo→רן) sees ONLY their own feed (#66 — the
// same isolation rule as the tasks). Persisted under `bs.worker-notifs.v1`
// with the board_auth load-guard idiom (a user write before the async load
// resolves wins; the late load is dropped).

import 'dart:convert';

import 'package:buildsmart/state/board_auth.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

/// SharedPreferences key (versioned like the other `bs.*.v1` keys).
const String kWorkerNotifsKey = 'bs.worker-notifs.v1';

/// Cap per username so the prefs payload stays small — oldest entries drop.
const int kWorkerNotifsCap = 50;

/// Worker seed index → the board usernames that log in AS that worker — the
/// REVERSE of `workerIndexForSession` (worker_profile_screen.dart): ran→0 (רן)
/// · omer→1 (עומר) · demo→0 (a demo session enters as רן). Engine events know
/// only the task's worker INDEX, so a notification fans out to every username
/// mapped to it — each session still reads exactly its own list.
/// SERVER-SWAP: becomes the server's user↔worker mapping with Firebase Auth.
const Map<int, List<String>> kWorkerUsernames = {
  0: ['ran', 'demo'],
  1: ['omer'],
};

/// One runtime notification on a worker's feed.
class WorkerNotif {
  const WorkerNotif({
    required this.id,
    required this.emoji,
    required this.title,
    required this.ts,
    this.body = '',
    this.read = false,
  });

  factory WorkerNotif.fromJson(Map<String, dynamic> j) => WorkerNotif(
        id: j['id'] as String? ?? '',
        emoji: j['emoji'] as String? ?? '🔔',
        title: j['title'] as String? ?? '',
        body: j['body'] as String? ?? '',
        ts: DateTime.tryParse(j['ts'] as String? ?? '') ?? DateTime.now(),
        read: j['read'] as bool? ?? false,
      );

  final String id;
  final String emoji;
  final String title;

  /// Secondary line (e.g. the task name) — may be empty.
  final String body;
  final DateTime ts;
  final bool read;

  WorkerNotif copyWith({bool? read}) => WorkerNotif(
        id: id,
        emoji: emoji,
        title: title,
        body: body,
        ts: ts,
        read: read ?? this.read,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'emoji': emoji,
        'title': title,
        'body': body,
        'ts': ts.toIso8601String(),
        'read': read,
      };
}

/// The full per-username store: `username → newest-first list`.
class WorkerNotifsNotifier
    extends StateNotifier<Map<String, List<WorkerNotif>>> {
  WorkerNotifsNotifier({this.persist = true}) : super(const {}) {
    if (persist) _load();
  }

  /// When false (tests), skip SharedPreferences entirely (engine pattern).
  final bool persist;

  /// One-shot guard (board_auth idiom): once any mutation wrote state, a late
  /// async `_load()` must not clobber it.
  bool _userTouched = false;

  /// Monotonic suffix so two adds in the same microsecond stay unique.
  int _seq = 0;

  Future<void> _load() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final raw = prefs.getString(kWorkerNotifsKey);
      if (raw == null || raw.isEmpty || _userTouched) return;
      final m = jsonDecode(raw) as Map<String, dynamic>;
      if (_userTouched) return;
      state = {
        for (final e in m.entries)
          if (e.value is List)
            e.key: [
              for (final j in e.value as List)
                if (j is Map)
                  WorkerNotif.fromJson(j.cast<String, dynamic>()),
            ],
      };
    } on Object catch (_) {
      // Corrupt/old payload — start empty (the feed refills from live events).
    }
  }

  Future<void> _persist() async {
    if (!persist) return;
    try {
      final prefs = await SharedPreferences.getInstance();
      await prefs.setString(
        kWorkerNotifsKey,
        jsonEncode({
          for (final e in state.entries)
            e.key: [for (final n in e.value) n.toJson()],
        }),
      );
    } on Object catch (_) {}
  }

  void _set(Map<String, List<WorkerNotif>> next) {
    _userTouched = true;
    state = next;
    _persist();
  }

  /// Append a notification to [username]'s feed (newest first, capped).
  /// SERVER-READY: this is the seam a real push pipeline writes into.
  void addNotification({
    required String username,
    required String emoji,
    required String title,
    String body = '',
  }) {
    final n = WorkerNotif(
      id: '${DateTime.now().microsecondsSinceEpoch}-${_seq++}',
      emoji: emoji,
      title: title,
      body: body,
      ts: DateTime.now(),
    );
    final cur = state[username] ?? const <WorkerNotif>[];
    _set({
      ...state,
      username: [n, ...cur].take(kWorkerNotifsCap).toList(),
    });
  }

  /// Fan a notification out to every username logged in as seed-worker
  /// [worker] (see [kWorkerUsernames]) — the engine-event entry point.
  void addForWorker(
    int worker, {
    required String emoji,
    required String title,
    String body = '',
  }) {
    for (final u in kWorkerUsernames[worker] ?? const <String>[]) {
      addNotification(username: u, emoji: emoji, title: title, body: body);
    }
  }

  /// Mark one notification of [username] as read.
  void markRead(String username, String id) {
    final cur = state[username];
    if (cur == null) return;
    _set({
      ...state,
      username: [
        for (final n in cur)
          if (n.id == id) n.copyWith(read: true) else n,
      ],
    });
  }

  /// Mark the whole feed of [username] as read ("סמן הכל כנקרא").
  void markAllRead(String username) {
    final cur = state[username];
    if (cur == null || cur.every((n) => n.read)) return;
    _set({
      ...state,
      username: [for (final n in cur) n.copyWith(read: true)],
    });
  }

  /// Clear [username]'s feed. IRREVERSIBLE — call sites must confirm first
  /// (`confirmDestructive`).
  void clear(String username) {
    if ((state[username] ?? const []).isEmpty) return;
    _set({...state, username: const []});
  }
}

/// The per-username notification store (map). Most UI reads the derived
/// [currentWorkerNotifsProvider] instead.
final workerNotifsProvider = StateNotifierProvider<WorkerNotifsNotifier,
    Map<String, List<WorkerNotif>>>((ref) => WorkerNotifsNotifier());

/// The LOGGED worker's own feed (newest first) — empty when no worker session
/// (the board gate keeps these widgets unbuilt anyway).
final currentWorkerNotifsProvider = Provider<List<WorkerNotif>>((ref) {
  final s = ref.watch(boardAuthProvider);
  if (s == null || s.role != BoardRole.worker) return const [];
  return ref.watch(workerNotifsProvider)[s.username] ?? const [];
});

/// Unread count for the bell badge on the worker board AppBar.
final currentWorkerUnreadCountProvider = Provider<int>(
  (ref) =>
      ref.watch(currentWorkerNotifsProvider).where((n) => !n.read).length,
);
