// 🔨 אטום-Dart מחושל (forge) · משפחת-Pure "media" · מחולל ע"י machtzev/ds-forge.mjs ממקור-האמת
// machtzev/pure/media-family.html (אל תערוך ידנית — regen). לובש עיצוב מהחריץ בלבד (DsSeam.skinOf/of/fontsOf,
// חוק-5/6): אפס צבע-קבוע. תוכן Label/Value/Meta.
import 'package:flutter/material.dart';
import '../../dart-ui-bs/ds/ds_seam.dart';

/// AvatarGroup — seam:collection
class ForgeAvatarGroup extends StatelessWidget {
  const ForgeAvatarGroup({super.key});
  @override
  Widget build(BuildContext context) {
    final skin = DsSeam.skinOf(context);   // מלוא-העיצוב מהחריץ
    final theme = DsSeam.of(context);       // אקצנט (מורף)
    final fonts = DsSeam.fontsOf(context);  // פונט
    return Container(height: 88, alignment: Alignment.centerRight, child: Wrap(spacing: 14, runSpacing: 14, crossAxisAlignment: WrapCrossAlignment.center, children: [SizedBox(width: 94, height: 34, child: Stack(clipBehavior: Clip.none, children: [Positioned(right: 0, top: 0, bottom: 0, child: Center(widthFactor: 1.0, child: Container(width: 34, height: 34, alignment: Alignment.center, margin: const EdgeInsets.fromLTRB(0, 0, 0, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(999), boxShadow: [BoxShadow(color: skin.canvas, offset: const Offset(0, 0), blurRadius: 0, spreadRadius: 2.5)]), child: Text("L", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.grotesk, fontSize: 13.6, fontWeight: FontWeight.w700, height: 1, leadingDistribution: TextLeadingDistribution.even))))), Positioned(right: 20, top: 0, bottom: 0, child: Center(widthFactor: 1.0, child: Container(width: 34, height: 34, alignment: Alignment.center, margin: const EdgeInsets.fromLTRB(0, 0, 0, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.c2, theme.a, theme.c3], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(999), boxShadow: [BoxShadow(color: skin.canvas, offset: const Offset(0, 0), blurRadius: 0, spreadRadius: 2.5)]), child: Text("L", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.grotesk, fontSize: 13.6, fontWeight: FontWeight.w700, height: 1, leadingDistribution: TextLeadingDistribution.even))))), Positioned(right: 40, top: 0, bottom: 0, child: Center(widthFactor: 1.0, child: Container(width: 34, height: 34, alignment: Alignment.center, margin: const EdgeInsets.fromLTRB(0, 0, 0, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.aHi, theme.a], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(999), boxShadow: [BoxShadow(color: skin.canvas, offset: const Offset(0, 0), blurRadius: 0, spreadRadius: 2.5)]), child: Text("L", style: TextStyle(color: const Color(0xFF0B0B0D), fontFamily: fonts.grotesk, fontSize: 13.6, fontWeight: FontWeight.w700, height: 1, leadingDistribution: TextLeadingDistribution.even))))), Positioned(right: 60, top: 0, bottom: 0, child: Center(widthFactor: 1.0, child: Container(width: 34, height: 34, alignment: Alignment.center, margin: const EdgeInsets.fromLTRB(0, 0, 0, 0), decoration: BoxDecoration(gradient: LinearGradient(colors: [skin.raised2, skin.surface], begin: Alignment.topCenter, end: Alignment.bottomCenter), borderRadius: BorderRadius.circular(999), boxShadow: [BoxShadow(color: skin.canvas, offset: const Offset(0, 0), blurRadius: 0, spreadRadius: 2.5)]), child: Text("L", style: TextStyle(color: skin.mut, fontFamily: fonts.grotesk, fontSize: 13.6, fontWeight: FontWeight.w700, height: 1, leadingDistribution: TextLeadingDistribution.even)))))]))]));
  }
}
