// ✨ חולל ע"י מנוע-הרינדור (render-ds) — דשבורד מנתוני-הישויות. אל תערוך ידנית.
import '../dart-data-bs/auto/gen_app_scr34_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import 'package:flutter/material.dart';

class GenAppScr34Screen extends StatelessWidget {
  const GenAppScr34Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return DsScaffold(
      title: gen_app_scr34_c0,
      subtitle: gen_app_scr34_c1,
      icon: gen_app_scr34_c2,
      children: [
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c3, value: gen_app_scr34_c4, sub: gen_app_scr34_c5, glyph: gen_app_scr34_c6)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c7, value: gen_app_scr34_c8, sub: gen_app_scr34_c9, glyph: gen_app_scr34_c10))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c11, value: gen_app_scr34_c12, sub: gen_app_scr34_c13, glyph: gen_app_scr34_c14)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c15, value: gen_app_scr34_c16, sub: gen_app_scr34_c17, glyph: gen_app_scr34_c18))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c19, value: gen_app_scr34_c20, sub: gen_app_scr34_c21, glyph: gen_app_scr34_c22)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c23, value: gen_app_scr34_c24, sub: gen_app_scr34_c25, glyph: gen_app_scr34_c26))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c27, value: gen_app_scr34_c28, sub: gen_app_scr34_c29, glyph: gen_app_scr34_c30)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c31, value: gen_app_scr34_c32, sub: gen_app_scr34_c33, glyph: gen_app_scr34_c34))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c35, value: gen_app_scr34_c36, sub: gen_app_scr34_c37, glyph: gen_app_scr34_c38)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c39, value: gen_app_scr34_c40, sub: gen_app_scr34_c41, glyph: gen_app_scr34_c42))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c43, value: gen_app_scr34_c44, sub: gen_app_scr34_c45, glyph: gen_app_scr34_c46)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c47, value: gen_app_scr34_c48, sub: gen_app_scr34_c49, glyph: gen_app_scr34_c50))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c51, value: gen_app_scr34_c52, sub: gen_app_scr34_c53, glyph: gen_app_scr34_c54)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c55, value: gen_app_scr34_c56, sub: gen_app_scr34_c57, glyph: gen_app_scr34_c58))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c59, value: gen_app_scr34_c60, sub: gen_app_scr34_c61, glyph: gen_app_scr34_c62)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c63, value: gen_app_scr34_c64, sub: gen_app_scr34_c65, glyph: gen_app_scr34_c66))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c67, value: gen_app_scr34_c68, sub: gen_app_scr34_c69, glyph: gen_app_scr34_c70)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c71, value: gen_app_scr34_c72, sub: gen_app_scr34_c73, glyph: gen_app_scr34_c74))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c75, value: gen_app_scr34_c76, sub: gen_app_scr34_c77, glyph: gen_app_scr34_c78)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c79, value: gen_app_scr34_c80, sub: gen_app_scr34_c81, glyph: gen_app_scr34_c82))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c83, value: gen_app_scr34_c84, sub: gen_app_scr34_c85, glyph: gen_app_scr34_c86)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c87, value: gen_app_scr34_c88, sub: gen_app_scr34_c89, glyph: gen_app_scr34_c90))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c91, value: gen_app_scr34_c92, sub: gen_app_scr34_c93, glyph: gen_app_scr34_c94)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c95, value: gen_app_scr34_c96, sub: gen_app_scr34_c97, glyph: gen_app_scr34_c98))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c99, value: gen_app_scr34_c100, sub: gen_app_scr34_c101, glyph: gen_app_scr34_c102)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c103, value: gen_app_scr34_c104, sub: gen_app_scr34_c105, glyph: gen_app_scr34_c106))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c107, value: gen_app_scr34_c108, sub: gen_app_scr34_c109, glyph: gen_app_scr34_c110)), const SizedBox(width: 12), Expanded(child: DsStat(label: gen_app_scr34_c111, value: gen_app_scr34_c112, sub: gen_app_scr34_c113, glyph: gen_app_scr34_c114))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: DsStat(label: gen_app_scr34_c115, value: gen_app_scr34_c116, sub: gen_app_scr34_c117, glyph: gen_app_scr34_c118)), const SizedBox(width: 12), const Expanded(child: SizedBox())]))),
      ],
    );
  }
}
