// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   טבלה = [טבלה] ⇒ table ⇒ [table] ⇒ DsTable
//   פעולה פתח תיק = [פעולה] פתח תיק ⇒ act ⇒ [action] ⇒ DsChipButton
//   ריק אין תיקים עדיין = [ריק] אין תיקים עדיין ⇒ empty ⇒ [empty] ⇒ EmptyState@premium/feedback
//   מסגרת = [תוכן מסגרת] ⇒ content ⇒ [alert] ⇒ DsNote
//   בלוקים = [תוכן בלוקים] ⇒ content ⇒ [alert] ⇒ DsNote
//   סיווג = [תוכן סיווג] ⇒ content ⇒ [group, alert] ⇒ DsNote
//   אסור = [תוכן אסור] ⇒ content ⇒ [alert] ⇒ DsNote
//   הודעה למשכיר וואטסאפ תיאור = [הודעה] אופציות אחרי השעון רק = [תוכן הודעה] ⇒ message ⇒ [switch, alert] ⇒ ForgeMustChip + DsNote
//   הודעה אם אין תשובה = [הודעה] אופציות אחרי השעון רק = [תוכן הודעה] ⇒ message ⇒ [switch, alert] ⇒ ForgeMustChip + DsNote
//   לוח = [לוח] ⇒ dates ⇒ [magnitude] ⇒ KvLine

import '../dart-data-bs/auto/gen_app_peruk03_px1_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-forge-bs/composite/split_control.dart';
import '../dart-forge-bs/selection/must_chip.dart';
import '../dart-forge-bs/selection/seg_picker_selection.dart';
import '../dart-forge-bs/selection/segmented_pill_toggle_selection.dart';
import '../dart-forge-bs/selection/star_rating.dart';
import '../dart-forge-bs/selection/unit_segment_toggle_selection.dart';
import '../dart-forge-bs/spatial/data_grid.dart';
import '../dart-forge-bs/temporal/event_calendar.dart';
import '../dart-ui-bs/auto/empty_state.dart';
import '../dart-ui-bs/auto/kv_line.dart';
import '../dart-ui-bs/ds/ds_table.dart';
import 'gen_app_peruk03_ent1.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/spatial/spatial.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppPeruk03Px1Screen extends StatelessWidget {
  const GenAppPeruk03Px1Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_peruk03_px1_c203, subtitle: gen_app_peruk03_px1_c204, icon: gen_app_peruk03_px1_c205, children: [
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => ForgeDataGrid(bare: true, columns: [gen_app_peruk03_px1_c1, gen_app_peruk03_px1_c2, gen_app_peruk03_px1_c3, gen_app_peruk03_px1_c4, gen_app_peruk03_px1_c5, gen_app_peruk03_px1_c6, gen_app_peruk03_px1_c7, gen_app_peruk03_px1_c8, gen_app_peruk03_px1_c9, gen_app_peruk03_px1_c10, gen_app_peruk03_px1_c11], items: [for (final r in appStore.records('app_peruk03_ent1')) [(r[gen_app_peruk03_px1_c12] ?? ''), (r[gen_app_peruk03_px1_c13] ?? ''), (r[gen_app_peruk03_px1_c14] ?? ''), (r[gen_app_peruk03_px1_c15] ?? ''), (r[gen_app_peruk03_px1_c16] ?? ''), (r[gen_app_peruk03_px1_c17] ?? ''), (r[gen_app_peruk03_px1_c18] ?? ''), (r[gen_app_peruk03_px1_c19] ?? ''), (r[gen_app_peruk03_px1_c20] ?? ''), (r[gen_app_peruk03_px1_c21] ?? ''), (r[gen_app_peruk03_px1_c22] ?? '')]]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: DsChipButton(label: gen_app_peruk03_px1_c24, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => const GenAppPeruk03Ent1Screen())))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => appStore.records('app_peruk03_ent1').isEmpty ? EmptyState(label: gen_app_peruk03_px1_c26) : const SizedBox.shrink())),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsNote(message: gen_app_peruk03_px1_c30, label: gen_app_peruk03_px1_c31, tone: 0), DsNote(message: gen_app_peruk03_px1_c33, label: gen_app_peruk03_px1_c34, tone: 0), DsNote(message: gen_app_peruk03_px1_c36, label: gen_app_peruk03_px1_c37, tone: 0), DsNote(message: gen_app_peruk03_px1_c39, label: gen_app_peruk03_px1_c40, tone: 0), DsNote(message: gen_app_peruk03_px1_c42, label: gen_app_peruk03_px1_c43, tone: 0), DsNote(message: gen_app_peruk03_px1_c45, label: gen_app_peruk03_px1_c46, tone: 0), DsNote(message: gen_app_peruk03_px1_c48, label: gen_app_peruk03_px1_c49, tone: 0), DsNote(message: gen_app_peruk03_px1_c51, label: gen_app_peruk03_px1_c52, tone: 0)])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsNote(message: gen_app_peruk03_px1_c55, label: gen_app_peruk03_px1_c56, tone: 0), DsNote(message: gen_app_peruk03_px1_c58, label: gen_app_peruk03_px1_c59, tone: 0), DsNote(message: gen_app_peruk03_px1_c61, label: gen_app_peruk03_px1_c62, tone: 0), DsNote(message: gen_app_peruk03_px1_c64, label: gen_app_peruk03_px1_c65, tone: 0), DsNote(message: gen_app_peruk03_px1_c67, label: gen_app_peruk03_px1_c68, tone: 0), DsNote(message: gen_app_peruk03_px1_c70, label: gen_app_peruk03_px1_c71, tone: 0), DsNote(message: gen_app_peruk03_px1_c73, label: gen_app_peruk03_px1_c74, tone: 0), DsNote(message: gen_app_peruk03_px1_c76, label: gen_app_peruk03_px1_c77, tone: 0), DsNote(message: gen_app_peruk03_px1_c79, label: gen_app_peruk03_px1_c80, tone: 0), DsNote(message: gen_app_peruk03_px1_c82, label: gen_app_peruk03_px1_c83, tone: 0)])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsSection(title: gen_app_peruk03_px1_c119, children: [DsNote(message: gen_app_peruk03_px1_c86, label: gen_app_peruk03_px1_c87, tone: 0), DsNote(message: gen_app_peruk03_px1_c89, label: gen_app_peruk03_px1_c90, tone: 0), DsNote(message: gen_app_peruk03_px1_c92, label: gen_app_peruk03_px1_c93, tone: 0), DsNote(message: gen_app_peruk03_px1_c95, label: gen_app_peruk03_px1_c96, tone: 0)], tone: 0), DsSection(title: gen_app_peruk03_px1_c122, children: [DsNote(message: gen_app_peruk03_px1_c98, label: gen_app_peruk03_px1_c99, tone: 0)], tone: 0), DsSection(title: gen_app_peruk03_px1_c125, children: [DsNote(message: gen_app_peruk03_px1_c101, label: gen_app_peruk03_px1_c102, tone: 0)], tone: 0), DsSection(title: gen_app_peruk03_px1_c128, children: [DsNote(message: gen_app_peruk03_px1_c104, label: gen_app_peruk03_px1_c105, tone: 0), DsNote(message: gen_app_peruk03_px1_c107, label: gen_app_peruk03_px1_c108, tone: 0), DsNote(message: gen_app_peruk03_px1_c110, label: gen_app_peruk03_px1_c111, tone: 0), DsNote(message: gen_app_peruk03_px1_c113, label: gen_app_peruk03_px1_c114, tone: 0)], tone: 0), DsSection(title: gen_app_peruk03_px1_c131, children: [DsNote(message: gen_app_peruk03_px1_c116, label: gen_app_peruk03_px1_c117, tone: 0)], tone: 0)])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsNote(message: gen_app_peruk03_px1_c135, label: gen_app_peruk03_px1_c136, tone: 0), DsNote(message: gen_app_peruk03_px1_c138, label: gen_app_peruk03_px1_c139, tone: 0), DsNote(message: gen_app_peruk03_px1_c141, label: gen_app_peruk03_px1_c142, tone: 0), DsNote(message: gen_app_peruk03_px1_c144, label: gen_app_peruk03_px1_c145, tone: 0), DsNote(message: gen_app_peruk03_px1_c147, label: gen_app_peruk03_px1_c148, tone: 0), DsNote(message: gen_app_peruk03_px1_c150, label: gen_app_peruk03_px1_c151, tone: 0), DsNote(message: gen_app_peruk03_px1_c153, label: gen_app_peruk03_px1_c154, tone: 0), DsNote(message: gen_app_peruk03_px1_c156, label: gen_app_peruk03_px1_c157, tone: 0)])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_peruk03_ent1')) Padding(padding: const EdgeInsets.only(bottom: 8), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Padding(padding: const EdgeInsets.only(bottom: 8), child: ForgeMustChip(bare: true, items: [for (final s in [gen_app_peruk03_px1_c164, gen_app_peruk03_px1_c165]) [s]], selected: {((r[gen_app_peruk03_px1_c160] ?? '') == gen_app_peruk03_px1_c161 ? 0 : (r[gen_app_peruk03_px1_c162] ?? '') == gen_app_peruk03_px1_c163 ? 1 : 0)}, onSelect: (i) => appStore.update('app_peruk03_ent1', (r[AppStore.idKey] ?? ''), {gen_app_peruk03_px1_c166: [gen_app_peruk03_px1_c167, gen_app_peruk03_px1_c168][i]}))), DsNote(message: [gen_app_peruk03_px1_c169, ([(r[gen_app_peruk03_px1_c171] ?? '')].any((x) => x.trim().isEmpty) ? '' : (gen_app_peruk03_px1_c170 + (r[gen_app_peruk03_px1_c171] ?? '') + gen_app_peruk03_px1_c172)), ([gen_app_peruk03_px1_c174].any((x) => x.trim().isEmpty) ? '' : (gen_app_peruk03_px1_c173 + gen_app_peruk03_px1_c174 + gen_app_peruk03_px1_c175))].where((x) => x.trim().isNotEmpty).join(' '), label: gen_app_peruk03_px1_c176, tone: 0)]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_peruk03_ent1')) Padding(padding: const EdgeInsets.only(bottom: 8), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Padding(padding: const EdgeInsets.only(bottom: 8), child: ForgeMustChip(bare: true, items: [for (final s in [gen_app_peruk03_px1_c183, gen_app_peruk03_px1_c184]) [s]], selected: {((r[gen_app_peruk03_px1_c179] ?? '') == gen_app_peruk03_px1_c180 ? 0 : (r[gen_app_peruk03_px1_c181] ?? '') == gen_app_peruk03_px1_c182 ? 1 : 0)}, onSelect: (i) => appStore.update('app_peruk03_ent1', (r[AppStore.idKey] ?? ''), {gen_app_peruk03_px1_c185: [gen_app_peruk03_px1_c186, gen_app_peruk03_px1_c187][i]}))), DsNote(message: [gen_app_peruk03_px1_c188, ([(r[gen_app_peruk03_px1_c190] ?? '')].any((x) => x.trim().isEmpty) ? '' : (gen_app_peruk03_px1_c189 + (r[gen_app_peruk03_px1_c190] ?? '') + gen_app_peruk03_px1_c191)), ([gen_app_peruk03_px1_c193].any((x) => x.trim().isEmpty) ? '' : (gen_app_peruk03_px1_c192 + gen_app_peruk03_px1_c193 + gen_app_peruk03_px1_c194))].where((x) => x.trim().isNotEmpty).join(' '), label: gen_app_peruk03_px1_c195, tone: 0)]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_peruk03_ent1')) Padding(padding: const EdgeInsets.only(bottom: 8), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final e in (<List<String>>[[gen_app_peruk03_px1_c199, (r[gen_app_peruk03_px1_c200] ?? '')], [gen_app_peruk03_px1_c201, (r[gen_app_peruk03_px1_c202] ?? '')]].where((e) => e[1].trim().isNotEmpty).toList()..sort((a, b) => a[1].compareTo(b[1])))) KvLine(label: e[0], value: e[1])]))]))),
  ]);
}
