// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   שכירות לשנה = שכירות לשנה ⇒ raw ⇒ [fact] ⇒ DsChip
//   טבלה = [טבלה] ⇒ table ⇒ [table] ⇒ DsTable
//   פעולה פתח תיק = [פעולה] פתח תיק ⇒ act ⇒ [action] ⇒ DsChipButton
//   החלטה = החלטה ⇒ partition ⇒ [group, alert] ⇒ DsSection + DsNote
//   המספר שלך = [מספר] תקרה לפי 3 חודשים: הבטוחות לא יעלו על הסכום הזה במצטבר ⇒ number ⇒ [hero] ⇒ KvLine
//   התשובה = [הודעה] החלטה = [תוכן הודעה] ⇒ message ⇒ [switch, alert] ⇒ ForgeMustChip + DsNote
//   לוח = [לוח] ⇒ dates ⇒ [magnitude] ⇒ KvLine
//   אסור בפלט = [תוכן אסור] ⇒ content ⇒ [alert] ⇒ DsNote

import '../dart-data-bs/auto/gen_app_sechirut_px1_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-forge-bs/composite/split_control.dart';
import '../dart-forge-bs/selection/must_chip.dart';
import '../dart-forge-bs/selection/seg_picker_selection.dart';
import '../dart-forge-bs/selection/segmented_pill_toggle_selection.dart';
import '../dart-forge-bs/selection/star_rating.dart';
import '../dart-forge-bs/selection/unit_segment_toggle_selection.dart';
import '../dart-forge-bs/spatial/data_grid.dart';
import '../dart-forge-bs/temporal/event_calendar.dart';
import '../dart-ui-bs/auto/kv_line.dart';
import '../dart-ui-bs/ds/ds_table.dart';
import 'gen_app_sechirut_ent1.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/spatial/spatial.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/status/status.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppSechirutPx1Screen extends StatelessWidget {
  const GenAppSechirutPx1Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_sechirut_px1_c122, subtitle: gen_app_sechirut_px1_c123, icon: gen_app_sechirut_px1_c124, children: [
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c5] ?? '').toString().trim().isNotEmpty)) Padding(padding: const EdgeInsets.only(bottom: 8), child: ForgeStatusChip(items: [[(r[gen_app_sechirut_px1_c1] ?? '')]], variants: const <int>[0]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => ForgeDataGrid(bare: true, columns: [gen_app_sechirut_px1_c7, gen_app_sechirut_px1_c8, gen_app_sechirut_px1_c9, gen_app_sechirut_px1_c10, gen_app_sechirut_px1_c11, gen_app_sechirut_px1_c12, gen_app_sechirut_px1_c13, gen_app_sechirut_px1_c14, gen_app_sechirut_px1_c15, gen_app_sechirut_px1_c16, gen_app_sechirut_px1_c17, gen_app_sechirut_px1_c18], items: [for (final r in appStore.records('app_sechirut_ent1')) [(r[gen_app_sechirut_px1_c19] ?? ''), (r[gen_app_sechirut_px1_c20] ?? ''), (r[gen_app_sechirut_px1_c21] ?? ''), (r[gen_app_sechirut_px1_c22] ?? ''), (r[gen_app_sechirut_px1_c23] ?? ''), (r[gen_app_sechirut_px1_c24] ?? ''), (r[gen_app_sechirut_px1_c25] ?? ''), (r[gen_app_sechirut_px1_c26] ?? ''), (r[gen_app_sechirut_px1_c27] ?? ''), (r[gen_app_sechirut_px1_c28] ?? ''), (r[gen_app_sechirut_px1_c29] ?? ''), (r[gen_app_sechirut_px1_c30] ?? '')]]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: DsChipButton(label: gen_app_sechirut_px1_c32, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => const GenAppSechirutEnt1Screen())))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsSection(title: gen_app_sechirut_px1_c40 + ' · ' + appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c38] ?? '') == gen_app_sechirut_px1_c39).toList().length.toString(), children: [for (final r in appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c38] ?? '') == gen_app_sechirut_px1_c39).toList()) DsNote(message: (r[gen_app_sechirut_px1_c35] ?? ''), label: (r[gen_app_sechirut_px1_c36] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_sechirut_px1_c45 + ' · ' + appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c43] ?? '') == gen_app_sechirut_px1_c44).toList().length.toString(), children: [for (final r in appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c43] ?? '') == gen_app_sechirut_px1_c44).toList()) DsNote(message: (r[gen_app_sechirut_px1_c35] ?? ''), label: (r[gen_app_sechirut_px1_c36] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_sechirut_px1_c50 + ' · ' + appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c48] ?? '') == gen_app_sechirut_px1_c49).toList().length.toString(), children: [for (final r in appStore.records('app_sechirut_ent1').where((r) => (r[gen_app_sechirut_px1_c48] ?? '') == gen_app_sechirut_px1_c49).toList()) DsNote(message: (r[gen_app_sechirut_px1_c35] ?? ''), label: (r[gen_app_sechirut_px1_c36] ?? ''), tone: 0)], tone: 0)]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_sechirut_ent1')) Padding(padding: const EdgeInsets.only(bottom: 8), child: KvLine(label: gen_app_sechirut_px1_c53, value: (num.tryParse(r[gen_app_sechirut_px1_c54] ?? '') ?? 0).toStringAsFixed(0)))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_sechirut_ent1')) Padding(padding: const EdgeInsets.only(bottom: 8), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Padding(padding: const EdgeInsets.only(bottom: 8), child: ForgeMustChip(bare: true, items: [for (final s in [gen_app_sechirut_px1_c65, gen_app_sechirut_px1_c66, gen_app_sechirut_px1_c67]) [s]], selected: {((r[gen_app_sechirut_px1_c59] ?? '') == gen_app_sechirut_px1_c60 ? 0 : (r[gen_app_sechirut_px1_c61] ?? '') == gen_app_sechirut_px1_c62 ? 1 : (r[gen_app_sechirut_px1_c63] ?? '') == gen_app_sechirut_px1_c64 ? 2 : 0)}, onSelect: (i) => appStore.update('app_sechirut_ent1', (r[AppStore.idKey] ?? ''), {gen_app_sechirut_px1_c68: [gen_app_sechirut_px1_c69, gen_app_sechirut_px1_c70, gen_app_sechirut_px1_c71][i]}))), DsNote(message: ((r[gen_app_sechirut_px1_c92] ?? '') == gen_app_sechirut_px1_c93 ? ([gen_app_sechirut_px1_c94, ([appStore.referencing('app_sechirut_ent3', gen_app_sechirut_px1_c96, (r[AppStore.idKey] ?? '')).map((c) => (c[gen_app_sechirut_px1_c97] ?? '')).where((x) => x.trim().isNotEmpty).join(', ')].any((x) => x.trim().isEmpty) ? '' : (gen_app_sechirut_px1_c95 + appStore.referencing('app_sechirut_ent3', gen_app_sechirut_px1_c96, (r[AppStore.idKey] ?? '')).map((c) => (c[gen_app_sechirut_px1_c97] ?? '')).where((x) => x.trim().isNotEmpty).join(', ') + gen_app_sechirut_px1_c98)), gen_app_sechirut_px1_c99].where((x) => x.trim().isNotEmpty).join(' ')) : (((r[gen_app_sechirut_px1_c81] ?? '') == gen_app_sechirut_px1_c82 ? ([gen_app_sechirut_px1_c83, ([appStore.referencing('app_sechirut_ent3', gen_app_sechirut_px1_c85, (r[AppStore.idKey] ?? '')).map((c) => (c[gen_app_sechirut_px1_c86] ?? '')).where((x) => x.trim().isNotEmpty).join(', ')].any((x) => x.trim().isEmpty) ? '' : (gen_app_sechirut_px1_c84 + appStore.referencing('app_sechirut_ent3', gen_app_sechirut_px1_c85, (r[AppStore.idKey] ?? '')).map((c) => (c[gen_app_sechirut_px1_c86] ?? '')).where((x) => x.trim().isNotEmpty).join(', ') + gen_app_sechirut_px1_c87)), ([(r[gen_app_sechirut_px1_c89] ?? '')].any((x) => x.trim().isEmpty) ? '' : (gen_app_sechirut_px1_c88 + (r[gen_app_sechirut_px1_c89] ?? '') + gen_app_sechirut_px1_c90)), gen_app_sechirut_px1_c91].where((x) => x.trim().isNotEmpty).join(' ')) : (((r[gen_app_sechirut_px1_c77] ?? '') == gen_app_sechirut_px1_c78 ? ([gen_app_sechirut_px1_c79, gen_app_sechirut_px1_c80].where((x) => x.trim().isNotEmpty).join(' ')) : ([gen_app_sechirut_px1_c72, ([(r[gen_app_sechirut_px1_c74] ?? '')].any((x) => x.trim().isEmpty) ? '' : (gen_app_sechirut_px1_c73 + (r[gen_app_sechirut_px1_c74] ?? '') + gen_app_sechirut_px1_c75)), gen_app_sechirut_px1_c76].where((x) => x.trim().isNotEmpty).join(' '))))))), label: gen_app_sechirut_px1_c100, tone: 0)]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_sechirut_ent1')) Padding(padding: const EdgeInsets.only(bottom: 8), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final e in (<List<String>>[[gen_app_sechirut_px1_c104, (r[gen_app_sechirut_px1_c105] ?? '')]].where((e) => e[1].trim().isNotEmpty).toList()..sort((a, b) => a[1].compareTo(b[1])))) KvLine(label: e[0], value: e[1])]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsNote(message: gen_app_sechirut_px1_c107, label: gen_app_sechirut_px1_c108, tone: 0), DsNote(message: gen_app_sechirut_px1_c110, label: gen_app_sechirut_px1_c111, tone: 0), DsNote(message: gen_app_sechirut_px1_c113, label: gen_app_sechirut_px1_c114, tone: 0), DsNote(message: gen_app_sechirut_px1_c116, label: gen_app_sechirut_px1_c117, tone: 0), DsNote(message: gen_app_sechirut_px1_c119, label: gen_app_sechirut_px1_c120, tone: 0)])),
  ]);
}
