// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   אדומים = מונה(צבע=אדום) ⇒ count ⇒ [headline] ⇒ KpiTile
//   צבע = צבע ⇒ partition ⇒ [group, alert] ⇒ DsSection + ToastCard
//   מה לבקש = מה לבקש ⇒ raw ⇒ [fact] ⇒ DsChip
//   ריק אין ממצאים עדיין = [ריק] אין ממצאים עדיין ⇒ empty ⇒ [empty] ⇒ EmptyState@premium/feedback
//   רשימת בדיקה = [תוכן בדיקה] ⇒ content ⇒ [group, alert] ⇒ ToastCard
//   נוסחים לוואטסאפ = [תוכן בקשה] ⇒ content ⇒ [alert] ⇒ ToastCard

import '../dart-data-bs/auto/gen_app_sechirut_px3_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/auto/empty_state.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/premium/dataviz/kpi_tile.dart';
import '../dart-ui-bs/premium/feedback/toast_card.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/card/card.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/header/header.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/status/status.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppSechirutPx3Screen extends StatelessWidget {
  const GenAppSechirutPx3Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_sechirut_px3_c138, subtitle: gen_app_sechirut_px3_c139, icon: gen_app_sechirut_px3_c140, header: false, children: [ForgeCenteredPageHeader(fields: ['', gen_app_sechirut_px3_c138, gen_app_sechirut_px3_c139]), ...[
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => ForgeStatPlain(fields: [gen_app_sechirut_px3_c0, appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c2] ?? '') == gen_app_sechirut_px3_c3).length.toDouble().toStringAsFixed(0)]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [ForgeTitledSection(fields: [gen_app_sechirut_px3_c12 + ' · ' + appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c10] ?? '') == gen_app_sechirut_px3_c11).toList().length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c10] ?? '') == gen_app_sechirut_px3_c11).toList()) ToastCard(message: (r[gen_app_sechirut_px3_c7] ?? ''), tone: 0)]])), ForgeTitledSection(fields: [gen_app_sechirut_px3_c17 + ' · ' + appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c15] ?? '') == gen_app_sechirut_px3_c16).toList().length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c15] ?? '') == gen_app_sechirut_px3_c16).toList()) ToastCard(message: (r[gen_app_sechirut_px3_c7] ?? ''), tone: 0)]])), ForgeTitledSection(fields: [gen_app_sechirut_px3_c22 + ' · ' + appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c20] ?? '') == gen_app_sechirut_px3_c21).toList().length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c20] ?? '') == gen_app_sechirut_px3_c21).toList()) ToastCard(message: (r[gen_app_sechirut_px3_c7] ?? ''), tone: 0)]]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c30] ?? '').toString().trim().isNotEmpty)) Padding(padding: const EdgeInsets.only(bottom: 8), child: ForgeStatusChip(items: [[(r[gen_app_sechirut_px3_c26] ?? '')]], variants: const <int>[0]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => appStore.records('app_sechirut_ent3').isEmpty ? EmptyState(label: gen_app_sechirut_px3_c31) : const SizedBox.shrink())),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [ForgeTitledSection(fields: [gen_app_sechirut_px3_c116, '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[ToastCard(message: gen_app_sechirut_px3_c35, tone: 0), ToastCard(message: gen_app_sechirut_px3_c38, tone: 0), ToastCard(message: gen_app_sechirut_px3_c41, tone: 0), ToastCard(message: gen_app_sechirut_px3_c44, tone: 0), ToastCard(message: gen_app_sechirut_px3_c47, tone: 0), ToastCard(message: gen_app_sechirut_px3_c50, tone: 0), ToastCard(message: gen_app_sechirut_px3_c53, tone: 0)]])), ForgeTitledSection(fields: [gen_app_sechirut_px3_c119, '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[ToastCard(message: gen_app_sechirut_px3_c56, tone: 0), ToastCard(message: gen_app_sechirut_px3_c59, tone: 0), ToastCard(message: gen_app_sechirut_px3_c62, tone: 0), ToastCard(message: gen_app_sechirut_px3_c65, tone: 0), ToastCard(message: gen_app_sechirut_px3_c68, tone: 0), ToastCard(message: gen_app_sechirut_px3_c71, tone: 0), ToastCard(message: gen_app_sechirut_px3_c74, tone: 0), ToastCard(message: gen_app_sechirut_px3_c77, tone: 0), ToastCard(message: gen_app_sechirut_px3_c80, tone: 0), ToastCard(message: gen_app_sechirut_px3_c83, tone: 0)]])), ForgeTitledSection(fields: [gen_app_sechirut_px3_c122, '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[ToastCard(message: gen_app_sechirut_px3_c86, tone: 0), ToastCard(message: gen_app_sechirut_px3_c89, tone: 0), ToastCard(message: gen_app_sechirut_px3_c92, tone: 0), ToastCard(message: gen_app_sechirut_px3_c95, tone: 0), ToastCard(message: gen_app_sechirut_px3_c98, tone: 0), ToastCard(message: gen_app_sechirut_px3_c101, tone: 0), ToastCard(message: gen_app_sechirut_px3_c104, tone: 0), ToastCard(message: gen_app_sechirut_px3_c107, tone: 0), ToastCard(message: gen_app_sechirut_px3_c110, tone: 0), ToastCard(message: gen_app_sechirut_px3_c113, tone: 0)]]))])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [ToastCard(message: gen_app_sechirut_px3_c126, tone: 0), ToastCard(message: gen_app_sechirut_px3_c129, tone: 0), ToastCard(message: gen_app_sechirut_px3_c132, tone: 0), ToastCard(message: gen_app_sechirut_px3_c135, tone: 0)])),
  ]]);
}
