// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   בדיקה = [תוכן בדיקה] ⇒ content ⇒ [group, alert] ⇒ DsNote
//   צבע = צבע ⇒ partition ⇒ [group, alert] ⇒ DsSection + DsNote

import '../dart-data-bs/auto/gen_app_peruk05_px2_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/auto/section_header.dart';
import 'package:flutter/material.dart';

class GenAppPeruk05Px2Screen extends StatelessWidget {
  const GenAppPeruk05Px2Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_peruk05_px2_c68, subtitle: gen_app_peruk05_px2_c69, icon: gen_app_peruk05_px2_c70, children: [
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk05_px2_c40), DsNote(message: gen_app_peruk05_px2_c1, label: gen_app_peruk05_px2_c2, tone: 0), DsNote(message: gen_app_peruk05_px2_c4, label: gen_app_peruk05_px2_c5, tone: 0), DsNote(message: gen_app_peruk05_px2_c7, label: gen_app_peruk05_px2_c8, tone: 0), DsNote(message: gen_app_peruk05_px2_c10, label: gen_app_peruk05_px2_c11, tone: 0), DsNote(message: gen_app_peruk05_px2_c13, label: gen_app_peruk05_px2_c14, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk05_px2_c43), DsNote(message: gen_app_peruk05_px2_c16, label: gen_app_peruk05_px2_c17, tone: 0), DsNote(message: gen_app_peruk05_px2_c19, label: gen_app_peruk05_px2_c20, tone: 0), DsNote(message: gen_app_peruk05_px2_c22, label: gen_app_peruk05_px2_c23, tone: 0), DsNote(message: gen_app_peruk05_px2_c25, label: gen_app_peruk05_px2_c26, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk05_px2_c46), DsNote(message: gen_app_peruk05_px2_c28, label: gen_app_peruk05_px2_c29, tone: 0), DsNote(message: gen_app_peruk05_px2_c31, label: gen_app_peruk05_px2_c32, tone: 0), DsNote(message: gen_app_peruk05_px2_c34, label: gen_app_peruk05_px2_c35, tone: 0), DsNote(message: gen_app_peruk05_px2_c37, label: gen_app_peruk05_px2_c38, tone: 0)])])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsSection(title: gen_app_peruk05_px2_c55 + ' · ' + appStore.records('app_peruk05_ent2').where((r) => (r[gen_app_peruk05_px2_c53] ?? '') == gen_app_peruk05_px2_c54).toList().length.toString(), children: [for (final r in appStore.records('app_peruk05_ent2').where((r) => (r[gen_app_peruk05_px2_c53] ?? '') == gen_app_peruk05_px2_c54).toList()) DsNote(message: (r[gen_app_peruk05_px2_c50] ?? ''), label: (r[gen_app_peruk05_px2_c51] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_peruk05_px2_c60 + ' · ' + appStore.records('app_peruk05_ent2').where((r) => (r[gen_app_peruk05_px2_c58] ?? '') == gen_app_peruk05_px2_c59).toList().length.toString(), children: [for (final r in appStore.records('app_peruk05_ent2').where((r) => (r[gen_app_peruk05_px2_c58] ?? '') == gen_app_peruk05_px2_c59).toList()) DsNote(message: (r[gen_app_peruk05_px2_c50] ?? ''), label: (r[gen_app_peruk05_px2_c51] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_peruk05_px2_c65 + ' · ' + appStore.records('app_peruk05_ent2').where((r) => (r[gen_app_peruk05_px2_c63] ?? '') == gen_app_peruk05_px2_c64).toList().length.toString(), children: [for (final r in appStore.records('app_peruk05_ent2').where((r) => (r[gen_app_peruk05_px2_c63] ?? '') == gen_app_peruk05_px2_c64).toList()) DsNote(message: (r[gen_app_peruk05_px2_c50] ?? ''), label: (r[gen_app_peruk05_px2_c51] ?? ''), tone: 0)], tone: 0)]))),
  ]);
}
