// ✨ חולל ע"י מנוע-הרינדור (render-ds) — דשבורד מנתוני-הישויות החיים. אל תערוך ידנית.
import '../dart-data-bs/auto/gen_app_scr31_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import 'package:flutter/material.dart';

class GenAppScr31Screen extends StatelessWidget {
  const GenAppScr31Screen({super.key});

  @override
  Widget build(BuildContext context) {
    return DsScaffold(
      title: gen_app_scr31_c0,
      subtitle: gen_app_scr31_c1,
      icon: gen_app_scr31_c2,
      children: [
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c3, value: appStore.count(gen_app_scr31_c3).toString(), sub: gen_app_scr31_c4, glyph: gen_app_scr31_c5))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c6, value: appStore.count(gen_app_scr31_c6).toString(), sub: gen_app_scr31_c7, glyph: gen_app_scr31_c8)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c9, value: appStore.count(gen_app_scr31_c9).toString(), sub: gen_app_scr31_c10, glyph: gen_app_scr31_c11))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c12, value: appStore.count(gen_app_scr31_c12).toString(), sub: gen_app_scr31_c13, glyph: gen_app_scr31_c14)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c15, value: appStore.count(gen_app_scr31_c15).toString(), sub: gen_app_scr31_c16, glyph: gen_app_scr31_c17))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c18, value: appStore.count(gen_app_scr31_c18).toString(), sub: gen_app_scr31_c19, glyph: gen_app_scr31_c20)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c21, value: appStore.count(gen_app_scr31_c21).toString(), sub: gen_app_scr31_c22, glyph: gen_app_scr31_c23))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c24, value: appStore.count(gen_app_scr31_c24).toString(), sub: gen_app_scr31_c25, glyph: gen_app_scr31_c26)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c27, value: appStore.count(gen_app_scr31_c27).toString(), sub: gen_app_scr31_c28, glyph: gen_app_scr31_c29))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c30, value: appStore.count(gen_app_scr31_c30).toString(), sub: gen_app_scr31_c31, glyph: gen_app_scr31_c32)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c33, value: appStore.count(gen_app_scr31_c33).toString(), sub: gen_app_scr31_c34, glyph: gen_app_scr31_c35))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c36, value: appStore.count(gen_app_scr31_c36).toString(), sub: gen_app_scr31_c37, glyph: gen_app_scr31_c38)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c39, value: appStore.count(gen_app_scr31_c39).toString(), sub: gen_app_scr31_c40, glyph: gen_app_scr31_c41))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c42, value: appStore.count(gen_app_scr31_c42).toString(), sub: gen_app_scr31_c43, glyph: gen_app_scr31_c44)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c45, value: appStore.count(gen_app_scr31_c45).toString(), sub: gen_app_scr31_c46, glyph: gen_app_scr31_c47))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c48, value: appStore.count(gen_app_scr31_c48).toString(), sub: gen_app_scr31_c49, glyph: gen_app_scr31_c50)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c51, value: appStore.count(gen_app_scr31_c51).toString(), sub: gen_app_scr31_c52, glyph: gen_app_scr31_c53))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c54, value: appStore.count(gen_app_scr31_c54).toString(), sub: gen_app_scr31_c55, glyph: gen_app_scr31_c56)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c57, value: appStore.count(gen_app_scr31_c57).toString(), sub: gen_app_scr31_c58, glyph: gen_app_scr31_c59))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c60, value: appStore.count(gen_app_scr31_c60).toString(), sub: gen_app_scr31_c61, glyph: gen_app_scr31_c62)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c63, value: appStore.count(gen_app_scr31_c63).toString(), sub: gen_app_scr31_c64, glyph: gen_app_scr31_c65))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c66, value: appStore.count(gen_app_scr31_c66).toString(), sub: gen_app_scr31_c67, glyph: gen_app_scr31_c68)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c69, value: appStore.count(gen_app_scr31_c69).toString(), sub: gen_app_scr31_c70, glyph: gen_app_scr31_c71))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c72, value: appStore.count(gen_app_scr31_c72).toString(), sub: gen_app_scr31_c73, glyph: gen_app_scr31_c74)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c75, value: appStore.count(gen_app_scr31_c75).toString(), sub: gen_app_scr31_c76, glyph: gen_app_scr31_c77))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c78, value: appStore.count(gen_app_scr31_c78).toString(), sub: gen_app_scr31_c79, glyph: gen_app_scr31_c80)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c81, value: appStore.count(gen_app_scr31_c81).toString(), sub: gen_app_scr31_c82, glyph: gen_app_scr31_c83))), const SizedBox(width: 12), Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c84, value: appStore.count(gen_app_scr31_c84).toString(), sub: gen_app_scr31_c85, glyph: gen_app_scr31_c86)))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: IntrinsicHeight(child: Row(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Expanded(child: AnimatedBuilder(animation: appStore, builder: (context, _) => DsStat(label: gen_app_scr31_c87, value: appStore.count(gen_app_scr31_c87).toString(), sub: gen_app_scr31_c88, glyph: gen_app_scr31_c89))), const SizedBox(width: 12), const Expanded(child: SizedBox())]))),
      ],
    );
  }
}
