// 🧭 חולל ע"י ניווט-מקשרים (app-shell · G26 · הכרעה-27) — עמוד-השורש: עובדות · ישויות-בנות (מסוננות לרשומה) · דוח. אל תערוך ידנית.

import '../dart-data-bs/auto/gen_app_sechirut_root_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/premium/surfaces/stat_hero.dart';
import 'gen_app_sechirut_ent1.dart';
import 'gen_app_sechirut_ent2.dart';
import 'gen_app_sechirut_ent3.dart';
import 'gen_app_sechirut_ent4.dart';
import 'gen_app_sechirut_rp1.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/card/card.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/header/header.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/action/action.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppSechirutRootScreen extends StatelessWidget {
  const GenAppSechirutRootScreen({required this.id, super.key});
  final String id;
  @override
  Widget build(BuildContext context) => AnimatedBuilder(animation: appStore, builder: (context, _) {
    final r0 = appStore.byId('app_sechirut_ent1', id);
    if (r0 == null) return DsScaffold(title: gen_app_sechirut_root_c93, subtitle: gen_app_sechirut_root_c94, icon: gen_app_sechirut_root_c95, header: false, children: [ForgeCenteredPageHeader(fields: ['', gen_app_sechirut_root_c93, gen_app_sechirut_root_c94]), ...const []]);
    return DsScaffold(title: appStore.displayOf('app_sechirut_ent1', id), subtitle: const [gen_app_sechirut_root_c87, gen_app_sechirut_root_c88, gen_app_sechirut_root_c89, gen_app_sechirut_root_c90, gen_app_sechirut_root_c91, gen_app_sechirut_root_c92][appStore.stageOf('app_sechirut_ent1', id).clamp(0, 5)], icon: gen_app_sechirut_root_c96, header: false, children: [ForgeCenteredPageHeader(fields: ['', appStore.displayOf('app_sechirut_ent1', id), const [gen_app_sechirut_root_c87, gen_app_sechirut_root_c88, gen_app_sechirut_root_c89, gen_app_sechirut_root_c90, gen_app_sechirut_root_c91, gen_app_sechirut_root_c92][appStore.stageOf('app_sechirut_ent1', id).clamp(0, 5)]]), ...[
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ForgeTitledSection(fields: [gen_app_sechirut_root_c60, '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[if ((r0[gen_app_sechirut_root_c48] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c0, (r0[gen_app_sechirut_root_c1] ?? '')])), if ((r0[gen_app_sechirut_root_c49] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c4, (r0[gen_app_sechirut_root_c5] ?? '')])), if ((r0[gen_app_sechirut_root_c50] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c8, (r0[gen_app_sechirut_root_c9] ?? '')])), if ((r0[gen_app_sechirut_root_c51] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c12, (r0[gen_app_sechirut_root_c13] ?? '')])), if ((r0[gen_app_sechirut_root_c52] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c16, (r0[gen_app_sechirut_root_c17] ?? '')])), if ((r0[gen_app_sechirut_root_c53] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c20, (r0[gen_app_sechirut_root_c21] ?? '')])), if ((r0[gen_app_sechirut_root_c54] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c24, (r0[gen_app_sechirut_root_c25] ?? '')])), if ((r0[gen_app_sechirut_root_c55] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c28, (r0[gen_app_sechirut_root_c29] ?? '')])), if ((r0[gen_app_sechirut_root_c56] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c32, (r0[gen_app_sechirut_root_c33] ?? '')])), if ((r0[gen_app_sechirut_root_c57] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c36, (r0[gen_app_sechirut_root_c37] ?? '')])), if ((r0[gen_app_sechirut_root_c58] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c40, (r0[gen_app_sechirut_root_c41] ?? '')])), if ((r0[gen_app_sechirut_root_c59] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_sechirut_root_c44, (r0[gen_app_sechirut_root_c45] ?? '')]))]]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ForgeTitledSection(fields: [gen_app_sechirut_root_c68 + ' · ' + appStore.referencing('app_sechirut_ent2', gen_app_sechirut_root_c61, id).length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.referencing('app_sechirut_ent2', gen_app_sechirut_root_c61, id)) GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutEnt2Screen(scopeField: gen_app_sechirut_root_c64, scopeId: id))), child: ForgeGridHubCard(fields: [(r[gen_app_sechirut_root_c62] ?? ''), (r[gen_app_sechirut_root_c63] ?? '')])), GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutEnt2Screen(scopeField: gen_app_sechirut_root_c64, scopeId: id))), child: ForgeToneButton(items: [[gen_app_sechirut_root_c65]]))]]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ForgeTitledSection(fields: [gen_app_sechirut_root_c76 + ' · ' + appStore.referencing('app_sechirut_ent3', gen_app_sechirut_root_c69, id).length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.referencing('app_sechirut_ent3', gen_app_sechirut_root_c69, id)) GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutEnt3Screen(scopeField: gen_app_sechirut_root_c72, scopeId: id))), child: ForgeGridHubCard(fields: [(r[gen_app_sechirut_root_c70] ?? ''), (r[gen_app_sechirut_root_c71] ?? '')])), GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutEnt3Screen(scopeField: gen_app_sechirut_root_c72, scopeId: id))), child: ForgeToneButton(items: [[gen_app_sechirut_root_c73]]))]]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ForgeTitledSection(fields: [gen_app_sechirut_root_c84 + ' · ' + appStore.referencing('app_sechirut_ent4', gen_app_sechirut_root_c77, id).length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.referencing('app_sechirut_ent4', gen_app_sechirut_root_c77, id)) GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutEnt4Screen(scopeField: gen_app_sechirut_root_c80, scopeId: id))), child: ForgeGridHubCard(fields: [(r[gen_app_sechirut_root_c78] ?? ''), (r[gen_app_sechirut_root_c79] ?? '')])), GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutEnt4Screen(scopeField: gen_app_sechirut_root_c80, scopeId: id))), child: ForgeToneButton(items: [[gen_app_sechirut_root_c81]]))]]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppSechirutRp1Screen(initialId: id))), child: ForgeToneButton(items: [[gen_app_sechirut_root_c85]]))),
    ]]);
  });
}
