// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   אדומים = מונה(צבע=אדום) ⇒ count ⇒ [headline] ⇒ KvLine
//   צבע = צבע ⇒ partition ⇒ [group, alert] ⇒ DsSection + DsNote
//   מה לבקש = מה לבקש ⇒ raw ⇒ [fact] ⇒ DsChip
//   ריק אין ממצאים עדיין = [ריק] אין ממצאים עדיין ⇒ empty ⇒ [empty] ⇒ EmptyState@premium/feedback
//   רשימת בדיקה = [תוכן בדיקה] ⇒ content ⇒ [group, alert] ⇒ DsNote
//   נוסחים לוואטסאפ = [תוכן בקשה] ⇒ content ⇒ [alert] ⇒ DsNote

import '../dart-data-bs/auto/gen_app_sechirut_px3_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/auto/empty_state.dart';
import '../dart-ui-bs/auto/kv_line.dart';
import '../dart-ui-bs/ds/ds.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/status/status.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppSechirutPx3Screen extends StatelessWidget {
  const GenAppSechirutPx3Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_sechirut_px3_c138, subtitle: gen_app_sechirut_px3_c139, icon: gen_app_sechirut_px3_c140, children: [
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => KvLine(label: gen_app_sechirut_px3_c0, value: appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c2] ?? '') == gen_app_sechirut_px3_c3).length.toDouble().toStringAsFixed(0)))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsSection(title: gen_app_sechirut_px3_c12 + ' · ' + appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c10] ?? '') == gen_app_sechirut_px3_c11).toList().length.toString(), children: [for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c10] ?? '') == gen_app_sechirut_px3_c11).toList()) DsNote(message: (r[gen_app_sechirut_px3_c7] ?? ''), label: (r[gen_app_sechirut_px3_c8] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_sechirut_px3_c17 + ' · ' + appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c15] ?? '') == gen_app_sechirut_px3_c16).toList().length.toString(), children: [for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c15] ?? '') == gen_app_sechirut_px3_c16).toList()) DsNote(message: (r[gen_app_sechirut_px3_c7] ?? ''), label: (r[gen_app_sechirut_px3_c8] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_sechirut_px3_c22 + ' · ' + appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c20] ?? '') == gen_app_sechirut_px3_c21).toList().length.toString(), children: [for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c20] ?? '') == gen_app_sechirut_px3_c21).toList()) DsNote(message: (r[gen_app_sechirut_px3_c7] ?? ''), label: (r[gen_app_sechirut_px3_c8] ?? ''), tone: 0)], tone: 0)]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [for (final r in appStore.records('app_sechirut_ent3').where((r) => (r[gen_app_sechirut_px3_c30] ?? '').toString().trim().isNotEmpty)) Padding(padding: const EdgeInsets.only(bottom: 8), child: ForgeStatusChip(items: [[(r[gen_app_sechirut_px3_c26] ?? '')]], variants: const <int>[0]))]))),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => appStore.records('app_sechirut_ent3').isEmpty ? EmptyState(label: gen_app_sechirut_px3_c31) : const SizedBox.shrink())),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsSection(title: gen_app_sechirut_px3_c116, children: [DsNote(message: gen_app_sechirut_px3_c35, label: gen_app_sechirut_px3_c36, tone: 0), DsNote(message: gen_app_sechirut_px3_c38, label: gen_app_sechirut_px3_c39, tone: 0), DsNote(message: gen_app_sechirut_px3_c41, label: gen_app_sechirut_px3_c42, tone: 0), DsNote(message: gen_app_sechirut_px3_c44, label: gen_app_sechirut_px3_c45, tone: 0), DsNote(message: gen_app_sechirut_px3_c47, label: gen_app_sechirut_px3_c48, tone: 0), DsNote(message: gen_app_sechirut_px3_c50, label: gen_app_sechirut_px3_c51, tone: 0), DsNote(message: gen_app_sechirut_px3_c53, label: gen_app_sechirut_px3_c54, tone: 0)], tone: 0), DsSection(title: gen_app_sechirut_px3_c119, children: [DsNote(message: gen_app_sechirut_px3_c56, label: gen_app_sechirut_px3_c57, tone: 0), DsNote(message: gen_app_sechirut_px3_c59, label: gen_app_sechirut_px3_c60, tone: 0), DsNote(message: gen_app_sechirut_px3_c62, label: gen_app_sechirut_px3_c63, tone: 0), DsNote(message: gen_app_sechirut_px3_c65, label: gen_app_sechirut_px3_c66, tone: 0), DsNote(message: gen_app_sechirut_px3_c68, label: gen_app_sechirut_px3_c69, tone: 0), DsNote(message: gen_app_sechirut_px3_c71, label: gen_app_sechirut_px3_c72, tone: 0), DsNote(message: gen_app_sechirut_px3_c74, label: gen_app_sechirut_px3_c75, tone: 0), DsNote(message: gen_app_sechirut_px3_c77, label: gen_app_sechirut_px3_c78, tone: 0), DsNote(message: gen_app_sechirut_px3_c80, label: gen_app_sechirut_px3_c81, tone: 0), DsNote(message: gen_app_sechirut_px3_c83, label: gen_app_sechirut_px3_c84, tone: 0)], tone: 0), DsSection(title: gen_app_sechirut_px3_c122, children: [DsNote(message: gen_app_sechirut_px3_c86, label: gen_app_sechirut_px3_c87, tone: 0), DsNote(message: gen_app_sechirut_px3_c89, label: gen_app_sechirut_px3_c90, tone: 0), DsNote(message: gen_app_sechirut_px3_c92, label: gen_app_sechirut_px3_c93, tone: 0), DsNote(message: gen_app_sechirut_px3_c95, label: gen_app_sechirut_px3_c96, tone: 0), DsNote(message: gen_app_sechirut_px3_c98, label: gen_app_sechirut_px3_c99, tone: 0), DsNote(message: gen_app_sechirut_px3_c101, label: gen_app_sechirut_px3_c102, tone: 0), DsNote(message: gen_app_sechirut_px3_c104, label: gen_app_sechirut_px3_c105, tone: 0), DsNote(message: gen_app_sechirut_px3_c107, label: gen_app_sechirut_px3_c108, tone: 0), DsNote(message: gen_app_sechirut_px3_c110, label: gen_app_sechirut_px3_c111, tone: 0), DsNote(message: gen_app_sechirut_px3_c113, label: gen_app_sechirut_px3_c114, tone: 0)], tone: 0)])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsNote(message: gen_app_sechirut_px3_c126, label: gen_app_sechirut_px3_c127, tone: 0), DsNote(message: gen_app_sechirut_px3_c129, label: gen_app_sechirut_px3_c130, tone: 0), DsNote(message: gen_app_sechirut_px3_c132, label: gen_app_sechirut_px3_c133, tone: 0), DsNote(message: gen_app_sechirut_px3_c135, label: gen_app_sechirut_px3_c136, tone: 0)])),
  ]);
}
