// 🧭 חולל ע"י ניווט-מקשרים (app-shell · G26 · הכרעה-27) — עמוד-השורש: עובדות · ישויות-בנות (מסוננות לרשומה) · דוח. אל תערוך ידנית.

import '../dart-data-bs/auto/gen_app_peruk06_root_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/auto/kv_line.dart';
import 'gen_app_peruk06_ent1.dart';
import 'gen_app_peruk06_ent2.dart';
import 'gen_app_peruk06_rp1.dart';
import 'dart:convert';
import 'package:url_launcher/url_launcher.dart';
import 'package:flutter/material.dart';

/// 8000 ⇒ 8,000 · 12.5 ⇒ 12.5 — סכום קריא בתיק (רק תצוגה; הרשומה נשארת ספרות)
String _fmtNum(String s) { final t = s.trim(); final v = num.tryParse(t.replaceAll(',', '')); if (v == null) return t; final parts = t.replaceAll(',', '').split('.'); final ip = parts[0].replaceAllMapped(RegExp(r'\B(?=(\d{3})+(?!\d))'), (m) => ','); return parts.length > 1 ? ip + '.' + parts[1] : ip; }

class GenAppPeruk06RootScreen extends StatelessWidget {
  const GenAppPeruk06RootScreen({required this.id, super.key});
  final String id;   // ignore: unused_element
  @override
  Widget build(BuildContext context) => AnimatedBuilder(animation: appStore, builder: (context, _) {
    final r0 = appStore.byId('app_peruk06_ent1', id);
    if (r0 == null) return DsScaffold(title: gen_app_peruk06_root_c73, subtitle: gen_app_peruk06_root_c74, icon: gen_app_peruk06_root_c75, children: const []);
    return DsScaffold(title: appStore.displayOf('app_peruk06_ent1', id), subtitle: const [gen_app_peruk06_root_c68, gen_app_peruk06_root_c69, gen_app_peruk06_root_c70, gen_app_peruk06_root_c71, gen_app_peruk06_root_c72][appStore.stageOf('app_peruk06_ent1', id).clamp(0, 4)], icon: gen_app_peruk06_root_c76, children: [
      Padding(padding: const EdgeInsets.only(bottom: 12), child: DsSection(title: gen_app_peruk06_root_c52 + ' · ' + appStore.referencing('app_peruk06_ent2', gen_app_peruk06_root_c45, id).length.toString(), children: [for (final r in appStore.referencing('app_peruk06_ent2', gen_app_peruk06_root_c45, id)) DsNavTile(glyph: gen_app_peruk06_root_c51, title: (r[gen_app_peruk06_root_c46] ?? ''), sub: (r[gen_app_peruk06_root_c47] ?? ''), onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk06Ent2Screen(scopeField: gen_app_peruk06_root_c48, scopeId: id)))), DsPrimaryButton(label: gen_app_peruk06_root_c49, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk06Ent2Screen(scopeField: gen_app_peruk06_root_c48, scopeId: id))))], tone: 0)),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: DsPrimaryButton(label: gen_app_peruk06_root_c53, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk06Rp1Screen(initialId: id))))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: DsFold(title: gen_app_peruk06_root_c55, details: [if ((r0[gen_app_peruk06_root_c36] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c0, value: (r0[gen_app_peruk06_root_c1] ?? '')), if ((r0[gen_app_peruk06_root_c37] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c4, value: (r0[gen_app_peruk06_root_c5] ?? '')), if ((r0[gen_app_peruk06_root_c38] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c8, value: (r0[gen_app_peruk06_root_c9] ?? '')), if ((r0[gen_app_peruk06_root_c39] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c12, value: (r0[gen_app_peruk06_root_c13] ?? '')), if ((r0[gen_app_peruk06_root_c40] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c16, value: (r0[gen_app_peruk06_root_c17] ?? '')), if ((r0[gen_app_peruk06_root_c41] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c20, value: (r0[gen_app_peruk06_root_c21] ?? '')), if ((r0[gen_app_peruk06_root_c42] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c24, value: (r0[gen_app_peruk06_root_c25] ?? '')), if ((r0[gen_app_peruk06_root_c43] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c28, value: (r0[gen_app_peruk06_root_c29] ?? '')), if ((r0[gen_app_peruk06_root_c44] ?? '').trim().isNotEmpty) KvLine(label: gen_app_peruk06_root_c32, value: (r0[gen_app_peruk06_root_c33] ?? ''))])),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: (() { final ph = [(r0[gen_app_peruk06_root_c56] ?? '')].map((x) => x.replaceAll(RegExp(r'[^0-9+]'), '')).firstWhere((x) => x.length >= 9, orElse: () => ''); if (ph.isEmpty) return const SizedBox.shrink(); final intl = ph.startsWith('+') ? ph.substring(1) : (ph.startsWith('0') ? '972' + ph.substring(1) : ph); return Padding(padding: const EdgeInsets.only(bottom: 10), child: Row(children: [DsChipButton(label: gen_app_peruk06_root_c57, onTap: () => launchUrl(Uri.parse('tel:' + ph), mode: LaunchMode.externalApplication)), const SizedBox(width: 8), DsChipButton(label: gen_app_peruk06_root_c58, onTap: () => launchUrl(Uri.parse('https://wa.me/' + intl), mode: LaunchMode.externalApplication))])); })()),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: Padding(padding: const EdgeInsets.only(bottom: 10), child: DsQuickAdd(hint: gen_app_peruk06_root_c59, onSubmit: (t) { final v = t.trim(); if (v.isEmpty) return; final prev = r0['__note'] ?? ''; final stamp = DateTime.now().toIso8601String().substring(0, 10); appStore.update('app_peruk06_ent1', id, {'__note': (prev.isEmpty ? '' : prev + '\n') + stamp + ' · ' + v}); appStore.logAction('auto', gen_app_peruk06_root_c60.replaceAll('{who}', appStore.displayOf('app_peruk06_ent1', id)), entity: 'app_peruk06_ent1', rid: id, field: '__note', prev: prev); }))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: (appStore.stageOf('app_peruk06_ent1', id) >= 4 ? const SizedBox.shrink() : Padding(padding: const EdgeInsets.only(bottom: 10), child: Row(children: [DsChipButton(label: gen_app_peruk06_root_c61, onTap: () { final prev = r0[AppStore.stageKey] ?? '0'; appStore.update('app_peruk06_ent1', id, {AppStore.stageKey: '4'}); appStore.logAction('auto', gen_app_peruk06_root_c62.replaceAll('{who}', appStore.displayOf('app_peruk06_ent1', id)), entity: 'app_peruk06_ent1', rid: id, field: AppStore.stageKey, prev: prev); })])))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: Padding(padding: const EdgeInsets.only(bottom: 10), child: Row(children: [DsChipButton(label: gen_app_peruk06_root_c63, onTap: () { final snap = Map<String, String>.from(r0); appStore.removeById('app_peruk06_ent1', id); appStore.logAction('del', gen_app_peruk06_root_c64.replaceAll('{who}', snap.values.take(2).join(' · ')), entity: 'app_peruk06_ent1', rid: id, prev: jsonEncode(snap)); Navigator.of(context).pop(); })]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: Padding(padding: const EdgeInsets.only(bottom: 10), child: Row(children: [DsChipButton(label: gen_app_peruk06_root_c65, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk06Ent1Screen(editId: id))))]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ((r0['__note'] ?? '').trim().isNotEmpty ? DsFold(title: gen_app_peruk06_root_c66, details: [Text(r0['__note'] ?? '', style: TextStyle(color: DsLook.of(context).ink, fontSize: 15, height: 1.5))]) : const SizedBox.shrink())),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ((r0['__doc'] ?? '').startsWith('data:image') ? DsFold(title: gen_app_peruk06_root_c67, details: [ClipRRect(borderRadius: BorderRadius.circular(12), child: Image.memory(base64Decode((r0['__doc'] ?? '').split(',').last), fit: BoxFit.fitWidth))]) : const SizedBox.shrink())),
    ]);
  });
}
