// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   בדיקה = [תוכן בדיקה] ⇒ content ⇒ [group, alert] ⇒ ToastCard
//   צבע = צבע ⇒ partition ⇒ [group, alert] ⇒ DsSection + ToastCard

import '../dart-data-bs/auto/gen_app_peruk01_px2_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/auto/section_header.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/premium/feedback/toast_card.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/header/header.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppPeruk01Px2Screen extends StatelessWidget {
  const GenAppPeruk01Px2Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_peruk01_px2_c119, subtitle: gen_app_peruk01_px2_c120, icon: gen_app_peruk01_px2_c121, header: false, children: [ForgeCenteredPageHeader(fields: ['', gen_app_peruk01_px2_c119, gen_app_peruk01_px2_c120]), ...[
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c88), ToastCard(message: gen_app_peruk01_px2_c1, tone: 0), ToastCard(message: gen_app_peruk01_px2_c4, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c91), ToastCard(message: gen_app_peruk01_px2_c7, tone: 0), ToastCard(message: gen_app_peruk01_px2_c10, tone: 0), ToastCard(message: gen_app_peruk01_px2_c13, tone: 0), ToastCard(message: gen_app_peruk01_px2_c16, tone: 0), ToastCard(message: gen_app_peruk01_px2_c19, tone: 0), ToastCard(message: gen_app_peruk01_px2_c22, tone: 0), ToastCard(message: gen_app_peruk01_px2_c25, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c94), ToastCard(message: gen_app_peruk01_px2_c28, tone: 0), ToastCard(message: gen_app_peruk01_px2_c31, tone: 0), ToastCard(message: gen_app_peruk01_px2_c34, tone: 0), ToastCard(message: gen_app_peruk01_px2_c37, tone: 0), ToastCard(message: gen_app_peruk01_px2_c40, tone: 0), ToastCard(message: gen_app_peruk01_px2_c43, tone: 0), ToastCard(message: gen_app_peruk01_px2_c46, tone: 0), ToastCard(message: gen_app_peruk01_px2_c49, tone: 0), ToastCard(message: gen_app_peruk01_px2_c52, tone: 0), ToastCard(message: gen_app_peruk01_px2_c55, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c97), ToastCard(message: gen_app_peruk01_px2_c58, tone: 0), ToastCard(message: gen_app_peruk01_px2_c61, tone: 0), ToastCard(message: gen_app_peruk01_px2_c64, tone: 0), ToastCard(message: gen_app_peruk01_px2_c67, tone: 0), ToastCard(message: gen_app_peruk01_px2_c70, tone: 0), ToastCard(message: gen_app_peruk01_px2_c73, tone: 0), ToastCard(message: gen_app_peruk01_px2_c76, tone: 0), ToastCard(message: gen_app_peruk01_px2_c79, tone: 0), ToastCard(message: gen_app_peruk01_px2_c82, tone: 0), ToastCard(message: gen_app_peruk01_px2_c85, tone: 0)])])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [ForgeTitledSection(fields: [gen_app_peruk01_px2_c106 + ' · ' + appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c104] ?? '') == gen_app_peruk01_px2_c105).toList().length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c104] ?? '') == gen_app_peruk01_px2_c105).toList()) ToastCard(message: (r[gen_app_peruk01_px2_c101] ?? ''), tone: 0)]])), ForgeTitledSection(fields: [gen_app_peruk01_px2_c111 + ' · ' + appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c109] ?? '') == gen_app_peruk01_px2_c110).toList().length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c109] ?? '') == gen_app_peruk01_px2_c110).toList()) ToastCard(message: (r[gen_app_peruk01_px2_c101] ?? ''), tone: 0)]])), ForgeTitledSection(fields: [gen_app_peruk01_px2_c116 + ' · ' + appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c114] ?? '') == gen_app_peruk01_px2_c115).toList().length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c114] ?? '') == gen_app_peruk01_px2_c115).toList()) ToastCard(message: (r[gen_app_peruk01_px2_c101] ?? ''), tone: 0)]]))]))),
  ]]);
}
