// 🧭 חולל ע"י ניווט-מקשרים (app-shell · G26 · הכרעה-27) — עמוד-השורש: עובדות · ישויות-בנות (מסוננות לרשומה) · דוח. אל תערוך ידנית.

import '../dart-data-bs/auto/gen_app_peruk04_root_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/premium/surfaces/stat_hero.dart';
import 'gen_app_peruk04_ent1.dart';
import 'gen_app_peruk04_ent2.dart';
import 'gen_app_peruk04_rp1.dart';
import 'package:flutter/material.dart';
import '../dart-forge-bs/card/card.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/header/header.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)
import '../dart-forge-bs/action/action.dart'; // G12c · עור-forge במודול (skin.stat/hero) — אטומי-DS הוחלפו באטומי-forge עם fields; צבעי-מצב של ה-DS (סכנה/תקין) לא מועברים (האטום לובש את החריץ)

class GenAppPeruk04RootScreen extends StatelessWidget {
  const GenAppPeruk04RootScreen({required this.id, super.key});
  final String id;
  @override
  Widget build(BuildContext context) => AnimatedBuilder(animation: appStore, builder: (context, _) {
    final r0 = appStore.byId('app_peruk04_ent1', id);
    if (r0 == null) return DsScaffold(title: gen_app_peruk04_root_c71, subtitle: gen_app_peruk04_root_c72, icon: gen_app_peruk04_root_c73, header: false, children: [ForgeCenteredPageHeader(fields: ['', gen_app_peruk04_root_c71, gen_app_peruk04_root_c72]), ...const []]);
    return DsScaffold(title: appStore.displayOf('app_peruk04_ent1', id), subtitle: const [gen_app_peruk04_root_c66, gen_app_peruk04_root_c67, gen_app_peruk04_root_c68, gen_app_peruk04_root_c69, gen_app_peruk04_root_c70][appStore.stageOf('app_peruk04_ent1', id).clamp(0, 4)], icon: gen_app_peruk04_root_c74, header: false, children: [ForgeCenteredPageHeader(fields: ['', appStore.displayOf('app_peruk04_ent1', id), const [gen_app_peruk04_root_c66, gen_app_peruk04_root_c67, gen_app_peruk04_root_c68, gen_app_peruk04_root_c69, gen_app_peruk04_root_c70][appStore.stageOf('app_peruk04_ent1', id).clamp(0, 4)]]), ...[
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ForgeTitledSection(fields: [gen_app_peruk04_root_c55, '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[if ((r0[gen_app_peruk04_root_c44] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c0, (r0[gen_app_peruk04_root_c1] ?? '')])), if ((r0[gen_app_peruk04_root_c45] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c4, (r0[gen_app_peruk04_root_c5] ?? '')])), if ((r0[gen_app_peruk04_root_c46] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c8, (r0[gen_app_peruk04_root_c9] ?? '')])), if ((r0[gen_app_peruk04_root_c47] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c12, (r0[gen_app_peruk04_root_c13] ?? '')])), if ((r0[gen_app_peruk04_root_c48] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c16, (r0[gen_app_peruk04_root_c17] ?? '')])), if ((r0[gen_app_peruk04_root_c49] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c20, (r0[gen_app_peruk04_root_c21] ?? '')])), if ((r0[gen_app_peruk04_root_c50] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c24, (r0[gen_app_peruk04_root_c25] ?? '')])), if ((r0[gen_app_peruk04_root_c51] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c28, (r0[gen_app_peruk04_root_c29] ?? '')])), if ((r0[gen_app_peruk04_root_c52] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c32, (r0[gen_app_peruk04_root_c33] ?? '')])), if ((r0[gen_app_peruk04_root_c53] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c36, (r0[gen_app_peruk04_root_c37] ?? '')])), if ((r0[gen_app_peruk04_root_c54] ?? '').trim().isNotEmpty) ConstrainedBox(constraints: const BoxConstraints(maxWidth: 420), child: ForgeStatPlain(fields: [gen_app_peruk04_root_c40, (r0[gen_app_peruk04_root_c41] ?? '')]))]]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: ForgeTitledSection(fields: [gen_app_peruk04_root_c63 + ' · ' + appStore.referencing('app_peruk04_ent2', gen_app_peruk04_root_c56, id).length.toString(), '', '', ''], child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.stretch, children: [...[for (final r in appStore.referencing('app_peruk04_ent2', gen_app_peruk04_root_c56, id)) GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk04Ent2Screen(scopeField: gen_app_peruk04_root_c59, scopeId: id))), child: ForgeGridHubCard(fields: [(r[gen_app_peruk04_root_c57] ?? ''), (r[gen_app_peruk04_root_c58] ?? '')])), GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk04Ent2Screen(scopeField: gen_app_peruk04_root_c59, scopeId: id))), child: ForgeToneButton(items: [[gen_app_peruk04_root_c60]]))]]))),
      Padding(padding: const EdgeInsets.only(bottom: 12), child: GestureDetector(behavior: HitTestBehavior.opaque, onTap: () => Navigator.of(context).push(MaterialPageRoute<void>(builder: (_) => GenAppPeruk04Rp1Screen(initialId: id))), child: ForgeToneButton(items: [[gen_app_peruk04_root_c64]]))),
    ]]);
  });
}
