// 🧩 חולל ע"י מפרק-החלקיקים הפתוח (particles · הכרעה-27): כל חלקיק נמצא בכל הקטלוג ומורכב מחדש. אל תערוך ידנית.
//   בדיקה = [תוכן בדיקה] ⇒ content ⇒ [group, alert] ⇒ DsNote
//   צבע = צבע ⇒ partition ⇒ [group, alert] ⇒ DsSection + DsNote

import '../dart-data-bs/auto/gen_app_peruk01_px2_content.dart';
import '../dart-ui-bs/ds/ds.dart';
import '../dart-ui-bs/ds/ds_store.dart';
import '../dart-ui-bs/auto/section_header.dart';
import '../dart-ui-bs/ds/ds.dart';
import 'package:flutter/material.dart';

class GenAppPeruk01Px2Screen extends StatelessWidget {
  const GenAppPeruk01Px2Screen({super.key});
  @override
  Widget build(BuildContext context) => DsScaffold(title: gen_app_peruk01_px2_c119, subtitle: gen_app_peruk01_px2_c120, icon: gen_app_peruk01_px2_c121, children: [
    Padding(padding: const EdgeInsets.only(bottom: 10), child: Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c88), DsNote(message: gen_app_peruk01_px2_c1, label: gen_app_peruk01_px2_c2, tone: 0), DsNote(message: gen_app_peruk01_px2_c4, label: gen_app_peruk01_px2_c5, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c91), DsNote(message: gen_app_peruk01_px2_c7, label: gen_app_peruk01_px2_c8, tone: 0), DsNote(message: gen_app_peruk01_px2_c10, label: gen_app_peruk01_px2_c11, tone: 0), DsNote(message: gen_app_peruk01_px2_c13, label: gen_app_peruk01_px2_c14, tone: 0), DsNote(message: gen_app_peruk01_px2_c16, label: gen_app_peruk01_px2_c17, tone: 0), DsNote(message: gen_app_peruk01_px2_c19, label: gen_app_peruk01_px2_c20, tone: 0), DsNote(message: gen_app_peruk01_px2_c22, label: gen_app_peruk01_px2_c23, tone: 0), DsNote(message: gen_app_peruk01_px2_c25, label: gen_app_peruk01_px2_c26, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c94), DsNote(message: gen_app_peruk01_px2_c28, label: gen_app_peruk01_px2_c29, tone: 0), DsNote(message: gen_app_peruk01_px2_c31, label: gen_app_peruk01_px2_c32, tone: 0), DsNote(message: gen_app_peruk01_px2_c34, label: gen_app_peruk01_px2_c35, tone: 0), DsNote(message: gen_app_peruk01_px2_c37, label: gen_app_peruk01_px2_c38, tone: 0), DsNote(message: gen_app_peruk01_px2_c40, label: gen_app_peruk01_px2_c41, tone: 0), DsNote(message: gen_app_peruk01_px2_c43, label: gen_app_peruk01_px2_c44, tone: 0), DsNote(message: gen_app_peruk01_px2_c46, label: gen_app_peruk01_px2_c47, tone: 0), DsNote(message: gen_app_peruk01_px2_c49, label: gen_app_peruk01_px2_c50, tone: 0), DsNote(message: gen_app_peruk01_px2_c52, label: gen_app_peruk01_px2_c53, tone: 0), DsNote(message: gen_app_peruk01_px2_c55, label: gen_app_peruk01_px2_c56, tone: 0)]), Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [SectionHeader(gen_app_peruk01_px2_c97), DsNote(message: gen_app_peruk01_px2_c58, label: gen_app_peruk01_px2_c59, tone: 0), DsNote(message: gen_app_peruk01_px2_c61, label: gen_app_peruk01_px2_c62, tone: 0), DsNote(message: gen_app_peruk01_px2_c64, label: gen_app_peruk01_px2_c65, tone: 0), DsNote(message: gen_app_peruk01_px2_c67, label: gen_app_peruk01_px2_c68, tone: 0), DsNote(message: gen_app_peruk01_px2_c70, label: gen_app_peruk01_px2_c71, tone: 0), DsNote(message: gen_app_peruk01_px2_c73, label: gen_app_peruk01_px2_c74, tone: 0), DsNote(message: gen_app_peruk01_px2_c76, label: gen_app_peruk01_px2_c77, tone: 0), DsNote(message: gen_app_peruk01_px2_c79, label: gen_app_peruk01_px2_c80, tone: 0), DsNote(message: gen_app_peruk01_px2_c82, label: gen_app_peruk01_px2_c83, tone: 0), DsNote(message: gen_app_peruk01_px2_c85, label: gen_app_peruk01_px2_c86, tone: 0)])])),
    Padding(padding: const EdgeInsets.only(bottom: 10), child: AnimatedBuilder(animation: appStore, builder: (context, _) => Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [DsSection(title: gen_app_peruk01_px2_c106 + ' · ' + appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c104] ?? '') == gen_app_peruk01_px2_c105).toList().length.toString(), children: [for (final r in appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c104] ?? '') == gen_app_peruk01_px2_c105).toList()) DsNote(message: (r[gen_app_peruk01_px2_c101] ?? ''), label: (r[gen_app_peruk01_px2_c102] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_peruk01_px2_c111 + ' · ' + appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c109] ?? '') == gen_app_peruk01_px2_c110).toList().length.toString(), children: [for (final r in appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c109] ?? '') == gen_app_peruk01_px2_c110).toList()) DsNote(message: (r[gen_app_peruk01_px2_c101] ?? ''), label: (r[gen_app_peruk01_px2_c102] ?? ''), tone: 0)], tone: 0), DsSection(title: gen_app_peruk01_px2_c116 + ' · ' + appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c114] ?? '') == gen_app_peruk01_px2_c115).toList().length.toString(), children: [for (final r in appStore.records('app_peruk01_ent2').where((r) => (r[gen_app_peruk01_px2_c114] ?? '') == gen_app_peruk01_px2_c115).toList()) DsNote(message: (r[gen_app_peruk01_px2_c101] ?? ''), label: (r[gen_app_peruk01_px2_c102] ?? ''), tone: 0)], tone: 0)]))),
  ]);
}
