// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent2_c0 = 'משימה';
const String gen_app_ent2_c1 = '6 שדות · 6 שלבים';
const String gen_app_ent2_c2 = '🗂️';
const String gen_app_ent2_c3 = 'שמירה';
const String gen_app_ent2_c4 = 'עדכון';
const String gen_app_ent2_c5 = 'פרטי הרשומה';
const String gen_app_ent2_c6 = 'רשומות';
const String gen_app_ent2_c7 = 'אין משימה עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent2_c8 = 'לא נמצאו רשומות תואמות';
const String gen_app_ent2_c9 = 'שם';
const String gen_app_ent2_c10 = 'מטרה';
const String gen_app_ent2_c11 = 'חללית';
const String gen_app_ent2_c12 = 'תקציב';
const String gen_app_ent2_c13 = 'תאריך התחלה';
const String gen_app_ent2_c14 = 'תאריך סיום';
const String gen_app_ent2_c15 = 'תאריך סיום >= תאריך התחלה';
const String gen_app_ent2_c16 = 'טווח תקציב (0–1000000)';
const String gen_app_ent2_c17 = 'תכנון';
const String gen_app_ent2_c18 = 'שיגור';
const String gen_app_ent2_c19 = 'מעבר';
const String gen_app_ent2_c20 = 'תפעול';
const String gen_app_ent2_c21 = 'חזרה';
const String gen_app_ent2_c22 = 'הושלם';
const String gen_app_ent2_c23 = 'סכום';
const String gen_app_ent2_c24 = '🧮';
const String gen_app_ent2_c25 = 'סה"כ רשומות';
const String gen_app_ent2_c26 = '🗂️';
