// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent1_crumbs_option = 'חדש';
const String gen_app_ent1_crumbs_option2 = 'קשר';
const String gen_app_ent1_crumbs_option3 = 'אפיון';
const String gen_app_ent1_crumbs_option4 = 'סיור';
const String gen_app_ent1_crumbs_option5 = 'תמחור';
const String gen_app_ent1_crumbs_option6 = 'הצעה';
const String gen_app_ent1_crumbs_option7 = 'זכה';
const String gen_app_ent1_header_text = 'טופס ליד';
const String gen_app_ent1_textfield_label = 'שם'; // t_8b1aa6b1
const String gen_app_ent1_textfield_hint = '';
const String gen_app_ent1_textfield_label2 = 'חברה';
const String gen_app_ent1_textfield_hint2 = '';
const String gen_app_ent1_textfield_label3 = 'טלפון'; // t_737232c2
const String gen_app_ent1_textfield_hint3 = '';
const String gen_app_ent1_textfield_label4 = 'מייל'; // t_81f4d41a
const String gen_app_ent1_textfield_hint4 = '';
const String gen_app_ent1_textfield_label5 = 'סוג פרויקט';
const String gen_app_ent1_textfield_hint5 = '';
const String gen_app_ent1_textfield_label6 = 'מיקום'; // t_26d0e7de
const String gen_app_ent1_textfield_hint6 = '';
const String gen_app_ent1_numstep_label = 'תקציב'; // t_3bb32ddd
const String gen_app_ent1_textfield_label7 = 'ציון';
const String gen_app_ent1_textfield_hint7 = '';
const String gen_app_ent1_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent1_neon_label = 'קדם לקשר';
const String gen_app_ent1_neon_toast = 'קדם לקשר';
const String gen_app_ent1_header_text2 = 'רשומות ליד';
const String gen_app_ent1_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent1_stat_label = 'אין שקעים שם פרטי';
const String gen_app_ent1_stat_label2 = 'נרמול טלפון למפתח דדופ';
const String gen_app_ent1_banner_sub = 'ישות ליד';
const String gen_app_ent1_app_bar_title = '🗂️ ליד';
