// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent15_header_text = 'טופס חומר';
const String gen_app_ent15_textfield_label = 'קוד'; // t_2e916690
const String gen_app_ent15_textfield_hint = 'קוד'; // t_2e916690
const String gen_app_ent15_glowfield_hint = 'שם'; // t_8b1aa6b1
const String gen_app_ent15_textfield_label2 = 'קטגוריה'; // t_b593ae97
const String gen_app_ent15_textfield_hint2 = 'קטגוריה'; // t_b593ae97
const String gen_app_ent15_textfield_label3 = 'יחידת מידה';
const String gen_app_ent15_textfield_hint3 = 'יחידת מידה';
const String gen_app_ent15_numstep_label = 'מחיר'; // t_cc097285
const String gen_app_ent15_textfield_label4 = 'מינימום';
const String gen_app_ent15_textfield_hint4 = 'מינימום';
const String gen_app_ent15_textfield_label5 = 'נקודת הזמנה';
const String gen_app_ent15_textfield_hint5 = 'נקודת הזמנה';
const String gen_app_ent15_header_text2 = 'חוקים פר-שדה';
const String gen_app_ent15_stat_label = 'אין שקעים שם פרטי';
const String gen_app_ent15_header_text3 = 'רשומות חומר';
const String gen_app_ent15_banner_sub = 'ישות חומר';
const String gen_app_ent15_app_bar_title = 'הירו 🗂️ חומר | ישות מורכבת — טופס + טבלה';
