// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_scr34_other_glyph = '🔹';
const String gen_app_scr34_other_name = 'לקוח'; // t_9c2118be
const String gen_app_scr34_other_attrs = '8 שדות';
const String gen_app_scr34_other_price_label = '8 שדות';
const String gen_app_scr34_other_qty_label = '8 שדות';
const String gen_app_scr34_other_toast = 'לקוח'; // t_9c2118be
const String gen_app_scr34_other_toast2 = 'לקוח'; // t_9c2118be
const String gen_app_scr34_other_close_semantics_label = '8 שדות';
const String gen_app_scr34_other_close_tooltip = '8 שדות';
const String gen_app_scr34_sheet_title = 'פרויקט'; // t_5a15099c
const String gen_app_scr34_sheet_sub = '12 שדות · 6 שלבים';
const String gen_app_scr34_other_fallback = 'שדה';
const String gen_app_scr34_chip_glyph = '🔹';
const String gen_app_scr34_chip_label = 'סעיף כתב כמויות';
const String gen_app_scr34_chip_toast = 'סעיף כתב כמויות';
const String gen_app_scr34_row_glyph = '🔹';
const String gen_app_scr34_row_name = 'אומדן';
const String gen_app_scr34_row_unit_price_label = '9 שדות';
const String gen_app_scr34_row_qty_label = '9 שדות';
const String gen_app_scr34_row_line_total_label = '9 שדות';
const String gen_app_scr34_row_remove_label = '9 שדות';
const String gen_app_scr34_row_toast = 'אומדן';
const String gen_app_scr34_card_stage_label = 'הצעה';
const String gen_app_scr34_card_items_label = '7 שדות · 5 שלבים';
const String gen_app_scr34_card_sum_label = '7 שדות · 5 שלבים';
const String gen_app_scr34_card_toast = 'הצעה';
const String gen_app_scr34_header_text = 'דשבורד בטיחות עם בדיקות פתוחות · לוגיקה חיה';
const String gen_app_scr34_stat_label = 'סיווג אזור של מספר';
const String gen_app_scr34_banner_sub = 'המחולל מרכיב UI + לוגיקה מהמדף, ובחר לבד לפי משמעות';
const String gen_app_scr34_app_bar_title = '🎯 דשבורד בטיחות עם בדיקות פתוחות';
