// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent17_crumbs_option = 'טיוטה'; // t_25fd43cd
const String gen_app_ent17_crumbs_option2 = 'נבדק';
const String gen_app_ent17_crumbs_option3 = 'אושר'; // t_db4a9245
const String gen_app_ent17_header_text = 'טופס מסמך';
const String gen_app_ent17_textfield_label = 'פרויקט'; // t_5a15099c
const String gen_app_ent17_textfield_hint = '';
const String gen_app_ent17_textfield_label2 = 'סוג'; // t_f45000d5
const String gen_app_ent17_textfield_hint2 = '';
const String gen_app_ent17_textfield_label3 = 'שם'; // t_8b1aa6b1
const String gen_app_ent17_textfield_hint3 = '';
const String gen_app_ent17_textfield_label4 = 'גרסה';
const String gen_app_ent17_textfield_hint4 = '';
const String gen_app_ent17_textfield_label5 = 'תאריך'; // t_c87f355d
const String gen_app_ent17_textfield_hint5 = '';
const String gen_app_ent17_textfield_label6 = 'מאשר';
const String gen_app_ent17_textfield_hint6 = '';
const String gen_app_ent17_textfield_label7 = 'תוקף';
const String gen_app_ent17_textfield_hint7 = '';
const String gen_app_ent17_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent17_neon_label = 'קדם לנבדק';
const String gen_app_ent17_neon_toast = 'קדם לנבדק';
const String gen_app_ent17_header_text2 = 'רשומות מסמך';
const String gen_app_ent17_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent17_stat_label = 'אין שקעים שם פרטי';
const String gen_app_ent17_stat_label2 = 'תאריך לתצוגה';
const String gen_app_ent17_banner_sub = 'ישות מסמך';
const String gen_app_ent17_app_bar_title = '🗂️ מסמך';
