// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_mission_calc_arg = 'א'; // t_e194bcc5
const String gen_mission_calc_arg2 = 'ב'; // t_23c1e0ba
const String gen_mission_calc_arg3 = 'ג'; // t_e89d5099
const String gen_mission_calc_arg4 = 'ד'; // t_8aea2ff5
const String gen_mission_calc_arg5 = 'ה'; // t_cf3fdd9b
const String gen_mission_calc_arg6 = 'ו'; // t_8ccf3c9f
const String gen_mission_calc_arg7 = 'ז'; // t_66cac148
const String gen_mission_calc_arg8 = 'ח';
const String gen_mission_calc_arg9 = 'ט';
const String gen_mission_calc_arg10 = 'י';
const String gen_mission_calc_arg11 = 'כ'; // t_926d8abe
const String gen_mission_calc_arg12 = 'ל'; // t_d67cdc0f
const String gen_mission_calc_arg13 = 'מ'; // t_f29f753f
const String gen_mission_calc_arg14 = 'נ'; // t_c223f5f2
const String gen_mission_calc_arg15 = 'ס';
const String gen_mission_calc_arg16 = 'ע';
const String gen_mission_calc_arg17 = 'פ'; // t_a604395c
const String gen_mission_calc_arg18 = 'צ'; // t_13567a9b
const String gen_mission_calc_arg19 = 'ק';
const String gen_mission_calc_arg20 = 'ר';
const String gen_mission_calc_arg21 = 'ש'; // t_f604bef9
const String gen_mission_calc_arg22 = 'ת';
const String gen_mission_calc_arg23 = 'תק';
const String gen_mission_calc_arg24 = 'תר';
const String gen_mission_calc_arg25 = 'תש';
const String gen_mission_calc_arg26 = 'תת';
const String gen_mission_calc_arg27 = 'תתק';
const String gen_mission_calc_arg28 = 'טו';
const String gen_mission_calc_arg29 = 'טז';
const String gen_mission_calc_arg30 = '׳'; // t_92308040
const String gen_mission_calc_arg31 = '״'; // t_391c42e6
const String gen_mission_card_glyph = '🚀';
const String gen_mission_card_title = 'חדר בקרה - משימה לירח';
const String gen_mission_card_sub = 'אטומים שנולדו לצדקה ולבניין - מחווטים לעולם הפוך';
const String gen_mission_card_toast = 'חדר בקרה - משימה לירח';
const String gen_mission_header_text = 'אות קריאה - הקלידו שם משימה והמנוע טובע קוד';
const String gen_mission_stat_label = 'קוד זמנה דטרמיניסטי';
const String gen_mission_textfield_label = 'הקלידו את שם המשימה';
const String gen_mission_textfield_hint = 'הקלידו את שם המשימה';
const String gen_mission_header_text2 = 'אתר הנחיתה - הבחירה מחליפה את התדרוך';
const String gen_mission_stat_value = '3';
const String gen_mission_stat_label2 = 'ימי שהייה במישורי הבזלת';
const String gen_mission_stat_value2 = '14';
const String gen_mission_stat_label3 = 'ימי קידוח בקרח הקוטבי';
const String gen_mission_stat_value3 = '7';
const String gen_mission_stat_label4 = 'ימים ללא קשר ישיר עם כדור הארץ';
const String gen_mission_radio_option = 'ים השקט';
const String gen_mission_radio_option2 = 'הקוטב הדרומי';
const String gen_mission_radio_option3 = 'הצד הרחוק';
const String gen_mission_header_text3 = 'שעון המשימה - הלוח העברי חי';
const String gen_mission_row_label = 'שם חודש עברי';
const String gen_mission_header_text4 = 'מספר המשימה בגימטריה';
const String gen_mission_stat_label5 = 'גימטריה מספר אותיות עבריות';
const String gen_mission_row_label2 = 'יומן תדרים - ערוץ חירום מגהרץ';
const String gen_mission_switch_label = 'ערוץ קשר פתוח';
const String gen_mission_stat_value4 = '42';
const String gen_mission_stat_label6 = 'שלבי שיגור בתוכנית הטיסה';
const String gen_mission_banner_sub = 'כל אטום כאן נולד לקבלות ולמלאי ולחוגים - והמחולל חיווט מהם חדר בקרה לחלל';
const String gen_mission_button_label = 'שיגור';
const String gen_mission_button_toast = 'שיגור';
const String gen_mission_app_bar_title = 'חדר בקרה - משימה לירח';
