// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_capclockcalendar_card_glyph = '🧪';
const String gen_capclockcalendar_card_title = 'מסע-בזמן של השעון - שעת-יממה נהפכת לתאריך-תצוגה כשכל דקה מחצות נספרת כיום שלם בלוח';
const String gen_capclockcalendar_card_sub = 'יכולת שהוזמנה ולא היתה קיימת - הרכבתי אותה לבד מ-3 אטומים והוכחתי על 2 דוגמאות';
const String gen_capclockcalendar_card_toast = 'מסע-בזמן של השעון - שעת-יממה נהפכת לתאריך-תצוגה כשכל דקה מחצות נספרת כיום שלם בלוח';
const String gen_capclockcalendar_header_text = 'תחנת ההוכחה - הדוגמאות שהוזמנו מדליקות את השרשרת';
const String gen_capclockcalendar_stat_label = 'לדקות מחצות';
const String gen_capclockcalendar_stat_label2 = 'מספר סידורי';
const String gen_capclockcalendar_stat_label3 = 'תאריך לתצוגה';
const String gen_capclockcalendar_chip_option = '13:05';
const String gen_capclockcalendar_chip_option2 = '07:45';
const String gen_capclockcalendar_header_text2 = 'תחנת הקלט החופשי - הקלידו כל ערך והשרשרת רצה חיה';
const String gen_capclockcalendar_stat_label4 = 'לדקות מחצות';
const String gen_capclockcalendar_stat_label5 = 'מספר סידורי';
const String gen_capclockcalendar_stat_label6 = 'תאריך לתצוגה';
const String gen_capclockcalendar_textfield_label = 'הקלידו ערך עבור מסע-בזמן של השעון';
const String gen_capclockcalendar_textfield_hint = '';
const String gen_capclockcalendar_banner_sub = 'ההרכבה שמצאתי - timeToMin ⟵ excelSerialToIso ⟵ fmtDate - כל הדוגמאות עברו';
const String gen_capclockcalendar_app_bar_title = 'מסע-בזמן של השעון - שעת-יממה נהפכת לתאריך-תצוגה כשכל דקה מחצות נספרת כיום שלם בלוח';
