// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent2_header_text = 'טופס לקוח';
const String gen_app_ent2_textfield_label = 'שם'; // t_8b1aa6b1
const String gen_app_ent2_textfield_hint = 'שם'; // t_8b1aa6b1
const String gen_app_ent2_glowfield_hint = 'חברה';
const String gen_app_ent2_numstep_label = 'מספר עוסק';
const String gen_app_ent2_textfield_label2 = 'איש קשר';
const String gen_app_ent2_textfield_hint2 = 'איש קשר';
const String gen_app_ent2_textfield_label3 = 'טלפון'; // t_737232c2
const String gen_app_ent2_textfield_hint3 = 'טלפון'; // t_737232c2
const String gen_app_ent2_textfield_label4 = 'מייל'; // t_81f4d41a
const String gen_app_ent2_textfield_hint4 = 'מייל'; // t_81f4d41a
const String gen_app_ent2_textfield_label5 = 'כתובת'; // t_daab1ad0
const String gen_app_ent2_textfield_hint5 = 'כתובת'; // t_daab1ad0
const String gen_app_ent2_textfield_label6 = 'דירוג';
const String gen_app_ent2_textfield_hint6 = 'דירוג';
const String gen_app_ent2_header_text2 = 'חוקים פר-שדה';
const String gen_app_ent2_stat_label = 'אין שקעים שם פרטי';
const String gen_app_ent2_stat_label2 = 'מספר סידורי של';
const String gen_app_ent2_stat_label3 = 'נרמול טלפון למפתח דדופ';
const String gen_app_ent2_header_text3 = 'רשומות לקוח';
const String gen_app_ent2_banner_sub = 'ישות לקוח';
const String gen_app_ent2_app_bar_title = 'הירו 🗂️ לקוח | ישות מורכבת — טופס + טבלה';
