// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent19_crumbs_option = 'הוגש';
const String gen_app_ent19_crumbs_option2 = 'בבדיקה';
const String gen_app_ent19_crumbs_option3 = 'תיקונים';
const String gen_app_ent19_crumbs_option4 = 'אושר'; // t_db4a9245
const String gen_app_ent19_crumbs_option5 = 'נסגר';
const String gen_app_ent19_header_text = 'טופס שדה';
const String gen_app_ent19_textfield_label = 'פרויקט'; // t_5a15099c
const String gen_app_ent19_textfield_hint = '';
const String gen_app_ent19_textfield_label2 = 'חומר'; // t_9a215501
const String gen_app_ent19_textfield_hint2 = '';
const String gen_app_ent19_textfield_label3 = 'יצרן'; // t_ae3831b4
const String gen_app_ent19_textfield_hint3 = '';
const String gen_app_ent19_textfield_label4 = 'ספק'; // t_7c71c3ed
const String gen_app_ent19_textfield_hint4 = '';
const String gen_app_ent19_textfield_label5 = 'תאריך הגשה';
const String gen_app_ent19_textfield_hint5 = '';
const String gen_app_ent19_textfield_label6 = 'בודק';
const String gen_app_ent19_textfield_hint6 = '';
const String gen_app_ent19_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent19_neon_label = 'קדם לבבדיקה';
const String gen_app_ent19_neon_toast = 'קדם לבבדיקה';
const String gen_app_ent19_header_text2 = 'רשומות שדה';
const String gen_app_ent19_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent19_stat_label = 'תאריך לתצוגה';
const String gen_app_ent19_banner_sub = 'ישות שדה';
const String gen_app_ent19_app_bar_title = '🗂️ שדה';
