// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent4_header_text = 'טופס שדה';
const String gen_app_ent4_textfield_label = 'קוד'; // t_2e916690
const String gen_app_ent4_textfield_hint = '';
const String gen_app_ent4_textfield_label2 = 'שם'; // t_8b1aa6b1
const String gen_app_ent4_textfield_hint2 = '';
const String gen_app_ent4_textfield_label3 = 'שלב'; // t_42662332
const String gen_app_ent4_textfield_hint3 = '';
const String gen_app_ent4_textfield_label4 = 'אחראי';
const String gen_app_ent4_textfield_hint4 = '';
const String gen_app_ent4_textfield_label5 = 'תאריך התחלה';
const String gen_app_ent4_textfield_hint5 = '';
const String gen_app_ent4_textfield_label6 = 'תאריך סיום';
const String gen_app_ent4_textfield_hint6 = '';
const String gen_app_ent4_numstep_label = 'אחוז ביצוע';
const String gen_app_ent4_numstep_label2 = 'תקציב'; // t_3bb32ddd
const String gen_app_ent4_numstep_label3 = 'עלות בפועל';
const String gen_app_ent4_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent4_header_text2 = 'רשומות שדה';
const String gen_app_ent4_banner_sub = 'ישות שדה';
const String gen_app_ent4_app_bar_title = '🗂️ שדה';
