// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent28_crumbs_option = 'טיוטה'; // t_25fd43cd
const String gen_app_ent28_crumbs_option2 = 'הופקה';
const String gen_app_ent28_crumbs_option3 = 'נשלחה';
const String gen_app_ent28_crumbs_option4 = 'שולמה';
const String gen_app_ent28_header_text = 'טופס חשבונית';
const String gen_app_ent28_numstep_label = 'מספר'; // t_c19510f4
const String gen_app_ent28_textfield_label = 'לקוח'; // t_9c2118be
const String gen_app_ent28_textfield_hint = '';
const String gen_app_ent28_textfield_label2 = 'פרויקט'; // t_5a15099c
const String gen_app_ent28_textfield_hint2 = '';
const String gen_app_ent28_numstep_label2 = 'סכום'; // t_2ef7fdce
const String gen_app_ent28_textfield_label3 = 'מס';
const String gen_app_ent28_textfield_hint3 = '';
const String gen_app_ent28_textfield_label4 = 'תאריך'; // t_c87f355d
const String gen_app_ent28_textfield_hint4 = '';
const String gen_app_ent28_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent28_neon_label = 'קדם להופקה';
const String gen_app_ent28_neon_toast = 'קדם להופקה';
const String gen_app_ent28_header_text2 = 'רשומות חשבונית';
const String gen_app_ent28_banner_sub = 'ישות חשבונית';
const String gen_app_ent28_app_bar_title = '🗂️ חשבונית';
