// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_captimegematria_calc_arg = 'א'; // t_e194bcc5
const String gen_captimegematria_calc_arg2 = 'ב'; // t_23c1e0ba
const String gen_captimegematria_calc_arg3 = 'ג'; // t_e89d5099
const String gen_captimegematria_calc_arg4 = 'ד'; // t_8aea2ff5
const String gen_captimegematria_calc_arg5 = 'ה'; // t_cf3fdd9b
const String gen_captimegematria_calc_arg6 = 'ו'; // t_8ccf3c9f
const String gen_captimegematria_calc_arg7 = 'ז'; // t_66cac148
const String gen_captimegematria_calc_arg8 = 'ח';
const String gen_captimegematria_calc_arg9 = 'ט';
const String gen_captimegematria_calc_arg10 = 'י';
const String gen_captimegematria_calc_arg11 = 'כ'; // t_926d8abe
const String gen_captimegematria_calc_arg12 = 'ל'; // t_d67cdc0f
const String gen_captimegematria_calc_arg13 = 'מ'; // t_f29f753f
const String gen_captimegematria_calc_arg14 = 'נ'; // t_c223f5f2
const String gen_captimegematria_calc_arg15 = 'ס';
const String gen_captimegematria_calc_arg16 = 'ע';
const String gen_captimegematria_calc_arg17 = 'פ'; // t_a604395c
const String gen_captimegematria_calc_arg18 = 'צ'; // t_13567a9b
const String gen_captimegematria_calc_arg19 = 'ק';
const String gen_captimegematria_calc_arg20 = 'ר';
const String gen_captimegematria_calc_arg21 = 'ש'; // t_f604bef9
const String gen_captimegematria_calc_arg22 = 'ת';
const String gen_captimegematria_calc_arg23 = 'תק';
const String gen_captimegematria_calc_arg24 = 'תר';
const String gen_captimegematria_calc_arg25 = 'תש';
const String gen_captimegematria_calc_arg26 = 'תת';
const String gen_captimegematria_calc_arg27 = 'תתק';
const String gen_captimegematria_calc_arg28 = 'טו';
const String gen_captimegematria_calc_arg29 = 'טז';
const String gen_captimegematria_calc_arg30 = '׳'; // t_92308040
const String gen_captimegematria_calc_arg31 = '״'; // t_391c42e6
const String gen_captimegematria_calc_arg32 = 'א'; // t_e194bcc5
const String gen_captimegematria_calc_arg33 = 'ב'; // t_23c1e0ba
const String gen_captimegematria_calc_arg34 = 'ג'; // t_e89d5099
const String gen_captimegematria_calc_arg35 = 'ד'; // t_8aea2ff5
const String gen_captimegematria_calc_arg36 = 'ה'; // t_cf3fdd9b
const String gen_captimegematria_calc_arg37 = 'ו'; // t_8ccf3c9f
const String gen_captimegematria_calc_arg38 = 'ז'; // t_66cac148
const String gen_captimegematria_calc_arg39 = 'ח';
const String gen_captimegematria_calc_arg40 = 'ט';
const String gen_captimegematria_calc_arg41 = 'י';
const String gen_captimegematria_calc_arg42 = 'כ'; // t_926d8abe
const String gen_captimegematria_calc_arg43 = 'ל'; // t_d67cdc0f
const String gen_captimegematria_calc_arg44 = 'מ'; // t_f29f753f
const String gen_captimegematria_calc_arg45 = 'נ'; // t_c223f5f2
const String gen_captimegematria_calc_arg46 = 'ס';
const String gen_captimegematria_calc_arg47 = 'ע';
const String gen_captimegematria_calc_arg48 = 'פ'; // t_a604395c
const String gen_captimegematria_calc_arg49 = 'צ'; // t_13567a9b
const String gen_captimegematria_calc_arg50 = 'ק';
const String gen_captimegematria_calc_arg51 = 'ר';
const String gen_captimegematria_calc_arg52 = 'ש'; // t_f604bef9
const String gen_captimegematria_calc_arg53 = 'ת';
const String gen_captimegematria_calc_arg54 = 'תק';
const String gen_captimegematria_calc_arg55 = 'תר';
const String gen_captimegematria_calc_arg56 = 'תש';
const String gen_captimegematria_calc_arg57 = 'תת';
const String gen_captimegematria_calc_arg58 = 'תתק';
const String gen_captimegematria_calc_arg59 = 'טו';
const String gen_captimegematria_calc_arg60 = 'טז';
const String gen_captimegematria_calc_arg61 = '׳'; // t_92308040
const String gen_captimegematria_calc_arg62 = '״'; // t_391c42e6
const String gen_captimegematria_card_glyph = '🧪';
const String gen_captimegematria_card_title = 'חתימת-אותיות עברית לשעה על השעון - כמה דקות עברו מחצות הלילה כתוב בגימטריה';
const String gen_captimegematria_card_sub = 'יכולת שהוזמנה ולא היתה קיימת - הרכבתי אותה לבד מ-2 אטומים והוכחתי על 2 דוגמאות';
const String gen_captimegematria_card_toast = 'חתימת-אותיות עברית לשעה על השעון - כמה דקות עברו מחצות הלילה כתוב בגימטריה';
const String gen_captimegematria_header_text = 'תחנת ההוכחה - הדוגמאות שהוזמנו מדליקות את השרשרת';
const String gen_captimegematria_stat_label = 'לדקות מחצות';
const String gen_captimegematria_stat_label2 = 'גימטריה מספר אותיות עבריות';
const String gen_captimegematria_chip_option = '07:45';
const String gen_captimegematria_chip_option2 = '13:05';
const String gen_captimegematria_header_text2 = 'תחנת הקלט החופשי - הקלידו כל ערך והשרשרת רצה חיה';
const String gen_captimegematria_stat_label3 = 'לדקות מחצות';
const String gen_captimegematria_stat_label4 = 'גימטריה מספר אותיות עבריות';
const String gen_captimegematria_textfield_label = 'הקלידו ערך עבור חתימת-אותיות עברית לשעה';
const String gen_captimegematria_textfield_hint = 'הקלידו ערך עבור חתימת-אותיות עברית לשעה';
const String gen_captimegematria_banner_sub = 'ההרכבה שמצאתי - timeToMin ⟵ gem - כל הדוגמאות עברו';
const String gen_captimegematria_app_bar_title = 'חתימת-אותיות עברית לשעה על השעון - כמה דקות עברו מחצות הלילה כתוב בגימטריה';
