// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_balagan_keys_c0 = 'הועתק ({n} תווים). הדבק בהודעה לעצמך או בקובץ.';
const String gen_balagan_keys_c1 = 'זה לא גיבוי של בלגן.';
const String gen_balagan_keys_c2 = 'שוחזר: {n} תיקים. הקודם נשמר — «בטל שחזור».';
const String gen_balagan_keys_c3 = 'חזרנו לנתונים שלפני השחזור.';
const String gen_balagan_keys_c4 = 'זה לא גיבוי של בלגן.';
const String gen_balagan_keys_c5 = 'חיבורים';
const String gen_balagan_keys_c6 = 'המפתחות שלך, במכשיר שלך';
const String gen_balagan_keys_c7 = '';
const String gen_balagan_keys_c8 = 'גיבוי';
const String gen_balagan_keys_c9 = 'העתק גיבוי';
const String gen_balagan_keys_c10 = 'הדבק גיבוי לשחזור';
const String gen_balagan_keys_c11 = 'שחזר';
const String gen_balagan_keys_c12 = 'בטל שחזור';
const String gen_balagan_keys_c13 = 'הנתונים במכשיר בלבד. גיבוי = טקסט שאתה שומר איפה שנוח. שחזור מחליף הכל, עם ביטול.';
const String gen_balagan_keys_c14 = 'מפתח-בינה (Anthropic)';
const String gen_balagan_keys_c15 = 'sk-ant-…';
const String gen_balagan_keys_c16 = 'מודל';
const String gen_balagan_keys_c17 = 'claude-sonnet-5';
const String gen_balagan_keys_c18 = 'המפתח נשמר רק במכשיר הזה ולעולם לא נשלח אלינו. בלי מפתח — אני מזהה מטקסט בלבד.';
const String gen_balagan_keys_c19 = 'טוקן-גישה Gmail (OAuth)';
const String gen_balagan_keys_c20 = 'ya29.…';
const String gen_balagan_keys_c21 = 'הטוקן נשמר רק במכשיר. עם טוקן — «היום» קורא את המיילים של השבוע האחרון, מזהה מה זה, ומציע לפתוח. בלי — כלום.';
const String gen_balagan_keys_c22 = 'וואטסאפ · יומן דו-כיווני — הגל הבא, באותו מסך.';
