// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_entry_card_glyph = '🧬';
const String gen_entry_card_title = 'המחולל של המחצב';
const String gen_entry_card_sub = 'דיוקן עצמי חי - את כל ההדגמות כאן בחרתי בעצמי';
const String gen_entry_card_toast = 'המחולל של המחצב';
const String gen_entry_header_text = 'המפעל במספרים - עדכון חי מהאטלס';
const String gen_entry_stat_value = '381';
const String gen_entry_stat_label = 'לבנים ויזואליות על המדף';
const String gen_entry_stat_value2 = '438';
const String gen_entry_stat_label2 = 'אטומי לוגיקה פעילים';
const String gen_entry_stat_value3 = '79';
const String gen_entry_stat_label3 = 'מסכים הורכבו מחדש';
const String gen_entry_header_text2 = 'גשר הלוגיקה - פונקציה שבחרתי מהמדף';
const String gen_entry_stat_label4 = 'שם חודש עברי';
const String gen_entry_header_text3 = 'יכולת מורכבת - שדה מזין חישוב חי';
const String gen_entry_stat_label5 = 'דין אדר';
const String gen_entry_textfield_label = 'הקלידו ערך עבור דין אדר';
const String gen_entry_textfield_hint = 'הקלידו ערך עבור דין אדר';
const String gen_entry_header_text4 = 'חיבור אטום לאטום - הבחירה מחליפה את המוצג';
const String gen_entry_switch_label = 'סגור'; // t_55247199
const String gen_entry_textfield_label2 = 'ביטול'; // t_a7c55a8d
const String gen_entry_textfield_hint2 = 'ביטול'; // t_a7c55a8d
const String gen_entry_stat_label6 = 'מחק'; // t_09b6bcca
const String gen_entry_radio_option = 'סגור'; // t_55247199
const String gen_entry_radio_option2 = 'ביטול'; // t_a7c55a8d
const String gen_entry_radio_option3 = 'מחק'; // t_09b6bcca
const String gen_entry_header_text5 = 'חיבור בין מסכים - המסכים שיצרתי מבקשות';
const String gen_entry_card_glyph2 = '🔹';
const String gen_entry_card_title2 = 'פרופיל עסק'; // t_4f815fcd
const String gen_entry_card_sub2 = 'נוצר מבקשה בעברית - הקישו לפתיחה';
const String gen_entry_card_glyph3 = '🔹';
const String gen_entry_card_title3 = 'יכולת מאולתרת - הגרלת היום';
const String gen_entry_card_sub3 = 'נוצר מבקשה בעברית - הקישו לפתיחה';
const String gen_entry_card_glyph4 = '🔹';
const String gen_entry_card_title4 = 'הגדרות משלוחים';
const String gen_entry_card_sub4 = 'נוצר מבקשה בעברית - הקישו לפתיחה';
const String gen_entry_card_glyph5 = '🔹';
const String gen_entry_card_title5 = 'ניהול צוות';
const String gen_entry_card_sub5 = 'נוצר מבקשה בעברית - הקישו לפתיחה';
const String gen_entry_chip_option = 'מתג';
const String gen_entry_chip_option2 = 'שדה';
const String gen_entry_chip_option3 = 'מספר'; // t_c19510f4
const String gen_entry_chip_option4 = 'כפתור';
const String gen_entry_chip_option5 = 'באנר';
const String gen_entry_chip_option6 = 'בחירה'; // t_9439d121
const String gen_entry_chip_option7 = 'תגיות';
const String gen_entry_chip_option8 = 'כרטיס'; // t_a0d9b485
const String gen_entry_chip_option9 = 'כותרת';
const String gen_entry_chip_option10 = 'שורה';
const String gen_entry_chip_option11 = 'נתון';
const String gen_entry_chip_option12 = 'חישוב';
const String gen_entry_banner_sub = 'את המסך הזה כתבתי והרכבתי לבד מהידע החי שלי - מאטומים קיימים בלבד';
const String gen_entry_button_label = 'צרו מסך חדש';
const String gen_entry_button_toast = 'צרו מסך חדש';
const String gen_entry_app_bar_title = 'המחולל';
