// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_scr30_other_ic = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_other_title = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_other_sub = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_other_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_other_label2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_other_toast = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_card_glyph = '🔹';
const String gen_app_scr30_card_title = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_card_preview = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_card_fav_add_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_card_fav_remove_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_card_toast = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_card_toast2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_ic = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_title = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_sub = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_toast = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_label2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_label22 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_ic2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_row_name = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr30_chip_label = 'פרויקטים'; // t_2335cb44
const String gen_app_scr30_chip_toast = 'פרויקטים'; // t_2335cb44
const String gen_app_scr30_chip_label2 = 'פרויקטים בסיכון';
const String gen_app_scr30_chip_toast2 = 'פרויקטים בסיכון';
const String gen_app_scr30_header_text = 'דשבורד הנהלה עם פרויקטים · לוגיקה חיה';
const String gen_app_scr30_stat_label = 'כרעת מנהל';
const String gen_app_scr30_banner_sub = 'המחולל מרכיב UI + לוגיקה מהמדף, ובחר לבד לפי משמעות';
const String gen_app_scr30_app_bar_title = '🎯 דשבורד הנהלה עם פרויקטים';
