// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent2_crumbs_option = 'חדש';
const String gen_app_ent2_crumbs_option2 = 'קשר';
const String gen_app_ent2_crumbs_option3 = 'סיור';
const String gen_app_ent2_crumbs_option4 = 'הצעה';
const String gen_app_ent2_crumbs_option5 = 'זכה';
const String gen_app_ent2_header_text = 'טופס ליד';
const String gen_app_ent2_textfield_label = 'שם'; // t_8b1aa6b1
const String gen_app_ent2_textfield_hint = 'שם'; // t_8b1aa6b1
const String gen_app_ent2_glowfield_hint = 'טלפון'; // t_737232c2
const String gen_app_ent2_textfield_label2 = 'מקור';
const String gen_app_ent2_textfield_hint2 = 'מקור';
const String gen_app_ent2_numstep_label = 'תקציב'; // t_3bb32ddd
const String gen_app_ent2_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent2_neon_label = 'קדם לקשר';
const String gen_app_ent2_neon_toast = 'קדם לקשר';
const String gen_app_ent2_header_text2 = 'רשומות ליד';
const String gen_app_ent2_banner_sub = 'ישות ליד';
const String gen_app_ent2_app_bar_title = 'הירו 🗂️ ליד | ישות מורכבת — טופס + טבלה';
