// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent8_crumbs_option = 'טיוטה'; // t_25fd43cd
const String gen_app_ent8_crumbs_option2 = 'נחתם';
const String gen_app_ent8_crumbs_option3 = 'פעיל'; // t_91181c78
const String gen_app_ent8_crumbs_option4 = 'הושלם';
const String gen_app_ent8_header_text = 'טופס חוזה';
const String gen_app_ent8_numstep_label = 'מספר'; // t_c19510f4
const String gen_app_ent8_textfield_label = 'סוג'; // t_f45000d5
const String gen_app_ent8_textfield_hint = '';
const String gen_app_ent8_textfield_label2 = 'פרויקט'; // t_5a15099c
const String gen_app_ent8_textfield_hint2 = '';
const String gen_app_ent8_numstep_label2 = 'סכום'; // t_2ef7fdce
const String gen_app_ent8_textfield_label3 = 'תאריך חתימה';
const String gen_app_ent8_textfield_hint3 = '';
const String gen_app_ent8_textfield_label4 = 'התחלה'; // t_dcafaf69
const String gen_app_ent8_textfield_hint4 = '';
const String gen_app_ent8_textfield_label5 = 'סיום'; // t_f600808f
const String gen_app_ent8_textfield_hint5 = '';
const String gen_app_ent8_textfield_label6 = 'עיכבון';
const String gen_app_ent8_textfield_hint6 = '';
const String gen_app_ent8_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent8_neon_label = 'קדם לנחתם';
const String gen_app_ent8_neon_toast = 'קדם לנחתם';
const String gen_app_ent8_header_text2 = 'רשומות חוזה';
const String gen_app_ent8_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent8_stat_label = 'מספר סידורי של';
const String gen_app_ent8_stat_label2 = 'עיטוף סכום שקלים לתצוגה';
const String gen_app_ent8_stat_label3 = 'תאריך לתצוגה';
const String gen_app_ent8_banner_sub = 'ישות חוזה';
const String gen_app_ent8_app_bar_title = '🗂️ חוזה';
