// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_balagan_keys_c0 = 'הועתק ({n} תווים). הדבק בהודעה לעצמך או בקובץ.';
const String gen_balagan_keys_c1 = 'זה לא גיבוי של בלגן.';
const String gen_balagan_keys_c2 = 'שוחזר: {n} תיקים. הקודם נשמר — «בטל שחזור».';
const String gen_balagan_keys_c3 = 'חזרנו לנתונים שלפני השחזור.';
const String gen_balagan_keys_c4 = 'זה לא גיבוי של בלגן.';
const String gen_balagan_keys_c5 = 'לא זיהיתי מודול לפי הכותרות. שמות-העמודות צריכים להתאים לשמות-השדות של תיק.';
const String gen_balagan_keys_c6 = 'יובאו {n} שורות ל«{module}».';
const String gen_balagan_keys_c7 = 'חיבורים';
const String gen_balagan_keys_c8 = 'המפתחות שלך, במכשיר שלך';
const String gen_balagan_keys_c9 = '';
const String gen_balagan_keys_c10 = 'גיבוי';
const String gen_balagan_keys_c11 = 'עוד לא גיבית — הכל רק במכשיר הזה.';
const String gen_balagan_keys_c12 = 'גיבוי אחרון: {d}';
const String gen_balagan_keys_c13 = 'העתק גיבוי';
const String gen_balagan_keys_c14 = 'הדבק גיבוי לשחזור';
const String gen_balagan_keys_c15 = 'שחזר';
const String gen_balagan_keys_c16 = 'בטל שחזור';
const String gen_balagan_keys_c17 = 'הנתונים במכשיר בלבד. גיבוי = טקסט שאתה שומר איפה שנוח. שחזור מחליף הכל, עם ביטול.';
const String gen_balagan_keys_c18 = 'ייבוא CSV';
const String gen_balagan_keys_c19 = 'הדבק CSV (שורה ראשונה = שמות-השדות)';
const String gen_balagan_keys_c20 = 'ייבא';
const String gen_balagan_keys_c21 = 'טיפ: «הוסף למסך הבית» בדפדפן — ואז «בלגן» מופיעה ב«שתף» של הטלפון: הודעה מוואטסאפ ⇒ שתף ⇒ בלגן ⇒ שמור.';
const String gen_balagan_keys_c22 = 'מפתח-בינה (Anthropic)';
const String gen_balagan_keys_c23 = 'sk-ant-…';
const String gen_balagan_keys_c24 = 'תקציב חודשי (₪)';
const String gen_balagan_keys_c25 = 'למשל 5000 — «החודש» יראה כמה מזה נוצל';
const String gen_balagan_keys_c26 = 'מודל';
const String gen_balagan_keys_c27 = 'claude-sonnet-5';
const String gen_balagan_keys_c28 = 'המפתח נשמר רק במכשיר הזה ולעולם לא נשלח אלינו. בלי מפתח — אני מזהה מטקסט בלבד.';
const String gen_balagan_keys_c29 = 'טוקן-גישה Gmail (OAuth)';
const String gen_balagan_keys_c30 = 'ya29.…';
const String gen_balagan_keys_c31 = 'הטוקן נשמר רק במכשיר. עם טוקן — «היום» קורא את המיילים של השבוע האחרון, מזהה מה זה, ומציע לפתוח. בלי — כלום.';
const String gen_balagan_keys_c32 = 'וואטסאפ · יומן דו-כיווני — הגל הבא, באותו מסך.';
