// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent3_crumbs_option = 'תכנון';
const String gen_app_ent3_crumbs_option2 = 'הצעה';
const String gen_app_ent3_crumbs_option3 = 'חוזה';
const String gen_app_ent3_crumbs_option4 = 'ביצוע';
const String gen_app_ent3_crumbs_option5 = 'מסירה';
const String gen_app_ent3_crumbs_option6 = 'נסגר';
const String gen_app_ent3_header_text = 'טופס פרויקט';
const String gen_app_ent3_numstep_label = 'מספר'; // t_c19510f4
const String gen_app_ent3_textfield_label = 'שם'; // t_8b1aa6b1
const String gen_app_ent3_textfield_hint = '';
const String gen_app_ent3_textfield_label2 = 'סוג'; // t_f45000d5
const String gen_app_ent3_textfield_hint2 = '';
const String gen_app_ent3_textfield_label3 = 'לקוח'; // t_9c2118be
const String gen_app_ent3_textfield_hint3 = '';
const String gen_app_ent3_textfield_label4 = 'כתובת'; // t_daab1ad0
const String gen_app_ent3_textfield_hint4 = '';
const String gen_app_ent3_numstep_label2 = 'שטח';
const String gen_app_ent3_textfield_label5 = 'מנהל פרויקט';
const String gen_app_ent3_textfield_hint5 = '';
const String gen_app_ent3_numstep_label3 = 'מחיר חוזה';
const String gen_app_ent3_numstep_label4 = 'תקציב'; // t_3bb32ddd
const String gen_app_ent3_textfield_label6 = 'תאריך התחלה';
const String gen_app_ent3_textfield_hint6 = '';
const String gen_app_ent3_textfield_label7 = 'תאריך סיום';
const String gen_app_ent3_textfield_hint7 = '';
const String gen_app_ent3_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent3_neon_label = 'קדם להצעה';
const String gen_app_ent3_neon_toast = 'קדם להצעה';
const String gen_app_ent3_header_text2 = 'רשומות פרויקט';
const String gen_app_ent3_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent3_stat_label = 'מספר סידורי של';
const String gen_app_ent3_stat_label2 = 'אין שקעים שם פרטי';
const String gen_app_ent3_stat_label3 = 'כרעת מנהל';
const String gen_app_ent3_stat_label4 = 'פרטי במקור וצא לחוזה';
const String gen_app_ent3_stat_label5 = 'תאריך לתצוגה';
const String gen_app_ent3_stat_label6 = 'קלט חופשי או אם';
const String gen_app_ent3_banner_sub = 'ישות פרויקט';
const String gen_app_ent3_app_bar_title = '🗂️ פרויקט';
