// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_hub_statusdot_label = 'מחובר · מסונכרן';
const String gen_app_hub_card_glyph = '🗂️';
const String gen_app_hub_card_title = 'ליד';
const String gen_app_hub_card_sub = '9 שדות · 7 שלבים';
const String gen_app_hub_card_glyph2 = '🗂️';
const String gen_app_hub_card_title2 = 'לקוח'; // t_9c2118be
const String gen_app_hub_card_sub2 = '8 שדות';
const String gen_app_hub_card_glyph3 = '🗂️';
const String gen_app_hub_card_title3 = 'פרויקט'; // t_5a15099c
const String gen_app_hub_card_sub3 = '12 שדות · 6 שלבים';
const String gen_app_hub_card_glyph4 = '🗂️';
const String gen_app_hub_card_title4 = 'שדה';
const String gen_app_hub_card_sub4 = '10 שדות';
const String gen_app_hub_card_glyph5 = '🗂️';
const String gen_app_hub_card_title5 = 'סעיף כתב כמויות';
const String gen_app_hub_card_sub5 = '8 שדות';
const String gen_app_hub_card_glyph6 = '🗂️';
const String gen_app_hub_card_title6 = 'אומדן';
const String gen_app_hub_card_sub6 = '9 שדות';
const String gen_app_hub_card_glyph7 = '🗂️';
const String gen_app_hub_card_title7 = 'הצעה';
const String gen_app_hub_card_sub7 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph8 = '🗂️';
const String gen_app_hub_card_title8 = 'חוזה';
const String gen_app_hub_card_sub8 = '9 שדות · 4 שלבים';
const String gen_app_hub_card_glyph9 = '🗂️';
const String gen_app_hub_card_title9 = 'תקציב'; // t_3bb32ddd
const String gen_app_hub_card_sub9 = '7 שדות';
const String gen_app_hub_card_glyph10 = '🗂️';
const String gen_app_hub_card_title10 = 'משימה'; // t_363ce3ab
const String gen_app_hub_card_sub10 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph11 = '🗂️';
const String gen_app_hub_card_title11 = 'דוח יומי';
const String gen_app_hub_card_sub11 = '7 שדות';
const String gen_app_hub_card_glyph12 = '🗂️';
const String gen_app_hub_card_title12 = 'עובד'; // t_2e131aef
const String gen_app_hub_card_sub12 = '6 שדות';
const String gen_app_hub_card_glyph13 = '🗂️';
const String gen_app_hub_card_title13 = 'קבלן משנה';
const String gen_app_hub_card_sub13 = '7 שדות · 4 שלבים';
const String gen_app_hub_card_glyph14 = '🗂️';
const String gen_app_hub_card_title14 = 'הזמנת רכש';
const String gen_app_hub_card_sub14 = '7 שדות · 4 שלבים';
const String gen_app_hub_card_glyph15 = '🗂️';
const String gen_app_hub_card_title15 = 'חומר'; // t_9a215501
const String gen_app_hub_card_sub15 = '7 שדות';
const String gen_app_hub_card_glyph16 = '🗂️';
const String gen_app_hub_card_title16 = 'ציוד';
const String gen_app_hub_card_sub16 = '7 שדות';
const String gen_app_hub_card_glyph17 = '🗂️';
const String gen_app_hub_card_title17 = 'מסמך'; // t_3c5e26fa
const String gen_app_hub_card_sub17 = '8 שדות · 3 שלבים';
const String gen_app_hub_card_glyph18 = '🗂️';
const String gen_app_hub_card_title18 = 'שדה';
const String gen_app_hub_card_sub18 = '8 שדות · 6 שלבים';
const String gen_app_hub_card_glyph19 = '🗂️';
const String gen_app_hub_card_title19 = 'שדה';
const String gen_app_hub_card_sub19 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph20 = '🗂️';
const String gen_app_hub_card_title20 = 'שינוי עבודה';
const String gen_app_hub_card_sub20 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph21 = '🗂️';
const String gen_app_hub_card_title21 = 'בדיקת איכות'; // t_dffeb48a
const String gen_app_hub_card_sub21 = '7 שדות';
const String gen_app_hub_card_glyph22 = '🗂️';
const String gen_app_hub_card_title22 = 'ליקוי';
const String gen_app_hub_card_sub22 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph23 = '🗂️';
const String gen_app_hub_card_title23 = 'אירוע בטיחות';
const String gen_app_hub_card_sub23 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph24 = '🗂️';
const String gen_app_hub_card_title24 = 'נוכחות'; // t_79fe5b92
const String gen_app_hub_card_sub24 = '7 שדות';
const String gen_app_hub_card_glyph25 = '🗂️';
const String gen_app_hub_card_title25 = 'קריאת תחזוקה';
const String gen_app_hub_card_sub25 = '6 שדות · 5 שלבים';
const String gen_app_hub_card_glyph26 = '🗂️';
const String gen_app_hub_card_title26 = 'מסירה';
const String gen_app_hub_card_sub26 = '5 שדות · 5 שלבים';
const String gen_app_hub_card_glyph27 = '🗂️';
const String gen_app_hub_card_title27 = 'אחריות';
const String gen_app_hub_card_sub27 = '6 שדות · 4 שלבים';
const String gen_app_hub_card_glyph28 = '🗂️';
const String gen_app_hub_card_title28 = 'חשבונית'; // t_261202e5
const String gen_app_hub_card_sub28 = '7 שדות · 4 שלבים';
const String gen_app_hub_card_glyph29 = '🗂️';
const String gen_app_hub_card_title29 = 'חשבון חלקי';
const String gen_app_hub_card_sub29 = '7 שדות · 5 שלבים';
const String gen_app_hub_card_glyph30 = '📊';
const String gen_app_hub_card_title30 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_hub_card_sub30 = '10 רכיבים';
const String gen_app_hub_card_glyph31 = '📊';
const String gen_app_hub_card_title31 = 'דשבורד מנהל פרויקט עם התקדמות';
const String gen_app_hub_card_sub31 = '3 רכיבים';
const String gen_app_hub_card_glyph32 = '📊';
const String gen_app_hub_card_title32 = 'דשבורד מנהל אתר עם משימות היום';
const String gen_app_hub_card_sub32 = '11 רכיבים';
const String gen_app_hub_card_glyph33 = '📊';
const String gen_app_hub_card_title33 = 'דשבורד כספים עם הכנסות';
const String gen_app_hub_card_sub33 = '8 רכיבים';
const String gen_app_hub_card_glyph34 = '📊';
const String gen_app_hub_card_title34 = 'דשבורד בטיחות עם בדיקות פתוחות';
const String gen_app_hub_card_sub34 = '9 רכיבים';
const String gen_app_hub_card_glyph35 = '🧾';
const String gen_app_hub_card_title35 = 'יומן פעולות';
const String gen_app_hub_card_sub35 = 'שכבת-מערכת';
const String gen_app_hub_card_glyph36 = '🎚️';
const String gen_app_hub_card_title36 = 'דגלי-יכולת';
const String gen_app_hub_card_sub36 = 'שכבת-מערכת';
const String gen_app_hub_card_glyph37 = '⚙️';
const String gen_app_hub_card_title37 = 'הגדרות'; // t_47cfdefb
const String gen_app_hub_card_sub37 = 'שכבת-מערכת';
const String gen_app_hub_banner_sub = 'מסכים · אפליקציה שלמה';
const String gen_app_hub_app_bar_title = '🏗️ האפליקציה שלי';
