// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent25_c0 = 'קריאת תחזוקה';
const String gen_app_ent25_c1 = '6 שדות · 5 שלבים';
const String gen_app_ent25_c2 = '🗂️';
const String gen_app_ent25_c3 = 'שמירה';
const String gen_app_ent25_c4 = 'פרטי הרשומה';
const String gen_app_ent25_c5 = 'רשומות';
const String gen_app_ent25_c6 = 'אין קריאת תחזוקה עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent25_c7 = 'דווח';
const String gen_app_ent25_c8 = 'סווג';
const String gen_app_ent25_c9 = 'בטיפול';
const String gen_app_ent25_c10 = 'תוקן';
const String gen_app_ent25_c11 = 'נסגר';
const String gen_app_ent25_c12 = 'ציוד';
const String gen_app_ent25_c13 = 'מיקום';
const String gen_app_ent25_c14 = 'תיאור';
const String gen_app_ent25_c15 = 'דחיפות';
const String gen_app_ent25_c16 = 'אחראי';
const String gen_app_ent25_c17 = 'סטטוס';
