// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent4_header_text = 'טופס שדה';
const String gen_app_ent4_textfield_label = 'קוד'; // t_2e916690
const String gen_app_ent4_textfield_hint = 'קוד'; // t_2e916690
const String gen_app_ent4_glowfield_hint = 'שם'; // t_8b1aa6b1
const String gen_app_ent4_textfield_label2 = 'שלב'; // t_42662332
const String gen_app_ent4_textfield_hint2 = 'שלב'; // t_42662332
const String gen_app_ent4_textfield_label3 = 'אחראי';
const String gen_app_ent4_textfield_hint3 = 'אחראי';
const String gen_app_ent4_numstep_label = 'אחוז ביצוע';
const String gen_app_ent4_numstep_label2 = 'עלות בפועל';
const String gen_app_ent4_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent4_header_text2 = 'חוקים פר-שדה';
const String gen_app_ent4_stat_label = 'אין שקעים שם פרטי';
const String gen_app_ent4_stat_label2 = 'תאריך לתצוגה';
const String gen_app_ent4_stat_label3 = 'קלט חופשי או אם';
const String gen_app_ent4_header_text3 = 'רשומות שדה';
const String gen_app_ent4_banner_sub = 'ישות שדה';
const String gen_app_ent4_app_bar_title = 'הירו 🗂️ שדה | ישות מורכבת — טופס + טבלה';
