// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_hub_card_glyph = '🗂️';
const String gen_app_hub_card_title = 'פרויקט'; // t_5a15099c
const String gen_app_hub_card_sub = 'פרויקט'; // t_5a15099c
const String gen_app_hub_card_glyph2 = '🗂️';
const String gen_app_hub_card_title2 = 'לקוח'; // t_9c2118be
const String gen_app_hub_card_sub2 = 'לקוח'; // t_9c2118be
const String gen_app_hub_card_glyph3 = '🗂️';
const String gen_app_hub_card_title3 = 'משימה'; // t_363ce3ab
const String gen_app_hub_card_sub3 = 'משימה'; // t_363ce3ab
const String gen_app_hub_card_glyph4 = '📊';
const String gen_app_hub_card_title4 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_hub_card_sub4 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_hub_card_glyph5 = '📊';
const String gen_app_hub_card_title5 = 'לוח זמנים גאנט עם משימות';
const String gen_app_hub_card_sub5 = 'לוח זמנים גאנט עם משימות';
const String gen_app_hub_card_glyph6 = '📊';
const String gen_app_hub_card_title6 = 'דוח יומי עם מזג אוויר';
const String gen_app_hub_card_sub6 = 'דוח יומי עם מזג אוויר';
const String gen_app_hub_banner_sub = 'מסכים · המחולל הרכיב אפליקציה שלמה מהמדף';
const String gen_app_hub_app_bar_title = 'הירו 🏗️ האפליקציה שלי | נבנתה מאפיון-חופשי';
