// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_scr30_other_ic = 'ליד';
const String gen_app_scr30_other_title = '9 שדות · 7 שלבים';
const String gen_app_scr30_other_sub = '9 שדות · 7 שלבים';
const String gen_app_scr30_row_label = 'לקוח'; // t_9c2118be
const String gen_app_scr30_other_label = 'שדה';
const String gen_app_scr30_other_label2 = 'סעיף כתב כמויות';
const String gen_app_scr30_other_toast = 'סעיף כתב כמויות';
const String gen_app_scr30_card_glyph = '🔹';
const String gen_app_scr30_card_title = 'אומדן';
const String gen_app_scr30_card_preview = '9 שדות';
const String gen_app_scr30_card_fav_add_label = '9 שדות';
const String gen_app_scr30_card_fav_remove_label = '9 שדות';
const String gen_app_scr30_card_toast = 'אומדן';
const String gen_app_scr30_card_toast2 = 'אומדן';
const String gen_app_scr30_row_ic = 'הצעה';
const String gen_app_scr30_row_title = '7 שדות · 5 שלבים';
const String gen_app_scr30_row_sub = '7 שדות · 5 שלבים';
const String gen_app_scr30_row_toast = 'הצעה';
const String gen_app_scr30_row_label2 = 'חוזה';
const String gen_app_scr30_row_label22 = '9 שדות · 4 שלבים';
const String gen_app_scr30_row_ic2 = '9 שדות · 4 שלבים';
const String gen_app_scr30_row_name = '9 שדות · 4 שלבים';
const String gen_app_scr30_chip_label = 'פרויקטים'; // t_2335cb44
const String gen_app_scr30_chip_toast = 'פרויקטים'; // t_2335cb44
const String gen_app_scr30_chip_label2 = 'פרויקטים בסיכון';
const String gen_app_scr30_chip_toast2 = 'פרויקטים בסיכון';
const String gen_app_scr30_header_text = 'דשבורד הנהלה עם פרויקטים · לוגיקה חיה';
const String gen_app_scr30_stat_label = 'כרעת מנהל';
const String gen_app_scr30_banner_sub = 'המחולל מרכיב UI + לוגיקה מהמדף, ובחר לבד לפי משמעות';
const String gen_app_scr30_app_bar_title = '🎯 דשבורד הנהלה עם פרויקטים';
