// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent16_c0 = 'ציוד';
const String gen_app_ent16_c1 = '7 שדות';
const String gen_app_ent16_c2 = '🗂️';
const String gen_app_ent16_c3 = 'שמירה';
const String gen_app_ent16_c4 = 'פרטי הרשומה';
const String gen_app_ent16_c5 = 'רשומות';
const String gen_app_ent16_c6 = 'אין ציוד עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent16_c7 = 'ציוד';
const String gen_app_ent16_c8 = 'שם';
const String gen_app_ent16_c9 = 'monthHeOf';
const String gen_app_ent16_c10 = 'סוג';
const String gen_app_ent16_c11 = 'מספר סידורי';
const String gen_app_ent16_c12 = 'gem';
const String gen_app_ent16_c13 = 'מיקום';
const String gen_app_ent16_c14 = 'תוקף בדיקה';
const String gen_app_ent16_c15 = 'שעות שימוש';
const String gen_app_ent16_c16 = 'סטטוס';
const String gen_app_ent16_c17 = 'advanceStatus';
