// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent29_crumbs_option = 'הוכן';
const String gen_app_ent29_crumbs_option2 = 'אושר מנהל';
const String gen_app_ent29_crumbs_option3 = 'אושר מפקח';
const String gen_app_ent29_crumbs_option4 = 'אושר לקוח';
const String gen_app_ent29_crumbs_option5 = 'שולם';
const String gen_app_ent29_header_text = 'טופס חשבון חלקי';
const String gen_app_ent29_textfield_label = 'פרויקט'; // t_5a15099c
const String gen_app_ent29_textfield_hint = '';
const String gen_app_ent29_textfield_label2 = 'תקופה';
const String gen_app_ent29_textfield_hint2 = '';
const String gen_app_ent29_numstep_label = 'אחוז ביצוע';
const String gen_app_ent29_textfield_label3 = 'ערך נוכחי';
const String gen_app_ent29_textfield_hint3 = '';
const String gen_app_ent29_textfield_label4 = 'עיכבון';
const String gen_app_ent29_textfield_hint4 = '';
const String gen_app_ent29_numstep_label2 = 'יתרה'; // t_f7d0bbbe
const String gen_app_ent29_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent29_neon_label = 'קדם לאושר מנהל';
const String gen_app_ent29_neon_toast = 'קדם לאושר מנהל';
const String gen_app_ent29_header_text2 = 'רשומות חשבון חלקי';
const String gen_app_ent29_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent29_stat_label = 'אין שקעים שם פרטי';
const String gen_app_ent29_banner_sub = 'ישות חשבון חלקי';
const String gen_app_ent29_app_bar_title = '🗂️ חשבון חלקי';
