// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent23_crumbs_option = 'דווח';
const String gen_app_ent23_crumbs_option2 = 'נחסם';
const String gen_app_ent23_crumbs_option3 = 'בתחקיר';
const String gen_app_ent23_crumbs_option4 = 'טופל';
const String gen_app_ent23_crumbs_option5 = 'נסגר';
const String gen_app_ent23_header_text = 'טופס אירוע בטיחות';
const String gen_app_ent23_textfield_label = 'תאריך'; // t_c87f355d
const String gen_app_ent23_textfield_hint = '';
const String gen_app_ent23_textfield_label2 = 'מיקום'; // t_26d0e7de
const String gen_app_ent23_textfield_hint2 = '';
const String gen_app_ent23_textfield_label3 = 'חומרה'; // t_6d1d6810
const String gen_app_ent23_textfield_hint3 = '';
const String gen_app_ent23_textfield_label4 = 'מעורבים';
const String gen_app_ent23_textfield_hint4 = '';
const String gen_app_ent23_textfield_label5 = 'תיאור'; // t_927492f8
const String gen_app_ent23_textfield_hint5 = '';
const String gen_app_ent23_textfield_label6 = 'גורם שורש';
const String gen_app_ent23_textfield_hint6 = '';
const String gen_app_ent23_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent23_neon_label = 'קדם לנחסם';
const String gen_app_ent23_neon_toast = 'קדם לנחסם';
const String gen_app_ent23_header_text2 = 'רשומות אירוע בטיחות';
const String gen_app_ent23_banner_sub = 'ישות אירוע בטיחות';
const String gen_app_ent23_app_bar_title = '🗂️ אירוע בטיחות';
