// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent6_header_text = 'טופס אומדן';
const String gen_app_ent6_textfield_label = 'פרויקט'; // t_5a15099c
const String gen_app_ent6_textfield_hint = '';
const String gen_app_ent6_textfield_label2 = 'לקוח'; // t_9c2118be
const String gen_app_ent6_textfield_hint2 = '';
const String gen_app_ent6_textfield_label3 = 'גרסה';
const String gen_app_ent6_textfield_hint3 = '';
const String gen_app_ent6_textfield_label4 = 'תאריך'; // t_c87f355d
const String gen_app_ent6_textfield_hint4 = '';
const String gen_app_ent6_numstep_label = 'עלות צפויה';
const String gen_app_ent6_numstep_label2 = 'מחיר'; // t_cc097285
const String gen_app_ent6_numstep_label3 = 'רווח יעד';
const String gen_app_ent6_textfield_label5 = 'תוקף';
const String gen_app_ent6_textfield_hint5 = '';
const String gen_app_ent6_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent6_header_text2 = 'רשומות אומדן';
const String gen_app_ent6_header_text3 = 'מנוע-חוקים חי · חוקים מהמדף';
const String gen_app_ent6_stat_label = 'תאריך לתצוגה';
const String gen_app_ent6_banner_sub = 'ישות אומדן';
const String gen_app_ent6_app_bar_title = '🗂️ אומדן';
