// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent27_crumbs_option = 'דווח';
const String gen_app_ent27_crumbs_option2 = 'אושר'; // t_db4a9245
const String gen_app_ent27_crumbs_option3 = 'בטיפול';
const String gen_app_ent27_crumbs_option4 = 'נסגר';
const String gen_app_ent27_header_text = 'טופס אחריות';
const String gen_app_ent27_textfield_label = 'פרויקט'; // t_5a15099c
const String gen_app_ent27_textfield_hint = '';
const String gen_app_ent27_textfield_label2 = 'אזור';
const String gen_app_ent27_textfield_hint2 = '';
const String gen_app_ent27_textfield_label3 = 'תיאור'; // t_927492f8
const String gen_app_ent27_textfield_hint3 = '';
const String gen_app_ent27_textfield_label4 = 'תוקף אחריות';
const String gen_app_ent27_textfield_hint4 = '';
const String gen_app_ent27_textfield_label5 = 'קבלן אחראי';
const String gen_app_ent27_textfield_hint5 = '';
const String gen_app_ent27_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent27_neon_label = 'קדם לאושר';
const String gen_app_ent27_neon_toast = 'קדם לאושר';
const String gen_app_ent27_header_text2 = 'רשומות אחריות';
const String gen_app_ent27_banner_sub = 'ישות אחריות';
const String gen_app_ent27_app_bar_title = '🗂️ אחריות';
