// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_scr32_other_label = 'לקוח'; // t_9c2118be
const String gen_app_scr32_other_toast = 'לקוח'; // t_9c2118be
const String gen_app_scr32_card_glyph = '🔹';
const String gen_app_scr32_card_message = 'שדה';
const String gen_app_scr32_stat_label = 'סעיף כתב כמויות';
const String gen_app_scr32_other_label2 = 'אומדן';
const String gen_app_scr32_other_label22 = '9 שדות';
const String gen_app_scr32_other_label3 = '9 שדות';
const String gen_app_scr32_other_label4 = '9 שדות';
const String gen_app_scr32_card_label = 'הצעה';
const String gen_app_scr32_card_label2 = '7 שדות · 5 שלבים';
const String gen_app_scr32_card_label3 = '7 שדות · 5 שלבים';
const String gen_app_scr32_card_label4 = '7 שדות · 5 שלבים';
const String gen_app_scr32_card_label5 = '7 שדות · 5 שלבים';
const String gen_app_scr32_header_title = 'חוזה';
const String gen_app_scr32_card_glyph2 = '🔹';
const String gen_app_scr32_card_title = 'עובדים באתר';
const String gen_app_scr32_card_sub = 'עובדים באתר';
const String gen_app_scr32_card_toast = 'עובדים באתר';
const String gen_app_scr32_other_text = 'חומרים';
const String gen_app_scr32_header_text = 'דשבורד מנהל אתר עם משימות היום · לוגיקה חיה';
const String gen_app_scr32_stat_label2 = 'כרעת מנהל';
const String gen_app_scr32_banner_sub = 'המחולל מרכיב UI + לוגיקה מהמדף, ובחר לבד לפי משמעות';
const String gen_app_scr32_app_bar_title = '🎯 דשבורד מנהל אתר עם משימות היום';
