// 📦 תוכן-DS (render-ds) — verbatim מהבקשה. אל תערוך ידנית.
const String gen_app_ent6_c0 = 'אומדן';
const String gen_app_ent6_c1 = '9 שדות';
const String gen_app_ent6_c2 = '🗂️';
const String gen_app_ent6_c3 = 'שמירה';
const String gen_app_ent6_c4 = 'פרטי הרשומה';
const String gen_app_ent6_c5 = 'רשומות';
const String gen_app_ent6_c6 = 'אין אומדן עדיין — הרשומה הראשונה תופיע כאן';
const String gen_app_ent6_c7 = 'אומדן';
const String gen_app_ent6_c8 = 'פרויקט';
const String gen_app_ent6_c9 = 'לקוח';
const String gen_app_ent6_c10 = 'גרסה';
const String gen_app_ent6_c11 = 'תאריך';
const String gen_app_ent6_c12 = 'fmtDate';
const String gen_app_ent6_c13 = 'עלות צפויה';
const String gen_app_ent6_c14 = 'מחיר';
const String gen_app_ent6_c15 = 'רווח יעד';
const String gen_app_ent6_c16 = 'תוקף';
const String gen_app_ent6_c17 = 'סטטוס';
