// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_ent13_crumbs_option = 'מועמד';
const String gen_app_ent13_crumbs_option2 = 'נבדק';
const String gen_app_ent13_crumbs_option3 = 'אושר'; // t_db4a9245
const String gen_app_ent13_crumbs_option4 = 'פעיל'; // t_91181c78
const String gen_app_ent13_header_text = 'טופס קבלן משנה';
const String gen_app_ent13_textfield_label = 'שם'; // t_8b1aa6b1
const String gen_app_ent13_textfield_hint = '';
const String gen_app_ent13_textfield_label2 = 'חברה';
const String gen_app_ent13_textfield_hint2 = '';
const String gen_app_ent13_textfield_label3 = 'תחום';
const String gen_app_ent13_textfield_hint3 = '';
const String gen_app_ent13_textfield_label4 = 'רישיון';
const String gen_app_ent13_textfield_hint4 = '';
const String gen_app_ent13_textfield_label5 = 'תוקף ביטוח';
const String gen_app_ent13_textfield_hint5 = '';
const String gen_app_ent13_textfield_label6 = 'דירוג';
const String gen_app_ent13_textfield_hint6 = '';
const String gen_app_ent13_toggle_label = 'סטטוס'; // t_c184d0ed
const String gen_app_ent13_neon_label = 'קדם לנבדק';
const String gen_app_ent13_neon_toast = 'קדם לנבדק';
const String gen_app_ent13_header_text2 = 'רשומות קבלן משנה';
const String gen_app_ent13_banner_sub = 'ישות קבלן משנה';
const String gen_app_ent13_app_bar_title = '🗂️ קבלן משנה';
