// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_app_scr4_other_ic = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_other_title = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_other_sub = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_other_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_other_label2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_other_toast = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_card_glyph = '🔹';
const String gen_app_scr4_card_title = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_card_preview = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_card_fav_add_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_card_fav_remove_label = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_card_toast = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_card_toast2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_ic = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_title = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_sub = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_toast = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_label2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_label22 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_ic2 = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_row_name = 'דשבורד הנהלה עם פרויקטים';
const String gen_app_scr4_chip_label = 'פרויקטים'; // t_2335cb44
const String gen_app_scr4_chip_toast = 'פרויקטים'; // t_2335cb44
const String gen_app_scr4_header_text = 'דשבורד הנהלה עם פרויקטים · לוגיקה חיה';
const String gen_app_scr4_stat_label = 'כרעת מנהל';
const String gen_app_scr4_banner_sub = 'המחולל מרכיב UI + לוגיקה מהמדף, ובחר לבד לפי משמעות';
const String gen_app_scr4_app_bar_title = 'הירו 🎯 דשבורד הנהלה עם פרויקטים | נבנה מתיאור חופשי';
