// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_entry_card_glyph = '🧬';
const String gen_entry_card_title = 'המחולל של המחצב';
const String gen_entry_card_sub = 'עכשיו עם חיבורים חיים בין אטומים';
const String gen_entry_card_toast = 'המחולל של המחצב';
const String gen_entry_header_text = 'גשר הלוגיקה פועם';
const String gen_entry_stat_label = 'החודש העברי כרגע לפי מנוע מאור';
const String gen_entry_stat_label2 = 'קוד הזמנה דטרמיניסטי "genesis"';
const String gen_entry_header_text2 = 'הבחירה כאן מחליפה את האטום שמתחתיה';
const String gen_entry_switch_label = 'התראות למסך ההגדרות';
const String gen_entry_textfield_label = 'שם מסך הניהול';
const String gen_entry_textfield_hint = 'שם מסך הניהול';
const String gen_entry_stat_value = '3';
const String gen_entry_stat_label3 = 'דוחות מוכנים להפקה';
const String gen_entry_radio_option = 'הגדרות'; // t_47cfdefb
const String gen_entry_radio_option2 = 'ניהול'; // t_3110a14f
const String gen_entry_radio_option3 = 'דוחות'; // t_b8111d4e
const String gen_entry_banner_sub = 'הבורר למעלה מחובר לאטומים שמתחתיו — בחירה מחליפה אטום';
const String gen_entry_button_label = 'צרו מסך חדש';
const String gen_entry_button_toast = 'צרו מסך חדש';
const String gen_entry_app_bar_title = 'המחולל';
