// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_improv_card_glyph = '🎲';
const String gen_improv_card_title = 'יכולת מאולתרת - חמישה אטומים שהגרלתי וחיברתי לבד';
const String gen_improv_card_sub = 'תבחר 5 אטומים רנדלמיים תחבר בין ותוציא את היכולת הכי טוב וחדשה שלה';
const String gen_improv_card_toast = 'יכולת מאולתרת - חמישה אטומים שהגרלתי וחיברתי לבד';
const String gen_improv_row_ic = 'צבע'; // t_be49d01c
const String gen_improv_row_title = 'צבע'; // t_be49d01c
const String gen_improv_row_sub = 'צבע'; // t_be49d01c
const String gen_improv_row_toast = 'צבע'; // t_be49d01c
const String gen_improv_switch_fallback = 'המתג הזה מדליק את האטום שמתחתיו';
const String gen_improv_switch_label = 'המתג הזה מדליק את האטום שמתחתיו';
const String gen_improv_other_label = 'פקק'; // t_d4522b6f
const String gen_improv_card_stage_label = 'ברך °';
const String gen_improv_card_items_label = 'ברך °';
const String gen_improv_card_sum_label = 'ברך °';
const String gen_improv_card_toast2 = 'ברך °';
const String gen_improv_button_badge = 'סוג'; // t_f45000d5
const String gen_improv_button_title = 'סוג'; // t_f45000d5
const String gen_improv_button_sub = 'סוג'; // t_f45000d5
const String gen_improv_button_toast = 'סוג'; // t_f45000d5
const String gen_improv_banner_sub = 'את ההגרלה החיבורים והמסך הזה עשיתי לבד - מחר תצא הגרלה חדשה';
const String gen_improv_app_bar_title = 'יכולת מאולתרת - הגרלת היום';
