// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_quest2_card_glyph = '🎯';
const String gen_quest2_card_title = 'עולם משחק שלם של מסע בריחה - חדרים שמובילים זה אל זה חידות חיות שמגיבות לשחקן ושערים נסתרים בדרך אל היציאה';
const String gen_quest2_card_sub = 'מטרה אחת קיבלתי - את המבנה האטומים והחיבורים בחרתי לבד';
const String gen_quest2_card_toast = 'עולם משחק שלם של מסע בריחה - חדרים שמובילים זה אל זה חידות חיות שמגיבות לשחקן ושערים נסתרים בדרך אל היציאה';
const String gen_quest2_header_text = 'בורר המנועים - הבחירה מחליפה את המנוע החי המוצג';
const String gen_quest2_stat_label = 'כותב כי וא מבוסס';
const String gen_quest2_stat_label2 = 'קופסה חיווט לוח עברי מלבנים עיוורות דאטה כרעת טוהר';
const String gen_quest2_stat_label3 = 'שם חודש עברי';
const String gen_quest2_radio_option = 'כותב כי';
const String gen_quest2_radio_option2 = 'קופסה חיווט';
const String gen_quest2_radio_option3 = 'שם חודש';
const String gen_quest2_stat_label4 = 'פרש ימים קלנדרי בין שני תאריכים חסין בונה חצות משני';
const String gen_quest2_switch_label = 'מתג השער - פתיחתו חושפת מנוע חבוי';
const String gen_quest2_card_glyph2 = '🔹';
const String gen_quest2_card_title2 = 'השער אל החדר הבא';
const String gen_quest2_card_sub2 = 'המסע ממשיך';
const String gen_quest2_banner_sub = 'מטרה אחת קיבלתי מהבעלים - את כל השאר תכננתי בחרתי וחיווטתי לבד מהמדף החי';
const String gen_quest2_app_bar_title = 'עולם משחק שלם - חדר 2';
