// 📦 דאטה · תוכן-המחולל (genesis-gen) — התוויות מן-הבקשה, verbatim. אל תערוך ידנית.
const String gen_entry_card_glyph = '🧬';
const String gen_entry_card_title = 'המחולל של המחצב';
const String gen_entry_card_sub = 'כותבים משפט בעברית - מקבלים מסך חי';
const String gen_entry_card_toast = 'המחולל של המחצב';
const String gen_entry_header_text = 'המפעל במספרים - עדכון חי מהאטלס';
const String gen_entry_stat_value = '381';
const String gen_entry_stat_label = 'לבנים ויזואליות על המדף';
const String gen_entry_stat_value2 = '438';
const String gen_entry_stat_label2 = 'אטומי לוגיקה פעילים';
const String gen_entry_stat_value3 = '79';
const String gen_entry_stat_label3 = 'מסכים הורכבו מחדש';
const String gen_entry_header_text2 = 'גשר הלוגיקה פועם';
const String gen_entry_stat_label4 = 'החודש העברי כרגע לפי מנוע מאור';
const String gen_entry_stat_label5 = 'קוד הזמנה דטרמיניסטי "genesis"';
const String gen_entry_header_text3 = 'הבחירה כאן מחליפה את האטום שמתחתיה';
const String gen_entry_switch_label = 'התראות למסך ההגדרות';
const String gen_entry_textfield_label = 'שם מסך הניהול';
const String gen_entry_textfield_hint = 'שם מסך הניהול';
const String gen_entry_stat_value4 = '3';
const String gen_entry_stat_label6 = 'דוחות מוכנים להפקה';
const String gen_entry_radio_option = 'הגדרות'; // t_47cfdefb
const String gen_entry_radio_option2 = 'ניהול'; // t_3110a14f
const String gen_entry_radio_option3 = 'דוחות'; // t_b8111d4e
const String gen_entry_chip_option = 'מתג';
const String gen_entry_chip_option2 = 'שדה';
const String gen_entry_chip_option3 = 'מספר'; // t_c19510f4
const String gen_entry_chip_option4 = 'כפתור';
const String gen_entry_chip_option5 = 'באנר';
const String gen_entry_chip_option6 = 'בחירה'; // t_9439d121
const String gen_entry_chip_option7 = 'תגיות';
const String gen_entry_chip_option8 = 'כרטיס'; // t_a0d9b485
const String gen_entry_chip_option9 = 'כותרת';
const String gen_entry_chip_option10 = 'שורה';
const String gen_entry_chip_option11 = 'נתון';
const String gen_entry_chip_option12 = 'חישוב';
const String gen_entry_banner_sub = 'נכתב והורכב בידי המחולל מהידע החי שלו — מאטומים קיימים בלבד';
const String gen_entry_button_label = 'צרו מסך חדש';
const String gen_entry_button_toast = 'צרו מסך חדש';
const String gen_entry_app_bar_title = 'המחולל';
