#!/bin/bash
# gen_version.sh — מייצר את app_flutter/lib/version.g.dart מ-git + STATUS.md.
# נקודת-הייצור היחידה. נקרא ע"י: .githooks/pre-commit · CI workflows · session-start.sh.
#
# version.g.dart הוא gitignored (לא tracked) — נוצר-מחדש בכל commit/build.
# מימוש P0 של PROPOSAL_version_friction.md (לקח #72). מאחד הכרעות 6 סוכנים:
#   - count.shortSHA (מקבץ) — ייחודי, לא דורש מונוטוניות בין branches
#   - empty-LABEL guard (מקבץ) — STATUS חסר → exit 1, לא drift שקט
#   - shallow-clone guard (מקבץ) — CI fetch-depth:1 → count לא-אמין, SHA מציל
#   - template-עם-גרשיים מפורש (מקבץ) — const String חוקי, לא שגיאת-קומפילציה
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT/app_flutter"

LABEL=$(grep -oE 'v[0-9]+\.[0-9]+' knowledge/STATUS.md 2>/dev/null | head -1)
if [[ -z "$LABEL" ]]; then
    echo "gen_version: ❌ STATUS.md חסר תווית vX.YY" >&2
    exit 1
fi

# shallow clone (CI fetch-depth:1) → count מחזיר 1 שקט; SHA מציל ייחודיות (מקבץ סבב-2)
if git rev-parse --is-shallow-repository 2>/dev/null | grep -q true; then
    COUNT="0"
else
    COUNT=$(git rev-list --count HEAD 2>/dev/null || echo "0")
fi
SHA=$(git rev-parse --short HEAD 2>/dev/null || echo "0000000")

cat > lib/version.g.dart <<EOF
// GENERATED by scripts/gen_version.sh — DO NOT EDIT, DO NOT COMMIT.
// gitignored + נוצר-מחדש מ-git בכל commit/build. ראה knowledge/PROPOSAL_version_friction.md.
// kBuild לא-דטרמיניסטי בין מכונות → אסור לקשור ל-asset-URL/cache-key (קטלגן).
const String kVersionLabel = '$LABEL';
const String kBuild = '$COUNT.$SHA';
const String kReleaseNote = '';
EOF
