// 🔨 אטום-Dart מחושל (forge) · משפחת-Pure "header" · מחולל ע"י machtzev/ds-forge.mjs ממקור-האמת
// machtzev/pure/header-family.html (אל תערוך ידנית — regen). לובש עיצוב מהחריץ בלבד (DsSeam.skinOf/of/fontsOf,
// חוק-5/6): אפס צבע-קבוע. תוכן Label/Value/Meta.
import 'package:flutter/material.dart';
import '../../dart-ui-bs/ds/ds_seam.dart';

/// WizardHeader — seam:progress
class ForgeWizardHeader extends StatelessWidget {
  const ForgeWizardHeader({super.key});
  @override
  Widget build(BuildContext context) {
    final skin = DsSeam.skinOf(context);   // מלוא-העיצוב מהחריץ
    final theme = DsSeam.of(context);       // אקצנט (מורף)
    final fonts = DsSeam.fontsOf(context);  // פונט
    return Container(padding: const EdgeInsets.fromLTRB(22, 20, 22, 20), decoration: BoxDecoration(gradient: LinearGradient(colors: [skin.surface, skin.sunken], begin: Alignment.topCenter, end: Alignment.bottomCenter), border: Border.all(color: skin.hair), borderRadius: BorderRadius.circular(16)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(mainAxisSize: MainAxisSize.max, mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.center, spacing: 12, children: [Directionality(textDirection: TextDirection.ltr, child: Text.rich(TextSpan(children: [TextSpan(text: "Step ", style: TextStyle(color: skin.mut, fontFamily: fonts.grotesk, fontFamilyFallback: [fonts.he], fontSize: 11, fontWeight: FontWeight.w600)), TextSpan(text: "2", style: TextStyle(color: theme.aHi, fontFamily: fonts.grotesk, fontFamilyFallback: [fonts.he], fontSize: 11, fontWeight: FontWeight.w700)), TextSpan(text: " of 5", style: TextStyle(color: skin.mut, fontFamily: fonts.grotesk, fontFamilyFallback: [fonts.he], fontSize: 11, fontWeight: FontWeight.w600))]))), Row(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.center, spacing: 7, children: [Container(width: 8, height: 8, decoration: BoxDecoration(color: theme.a, borderRadius: BorderRadius.circular(999))), Container(width: 8, height: 8, decoration: BoxDecoration(color: theme.aHi, borderRadius: BorderRadius.circular(999), boxShadow: [BoxShadow(color: theme.a, offset: const Offset(0, 0), blurRadius: 0, spreadRadius: 3)])), Container(width: 8, height: 8, decoration: BoxDecoration(color: skin.hair, borderRadius: BorderRadius.circular(999))), Container(width: 8, height: 8, decoration: BoxDecoration(color: skin.hair, borderRadius: BorderRadius.circular(999))), Container(width: 8, height: 8, decoration: BoxDecoration(color: skin.hair, borderRadius: BorderRadius.circular(999)))])]), const SizedBox(height: 12), SizedBox(width: double.infinity, child: Container(height: 6, decoration: BoxDecoration(color: skin.sunken, border: Border.all(color: skin.hair2), borderRadius: BorderRadius.circular(999)), child: FractionallySizedBox(widthFactor: 0.400, alignment: Alignment.centerRight, child: Container(decoration: BoxDecoration(gradient: LinearGradient(colors: [theme.a, theme.aHi], begin: Alignment.centerLeft, end: Alignment.centerRight), borderRadius: BorderRadius.circular(999)))))), const SizedBox(height: 14), Text("Label", style: TextStyle(color: skin.ink, fontFamily: fonts.serifHe, fontSize: 20, fontWeight: FontWeight.w700, letterSpacing: -0.20, height: 1.05, leadingDistribution: TextLeadingDistribution.even)), const SizedBox(height: 7), IntrinsicWidth(child: Text("Meta", style: TextStyle(color: skin.mut, fontSize: 12.5, height: 1.45, leadingDistribution: TextLeadingDistribution.even, fontFamily: fonts.he)))]));
  }
}
