#!/usr/bin/env node
/**
 * Reads the legacy index.html prototype, lifts the TREES constant (171
 * contractor catalog products), writes each base64 product image out to
 * public/catalog/<id>.jpg, and emits src/data/catalog.ts with the
 * de-bloated metadata plus a derived category tree.
 *
 * Re-run whenever the source catalog changes:
 *   node scripts/extract-catalog.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';

const here = path.dirname(url.fileURLToPath(import.meta.url));
const appRoot = path.resolve(here, '..');
const legacyHtml = path.resolve(appRoot, '../index.html');
const imagesDir = path.join(appRoot, 'public/catalog');
const outFile = path.join(appRoot, 'src/data/catalog.ts');

fs.mkdirSync(imagesDir, { recursive: true });

const html = fs.readFileSync(legacyHtml, 'utf8');
const lines = html.split('\n');

const startIdx = lines.findIndex((l) => l.includes('const TREES = {'));
if (startIdx < 0) throw new Error('TREES constant not found in legacy HTML');

let depth = 0;
let endIdx = -1;
for (let i = startIdx; i < lines.length; i++) {
  for (const ch of lines[i]) {
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) {
        endIdx = i;
        break;
      }
    }
  }
  if (endIdx >= 0) break;
}
if (endIdx < 0) throw new Error('Could not find matching close of TREES');

const treesCode = lines.slice(startIdx, endIdx + 1).join('\n');
const TREES = new Function(`${treesCode}; return TREES;`)();

const entries = Object.entries(TREES);
let imagesWritten = 0;

const products = entries.map(([id, raw]) => {
  let image;
  if (typeof raw.image === 'string' && raw.image.startsWith('data:image/jpeg;base64,')) {
    const base64 = raw.image.split(',', 2)[1];
    const buf = Buffer.from(base64, 'base64');
    const file = `${id}.jpg`;
    fs.writeFileSync(path.join(imagesDir, file), buf);
    image = `/catalog/${file}`;
    imagesWritten++;
  }

  const out = {
    id,
    name: String(raw.name ?? id),
    emoji: String(raw.img ?? '📦'),
    categoryId: String(raw.cat ?? 'אחר'),
  };
  if (raw.secondary) out.subcategoryId = String(raw.secondary);
  if (raw.productType) out.productType = String(raw.productType);
  if (raw.series) out.series = String(raw.series);
  if (raw.material) out.material = String(raw.material);
  if (raw.note) out.note = String(raw.note);
  if (typeof raw.price === 'number') out.price = raw.price;
  if (image) out.image = image;
  return out;
});

const categoriesMap = new Map();
for (const p of products) {
  if (!categoriesMap.has(p.categoryId)) {
    categoriesMap.set(p.categoryId, new Set());
  }
  if (p.subcategoryId) {
    categoriesMap.get(p.categoryId).add(p.subcategoryId);
  }
}

const slug = (s) => {
  return s
    .replace(/[\s/]+/g, '-')
    .replace(/["'״׳]/g, '')
    .replace(/[^֐-׿a-zA-Z0-9-]/g, '')
    .toLowerCase();
};

const categoryEmojiMap = {
  'אביזרים מכניים': '⚙️',
  'אביזרים נלווים': '🧰',
};

const subEmojiMap = {
  'ברזים ושסתומים': '🚰',
  'חיבורים ומחברים': '🔗',
  'צנרת וצינורות': '🟢',
  'חומרי איטום והדבקה': '🧴',
  'ברגים ועיגון': '🔩',
  'אטמים וגומיות': '⭕',
  'בנייה וריצוף': '🧱',
  'מיכלים וגופים סמויים': '📦',
  'חשמל וחימום': '⚡',
  'אחר': '✨',
  'הסתעפות': '🔱',
  'מעבר זווית': '↪️',
  'מחבר ישר': '➖',
  'הסתעפות מופחתת': '🪢',
  'תושבת לאסלה תלויה': '🚽',
  'אביזרי שירותים': '🧻',
  'מגופים וברזים': '🔧',
  'הלחמות והתכת חימום': '🔥',
  'כלי עבודה': '🛠️',
};

const cats = [];
let topCount = 0;
for (const [topName, subs] of categoriesMap.entries()) {
  topCount++;
  const topId = `top-${slug(topName)}` || `top-${topCount}`;
  cats.push({
    id: topId,
    name: topName,
    emoji: categoryEmojiMap[topName] ?? '📁',
    parentId: null,
  });
  for (const subName of subs) {
    const subId = `${topId}/${slug(subName)}`;
    cats.push({
      id: subId,
      name: subName,
      emoji: subEmojiMap[subName] ?? '•',
      parentId: topId,
    });
  }
}

for (const p of products) {
  const topId = `top-${slug(p.categoryId)}`;
  p.categoryTopId = topId;
  if (p.subcategoryId) {
    p.categoryLeafId = `${topId}/${slug(p.subcategoryId)}`;
  } else {
    p.categoryLeafId = topId;
  }
  delete p.categoryId;
  delete p.subcategoryId;
}

const header = `/* Auto-generated by scripts/extract-catalog.mjs — do not edit by hand.
 * Source: /home/user/buildsmart/index.html TREES constant.
 * Regenerate: node scripts/extract-catalog.mjs
 */
`;

const productType = `export type CatalogProduct = {
  id: string;
  name: string;
  emoji: string;
  categoryTopId: string;
  categoryLeafId: string;
  productType?: string;
  series?: string;
  material?: string;
  note?: string;
  price?: number;
  image?: string;
};

export type CatalogCategory = {
  id: string;
  name: string;
  emoji: string;
  parentId: string | null;
};
`;

const body =
  header +
  productType +
  `\nexport const CATEGORIES: CatalogCategory[] = ${JSON.stringify(cats, null, 2)};\n\n` +
  `export const PRODUCTS: CatalogProduct[] = ${JSON.stringify(products, null, 2)};\n` +
  `\nexport function childrenOf(parentId: string | null): CatalogCategory[] {
  return CATEGORIES.filter((c) => c.parentId === parentId);
}

export function categoryById(id: string): CatalogCategory | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function productsForPath(path: string[]): CatalogProduct[] {
  if (path.length === 0) return PRODUCTS;
  const current = path[path.length - 1];
  return PRODUCTS.filter(
    (p) => p.categoryLeafId === current || p.categoryTopId === current,
  );
}

export function productById(id: string): CatalogProduct | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
`;

fs.writeFileSync(outFile, body);

const sizeKb = Math.round(fs.statSync(outFile).size / 1024);
console.log(`Wrote ${products.length} products to ${outFile} (${sizeKb} KB)`);
console.log(`Wrote ${imagesWritten} catalog images to ${imagesDir}`);
console.log(`Categories: ${cats.filter((c) => !c.parentId).length} top, ${cats.filter((c) => c.parentId).length} sub`);
