/* Auto-generated by scripts/extract-catalog.mjs — do not edit by hand.
 * Source: /home/user/buildsmart/index.html TREES constant.
 * Regenerate: node scripts/extract-catalog.mjs
 */
export type CatalogProduct = {
  id: string;
  name: string;
  emoji: string;
  categoryTopId: string;
  categoryLeafId: string;
  productType?: string;
  series?: string;
  material?: string;
  note?: string;
  price?: number;
  image?: string;
};

export type CatalogCategory = {
  id: string;
  name: string;
  emoji: string;
  parentId: string | null;
};

export const CATEGORIES: CatalogCategory[] = [
  {
    "id": "top-אביזרים-מכניים",
    "name": "אביזרים מכניים",
    "emoji": "⚙️",
    "parentId": null
  },
  {
    "id": "top-אביזרים-מכניים/כללי",
    "name": "כללי",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/הברגה-פנימית",
    "name": "הברגה פנימית",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/90-מעבר",
    "name": "90° מעבר",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/זווית-45",
    "name": "זווית 45°",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/rc",
    "name": "R.C.",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/45-חוץ",
    "name": "45° חוץ",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/כדורית",
    "name": "כדורית",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/הברגה-חיצונית",
    "name": "הברגה חיצונית",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/עם-זקף",
    "name": "עם זקף",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/90-מתאם",
    "name": "90° מתאם",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/עם-אוגן-מתכת",
    "name": "עם אוגן מתכת",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/מודולארי",
    "name": "מודולארי",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אביזרים-מכניים/מוארך",
    "name": "מוארך",
    "emoji": "•",
    "parentId": "top-אביזרים-מכניים"
  },
  {
    "id": "top-אחר",
    "name": "אחר",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-ברזים-וכיורים",
    "name": "ברזים וכיורים",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-אסלות",
    "name": "אסלות",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-מקלחות-ואמבטיות",
    "name": "מקלחות ואמבטיות",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-בנייה-ומחיצות",
    "name": "בנייה ומחיצות",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-גמר",
    "name": "גמר",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-אינסטלציה-גסה",
    "name": "אינסטלציה גסה",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-חימום-מים",
    "name": "חימום מים",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-מטבח",
    "name": "מטבח",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-ניקוז-וצנרת",
    "name": "ניקוז וצנרת",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-גופי-תברואה",
    "name": "גופי תברואה",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-אביזרי-קצה-וחיבורים",
    "name": "אביזרי קצה וחיבורים",
    "emoji": "📁",
    "parentId": null
  },
  {
    "id": "top-אביזרים-נלווים",
    "name": "אביזרים נלווים",
    "emoji": "🧰",
    "parentId": null
  },
  {
    "id": "top-אביזרים-נלווים/אטמים-וגומיות",
    "name": "אטמים וגומיות",
    "emoji": "⭕",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/כלי-עבודה",
    "name": "כלי עבודה",
    "emoji": "🛠️",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/חומרי-איטום-והדבקה",
    "name": "חומרי איטום והדבקה",
    "emoji": "🧴",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/חיבורים-ומחברים",
    "name": "חיבורים ומחברים",
    "emoji": "🔗",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/ברזים-ושסתומים",
    "name": "ברזים ושסתומים",
    "emoji": "🚰",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים",
    "name": "מיכלים וגופים סמויים",
    "emoji": "📦",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/צנרת-וצינורות",
    "name": "צנרת וצינורות",
    "emoji": "🟢",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/בנייה-וריצוף",
    "name": "בנייה וריצוף",
    "emoji": "🧱",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/אחר",
    "name": "אחר",
    "emoji": "✨",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/חשמל-וחימום",
    "name": "חשמל וחימום",
    "emoji": "⚡",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/ברגים-ועיגון",
    "name": "ברגים ועיגון",
    "emoji": "🔩",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/מסננים-ומלכודות",
    "name": "מסננים ומלכודות",
    "emoji": "•",
    "parentId": "top-אביזרים-נלווים"
  },
  {
    "id": "top-אביזרים-נלווים/מוצרי-גמר",
    "name": "מוצרי גמר",
    "emoji": "•",
    "parentId": "top-אביזרים-נלווים"
  }
];

export const PRODUCTS: CatalogProduct[] = [
  {
    "id": "pl_0712060200",
    "name": "אביזר לקצה צינור (פקק)",
    "emoji": "🔘",
    "productType": "פקק",
    "series": "סדרה 7 שחורים",
    "note": "פקק לסגירת קצה צינור, סדרה 7 שחורים",
    "image": "/catalog/pl_0712060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/כללי"
  },
  {
    "id": "pl_0714060160",
    "name": "הסתעפות 90° הברגה פנימית",
    "emoji": "🔱",
    "productType": "הסתעפות",
    "series": "סדרה 7 שחורים",
    "note": "הסתעפות T בזווית 90° עם הברגה פנימית, סדרה 7 שחורים",
    "image": "/catalog/pl_0714060160.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/הברגה-פנימית"
  },
  {
    "id": "pl_0715060160",
    "name": "זוית 90° הברגה פנימית",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זוית 90° עם הברגה פנימית, סדרה 7 שחורים",
    "image": "/catalog/pl_0715060160.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/הברגה-פנימית"
  },
  {
    "id": "pl_0734060200",
    "name": "הסתעפות 90° מעבר",
    "emoji": "🔱",
    "productType": "הסתעפות",
    "series": "סדרה 7 שחורים",
    "note": "הסתעפות T בזווית 90° מעבר קוטר, סדרה 7 שחורים",
    "image": "/catalog/pl_0734060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/90-מעבר"
  },
  {
    "id": "pl_0755060160",
    "name": "מסעף 45°",
    "emoji": "🔱",
    "productType": "מסעף",
    "series": "סדרה 7 שחורים",
    "note": "מסעף בזווית 45°, סדרה 7 שחורים",
    "image": "/catalog/pl_0755060160.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/זווית-45"
  },
  {
    "id": "pl_0706060320",
    "name": "זוית 45°",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זוית בזווית 45°, סדרה 7 שחורים",
    "image": "/catalog/pl_0706060320.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/זווית-45"
  },
  {
    "id": "pl_0751060250",
    "name": "זוית 90° מעבר",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זוית 90° מעבר קוטר, סדרה 7 שחורים",
    "image": "/catalog/pl_0751060250.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/90-מעבר"
  },
  {
    "id": "pl_0761060200",
    "name": "אביזר תיקון R.C.",
    "emoji": "🔧",
    "productType": "אביזר תיקון",
    "series": "סדרה 7 שחורים",
    "note": "אביזר תיקון R.C. — מצמד דו-כיווני לתיקון צינור, סדרה 7 שחורים",
    "image": "/catalog/pl_0761060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/rc"
  },
  {
    "id": "pl_0745060200",
    "name": "זוית 45° חוץ",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זוית 45° עם הברגה חיצונית, סדרה 7 שחורים",
    "image": "/catalog/pl_0745060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/45-חוץ"
  },
  {
    "id": "pl_0764060630",
    "name": "הסתעפות 45°",
    "emoji": "🔱",
    "productType": "הסתעפות",
    "series": "סדרה 7 שחורים",
    "note": "הסתעפות בזווית 45°, סדרה 7 שחורים",
    "image": "/catalog/pl_0764060630.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/זווית-45"
  },
  {
    "id": "pl_074706032",
    "name": "זווית כדורית",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זווית כדורית מתכווננת עד 15°, מוצר חדש",
    "image": "/catalog/pl_074706032.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/כדורית"
  },
  {
    "id": "pl_0784060200",
    "name": "הסתעפות 90° הברגה חיצונית",
    "emoji": "🔱",
    "productType": "הסתעפות",
    "series": "סדרה 7 שחורים",
    "note": "הסתעפות T בזווית 90° עם הברגה חיצונית, סדרה 7 שחורים",
    "image": "/catalog/pl_0784060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/הברגה-חיצונית"
  },
  {
    "id": "pl_0781060400",
    "name": "דו כיווני עם זקף",
    "emoji": "🪛",
    "productType": "דו-כיווני",
    "series": "סדרה 7 שחורים",
    "note": "אביזר דו-כיווני עם זקף הברגה, סדרה 7 שחורים",
    "image": "/catalog/pl_0781060400.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/עם-זקף"
  },
  {
    "id": "pl_0785060200",
    "name": "זוית 90° הברגה חיצונית",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זוית 90° עם הברגה חיצונית, סדרה 7 שחורים",
    "image": "/catalog/pl_0785060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/הברגה-חיצונית"
  },
  {
    "id": "pl_0735060400",
    "name": "זוית 90° מתאם",
    "emoji": "📐",
    "productType": "זווית",
    "series": "סדרה 7 שחורים",
    "note": "זוית 90° מתאם קוטר עם זקף הברגה, סדרה 7 שחורים",
    "image": "/catalog/pl_0735060400.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/90-מתאם"
  },
  {
    "id": "pl_0722060400",
    "name": "מחבר אוגן כולל אוגן מתכת",
    "emoji": "⭕",
    "productType": "מחבר אוגן",
    "series": "סדרה 7 שחורים",
    "note": "מחבר אוגן הכולל אוגן מתכת, סימון PL50 x 1.1/2\" ISO, סדרה 7 שחורים",
    "image": "/catalog/pl_0722060400.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/עם-אוגן-מתכת"
  },
  {
    "id": "pl_0723060500",
    "name": "מתאם אוגן כולל אוגן מתכת",
    "emoji": "⭕",
    "productType": "מתאם אוגן",
    "series": "סדרה 7 שחורים",
    "note": "מתאם אוגן הכולל אוגן מתכת, סימון PL 50 x 1.1/2\" ISO, סדרה 7 שחורים",
    "image": "/catalog/pl_0723060500.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/עם-אוגן-מתכת"
  },
  {
    "id": "pl_05629020",
    "name": "אטם שטוח למחברי אוגן",
    "emoji": "⭕",
    "productType": "אטם",
    "series": "אטמים",
    "note": "אטם שטוח למחברי אוגן",
    "image": "/catalog/pl_05629020.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/כללי"
  },
  {
    "id": "pl_0793000250",
    "name": "ערכת הפחתת קוטר",
    "emoji": "🧰",
    "productType": "ערכה",
    "series": "סדרה 7 שחורים",
    "note": "ערכת הפחתת קוטר, סדרה 7 שחורים",
    "image": "/catalog/pl_0793000250.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/כללי"
  },
  {
    "id": "pl_0789010250",
    "name": "מתאם תבריג חוץ",
    "emoji": "🔩",
    "productType": "מתאם תבריג",
    "series": "סדרה 7 שחורים",
    "note": "מתאם תבריג חיצוני, סדרה 7 שחורים",
    "image": "/catalog/pl_0789010250.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/כללי"
  },
  {
    "id": "pl_078946025P",
    "name": "אום למתאם תבריג",
    "emoji": "🔩",
    "productType": "אום",
    "series": "סדרה 7 שחורים",
    "note": "אום למתאם תבריג, סדרה 7 שחורים",
    "image": "/catalog/pl_078946025P.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/כללי"
  },
  {
    "id": "pl_0794060200",
    "name": "מתאם מודולארי",
    "emoji": "🔗",
    "productType": "מתאם מודולארי",
    "series": "סדרה 7 שחורים",
    "note": "מתאם מודולארי, סדרה 7 שחורים",
    "image": "/catalog/pl_0794060200.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/מודולארי"
  },
  {
    "id": "pl_0794L60500",
    "name": "מתאם מודולארי - מוארך",
    "emoji": "🔗",
    "productType": "מתאם מודולארי",
    "series": "סדרה 7 שחורים",
    "note": "מתאם מודולארי מוארך, ייצור מיוחד, סדרה 7 שחורים",
    "image": "/catalog/pl_0794L60500.jpg",
    "categoryTopId": "top-אביזרים-מכניים",
    "categoryLeafId": "top-אביזרים-מכניים/מוארך"
  },
  {
    "id": "infra",
    "name": "תשתית ואינסטלציה גסה",
    "emoji": "🪛",
    "note": "שלב 1 — תשתית ואינסטלציה גסה",
    "categoryTopId": "top-אחר",
    "categoryLeafId": "top-אחר"
  },
  {
    "id": "sealing",
    "name": "איטום והכנת רצפה",
    "emoji": "🛡️",
    "note": "שלב 2 — איטום והכנת רצפה",
    "categoryTopId": "top-אחר",
    "categoryLeafId": "top-אחר"
  },
  {
    "id": "tiling",
    "name": "ריצוף וחיפוי",
    "emoji": "🧱",
    "note": "שלב 3 — ריצוף וחיפוי",
    "categoryTopId": "top-אחר",
    "categoryLeafId": "top-אחר"
  },
  {
    "id": "cable",
    "name": "כבל חשמל 3×1.5",
    "emoji": "🟧",
    "note": "התקנת מעגל תאורה",
    "categoryTopId": "top-אחר",
    "categoryLeafId": "top-אחר"
  },
  {
    "id": "profile",
    "name": "פרופיל גבס 70 מ\"מ",
    "emoji": "⬜",
    "note": "הרכבת מחיצת גבס",
    "categoryTopId": "top-אחר",
    "categoryLeafId": "top-אחר"
  },
  {
    "id": "faucet",
    "name": "ברז לכיור",
    "emoji": "🚰",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-ברזים-וכיורים",
    "categoryLeafId": "top-ברזים-וכיורים"
  },
  {
    "id": "kitchenFaucet",
    "name": "ברז למטבח",
    "emoji": "🚰",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-ברזים-וכיורים",
    "categoryLeafId": "top-ברזים-וכיורים"
  },
  {
    "id": "basin",
    "name": "כיור אמבטיה",
    "emoji": "🪣",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-ברזים-וכיורים",
    "categoryLeafId": "top-ברזים-וכיורים"
  },
  {
    "id": "toilet",
    "name": "אסלה תלויה",
    "emoji": "🚽",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אסלות",
    "categoryLeafId": "top-אסלות"
  },
  {
    "id": "toiletFloor",
    "name": "אסלה רגילה (עומדת)",
    "emoji": "🚽",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אסלות",
    "categoryLeafId": "top-אסלות"
  },
  {
    "id": "shower",
    "name": "סוללת מקלחת",
    "emoji": "🚿",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-מקלחות-ואמבטיות",
    "categoryLeafId": "top-מקלחות-ואמבטיות"
  },
  {
    "id": "bathtub",
    "name": "אמבטיה",
    "emoji": "🛁",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-מקלחות-ואמבטיות",
    "categoryLeafId": "top-מקלחות-ואמבטיות"
  },
  {
    "id": "wall",
    "name": "קיר גבס",
    "emoji": "🧱",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-בנייה-ומחיצות",
    "categoryLeafId": "top-בנייה-ומחיצות"
  },
  {
    "id": "door",
    "name": "דלת לשירותים",
    "emoji": "🚪",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-בנייה-ומחיצות",
    "categoryLeafId": "top-בנייה-ומחיצות"
  },
  {
    "id": "floor",
    "name": "ריצוף וחיפוי",
    "emoji": "🟫",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-גמר",
    "categoryLeafId": "top-גמר"
  },
  {
    "id": "seal",
    "name": "איטום הרצפה",
    "emoji": "🛡️",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-גמר",
    "categoryLeafId": "top-גמר"
  },
  {
    "id": "pipes",
    "name": "אינסטלציה (צנרת)",
    "emoji": "🔧",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אינסטלציה-גסה",
    "categoryLeafId": "top-אינסטלציה-גסה"
  },
  {
    "id": "boilerElectric",
    "name": "דוד חשמל",
    "emoji": "♨️",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-חימום-מים",
    "categoryLeafId": "top-חימום-מים"
  },
  {
    "id": "boilerSolar",
    "name": "מערכת דוד שמש",
    "emoji": "☀️",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-חימום-מים",
    "categoryLeafId": "top-חימום-מים"
  },
  {
    "id": "kitchenSink",
    "name": "כיור מטבח",
    "emoji": "🍽️",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-מטבח",
    "categoryLeafId": "top-מטבח"
  },
  {
    "id": "dishwasher",
    "name": "נקודת מים למדיח",
    "emoji": "💧",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-מטבח",
    "categoryLeafId": "top-מטבח"
  },
  {
    "id": "washingPoint",
    "name": "נקודת מכונת כביסה",
    "emoji": "🧺",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-מטבח",
    "categoryLeafId": "top-מטבח"
  },
  {
    "id": "floorDrain",
    "name": "מחסום רצפה",
    "emoji": "🕳️",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-ניקוז-וצנרת",
    "categoryLeafId": "top-ניקוז-וצנרת"
  },
  {
    "id": "pressureReg",
    "name": "וסת לחץ מים",
    "emoji": "⚙️",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-ניקוז-וצנרת",
    "categoryLeafId": "top-ניקוז-וצנרת"
  },
  {
    "id": "showerCabin",
    "name": "מקלחון (פינת מקלחת)",
    "emoji": "🛗",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-גופי-תברואה",
    "categoryLeafId": "top-גופי-תברואה"
  },
  {
    "id": "bidet",
    "name": "בידה",
    "emoji": "🚾",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-גופי-תברואה",
    "categoryLeafId": "top-גופי-תברואה"
  },
  {
    "id": "endTaps",
    "name": "ברזי קצה",
    "emoji": "🚰",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אביזרי-קצה-וחיבורים",
    "categoryLeafId": "top-אביזרי-קצה-וחיבורים"
  },
  {
    "id": "elbows",
    "name": "זוויות ומעברים",
    "emoji": "📐",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אביזרי-קצה-וחיבורים",
    "categoryLeafId": "top-אביזרי-קצה-וחיבורים"
  },
  {
    "id": "extenders",
    "name": "מאריכים וניפלים",
    "emoji": "➖",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אביזרי-קצה-וחיבורים",
    "categoryLeafId": "top-אביזרי-קצה-וחיבורים"
  },
  {
    "id": "connectors",
    "name": "חיבורי זכר / נקבה",
    "emoji": "🔗",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אביזרי-קצה-וחיבורים",
    "categoryLeafId": "top-אביזרי-קצה-וחיבורים"
  },
  {
    "id": "seals",
    "name": "אטמים וגומיות",
    "emoji": "⚫",
    "productType": "מוצר ראשי",
    "categoryTopId": "top-אביזרי-קצה-וחיבורים",
    "categoryLeafId": "top-אביזרי-קצה-וחיבורים"
  },
  {
    "id": "acc_1",
    "name": "חומר סיכה לאטם הגומי",
    "emoji": "🧴",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "מקל על החדרת הצינור לאביזר ומונע נזק לאטם",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_2",
    "name": "מפתח צינורות / מפתח שבדי",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "להידוק האום על הצינור — חובה להרכבה תקינה",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/כלי-עבודה"
  },
  {
    "id": "acc_3",
    "name": "חותך צינורות PE",
    "emoji": "✂️",
    "productType": "אביזרים נלווים",
    "note": "לחיתוך נקי וישר של הצינור לפני החיבור",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/כלי-עבודה"
  },
  {
    "id": "acc_4",
    "name": "סרט אטימה לתבריג (טפלון)",
    "emoji": "🎗️",
    "productType": "אביזרים נלווים",
    "note": "אוטם את חיבור ההברגה — בלי זה ההברגה דולפת",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_5",
    "name": "אטם גומי חלופי (NBR)",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "אם האטם המקורי נפגם — חלק חילוף נפוץ",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_6",
    "name": "אטם שטוח לאוגן",
    "emoji": "⭕",
    "productType": "אביזרים נלווים",
    "note": "אוטם בין שני אוגנים — חובה באיטום אוגן",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_7",
    "name": "בורגי אוגן + אומים",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "להרכבת האוגן — סט ברגים לפי מספר החורים",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_8",
    "name": "גוף סמוי לסוללת מקלחת",
    "emoji": "⬛",
    "productType": "אביזרים נלווים",
    "note": "מותקן בקיר — בלתי הפיך אחרי ריצוף",
    "price": 240,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_9",
    "name": "מיכל הדחה סמוי לאסלה",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "הבסיס למערכת האסלה התלויה",
    "price": 430,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_10",
    "name": "צינור PEX מים חמים/קרים",
    "emoji": "🟦",
    "productType": "אביזרים נלווים",
    "material": "PEX",
    "note": "קווי האספקה לכל נקודות המים",
    "price": 6,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_11",
    "name": "צינור ניקוז 50 מ\"מ",
    "emoji": "🟫",
    "productType": "אביזרים נלווים",
    "note": "ניקוז כיור ומקלחת לקו הראשי",
    "price": 14,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_12",
    "name": "מחברים וזוויות",
    "emoji": "📐",
    "productType": "אביזרים נלווים",
    "note": "חיבור הקווים בין הנקודות",
    "price": 7,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_13",
    "name": "נקזון רצפה",
    "emoji": "🕳️",
    "productType": "אביזרים נלווים",
    "note": "ניקוז רצפת המקלחת",
    "price": 58,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_14",
    "name": "יריעת איטום ביטומנית",
    "emoji": "🟪",
    "productType": "אביזרים נלווים",
    "note": "שכבת המגן מפני חדירת מים",
    "price": 35,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_15",
    "name": "פריימר הדבקה",
    "emoji": "🪣",
    "productType": "אביזרים נלווים",
    "note": "מכינה את הרצפה לקליטת האיטום",
    "price": 64,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_16",
    "name": "מסטיק איטום פינות",
    "emoji": "🧴",
    "productType": "אביזרים נלווים",
    "note": "איטום מפגשי קיר-רצפה — נקודת תורפה",
    "price": 28,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_17",
    "name": "בד חיזוק לפינות",
    "emoji": "🧵",
    "productType": "אביזרים נלווים",
    "note": "חיזוק האיטום בפינות ובמעברי צנרת",
    "price": 16,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_18",
    "name": "מדה ליישור ושיפוע",
    "emoji": "🪨",
    "productType": "אביזרים נלווים",
    "note": "יוצרת שיפוע ניקוז לכיוון הנקז",
    "price": 32,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_19",
    "name": "דבק אריחים גמיש",
    "emoji": "🪣",
    "productType": "אביזרים נלווים",
    "note": "הדבקת אריחי רצפה וקיר",
    "price": 52,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_20",
    "name": "אריחי קרמיקה",
    "emoji": "🟧",
    "productType": "אביזרים נלווים",
    "note": "חיפוי הרצפה והקירות",
    "price": 89,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_21",
    "name": "רובה אפוקסי",
    "emoji": "🎨",
    "productType": "אביזרים נלווים",
    "note": "מילוי המישקים — עמיד למים",
    "price": 46,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_22",
    "name": "פרופיל סיום לאריח",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "גימור קצוות וזוויות",
    "price": 22,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_23",
    "name": "מפרידי אריחים (קלסר)",
    "emoji": "➕",
    "productType": "אביזרים נלווים",
    "note": "שמירת מרווח אחיד בין אריחים",
    "price": 14,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_24",
    "name": "שרוול שרשורי 16 מ\"מ",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "הגנה על הכבל בקיר",
    "price": 1,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_25",
    "name": "קופסת התפצלות",
    "emoji": "⬛",
    "productType": "אביזרים נלווים",
    "note": "נדרשת בכל נקודת חיבור",
    "price": 6,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_26",
    "name": "מהדקי וואגו",
    "emoji": "🔌",
    "productType": "אביזרים נלווים",
    "note": "חיבור מהיר ובטוח",
    "price": 2,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_27",
    "name": "סרט בידוד",
    "emoji": "🎗️",
    "productType": "אביזרים נלווים",
    "note": "גימור וסימון פאזות",
    "price": 5,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_28",
    "name": "בורג גבס 25 מ\"מ",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "קיבוע לוחות — צריכה גבוהה",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_29",
    "name": "מסילה תחתונה 70 מ\"מ",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "בסיס לכל קיר גבס",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_30",
    "name": "סרט בד לפינות",
    "emoji": "🧵",
    "productType": "אביזרים נלווים",
    "note": "חיזוק חיבורי לוחות",
    "price": 12,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_31",
    "name": "דיבל פלסטיק 6 מ\"מ",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "material": "פלסטיק",
    "note": "עיגון מסילות לרצפה",
    "price": 0,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_32",
    "name": "שפכטל מוכן",
    "emoji": "🪣",
    "productType": "אביזרים נלווים",
    "note": "גמר וכיסוי ברגים",
    "price": 48,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/כלי-עבודה"
  },
  {
    "id": "acc_33",
    "name": "צינורות חיבור גמישים",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "מחבר את הברז למים",
    "price": 28,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_34",
    "name": "ברזי ניל זוויתיים",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "לסגור מים בעת תיקון",
    "price": 22,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_35",
    "name": "סרט טפלון",
    "emoji": "🎗️",
    "productType": "אביזרים נלווים",
    "note": "אוטם את ההברגה",
    "price": 4,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_36",
    "name": "אטם גומי לברז",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "מונע נזילה בחיבור",
    "price": 3,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_37",
    "name": "סיליקון סניטרי",
    "emoji": "🧴",
    "productType": "אביזרים נלווים",
    "note": "אם הברז יושב על המשטח",
    "price": 21,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_38",
    "name": "מפתח צינורות",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "רק אם אין לך בערכה",
    "price": 39,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/כלי-עבודה"
  },
  {
    "id": "acc_39",
    "name": "פקק ניקוז עם שרשרת",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "אם הכיור בלי פקק מובנה",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מסננים-ומלכודות"
  },
  {
    "id": "acc_40",
    "name": "מסנן מים לברז",
    "emoji": "💧",
    "productType": "אביזרים נלווים",
    "note": "אם רוצים סינון מי שתייה",
    "price": 95,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_41",
    "name": "סיפון לכיור",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "ניקוז הכיור — חובה",
    "price": 46,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_42",
    "name": "ברגי תלייה לכיור",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "אם הכיור תלוי על הקיר",
    "price": 14,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_43",
    "name": "רגל תמיכה לכיור",
    "emoji": "🦵",
    "productType": "אביזרים נלווים",
    "note": "אם הכיור עם רגל",
    "price": 120,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_44",
    "name": "מיכל הדחה סמוי",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "הבסיס למערכת — חובה",
    "price": 430,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_45",
    "name": "אטם לאסלה",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "note": "מונע ריחות ונזילות",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_46",
    "name": "ברגי קיבוע",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "מחזיק את האסלה",
    "price": 9,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_47",
    "name": "לחצן הדחה",
    "emoji": "⏹️",
    "productType": "אביזרים נלווים",
    "note": "הכפתור של ההדחה",
    "price": 65,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_48",
    "name": "מושב אסלה",
    "emoji": "⭕",
    "productType": "אביזרים נלווים",
    "note": "אם לא מגיע עם האסלה",
    "price": 89,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מוצרי-גמר"
  },
  {
    "id": "acc_49",
    "name": "מיכל הדחה",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "מיכל עליון — חובה",
    "price": 180,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_50",
    "name": "אטם שעווה לאסלה",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "note": "איטום מול קו הביוב",
    "price": 22,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_51",
    "name": "ברגי רצפה",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "מקבע את האסלה לרצפה",
    "price": 12,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_52",
    "name": "צינור חיבור למיכל",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "אם לא כלול בערכה",
    "price": 24,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_53",
    "name": "גוף סמוי לסוללה",
    "emoji": "⬛",
    "productType": "אביזרים נלווים",
    "note": "נכנס לקיר — חובה",
    "price": 240,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_54",
    "name": "ראש מקלחת + זרוע",
    "emoji": "🌧️",
    "productType": "אביזרים נלווים",
    "note": "החלק שרואים",
    "price": 155,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_55",
    "name": "צינור גמיש + מתקן",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "אם רוצים גם ראש נייד",
    "price": 32,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_56",
    "name": "מדף פינתי למקלחת",
    "emoji": "📐",
    "productType": "אביזרים נלווים",
    "note": "נחמד אבל לא חובה",
    "price": 48,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_57",
    "name": "סוללת מילוי לאמבטיה",
    "emoji": "🚰",
    "productType": "אביזרים נלווים",
    "note": "הברז של האמבטיה",
    "price": 320,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_58",
    "name": "סיפון לאמבטיה",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "ניקוז — חובה",
    "price": 78,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_59",
    "name": "רגליות תמיכה",
    "emoji": "🦵",
    "productType": "אביזרים נלווים",
    "note": "מייצב את האמבטיה",
    "price": 90,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_60",
    "name": "פאנל חזית לאמבטיה",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "אם האמבטיה חשופה",
    "price": 240,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_61",
    "name": "פרופילים + מסילות",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "השלד של הקיר",
    "price": 120,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_62",
    "name": "לוחות גבס",
    "emoji": "🟩",
    "productType": "אביזרים נלווים",
    "note": "החיפוי של הקיר",
    "price": 220,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_63",
    "name": "ברגי גבס",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "מחבר הכל",
    "price": 40,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_64",
    "name": "דיבלים לרצפה",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "עיגון המסילות",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_65",
    "name": "צמר סלעים לבידוד",
    "emoji": "🧵",
    "productType": "אביזרים נלווים",
    "note": "אם רוצים בידוד אקוסטי",
    "price": 95,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_66",
    "name": "משקוף",
    "emoji": "🟫",
    "productType": "אביזרים נלווים",
    "note": "המסגרת של הדלת — חובה",
    "price": 160,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_67",
    "name": "ידית + צילינדר",
    "emoji": "🔘",
    "productType": "אביזרים נלווים",
    "note": "הידית והנעילה",
    "price": 85,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_68",
    "name": "צירים",
    "emoji": "⚙️",
    "productType": "אביזרים נלווים",
    "note": "מחבר את הדלת למשקוף",
    "price": 32,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_69",
    "name": "אטם לדלת",
    "emoji": "🎗️",
    "productType": "אביזרים נלווים",
    "note": "מקטין רעש וטיוטות",
    "price": 24,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_70",
    "name": "אריחי רצפה",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "ריצוף הרצפה",
    "price": 680,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_71",
    "name": "אריחי חיפוי קיר",
    "emoji": "🟧",
    "productType": "אביזרים נלווים",
    "note": "חיפוי הקירות",
    "price": 570,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_72",
    "name": "פלסי ריווח",
    "emoji": "➕",
    "productType": "אביזרים נלווים",
    "note": "מרווח אחיד בין אריחים",
    "price": 14,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_73",
    "name": "יריעות איטום",
    "emoji": "⬛",
    "productType": "אביזרים נלווים",
    "note": "מגן מפני מים — חובה",
    "price": 280,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_74",
    "name": "פריימר ביטומני",
    "emoji": "🪣",
    "productType": "אביזרים נלווים",
    "note": "מכין את הרצפה",
    "price": 64,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_75",
    "name": "מחסום רצפה",
    "emoji": "🔘",
    "productType": "אביזרים נלווים",
    "note": "נקודת הניקוז",
    "price": 54,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_76",
    "name": "סרט איטום לפינות",
    "emoji": "🧵",
    "productType": "אביזרים נלווים",
    "note": "חיזוק נקודות התורפה",
    "price": 36,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_77",
    "name": "מדה לשיפועים",
    "emoji": "🪨",
    "productType": "אביזרים נלווים",
    "note": "אם הרצפה לא משופעת",
    "price": 120,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/בנייה-וריצוף"
  },
  {
    "id": "acc_78",
    "name": "צינורות מים PEX",
    "emoji": "🟧",
    "productType": "אביזרים נלווים",
    "material": "PEX",
    "note": "מים חמים וקרים",
    "price": 240,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_79",
    "name": "צינור ביוב 110",
    "emoji": "🟦",
    "productType": "אביזרים נלווים",
    "note": "מהאסלה החוצה",
    "price": 280,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_80",
    "name": "דבק PVC + פריימר",
    "emoji": "🪣",
    "productType": "אביזרים נלווים",
    "material": "PVC",
    "note": "איטום קווי הביוב",
    "price": 38,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_81",
    "name": "מרכזיית מים (מניפולד)",
    "emoji": "⚙️",
    "productType": "אביזרים נלווים",
    "note": "אם רוצים חלוקה מסודרת",
    "price": 320,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_82",
    "name": "גוף חימום",
    "emoji": "🔥",
    "productType": "אביזרים נלווים",
    "note": "מחמם את המים — חובה",
    "price": 120,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_83",
    "name": "תרמוסטט",
    "emoji": "🌡️",
    "productType": "אביזרים נלווים",
    "note": "שולט בטמפרטורה",
    "price": 85,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_84",
    "name": "שסתום ביטחון",
    "emoji": "⚙️",
    "productType": "אביזרים נלווים",
    "note": "בטיחות מפני לחץ — חובה",
    "price": 48,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_85",
    "name": "מתקן תלייה לקיר",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "אם הדוד תלוי על הקיר",
    "price": 64,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_86",
    "name": "אנוד מגנזיום",
    "emoji": "🔋",
    "productType": "אביזרים נלווים",
    "note": "מאריך את חיי הדוד",
    "price": 42,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_87",
    "name": "קולטים סולאריים",
    "emoji": "🟦",
    "productType": "אביזרים נלווים",
    "note": "אוספים את חום השמש — חובה",
    "price": 680,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_88",
    "name": "גוף חימום גיבוי (חשמל)",
    "emoji": "🔥",
    "productType": "אביזרים נלווים",
    "note": "לימים מעוננים",
    "price": 140,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חשמל-וחימום"
  },
  {
    "id": "acc_89",
    "name": "צנרת מבודדת לגג",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "מחברת קולטים לדוד",
    "price": 220,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_90",
    "name": "מתקן עיגון לגג",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "מקבע את המערכת לגג",
    "price": 180,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_91",
    "name": "סיפון כפול למטבח",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "ניקוז הכיור — חובה",
    "price": 68,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_92",
    "name": "מסנן שאריות מזון",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "מונע סתימות",
    "price": 24,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מסננים-ומלכודות"
  },
  {
    "id": "acc_93",
    "name": "מתקן סבון מובנה",
    "emoji": "🧼",
    "productType": "אביזרים נלווים",
    "note": "תוספת נוחות",
    "price": 55,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מוצרי-גמר"
  },
  {
    "id": "acc_94",
    "name": "ברז זוויתי למדיח",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "נקודת ניתוק המים — חובה",
    "price": 32,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_95",
    "name": "צינור מילוי",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "הזנת מים למדיח",
    "price": 28,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_96",
    "name": "צינור ניקוז",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "פינוי מים מהמדיח",
    "price": 24,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_97",
    "name": "שסתום אל-חזור",
    "emoji": "⚙️",
    "productType": "אביזרים נלווים",
    "note": "מונע חזרת מים מלוכלכים",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_98",
    "name": "ברז למכונת כביסה 3/4\"",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "נקודת ניתוק — חובה",
    "price": 38,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_99",
    "name": "צינור ניקוז עם וו",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "פינוי המים מהמכונה",
    "price": 24,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_100",
    "name": "מגש הצפה",
    "emoji": "🟦",
    "productType": "אביזרים נלווים",
    "note": "הגנה מנזילות — מומלץ",
    "price": 46,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מסננים-ומלכודות"
  },
  {
    "id": "acc_101",
    "name": "רשת ניקוז",
    "emoji": "⚙️",
    "productType": "אביזרים נלווים",
    "note": "מכסה המחסום — חובה",
    "price": 22,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מסננים-ומלכודות"
  },
  {
    "id": "acc_102",
    "name": "אטם גומי",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "מונע ריחות וחדירת מים",
    "price": 8,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_103",
    "name": "מלכודת ריח (סיפון)",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "חוסם ריחות ביוב — מומלץ",
    "price": 38,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מסננים-ומלכודות"
  },
  {
    "id": "acc_104",
    "name": "מד לחץ",
    "emoji": "🌡️",
    "productType": "אביזרים נלווים",
    "note": "מציג את לחץ המים",
    "price": 48,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_105",
    "name": "מסנן מים",
    "emoji": "💧",
    "productType": "אביזרים נלווים",
    "note": "מגן על הווסת מלכלוך",
    "price": 65,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מסננים-ומלכודות"
  },
  {
    "id": "acc_106",
    "name": "ברזי ניתוק",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "לתחזוקה עתידית — מומלץ",
    "price": 44,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_107",
    "name": "פרופילי עיגון לקיר",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "מקבעים את המקלחון — חובה",
    "price": 120,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_108",
    "name": "אגנית מקלחת",
    "emoji": "⬜",
    "productType": "אביזרים נלווים",
    "note": "בסיס המקלחון",
    "price": 340,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/מיכלים-וגופים-סמויים"
  },
  {
    "id": "acc_109",
    "name": "ידית + ציר לדלת",
    "emoji": "🔘",
    "productType": "אביזרים נלווים",
    "note": "אם הדלת לא מגיעה מורכבת",
    "price": 85,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברגים-ועיגון"
  },
  {
    "id": "acc_110",
    "name": "סוללת בידה",
    "emoji": "🚰",
    "productType": "אביזרים נלווים",
    "note": "הברז של הבידה — חובה",
    "price": 240,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_111",
    "name": "סיפון לבידה",
    "emoji": "🌀",
    "productType": "אביזרים נלווים",
    "note": "ניקוז — חובה",
    "price": 46,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/צנרת-וצינורות"
  },
  {
    "id": "acc_112",
    "name": "ברז גן 1/2\"",
    "emoji": "🚰",
    "productType": "אביזרים נלווים",
    "note": "ברז יציאה לגינה / מרפסת",
    "price": 32,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_113",
    "name": "ברז גן 3/4\"",
    "emoji": "🚰",
    "productType": "אביזרים נלווים",
    "note": "ברז גן בקוטר רחב",
    "price": 38,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_114",
    "name": "ברז מכונת כביסה 3/4\"",
    "emoji": "🚰",
    "productType": "אביזרים נלווים",
    "note": "נקודת ניתוק למכונה",
    "price": 38,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_115",
    "name": "ברז זוויתי לאסלה 1/2\"",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "ניתוק מים לאסלה",
    "price": 19,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_116",
    "name": "ברז זוויתי לכיור 1/2\"",
    "emoji": "🔧",
    "productType": "אביזרים נלווים",
    "note": "ניתוק מים לברז הכיור",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_117",
    "name": "ברז כדורי 1/2\"",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "ניתוק מהיר על קו מים",
    "price": 24,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_118",
    "name": "ברז כדורי 3/4\"",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "ניתוק על קו ראשי",
    "price": 31,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_119",
    "name": "ברז אל-חזור 1/2\"",
    "emoji": "⚙️",
    "productType": "אביזרים נלווים",
    "note": "מונע זרימת מים לאחור",
    "price": 28,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/ברזים-ושסתומים"
  },
  {
    "id": "acc_120",
    "name": "זווית 90° 1/2\" זכר-נקבה",
    "emoji": "📐",
    "productType": "אביזרים נלווים",
    "note": "שינוי כיוון קו 90 מעלות",
    "price": 6,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_121",
    "name": "זווית 90° 3/4\" זכר-נקבה",
    "emoji": "📐",
    "productType": "אביזרים נלווים",
    "note": "זווית בקוטר רחב",
    "price": 8,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_122",
    "name": "זווית 45° 1/2\"",
    "emoji": "📐",
    "productType": "אביזרים נלווים",
    "note": "שינוי כיוון מתון",
    "price": 7,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_123",
    "name": "זווית עם רקורד 1/2\"",
    "emoji": "📐",
    "productType": "אביזרים נלווים",
    "note": "זווית הניתנת לפירוק",
    "price": 14,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_124",
    "name": "טי 1/2\" (הסתעפות)",
    "emoji": "⊥",
    "productType": "אביזרים נלווים",
    "note": "פיצול קו לשני כיוונים",
    "price": 9,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_125",
    "name": "טי מעבר 3/4\"×1/2\"",
    "emoji": "⊥",
    "productType": "אביזרים נלווים",
    "note": "הסתעפות עם שינוי קוטר",
    "price": 12,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_126",
    "name": "צלב 1/2\" (4 כיוונים)",
    "emoji": "✚",
    "productType": "אביזרים נלווים",
    "note": "פיצול לארבעה כיוונים",
    "price": 16,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_127",
    "name": "ניפל 1/2\" (זכר-זכר)",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "מחבר שני חלקים נקביים",
    "price": 5,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_128",
    "name": "ניפל 3/4\" (זכר-זכר)",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "ניפל בקוטר רחב",
    "price": 7,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_129",
    "name": "מאריך 1/2\" — 2 ס\"מ",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "הארכה קצרה של נקודה",
    "price": 6,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_130",
    "name": "מאריך 1/2\" — 5 ס\"מ",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "הארכה בינונית",
    "price": 8,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_131",
    "name": "מאריך 1/2\" — 10 ס\"מ",
    "emoji": "➖",
    "productType": "אביזרים נלווים",
    "note": "הארכה ארוכה",
    "price": 11,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_132",
    "name": "ניפל מעבר 3/4\"×1/2\"",
    "emoji": "🔀",
    "productType": "אביזרים נלווים",
    "note": "חיבור בין שני קטרים",
    "price": 9,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_133",
    "name": "בוקסה (מקטין) 3/4\"→1/2\"",
    "emoji": "🔻",
    "productType": "אביזרים נלווים",
    "note": "הקטנת קוטר ההברגה",
    "price": 6,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_134",
    "name": "מופה 1/2\" (נקבה-נקבה)",
    "emoji": "🔗",
    "productType": "אביזרים נלווים",
    "note": "מחברת שני חלקים זכריים",
    "price": 5,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_135",
    "name": "מופה 3/4\" (נקבה-נקבה)",
    "emoji": "🔗",
    "productType": "אביזרים נלווים",
    "note": "מופה בקוטר רחב",
    "price": 7,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_136",
    "name": "רקורד 1/2\" (אגוז מתפרק)",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "חיבור הניתן לפירוק חוזר",
    "price": 16,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_137",
    "name": "רקורד 3/4\"",
    "emoji": "🔩",
    "productType": "אביזרים נלווים",
    "note": "רקורד בקוטר רחב",
    "price": 21,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_138",
    "name": "מחבר זכר-נקבה 1/2\"",
    "emoji": "🔗",
    "productType": "אביזרים נלווים",
    "note": "חיבור בין שני סוגי הברגה",
    "price": 6,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_139",
    "name": "פקק 1/2\" (סתימת קצה)",
    "emoji": "🔵",
    "productType": "אביזרים נלווים",
    "note": "סוגר קצה צינור פתוח",
    "price": 4,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חיבורים-ומחברים"
  },
  {
    "id": "acc_140",
    "name": "פלנש'ה לחיבור גמיש",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "חיבור צינור גמיש לקו קשיח",
    "price": 12,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אחר"
  },
  {
    "id": "acc_141",
    "name": "סרט טפלון (גליל)",
    "emoji": "🎗️",
    "productType": "אביזרים נלווים",
    "note": "אוטם הברגות — חובה בכל חיבור",
    "price": 4,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_142",
    "name": "חוט פשתן לאיטום",
    "emoji": "🧵",
    "productType": "אביזרים נלווים",
    "note": "איטום הברגות — חלופה לטפלון",
    "price": 9,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_143",
    "name": "משחת איטום",
    "emoji": "🪣",
    "productType": "אביזרים נלווים",
    "note": "איטום נוסף על חוט הפשתן",
    "price": 18,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/חומרי-איטום-והדבקה"
  },
  {
    "id": "acc_144",
    "name": "אטם גומי 1/2\"",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "אוטם חיבורי רקורד וברזים",
    "price": 1,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_145",
    "name": "אטם גומי 3/4\"",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "אטם בקוטר רחב",
    "price": 2,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_146",
    "name": "או-רינג (טבעת אטימה)",
    "emoji": "⭕",
    "productType": "אביזרים נלווים",
    "note": "אוטם חיבורים פנימיים",
    "price": 3,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_147",
    "name": "אטם פלנש' לסוללה",
    "emoji": "⚪",
    "productType": "אביזרים נלווים",
    "note": "אוטם בין הסוללה לקיר",
    "price": 4,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  },
  {
    "id": "acc_148",
    "name": "גומיית מילוי לאסלה",
    "emoji": "⚫",
    "productType": "אביזרים נלווים",
    "material": "גומי",
    "note": "אוטם בין מיכל ההדחה לאסלה",
    "price": 8,
    "categoryTopId": "top-אביזרים-נלווים",
    "categoryLeafId": "top-אביזרים-נלווים/אטמים-וגומיות"
  }
];

export function childrenOf(parentId: string | null): CatalogCategory[] {
  return CATEGORIES.filter((c) => c.parentId === parentId);
}

export function categoryById(id: string): CatalogCategory | undefined {
  return CATEGORIES.find((c) => c.id === id);
}

export function productsForPath(path: string[]): CatalogProduct[] {
  if (path.length === 0) return PRODUCTS;
  const current = path[path.length - 1];
  return PRODUCTS.filter(
    (p) => p.categoryLeafId === current || p.categoryTopId === current,
  );
}

export function productById(id: string): CatalogProduct | undefined {
  return PRODUCTS.find((p) => p.id === id);
}
