/* Auto-generated by scripts/extract-catalog.mjs — do not edit by hand.
 * Source: /home/user/buildsmart/index.html
 * Regenerate: node scripts/extract-catalog.mjs
 */
export type ToolItem = {
  name: string;
  emoji: string;
  why?: string;
  price: number;
};

export const TOOL_BUNDLES: Record<string, ToolItem[]> = {
  "faucet": [
    {
      "name": "מפתח צינורות מתכוונן",
      "emoji": "🔧",
      "why": "להידוק האום של הברז",
      "price": 39
    },
    {
      "name": "מפתח אלן",
      "emoji": "🔩",
      "why": "לקיבוע הברז מתחת לכיור",
      "price": 24
    },
    {
      "name": "מברגה",
      "emoji": "🪛",
      "why": "לעבודות קיבוע כלליות",
      "price": 280
    }
  ],
  "kitchenFaucet": [
    {
      "name": "מפתח צינורות מתכוונן",
      "emoji": "🔧",
      "why": "להידוק חיבורי הברז",
      "price": 39
    },
    {
      "name": "מפתח לסוללה (ארוך)",
      "emoji": "🔧",
      "why": "מגיע לאום העמוק מתחת לכיור",
      "price": 55
    }
  ],
  "basin": [
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא שהכיור ישר",
      "price": 45
    },
    {
      "name": "מקדחה רוטטת",
      "emoji": "🔩",
      "why": "לקדוח לעיגון הכיור בקיר",
      "price": 640
    },
    {
      "name": "סכין יפנית",
      "emoji": "🔪",
      "why": "לחיתוך עודפי סיליקון",
      "price": 18
    }
  ],
  "toilet": [
    {
      "name": "מקדחה רוטטת",
      "emoji": "🔩",
      "why": "לקדיחת חורי העיגון בקיר",
      "price": 640
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא שהאסלה ישרה",
      "price": 45
    },
    {
      "name": "מפתח שוודי",
      "emoji": "🔧",
      "why": "להידוק חיבורי המים",
      "price": 62
    }
  ],
  "toiletFloor": [
    {
      "name": "מקדחה",
      "emoji": "🔩",
      "why": "לקדיחת חורי הרצפה",
      "price": 480
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "יישור האסלה",
      "price": 45
    },
    {
      "name": "מפתח שוודי",
      "emoji": "🔧",
      "why": "חיבור המיכל לאסלה",
      "price": 62
    }
  ],
  "shower": [
    {
      "name": "מפתח אלן",
      "emoji": "🔩",
      "why": "לכוונון הגוף הסמוי",
      "price": 24
    },
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "להידוק ההברגות",
      "price": 39
    },
    {
      "name": "פטיש גומי",
      "emoji": "🔨",
      "why": "להתאמת הגוף הסמוי בקיר",
      "price": 38
    }
  ],
  "bathtub": [
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "יישור האמבטיה ושיפוע הניקוז",
      "price": 45
    },
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "לחיבור הסיפון והסוללה",
      "price": 39
    },
    {
      "name": "מברגה",
      "emoji": "🪛",
      "why": "לכוונון רגליות התמיכה",
      "price": 280
    }
  ],
  "wall": [
    {
      "name": "מברגת גבס",
      "emoji": "🪛",
      "why": "לקיבוע לוחות הגבס — חובה",
      "price": 340
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא שהקיר אנכי",
      "price": 45
    },
    {
      "name": "סכין גבס",
      "emoji": "🔪",
      "why": "לחיתוך הלוחות לפי מידה",
      "price": 28
    },
    {
      "name": "מספריים לפח",
      "emoji": "✂️",
      "why": "לחיתוך הפרופילים",
      "price": 65
    }
  ],
  "door": [
    {
      "name": "מברגה",
      "emoji": "🪛",
      "why": "לקיבוע המשקוף והצירים",
      "price": 280
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא שהמשקוף ישר",
      "price": 45
    },
    {
      "name": "אזמל",
      "emoji": "🔪",
      "why": "לחריצת מקום הצירים",
      "price": 34
    }
  ],
  "floor": [
    {
      "name": "מסור קרמיקה",
      "emoji": "🪚",
      "why": "לחיתוך אריחים — חובה",
      "price": 420
    },
    {
      "name": "מאלג' משונן",
      "emoji": "🔧",
      "why": "למריחת דבק האריחים",
      "price": 38
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא ריצוף ישר",
      "price": 45
    },
    {
      "name": "גומייה לרובה",
      "emoji": "🧽",
      "why": "למריחת הרובה במישקים",
      "price": 22
    }
  ],
  "seal": [
    {
      "name": "מברשת / רולר",
      "emoji": "🖌️",
      "why": "למריחת הפריימר",
      "price": 32
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לבדיקת שיפועי הניקוז",
      "price": 45
    },
    {
      "name": "מחמם אוויר חם",
      "emoji": "🔥",
      "why": "להדבקת יריעות האיטום",
      "price": 240
    }
  ],
  "pipes": [
    {
      "name": "מספריים לצינורות PEX",
      "emoji": "✂️",
      "why": "לחיתוך נקי של הצינורות",
      "price": 85
    },
    {
      "name": "מלחצי PEX",
      "emoji": "🔧",
      "why": "לחיבור הצינורות למחברים",
      "price": 380
    },
    {
      "name": "משאבת לחץ לבדיקה",
      "emoji": "⚙️",
      "why": "לבדיקת לחץ המים — חובה",
      "price": 290
    }
  ],
  "boilerElectric": [
    {
      "name": "מקדחה רוטטת",
      "emoji": "🔩",
      "why": "לקדיחת חורי התלייה בקיר",
      "price": 640
    },
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "לחיבור קווי המים לדוד",
      "price": 39
    },
    {
      "name": "מד מתח (בודק חשמל)",
      "emoji": "⚡",
      "why": "לבדיקת חיבור החשמל בבטחה",
      "price": 75
    }
  ],
  "boilerSolar": [
    {
      "name": "מפתחות צינורות",
      "emoji": "🔧",
      "why": "לחיבור הצנרת בין הקולטים לדוד",
      "price": 39
    },
    {
      "name": "מקדחה",
      "emoji": "🔩",
      "why": "לעיגון המתקן בגג",
      "price": 480
    },
    {
      "name": "סולם",
      "emoji": "🪜",
      "why": "לעבודה על הגג בבטחה",
      "price": 320
    }
  ],
  "kitchenSink": [
    {
      "name": "מסור אזמרל / חור",
      "emoji": "🪚",
      "why": "לחיתוך פתח הכיור במשטח",
      "price": 95
    },
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "לחיבור הסיפון",
      "price": 39
    },
    {
      "name": "אקדח סיליקון",
      "emoji": "🔫",
      "why": "למריחת סיליקון אחיד",
      "price": 32
    }
  ],
  "dishwasher": [
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "לחיבור ברז המדיח",
      "price": 39
    },
    {
      "name": "מברגה",
      "emoji": "🪛",
      "why": "לקיבוע ברז הזווית",
      "price": 280
    }
  ],
  "washingPoint": [
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "לחיבור ברז המכונה",
      "price": 39
    },
    {
      "name": "מברגה",
      "emoji": "🪛",
      "why": "לקיבוע נקודת המים",
      "price": 280
    }
  ],
  "floorDrain": [
    {
      "name": "מסור קרמיקה",
      "emoji": "🪚",
      "why": "לחיתוך אריח סביב המחסום",
      "price": 420
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא שיפוע נכון לכיוון המחסום",
      "price": 45
    }
  ],
  "pressureReg": [
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "להתקנת הווסת על הקו",
      "price": 39
    },
    {
      "name": "מפתח שוודי",
      "emoji": "🔧",
      "why": "להידוק חיבורי המים",
      "price": 62
    }
  ],
  "showerCabin": [
    {
      "name": "מקדחה רוטטת",
      "emoji": "🔩",
      "why": "לקדיחת חורי הפרופילים בקיר",
      "price": 640
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "לוודא שהמקלחון אנכי וישר",
      "price": 45
    },
    {
      "name": "אקדח סיליקון",
      "emoji": "🔫",
      "why": "לאיטום נקי",
      "price": 32
    },
    {
      "name": "כוס הרמה לזכוכית",
      "emoji": "🔵",
      "why": "להרמת לוחות הזכוכית בבטחה",
      "price": 88
    }
  ],
  "bidet": [
    {
      "name": "מקדחה רוטטת",
      "emoji": "🔩",
      "why": "לקדיחת חורי העיגון",
      "price": 640
    },
    {
      "name": "מפלס (פלס)",
      "emoji": "📏",
      "why": "יישור הבידה",
      "price": 45
    },
    {
      "name": "מפתח צינורות",
      "emoji": "🔧",
      "why": "לחיבור הסוללה והסיפון",
      "price": 39
    }
  ]
};

export function toolsFor(key: string): ToolItem[] {
  return TOOL_BUNDLES[key] ?? [];
}
