/* Auto-generated by scripts/extract-catalog.mjs — do not edit by hand.
 * Source: /home/user/buildsmart/index.html
 * Regenerate: node scripts/extract-catalog.mjs
 */
export type VariantOption = {
  name: string;
  sku?: string;
  unit?: string;
  diameter?: string;
  page?: string;
  delta?: number;
  model?: string;
};

export type VariantDef = {
  label: string;
  sku: boolean;
  opts: VariantOption[];
};

export const VARIANTS: Record<string, VariantDef> = {
  "pl_0712060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20",
        "sku": "0712060200A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "25",
        "sku": "0712060250A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "32",
        "sku": "0712060320A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "40",
        "sku": "0712060400A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "50",
        "sku": "0712060500A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "63",
        "sku": "0712060630A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "E75",
        "sku": "871206075",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "E90",
        "sku": "871206090",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 28",
        "delta": 0
      },
      {
        "name": "E110",
        "sku": "871206110",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 28",
        "delta": 0
      }
    ]
  },
  "pl_0714060160": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "16 x 1/2\" x 16",
        "sku": "0714060160050A",
        "unit": "יח'",
        "diameter": "16",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "16 x 3/4\" x 16",
        "sku": "0714060160070A",
        "unit": "יח'",
        "diameter": "16",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "20 x 3/4\" x 16",
        "sku": "0714S60200160A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "20 x 1/2\" x 20",
        "sku": "0714060200050A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "20 x 3/4\" x 20",
        "sku": "0714060200070A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "25 x 3/4\" x 20",
        "sku": "0714S60250200A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "25 x 1/2\" x 25",
        "sku": "0714060250050A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "25 x 3/4\" x 25",
        "sku": "0714060250070A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "25 x 1\" x 25",
        "sku": "0714060250100A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "25 x 1.1/4\" x 25",
        "sku": "0714060250130A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "32 x 3/4\" x 25",
        "sku": "0714S60320250A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "32 x 1\" x 25",
        "sku": "0714060320250A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "32 x 1\" x 32",
        "sku": "0714060320100A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "32 x 1.1/4\" x 32",
        "sku": "0714060320130A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "32 x 1.1/2\" x 32",
        "sku": "0714060320150A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "40 x 1\" x 40",
        "sku": "0714060400100A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "40 x 1.1/4\" x 40",
        "sku": "0714060400130A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "40 x 1.1/2\" x 40",
        "sku": "0714060400150A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "40 x 2\" x 40",
        "sku": "0714060400200A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "50 x 1.1/2\" x 50",
        "sku": "0714060500150A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "50 x 2\" x 50",
        "sku": "0714060500200A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "63 x 1.1/4\" x 63",
        "sku": "0714060630130A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "63 x 1.1/2\" x 63",
        "sku": "0714060630150A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "63 x 2\" x 63",
        "sku": "0714060630200A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "E75 x 2\" x 75",
        "sku": "871406075020",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "E75 x 2.1/2\" x 75",
        "sku": "871406075025",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "E75 x 3\" x 75",
        "sku": "871406075030",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "E90 x 3\" x 90",
        "sku": "871406090030",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 29",
        "delta": 0
      },
      {
        "name": "E110 x 4\" x 110",
        "sku": "871406110040",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 29",
        "delta": 0
      }
    ]
  },
  "pl_0715060160": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "16 x 1/2\"",
        "sku": "0715060160050A",
        "unit": "יח'",
        "diameter": "16",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "20 x 1/2\"",
        "sku": "0715060200050A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "20 x 3/4\"",
        "sku": "0715060200070A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "25 x 1/2\"",
        "sku": "0715060250050A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "25 x 3/4\"",
        "sku": "0715060250070A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "25 x 1\"",
        "sku": "0715060250100A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "32 x 3/4\"",
        "sku": "0715060320070A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "32 x 1\"",
        "sku": "0715060320100A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "32 x 1.1/4\"",
        "sku": "0715060320130A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "40 x 1\"",
        "sku": "0715060400100A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "40 x 1.1/4\"",
        "sku": "0715060400130A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "40 x 1.1/2\"",
        "sku": "0715060400150A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "50 x 1\"",
        "sku": "0715060500100A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "50 x 1.1/4\"",
        "sku": "0715060500130A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "50 x 1.1/2\"",
        "sku": "0715060500150A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "63 x 1.1/4\"",
        "sku": "0715060630130A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "63 x 1.1/2\"",
        "sku": "0715060630150A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "63 x 2\"",
        "sku": "0715060630200A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "E75 x 2\"",
        "sku": "871506075020",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "E75 x 2.1/2\"",
        "sku": "871506075025",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 30",
        "delta": 0
      },
      {
        "name": "E75 x 3\"",
        "sku": "871506075030",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 30",
        "delta": 0
      }
    ]
  },
  "pl_0734060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20 x 16 x 20",
        "sku": "0734060200160A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "25 x 20 x 25",
        "sku": "0734060250200A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "32 x 25 x 32",
        "sku": "0734060320250A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "40 x 25 x 40",
        "sku": "0734060400250A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "40 x 32 x 40",
        "sku": "0734060400320A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "50 x 25 x 50",
        "sku": "0734060500250A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "50 x 32 x 50",
        "sku": "0734060500320A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "50 x 40 x 50",
        "sku": "0734060500400A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "63 x 32 x 63",
        "sku": "0734060630320A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "63 x 40 x 63",
        "sku": "0734060630400A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "63 x 50 x 63",
        "sku": "0734060630500A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "E75 x 63 x 75",
        "sku": "873406075063",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 31",
        "delta": 0
      }
    ]
  },
  "pl_0755060160": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "16 x 16 x 3/4\"",
        "sku": "0755060160070A",
        "unit": "יח'",
        "diameter": "16",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "20 x 20 x 3/4\"",
        "sku": "0755060200070A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 31",
        "delta": 0
      },
      {
        "name": "25 x 25 x 3/4\"",
        "sku": "0755060250070A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 31",
        "delta": 0
      }
    ]
  },
  "pl_0706060320": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "32 x 32",
        "sku": "0706060320A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 32",
        "delta": 0
      },
      {
        "name": "40 x 40",
        "sku": "0706060400A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 32",
        "delta": 0
      },
      {
        "name": "50 x 50",
        "sku": "0706060500A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 32",
        "delta": 0
      },
      {
        "name": "63 x 63",
        "sku": "0706060630A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 32",
        "delta": 0
      },
      {
        "name": "E75 x 75",
        "sku": "870606075",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 32",
        "delta": 0
      },
      {
        "name": "E90 x 90",
        "sku": "870606090",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 32",
        "delta": 0
      },
      {
        "name": "E110 x 110",
        "sku": "870606110",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 32",
        "delta": 0
      }
    ]
  },
  "pl_0751060250": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "25 x 20",
        "sku": "0751060250200A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 32",
        "delta": 0
      }
    ]
  },
  "pl_0761060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20 x 20",
        "sku": "0761060200A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "25 x 25",
        "sku": "0761060250A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "32 x 32",
        "sku": "0761060320A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "40 x 40",
        "sku": "0761060400A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "50 x 50",
        "sku": "0761060500A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "63 x 63",
        "sku": "0761060630A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "E75 x 75",
        "sku": "876106075",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "E90 x 90",
        "sku": "876106090",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "E110 x 110",
        "sku": "876106110",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 33",
        "delta": 0
      }
    ]
  },
  "pl_0745060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20 x 1/2\"",
        "sku": "0745060200050A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 33",
        "delta": 0
      },
      {
        "name": "20 x 3/4\"",
        "sku": "0745060200070A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 33",
        "delta": 0
      }
    ]
  },
  "pl_0764060630": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "63 x 63 x 63",
        "sku": "0764060630A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 34",
        "delta": 0
      },
      {
        "name": "E75 x 75 x 75",
        "sku": "876406075",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 34",
        "delta": 0
      },
      {
        "name": "E90 x 90 x 90",
        "sku": "876406090",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 34",
        "delta": 0
      },
      {
        "name": "E110 x 110 x 110",
        "sku": "876406110",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 34",
        "delta": 0
      }
    ]
  },
  "pl_074706032": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "32 x 32",
        "sku": "074706032",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 34",
        "delta": 0
      },
      {
        "name": "40 x 40",
        "sku": "074706040",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 34",
        "delta": 0
      },
      {
        "name": "50 x 50",
        "sku": "074706050",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 34",
        "delta": 0
      },
      {
        "name": "63 x 63",
        "sku": "074706063",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 34",
        "delta": 0
      }
    ]
  },
  "pl_0784060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20 x 1/2\" x 20",
        "sku": "0784060200050A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "20 x 3/4\" x 20",
        "sku": "0784060200070A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "25 x 1/2\" x 25",
        "sku": "0784060250050A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "25 x 3/4\" x 25",
        "sku": "0784060250070A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "32 x 1\" x 32",
        "sku": "0784060320100A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "40 x 1.1/4\" x 40",
        "sku": "0784060400130A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "50 x 1.1/4\" x 50",
        "sku": "0784060500130A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "50 x 1.1/2\" x 50",
        "sku": "0784060500150A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "50 x 2\" x 50",
        "sku": "0784060500200A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "63 x 1.1/4\" x 63",
        "sku": "0784060630130A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "63 x 1.1/2\" x 63",
        "sku": "0784060630150A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "63 x 2\" x 63",
        "sku": "0784060630200A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 35",
        "delta": 0
      }
    ]
  },
  "pl_0781060400": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "40 x 3/4\" x 40",
        "sku": "0781060400070A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "50 x 3/4\" x 50",
        "sku": "0781060500070A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "50 x 1\" x 50",
        "sku": "0781060500100A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "63 x 3/4\" x 63",
        "sku": "0781060630070A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "63 x 1\" x 63",
        "sku": "0781060630100A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "E75 x 3/4\" x 75",
        "sku": "878106075007",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 35",
        "delta": 0
      },
      {
        "name": "E75 x 1\" x 75",
        "sku": "878106075010",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 35",
        "delta": 0
      }
    ]
  },
  "pl_0785060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20 x 1/2\"",
        "sku": "0785060200050A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "20 x 3/4\"",
        "sku": "0785060200070A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "25 x 1/2\"",
        "sku": "0785060250050A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "25 x 3/4\"",
        "sku": "0785060250070A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "25 x 1\"",
        "sku": "0785060250100A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "32 x 3/4\"",
        "sku": "0785060320070A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "32 x 1\"",
        "sku": "0785060320100A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "32 x 1.1/4\"",
        "sku": "0785060320130A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "40 x 1\"",
        "sku": "0785060400100A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "40 x 1.1/4\"",
        "sku": "0785060400130A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "40 x 1.1/2\"",
        "sku": "0785060400150A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "50 x 1\"",
        "sku": "0785060500100A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "50 x 1.1/4\"",
        "sku": "0785060500130A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "50 x 1.1/2\"",
        "sku": "0785060500150A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "50 x 2\"",
        "sku": "0785060500200A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "63 x 1.1/4\"",
        "sku": "0785060630130A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "63 x 1.1/2\"",
        "sku": "0785060630150A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "63 x 2\"",
        "sku": "0785060630200A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "E75 x 2.1/2\"",
        "sku": "878506075025",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "E75 x 3\"",
        "sku": "878506075030",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "E90 x 3\"",
        "sku": "878506090030",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 36",
        "delta": 0
      },
      {
        "name": "E110 x 4\"",
        "sku": "878506110040",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 36",
        "delta": 0
      }
    ]
  },
  "pl_0735060400": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "40 x 40",
        "sku": "0735060400400A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 37",
        "delta": 0
      },
      {
        "name": "40 x 50",
        "sku": "0735060400500A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 37",
        "delta": 0
      },
      {
        "name": "50 x 40",
        "sku": "0735060500400A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 37",
        "delta": 0
      },
      {
        "name": "50 x 50",
        "sku": "0735060500500A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 37",
        "delta": 0
      },
      {
        "name": "63 x 40",
        "sku": "0735060630400A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 37",
        "delta": 0
      },
      {
        "name": "63 x 50",
        "sku": "0735060630500A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 37",
        "delta": 0
      }
    ]
  },
  "pl_0722060400": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "40 x 1.1/2\"",
        "sku": "0722060400150A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "50 x 1.1/2\"",
        "sku": "0722060500150A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "50 x 2\"",
        "sku": "0722060500200A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "63 x 2\"",
        "sku": "0722060630200A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "125 x 5\"",
        "sku": "0722061250500A",
        "unit": "יח'",
        "diameter": "125",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "125 x 6\"",
        "sku": "0722061250600A",
        "unit": "יח'",
        "diameter": "125",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "E75 x 2.1/2\"",
        "sku": "872206075025",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "E90 x 3\"",
        "sku": "872206090030",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "E90 x 4\"",
        "sku": "872206090040",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 38",
        "delta": 0
      },
      {
        "name": "E110 x 4\"",
        "sku": "872206110040",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 38",
        "delta": 0
      }
    ]
  },
  "pl_0723060500": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "50 x 1.1/2\"",
        "sku": "0723060500150A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "50 x 2\"",
        "sku": "0723060500200A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "63 x 2\"",
        "sku": "0723060630200A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "63 x 2.1/2\"",
        "sku": "0723060630250A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E75 x 2\"",
        "sku": "872306075020",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E75 x 2.1/2\"",
        "sku": "872306075025",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E75 x 3\"",
        "sku": "872306075030",
        "unit": "יח'",
        "diameter": "E75",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E90 x 2.1/2\"",
        "sku": "872306090025",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E90 x 3\"",
        "sku": "872306090030",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E90 x 4\"",
        "sku": "872306090040",
        "unit": "יח'",
        "diameter": "E90",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E110 x 3\"",
        "sku": "872306110030",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E110 x 4\"",
        "sku": "872306110040",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "E110 x 5\"",
        "sku": "872306110050",
        "unit": "יח'",
        "diameter": "E110",
        "page": "עמוד 39",
        "delta": 0
      }
    ]
  },
  "pl_05629020": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20",
        "sku": "05629020",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "25",
        "sku": "05629025",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "32",
        "sku": "05629032",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "40",
        "sku": "05629040",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "50",
        "sku": "05629050",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "63",
        "sku": "05629063",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "75",
        "sku": "05629075",
        "unit": "יח'",
        "diameter": "75",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "90",
        "sku": "05629090",
        "unit": "יח'",
        "diameter": "90",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "125",
        "sku": "05629125",
        "unit": "יח'",
        "diameter": "125",
        "page": "עמוד 39",
        "delta": 0
      },
      {
        "name": "160",
        "sku": "05629160",
        "unit": "יח'",
        "diameter": "160",
        "page": "עמוד 39",
        "delta": 0
      }
    ]
  },
  "pl_0793000250": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "25 x 20",
        "sku": "079300025020",
        "unit": "ערכה",
        "diameter": "25",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "32 x 20",
        "sku": "079300032020",
        "unit": "ערכה",
        "diameter": "32",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "32 x 25",
        "sku": "079300032025",
        "unit": "ערכה",
        "diameter": "32",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "40 x 20",
        "sku": "079300040020",
        "unit": "ערכה",
        "diameter": "40",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "40 x 25",
        "sku": "079300040025",
        "unit": "ערכה",
        "diameter": "40",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "40 x 32",
        "sku": "079300040032",
        "unit": "ערכה",
        "diameter": "40",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "50 x 25",
        "sku": "079300050025",
        "unit": "ערכה",
        "diameter": "50",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "50 x 32",
        "sku": "079300050032",
        "unit": "ערכה",
        "diameter": "50",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "50 x 40",
        "sku": "079300050040",
        "unit": "ערכה",
        "diameter": "50",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "63 x 25",
        "sku": "079300063025",
        "unit": "ערכה",
        "diameter": "63",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "63 x 32",
        "sku": "079300063032",
        "unit": "ערכה",
        "diameter": "63",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "63 x 40",
        "sku": "079300063040",
        "unit": "ערכה",
        "diameter": "63",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "63 x 50",
        "sku": "079300063050",
        "unit": "ערכה",
        "diameter": "63",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "110 x 63",
        "sku": "079300110063",
        "unit": "ערכה",
        "diameter": "110",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "E75 x 63",
        "sku": "879300075063",
        "unit": "ערכה",
        "diameter": "E75",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "E110 x 75",
        "sku": "879300110075",
        "unit": "ערכה",
        "diameter": "E110",
        "page": "עמוד 40",
        "delta": 0
      },
      {
        "name": "E110 x 90",
        "sku": "879300110090",
        "unit": "ערכה",
        "diameter": "E110",
        "page": "עמוד 40",
        "delta": 0
      }
    ]
  },
  "pl_0789010250": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "25 x 1/2\"",
        "sku": "078901025005P",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "25 x 3/4\"",
        "sku": "078901025007P",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "32 x 1/2\"",
        "sku": "078901032005P",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "32 x 3/4\"",
        "sku": "078901032007P",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "32 x 1\"",
        "sku": "078901032010P",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "40 x 1\"",
        "sku": "078901040010P",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "40 x 1.1/4\"",
        "sku": "078901040013P",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "40 x 1.1/2\"",
        "sku": "078901040015P",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "50 x 1\"",
        "sku": "078901050010P",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "50 x 1.1/4\"",
        "sku": "078901050013P",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "50 x 1.1/2\"",
        "sku": "078901050015P",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "50 x 2\"",
        "sku": "078901050020P",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "63 x 1\"",
        "sku": "078901063010P",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "63 x 1.1/4\"",
        "sku": "078901063013P",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "63 x 1.1/2\"",
        "sku": "078901063015P",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "63 x 2\"",
        "sku": "078901063020P",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "63 x 2.1/2\"",
        "sku": "078901063025P",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "75 x 1.1/2\"",
        "sku": "078901075015P",
        "unit": "יח'",
        "diameter": "75",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "75 x 2\"",
        "sku": "078901075020P",
        "unit": "יח'",
        "diameter": "75",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "75 x 2.1/2\"",
        "sku": "078901075025P",
        "unit": "יח'",
        "diameter": "75",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "75 x 3\"",
        "sku": "078901075030P",
        "unit": "יח'",
        "diameter": "75",
        "page": "עמוד 41",
        "delta": 0
      }
    ]
  },
  "pl_078946025P": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "25",
        "sku": "078946025P",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "32",
        "sku": "078946032P",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "40",
        "sku": "078946040P",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "50",
        "sku": "078946050P",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "63",
        "sku": "078946063P",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 41",
        "delta": 0
      },
      {
        "name": "75",
        "sku": "078946075P",
        "unit": "יח'",
        "diameter": "75",
        "page": "עמוד 41",
        "delta": 0
      }
    ]
  },
  "pl_0794060200": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "20",
        "sku": "0794060200A",
        "unit": "יח'",
        "diameter": "20",
        "page": "עמוד 42",
        "delta": 0
      },
      {
        "name": "25",
        "sku": "0794060250A",
        "unit": "יח'",
        "diameter": "25",
        "page": "עמוד 42",
        "delta": 0
      },
      {
        "name": "32",
        "sku": "0794060320A",
        "unit": "יח'",
        "diameter": "32",
        "page": "עמוד 42",
        "delta": 0
      },
      {
        "name": "40",
        "sku": "0794060400A",
        "unit": "יח'",
        "diameter": "40",
        "page": "עמוד 42",
        "delta": 0
      },
      {
        "name": "50",
        "sku": "0794060500A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 42",
        "delta": 0
      },
      {
        "name": "63",
        "sku": "0794060630A",
        "unit": "יח'",
        "diameter": "63",
        "page": "עמוד 42",
        "delta": 0
      }
    ]
  },
  "pl_0794L60500": {
    "label": "מידה / קוטר",
    "sku": true,
    "opts": [
      {
        "name": "50",
        "sku": "0794L60500A",
        "unit": "יח'",
        "diameter": "50",
        "page": "עמוד 42",
        "delta": 0
      }
    ]
  },
  "faucet": {
    "label": "גובה הברז",
    "sku": false,
    "opts": [
      {
        "name": "ברז נמוך — סטנדרט",
        "delta": 0
      },
      {
        "name": "ברז גבוה — לכיור מונח",
        "delta": 60
      },
      {
        "name": "ברז עם פיה נשלפת",
        "delta": 140
      }
    ]
  },
  "kitchenFaucet": {
    "label": "סוג הברז",
    "sku": false,
    "opts": [
      {
        "name": "ברז רגיל",
        "delta": 0
      },
      {
        "name": "ברז גבוה — סיר",
        "delta": 70
      },
      {
        "name": "ברז עם פילטר מובנה",
        "delta": 190
      }
    ]
  },
  "basin": {
    "label": "סוג הכיור",
    "sku": false,
    "opts": [
      {
        "name": "כיור מונח",
        "delta": 0
      },
      {
        "name": "כיור שקוע (אינטגרלי)",
        "delta": 120
      },
      {
        "name": "כיור תלוי על הקיר",
        "delta": 80
      }
    ]
  },
  "toilet": {
    "label": "צבע / גימור",
    "sku": false,
    "opts": [
      {
        "name": "לבן — סטנדרט",
        "delta": 0
      },
      {
        "name": "לבן מאט",
        "delta": 90
      },
      {
        "name": "שחור מאט",
        "delta": 160
      }
    ]
  },
  "toiletFloor": {
    "label": "סוג ההדחה",
    "sku": false,
    "opts": [
      {
        "name": "מיכל עליון",
        "delta": 0
      },
      {
        "name": "הדחה כפולה חסכונית",
        "delta": 70
      }
    ]
  },
  "shower": {
    "label": "סוג הסוללה",
    "sku": false,
    "opts": [
      {
        "name": "סוללה ידנית",
        "delta": 0
      },
      {
        "name": "סוללה תרמוסטטית",
        "delta": 170
      },
      {
        "name": "מערכת עם 2 יציאות",
        "delta": 280
      }
    ]
  },
  "bathtub": {
    "label": "מידת האמבטיה",
    "sku": false,
    "opts": [
      {
        "name": "150×70 ס\"מ",
        "delta": 0
      },
      {
        "name": "170×75 ס\"מ",
        "delta": 140
      },
      {
        "name": "180×80 ס\"מ",
        "delta": 320
      }
    ]
  },
  "wall": {
    "label": "סוג הגבס",
    "sku": false,
    "opts": [
      {
        "name": "גבס רגיל (לבן)",
        "delta": 0
      },
      {
        "name": "גבס ירוק — עמיד לחות",
        "delta": 90
      },
      {
        "name": "גבס ורוד — עמיד אש",
        "delta": 130
      }
    ]
  },
  "door": {
    "label": "מידת הדלת",
    "sku": false,
    "opts": [
      {
        "name": "70 ס\"מ — צר",
        "delta": 0
      },
      {
        "name": "80 ס\"מ — סטנדרט",
        "delta": 40
      },
      {
        "name": "90 ס\"מ — רחב",
        "delta": 90
      }
    ]
  },
  "floor": {
    "label": "מידת האריח",
    "sku": false,
    "opts": [
      {
        "name": "30×30 ס\"מ",
        "delta": 0
      },
      {
        "name": "60×60 ס\"מ",
        "delta": 160
      },
      {
        "name": "אריח עץ 20×120 ס\"מ",
        "delta": 290
      }
    ]
  },
  "seal": {
    "label": "סוג מערכת האיטום",
    "sku": false,
    "opts": [
      {
        "name": "יריעות ביטומניות",
        "delta": 0
      },
      {
        "name": "איטום צמנטי מרוח",
        "delta": 80
      }
    ]
  },
  "pipes": {
    "label": "סוג הצנרת",
    "sku": false,
    "opts": [
      {
        "name": "צנרת PEX סטנדרט",
        "delta": 0
      },
      {
        "name": "צנרת מולטי-גז (רב-שכבתי)",
        "delta": 240
      }
    ]
  },
  "boilerElectric": {
    "label": "נפח הדוד",
    "sku": false,
    "opts": [
      {
        "name": "50 ליטר — דירה קטנה",
        "delta": 0
      },
      {
        "name": "80 ליטר — סטנדרט",
        "delta": 120
      },
      {
        "name": "120 ליטר — משפחה גדולה",
        "delta": 280
      }
    ]
  },
  "boilerSolar": {
    "label": "נפח המערכת",
    "sku": false,
    "opts": [
      {
        "name": "120 ליטר",
        "delta": 0
      },
      {
        "name": "150 ליטר — סטנדרט",
        "delta": 260
      },
      {
        "name": "200 ליטר — משפחה גדולה",
        "delta": 620
      }
    ]
  },
  "kitchenSink": {
    "label": "מספר כיורים",
    "sku": false,
    "opts": [
      {
        "name": "כיור יחיד",
        "delta": 0
      },
      {
        "name": "כיור וחצי",
        "delta": 90
      },
      {
        "name": "כיור כפול",
        "delta": 180
      }
    ]
  },
  "dishwasher": {
    "label": "סוג ההתקנה",
    "sku": false,
    "opts": [
      {
        "name": "חיבור סטנדרט",
        "delta": 0
      },
      {
        "name": "חיבור עם הגנת הצפה",
        "delta": 60
      }
    ]
  },
  "washingPoint": {
    "label": "סוג ההתקנה",
    "sku": false,
    "opts": [
      {
        "name": "חיבור סטנדרט",
        "delta": 0
      },
      {
        "name": "חיבור עם מגש הצפה",
        "delta": 55
      }
    ]
  },
  "floorDrain": {
    "label": "סוג המחסום",
    "sku": false,
    "opts": [
      {
        "name": "מחסום עגול רגיל",
        "delta": 0
      },
      {
        "name": "מחסום ליניארי (תעלה)",
        "delta": 140
      }
    ]
  },
  "pressureReg": {
    "label": "סוג הווסת",
    "sku": false,
    "opts": [
      {
        "name": "וסת רגיל",
        "delta": 0
      },
      {
        "name": "וסת עם מד לחץ",
        "delta": 55
      }
    ]
  },
  "showerCabin": {
    "label": "צורת המקלחון",
    "sku": false,
    "opts": [
      {
        "name": "פינתי מרובע",
        "delta": 0
      },
      {
        "name": "פינתי מעוגל",
        "delta": 120
      },
      {
        "name": "חזית ישרה (דלת בלבד)",
        "delta": 80
      }
    ]
  },
  "bidet": {
    "label": "סוג ההתקנה",
    "sku": false,
    "opts": [
      {
        "name": "בידה תלויה",
        "delta": 0
      },
      {
        "name": "בידה עומדת",
        "delta": -80
      }
    ]
  }
};

export function variantsOf(productId: string): VariantDef | undefined {
  return VARIANTS[productId];
}
